//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICrawlController")]
public interface ICrawlController
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartSearch", ReplyAction="http://tempuri.org/ICrawlController/StartSearchResponse")]
    void StartSearch();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartServices", ReplyAction="http://tempuri.org/ICrawlController/StartServicesResponse")]
    void StartServices();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StopServices", ReplyAction="http://tempuri.org/ICrawlController/StopServicesResponse")]
    void StopServices();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICrawlControllerChannel : ICrawlController, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CrawlControllerClient : System.ServiceModel.ClientBase<ICrawlController>, ICrawlController
{
    
    public CrawlControllerClient()
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void StartSearch()
    {
        base.Channel.StartSearch();
    }
    
    public void StartServices()
    {
        base.Channel.StartServices();
    }
    
    public void StopServices()
    {
        base.Channel.StopServices();
    }
}
