//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.WebCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.WebCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search started. ähnelt.
        /// </summary>
        internal static string CRAWL_CONTROLLER_SEARCH_STARTED {
            get {
                return ResourceManager.GetString("CRAWL_CONTROLLER_SEARCH_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown Services. ähnelt.
        /// </summary>
        internal static string CRAWL_CONTROLLER_SHUTDOWN {
            get {
                return ResourceManager.GetString("CRAWL_CONTROLLER_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for response from Solr. ähnelt.
        /// </summary>
        internal static string CRAWL_CONTROLLER_TRY_GET_RESPONSE {
            get {
                return ResourceManager.GetString("CRAWL_CONTROLLER_TRY_GET_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WCF service host closed. ähnelt.
        /// </summary>
        internal static string CRAWL_CONTROLLER_WCF_HOST_CLOSED {
            get {
                return ResourceManager.GetString("CRAWL_CONTROLLER_WCF_HOST_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WCF service host opened. ähnelt.
        /// </summary>
        internal static string CRAWL_CONTROLLER_WCF_HOST_OPENED {
            get {
                return ResourceManager.GetString("CRAWL_CONTROLLER_WCF_HOST_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User exited the application. ähnelt.
        /// </summary>
        internal static string WEB_CRAWLER_EXITED_BY_USER {
            get {
                return ResourceManager.GetString("WEB_CRAWLER_EXITED_BY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got user input key: [{0}] ähnelt.
        /// </summary>
        internal static string WEB_CRAWLER_GOT_USERINPUT {
            get {
                return ResourceManager.GetString("WEB_CRAWLER_GOT_USERINPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press q for quit. ähnelt.
        /// </summary>
        internal static string WEB_CRAWLER_QUIT_MESSAGE {
            get {
                return ResourceManager.GetString("WEB_CRAWLER_QUIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting server. ähnelt.
        /// </summary>
        internal static string WEB_CRAWLER_START_SERVER {
            get {
                return ResourceManager.GetString("WEB_CRAWLER_START_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unkown user input. ähnelt.
        /// </summary>
        internal static string WEB_CRAWLER_UNKOWN_USERINPUT {
            get {
                return ResourceManager.GetString("WEB_CRAWLER_UNKOWN_USERINPUT", resourceCulture);
            }
        }
    }
}
