.TH "C:/Users/michael/Development/HSA.InfoSys/3rdparty/nhibernate-core/src/NHibernate.Test/Immutable/EntityWithMutableCollection/Inverse Directory Reference" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/michael/Development/HSA.InfoSys/3rdparty/nhibernate-core/src/NHibernate.Test/Immutable/EntityWithMutableCollection/Inverse Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEntityWithInverseManyToManyTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBEntityWithInverseOneToManyJoinTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBEntityWithInverseOneToManyTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersionedEntityWithInverseManyToManyTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersionedEntityWithInverseOneToManyFailureExpectedTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersionedEntityWithInverseOneToManyJoinFailureExpectedTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersionedEntityWithInverseOneToManyJoinTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBVersionedEntityWithInverseOneToManyTest\&.cs\fP"
.br
.in -1c
