.TH "C:/Users/michael/Development/HSA.InfoSys/HSA.InfoSys.Logging/Properties Directory Reference" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/michael/Development/HSA.InfoSys/HSA.InfoSys.Logging/Properties Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBResources\&.Designer\&.cs\fP"
.br
.in -1c
