.TH "HSA.InfoSys.Common.Exceptions.SolrResponseBadRequestException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Exceptions.SolrResponseBadRequestException \- 
.PP
Throws an exception if solr gave a bad request as response\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolrResponseBadRequestException\fP (Exception e, string source)"
.br
.RI "\fIInitializes a new instance of the \fBSolrResponseBadRequestException\fP class\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIReturns a System\&.String that represents this instance\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Throws an exception if solr gave a bad request as response\&. 


.PP
Definition at line 13 of file SolrResponseBadRequestException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HSA\&.InfoSys\&.Common\&.Exceptions\&.SolrResponseBadRequestException\&.SolrResponseBadRequestException (Exceptione, stringsource)"

.PP
Initializes a new instance of the \fBSolrResponseBadRequestException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP The e\&.
.br
\fIsource\fP The source\&.
.RE
.PP

.PP
Definition at line 20 of file SolrResponseBadRequestException\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string HSA\&.InfoSys\&.Common\&.Exceptions\&.SolrResponseBadRequestException\&.ToString ()"

.PP
Returns a System\&.String that represents this instance\&. 
.PP
\fBReturns:\fP
.RS 4
A System\&.String that represents this instance\&. 
.RE
.PP
<PermissionSet> <IPermission class='System\&.Security\&.Permissions\&.FileIOPermission, mscorlib, Version=2\&.0\&.3600\&.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' version='1' pathdiscovery='*AllFiles*'> </PermissionSet> 
.PP
Definition at line 35 of file SolrResponseBadRequestException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
