.TH "HSA.InfoSys.Common.Services.WCFServices.IDbManager" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Services.WCFServices.IDbManager \- 
.PP
The interface for accessing the data base\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmailNotifierSettings\fP \fBGetMailSettings\fP ()"
.br
.RI "\fIGets the mail settings\&. \fP"
.ti -1c
.RI "\fBNutchControllerClientSettings\fP \fBGetNutchClientSettings\fP ()"
.br
.RI "\fIGets the nutch client settings\&. \fP"
.ti -1c
.RI "\fBSolrSearchClientSettings\fP \fBGetSolrClientSettings\fP ()"
.br
.RI "\fIGets the solr client settings\&. \fP"
.ti -1c
.RI "\fBWCFSettings\fP \fBGetWcfSettings\fP ()"
.br
.RI "\fIGets the WCF controller settings\&. \fP"
.ti -1c
.RI "string[] \fBLoadThisEntities\fP (params object[] param)"
.br
.RI "\fILoads this instances from \fBNHibernate\fP eager\&. \fBNHibernate\fP supports lazy loading, so we need some functionality to load a reference to a foreign table too\&. \fP"
.ti -1c
.RI "string[] \fBGetAllUrls\fP ()"
.br
.RI "\fIGets all URLs\&. \fP"
.ti -1c
.RI "Guid \fBAddEntity\fP (\fBEntity\fP entity)"
.br
.RI "\fIAdds a new Object (Component, Issue, Source\&.\&.\&.) and saves it in database\&. \fP"
.ti -1c
.RI "void \fBAddEntitys\fP (params \fBEntity\fP[] entities)"
.br
.RI "\fIAdds a Objects (Component, Issue, Source\&.\&.\&.) and saves it in database\&. \fP"
.ti -1c
.RI "Guid \fBUpdateEntity\fP (\fBEntity\fP entity)"
.br
.RI "\fISaves changings of a object in database\&. \fP"
.ti -1c
.RI "void \fBDeleteEntity\fP (\fBEntity\fP entity)"
.br
.RI "\fIDeletes the entity\&. \fP"
.ti -1c
.RI "\fBEntity\fP \fBGetEntity\fP (Guid entityGuid, string[] types=null)"
.br
.RI "\fIGets an entity from database\&. \fP"
.ti -1c
.RI "\fBOrgUnit\fP[] \fBGetOrgUnitsByUserId\fP (int userId, string[] types=null)"
.br
.RI "\fIGets the org units by user ID\&. \fP"
.ti -1c
.RI "Guid \fBGetOrgUnitGuidByOrgUnitConfigGuid\fP (Guid orgUnitConfigGUID, string[] types=null)"
.br
.RI "\fIGets the org unit GUID by org unit config GUID\&. \fP"
.ti -1c
.RI "\fBOrgUnitConfig\fP[] \fBGetOrgUnitConfigsByActiveScheduler\fP (string[] types=null)"
.br
.RI "\fIGets the org unit configurations by active scheduler\&. \fP"
.ti -1c
.RI "\fBComponent\fP[] \fBGetComponentsByOrgUnitId\fP (Guid orgUnitGUID)"
.br
.RI "\fIGets the components by org unit id\&. \fP"
.ti -1c
.RI "\fBResult\fP[] \fBGetResultsByComponentId\fP (Guid componentGUID)"
.br
.RI "\fIGets the results by component id\&. \fP"
.ti -1c
.RI "\fBOrgUnitConfig\fP[] \fBGetOrgUnitConfigurations\fP ()"
.br
.RI "\fIGets the scheduler times\&. \fP"
.ti -1c
.RI "string[] \fBGetEmailsByUrls\fP (string[] urls)"
.br
.RI "\fIGets the emails by urls\&. \fP"
.ti -1c
.RI "\fBComponent\fP \fBCreateComponent\fP (string name, Guid orgUnitGUID)"
.br
.RI "\fICreates a component object\&. \fP"
.ti -1c
.RI "\fBOrgUnit\fP \fBCreateOrgUnit\fP (int userId, string name)"
.br
.RI "\fICreates a OrgUnit object\&. \fP"
.ti -1c
.RI "\fBOrgUnitConfig\fP \fBCreateOrgUnitConfig\fP (string urls, string emails, bool emailNotification, int days, int time, bool schedulerActive)"
.br
.RI "\fICreates a OrgUnitConfig object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The interface for accessing the data base\&. 


.PP
Definition at line 20 of file IDBManager\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "Guid HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.AddEntity (\fBEntity\fPentity)"

.PP
Adds a new Object (Component, Issue, Source\&.\&.\&.) and saves it in database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentity\fP The entity to add in database\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The GUID of the added entity\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "void HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.AddEntitys (params \fBEntity\fP[]entities)"

.PP
Adds a Objects (Component, Issue, Source\&.\&.\&.) and saves it in database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentities\fP The entities\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBComponent\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.CreateComponent (stringname, GuidorgUnitGUID)"

.PP
Creates a component object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name\&.
.br
\fIorgUnitGUID\fP The org unit GUID\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The created component object\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBOrgUnit\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.CreateOrgUnit (intuserId, stringname)"

.PP
Creates a OrgUnit object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuserId\fP The user id\&.
.br
\fIname\fP The system name\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The created OrgUnit object\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBOrgUnitConfig\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.CreateOrgUnitConfig (stringurls, stringemails, boolemailNotification, intdays, inttime, boolschedulerActive)"

.PP
Creates a OrgUnitConfig object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurls\fP The URL\&.
.br
\fIemails\fP The email text\&.
.br
\fIemailNotification\fP if set to \fCtrue\fP [email notification]\&.
.br
\fIdays\fP The days\&.
.br
\fItime\fP The time\&.
.br
\fIschedulerActive\fP if set to \fCtrue\fP [scheduler active]\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The created OrgUnitConfig object\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "void HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.DeleteEntity (\fBEntity\fPentity)"

.PP
Deletes the entity\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentity\fP The entity\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "string [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetAllUrls ()"

.PP
Gets all URLs\&. 
.PP
\fBReturns:\fP
.RS 4
An array containing all URLs for crawling\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBComponent\fP [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetComponentsByOrgUnitId (GuidorgUnitGUID)"

.PP
Gets the components by org unit id\&. 
.PP
\fBParameters:\fP
.RS 4
\fIorgUnitGUID\fP The org unit GUID\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of components which belongs to the given OrgUnit\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "string [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetEmailsByUrls (string[]urls)"

.PP
Gets the emails by urls\&. 
.PP
\fBParameters:\fP
.RS 4
\fIurls\fP The urls\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of email addresses according to the url of an OrgUnitConfig\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBEntity\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetEntity (GuidentityGuid, string[]types = \fCnull\fP)"

.PP
Gets an entity from database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentityGuid\fP The entity GUID\&.
.br
\fItypes\fP The types you want load eager\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The entity you asked for\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBEmailNotifierSettings\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetMailSettings ()"

.PP
Gets the mail settings\&. 
.PP
\fBReturns:\fP
.RS 4
The mail settings\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBNutchControllerClientSettings\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetNutchClientSettings ()"

.PP
Gets the nutch client settings\&. 
.PP
\fBReturns:\fP
.RS 4
The nutch client settings\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBOrgUnitConfig\fP [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetOrgUnitConfigsByActiveScheduler (string[]types = \fCnull\fP)"

.PP
Gets the org unit configurations by active scheduler\&. 
.PP
\fBParameters:\fP
.RS 4
\fItypes\fP The types\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of Orgunit configurations where the \fBScheduler\fP is active\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBOrgUnitConfig\fP [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetOrgUnitConfigurations ()"

.PP
Gets the scheduler times\&. 
.PP
\fBReturns:\fP
.RS 4
A list of all OrgUnitConfig objects\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "Guid HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetOrgUnitGuidByOrgUnitConfigGuid (GuidorgUnitConfigGUID, string[]types = \fCnull\fP)"

.PP
Gets the org unit GUID by org unit config GUID\&. 
.PP
\fBParameters:\fP
.RS 4
\fIorgUnitConfigGUID\fP The org unit config GUID\&.
.br
\fItypes\fP The types\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The OrgUnitGUID of the OrgUnit belonging to the OrgUnitConfigGUID\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBOrgUnit\fP [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetOrgUnitsByUserId (intuserId, string[]types = \fCnull\fP)"

.PP
Gets the org units by user ID\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuserId\fP The user ID\&.
.br
\fItypes\fP The types\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of org units for the user id\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBResult\fP [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetResultsByComponentId (GuidcomponentGUID)"

.PP
Gets the results by component id\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcomponentGUID\fP The component GUID\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of results which belongs to the given component\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBSolrSearchClientSettings\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetSolrClientSettings ()"

.PP
Gets the solr client settings\&. 
.PP
\fBReturns:\fP
.RS 4
The solr client settings\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "\fBWCFSettings\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.GetWcfSettings ()"

.PP
Gets the WCF controller settings\&. 
.PP
\fBReturns:\fP
.RS 4
The WCF controller settings\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "string [] HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.LoadThisEntities (params object[]param)"

.PP
Loads this instances from \fBNHibernate\fP eager\&. \fBNHibernate\fP supports lazy loading, so we need some functionality to load a reference to a foreign table too\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparam\fP The names of the entities\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A list of entities \fBNHibernate\fP must load eager\&. 
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.
.SS "Guid HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.IDbManager\&.UpdateEntity (\fBEntity\fPentity)"

.PP
Saves changings of a object in database\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentity\fP The entity that should be updated\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The GUID of the updated entity\&.
.RE
.PP

.PP
Implemented in \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.DbManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
