.TH "HSA.InfoSys.Common.Entities.Settings" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Entities.Settings \- 
.PP
This is the base class for settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHSA\&.InfoSys\&.Common\&.Entities\&.Entity\fP\&.
.PP
Inherited by \fBHSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\fP, \fBHSA\&.InfoSys\&.Common\&.Entities\&.NutchControllerClientSettings\fP, \fBHSA\&.InfoSys\&.Common\&.Entities\&.SolrSearchClientSettings\fP, and \fBHSA\&.InfoSys\&.Common\&.Entities\&.WCFSettings\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.RI "\fIDetermines whether the specified System\&.Object is equal to this instance\&. \fP"
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "\fIReturns a hash code for this instance\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the base class for settings\&. 


.PP
Definition at line 14 of file Settings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool HSA\&.InfoSys\&.Common\&.Entities\&.Settings\&.Equals (objectobj)"

.PP
Determines whether the specified System\&.Object is equal to this instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP The System\&.Object to compare with this instance\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if the specified System\&.Object is equal to this instance; otherwise, \fCfalse\fP\&. 
.RE
.PP

.PP
Definition at line 23 of file Settings\&.cs\&.
.SS "override int HSA\&.InfoSys\&.Common\&.Entities\&.Settings\&.GetHashCode ()"

.PP
Returns a hash code for this instance\&. 
.PP
\fBReturns:\fP
.RS 4
A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table\&. 
.RE
.PP

.PP
Definition at line 39 of file Settings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
