.TH "HSA.InfoSys.Gui.Models.ValidatePasswordLengthAttribute" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Gui.Models.ValidatePasswordLengthAttribute \- 
.PP
This class provides functionality for password validation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ValidationAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValidatePasswordLengthAttribute\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBValidatePasswordLengthAttribute\fP class\&. \fP"
.ti -1c
.RI "override string \fBFormatErrorMessage\fP (string name)"
.br
.RI "\fIApplies a formatting on an error message on the base of that data field in which the error appeared\&. \fP"
.ti -1c
.RI "override bool \fBIsValid\fP (object value)"
.br
.RI "\fIDetermines if the value is valid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class provides functionality for password validation\&. 


.PP
Definition at line 17 of file ValidatePasswordLengthAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HSA\&.InfoSys\&.Gui\&.Models\&.ValidatePasswordLengthAttribute\&.ValidatePasswordLengthAttribute ()"

.PP
Initializes a new instance of the \fBValidatePasswordLengthAttribute\fP class\&. 
.PP
Definition at line 32 of file ValidatePasswordLengthAttribute\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string HSA\&.InfoSys\&.Gui\&.Models\&.ValidatePasswordLengthAttribute\&.FormatErrorMessage (stringname)"

.PP
Applies a formatting on an error message on the base of that data field in which the error appeared\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name which should be included\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of the formatted error message\&. 
.RE
.PP

.PP
Definition at line 43 of file ValidatePasswordLengthAttribute\&.cs\&.
.SS "override bool HSA\&.InfoSys\&.Gui\&.Models\&.ValidatePasswordLengthAttribute\&.IsValid (objectvalue)"

.PP
Determines if the value is valid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The value of the validated object\&.
.RE
.PP
\fBReturns:\fP
.RS 4
true, if value is valid, otherwise false\&. 
.RE
.PP

.PP
Definition at line 59 of file ValidatePasswordLengthAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
