.TH "HSA.InfoSys.Common.Entities.EmailNotifierSettings" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Entities.EmailNotifierSettings \- 
.PP
There we can store settings for email notifier\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHSA\&.InfoSys\&.Common\&.Entities\&.Settings\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIReturns a System\&.String that represents this instance\&. \fP"
.ti -1c
.RI "virtual void \fBSetDefaults\fP ()"
.br
.RI "\fISets the default values\&. \fP"
.ti -1c
.RI "virtual \fBSettings\fP \fBGetDefaults\fP ()"
.br
.RI "\fIGets the settings with default values\&. \fP"
.ti -1c
.RI "virtual bool \fBIsDefault\fP ()"
.br
.RI "\fIDetermines whether this settings has default values\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBSmtpServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the SMTP server address\&. \fP"
.ti -1c
.RI "virtual int \fBSmtpPort\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the SMTP port\&. \fP"
.ti -1c
.RI "virtual string \fBMailFrom\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the mail address from which account we want to send mails\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
There we can store settings for email notifier\&. 


.PP
Definition at line 16 of file EmailNotifierSettings\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSettings\fP HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.GetDefaults ()\fC [virtual]\fP"

.PP
Gets the settings with default values\&. 
.PP
\fBReturns:\fP
.RS 4
A new settings object with its default values\&.
.RE
.PP

.PP
Definition at line 81 of file EmailNotifierSettings\&.cs\&.
.SS "virtual bool HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.IsDefault ()\fC [virtual]\fP"

.PP
Determines whether this settings has default values\&. 
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if this settings has default values; otherwise, \fCfalse\fP\&. 
.RE
.PP

.PP
Definition at line 99 of file EmailNotifierSettings\&.cs\&.
.SS "virtual void HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.SetDefaults ()\fC [virtual]\fP"

.PP
Sets the default values\&. 
.PP
\fBExceptions:\fP
.RS 4
\fISystem\&.NotImplementedException\fP 
.RE
.PP

.PP
Definition at line 65 of file EmailNotifierSettings\&.cs\&.
.SS "override string HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.ToString ()"

.PP
Returns a System\&.String that represents this instance\&. 
.PP
\fBReturns:\fP
.RS 4
A System\&.String that represents this instance\&. 
.RE
.PP

.PP
Definition at line 51 of file EmailNotifierSettings\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual string HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.MailFrom\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the mail address from which account we want to send mails\&. The mail address of the sending account\&. 
.PP
Definition at line 43 of file EmailNotifierSettings\&.cs\&.
.SS "virtual int HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.SmtpPort\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the SMTP port\&. The SMTP port\&. 
.PP
Definition at line 34 of file EmailNotifierSettings\&.cs\&.
.SS "virtual string HSA\&.InfoSys\&.Common\&.Entities\&.EmailNotifierSettings\&.SmtpServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the SMTP server address\&. The SMTP server address\&. 
.PP
Definition at line 25 of file EmailNotifierSettings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
