.TH "HSA.InfoSys.Common.Services.LocalServices" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Services.LocalServices \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCountdown\fP"
.br
.RI "\fIThis class represents the countdown thread\&. \fP"
.ti -1c
.RI "class \fBCountdownTime\fP"
.br
.RI "\fIThis class represents the time object\&. \fP"
.ti -1c
.RI "class \fBCrawlController\fP"
.br
.RI "\fIThis class is the controller for the crawler it implements an interface for communication between the crawler and the GUI by using WCF\&. \fP"
.ti -1c
.RI "class \fBEmailNotifier\fP"
.br
.RI "\fIThis class sends emails to notify the owner of something what happed during crawling\&. \fP"
.ti -1c
.RI "interface \fBICrawlController\fP"
.br
.RI "\fIThis is the interface for communication between the GUI and the web crawler \fP"
.ti -1c
.RI "class \fBNutchController\fP"
.br
.RI "\fIThis class invokes the crawl and handles all pending crawls\&. \fP"
.ti -1c
.RI "class \fBNutchControllerClient\fP"
.br
.RI "\fIThe \fBNutchControllerClient\fP starts a crawl on the specified host\&. \fP"
.ti -1c
.RI "class \fBSolrResultPot\fP"
.br
.RI "\fIIs a container for search results from Solr\&. \fP"
.ti -1c
.RI "class \fBSolrSearchClient\fP"
.br
.RI "\fIThis class connects to the Solr server and invokes the search\&. \fP"
.ti -1c
.RI "class \fBSolrSearchController\fP"
.br
.RI "\fIThe solr search controller handles a search request for one OrgUnit and instanciates a new client for each component\&. There will be one controller for each OrgUnit we want search\&. \fP"
.ti -1c
.RI "class \fBWCFControllerAddresses\fP"
.br
.RI "\fIThis is a helper class to get the correct service address by its type\&. \fP"
.ti -1c
.RI "class \fBWCFControllerClient< T >\fP"
.br
.RI "\fIThis class is for clients which want use the WCF service \fP"
.ti -1c
.RI "class \fBWCFControllerHost\fP"
.br
.RI "\fIThis class provides the service host for WCF\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
