.TH "log4net.Config.AliasDomainAttribute" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Config.AliasDomainAttribute \- 
.PP
Assembly level attribute that specifies a domain to alias to this assembly's repository\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Config\&.AliasRepositoryAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAliasDomainAttribute\fP (string name)"
.br
.RI "\fIInitializes a new instance of the \fBAliasDomainAttribute\fP class with the specified domain to alias to this assembly's repository\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Assembly level attribute that specifies a domain to alias to this assembly's repository\&. 

\fB\fBAliasDomainAttribute\fP is obsolete\&. Use \fBAliasRepositoryAttribute\fP instead of \fBAliasDomainAttribute\fP\&.\fP 
.PP
An assembly's logger repository is defined by its \fBDomainAttribute\fP, however this can be overridden by an assembly loaded before the target assembly\&. 
.PP
An assembly can alias another assembly's domain to its repository by specifying this attribute with the name of the target domain\&. 
.PP
This attribute can only be specified on the assembly and may be used as many times as necessary to alias all the required domains\&. 
.PP
<author>Nicko Cadell</author> <author>Gert Driesen</author> 
.PP
Definition at line 52 of file AliasDomainAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4net\&.Config\&.AliasDomainAttribute\&.AliasDomainAttribute (stringname)"

.PP
Initializes a new instance of the \fBAliasDomainAttribute\fP class with the specified domain to alias to this assembly's repository\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The domain to alias to this assemby's repository\&.
.RE
.PP
.PP
Obsolete\&. Use \fBAliasRepositoryAttribute\fP instead of \fBAliasDomainAttribute\fP\&. 
.PP
Definition at line 66 of file AliasDomainAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
