.TH "log4net.Appender.RemotingAppender.IRemoteLoggingSink" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Appender.RemotingAppender.IRemoteLoggingSink \- 
.PP
Interface used to deliver LoggingEvent objects to a remote sink\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLogEvents\fP (\fBLoggingEvent\fP[] events)"
.br
.RI "\fIDelivers logging events to the remote sink \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface used to deliver LoggingEvent objects to a remote sink\&. 

This interface must be implemented by a remoting sink if the \fBRemotingAppender\fP is to be used to deliver logging events to the sink\&. 
.PP
Definition at line 312 of file RemotingAppender\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void log4net\&.Appender\&.RemotingAppender\&.IRemoteLoggingSink\&.LogEvents (\fBLoggingEvent\fP[]events)"

.PP
Delivers logging events to the remote sink 
.PP
\fBParameters:\fP
.RS 4
\fIevents\fP Array of events to log\&.
.RE
.PP
.PP
Delivers logging events to the remote sink 

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
