.TH "log4net.Filter.MdcFilter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Filter.MdcFilter \- 
.PP
Simple filter to match a keyed string in the \fBMDC\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Filter\&.PropertyFilter\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Simple filter to match a keyed string in the \fBMDC\fP 

Simple filter to match a keyed string in the \fBMDC\fP 
.PP
As the \fBMDC\fP has been replaced with layered properties the \fBPropertyFilter\fP should be used instead\&. 
.PP
<author>Nicko Cadell</author> <author>Gert Driesen</author> 
.PP
Definition at line 44 of file MdcFilter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
