.TH "log4net.Util.PropertyEntry" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Util.PropertyEntry \- 
.PP
A class to hold the key and data for a property set in the config file  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIOverride \fCObject\&.ToString\fP to return sensible debug info \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBKey\fP\fC [get, set]\fP"
.br
.RI "\fIProperty Key \fP"
.ti -1c
.RI "object \fBValue\fP\fC [get, set]\fP"
.br
.RI "\fIProperty Value \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class to hold the key and data for a property set in the config file 

A class to hold the key and data for a property set in the config file 
.PP
Definition at line 32 of file PropertyEntry\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string log4net\&.Util\&.PropertyEntry\&.ToString ()"

.PP
Override \fCObject\&.ToString\fP to return sensible debug info 
.PP
\fBReturns:\fP
.RS 4
string info about this object
.RE
.PP

.PP
Definition at line 75 of file PropertyEntry\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string log4net\&.Util\&.PropertyEntry\&.Key\fC [get]\fP, \fC [set]\fP"

.PP
Property Key Property Key 
.PP
Property Key\&. 
.PP
Definition at line 49 of file PropertyEntry\&.cs\&.
.SS "object log4net\&.Util\&.PropertyEntry\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Property Value Property Value 
.PP
Property Value\&. 
.PP
Definition at line 66 of file PropertyEntry\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
