.TH "log4net.Util.LevelMappingEntry" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Util.LevelMappingEntry \- 
.PP
An entry in the \fBLevelMapping\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Core\&.IOptionHandler\fP\&.
.PP
Inherited by \fBlog4net\&.Appender\&.AnsiColorTerminalAppender\&.LevelColors\fP, \fBlog4net\&.Appender\&.ColoredConsoleAppender\&.LevelColors\fP, \fBlog4net\&.Appender\&.EventLogAppender\&.Level2EventLogEntryType\fP, \fBlog4net\&.Appender\&.LocalSyslogAppender\&.LevelSeverity\fP, and \fBlog4net\&.Appender\&.RemoteSyslogAppender\&.LevelSeverity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBActivateOptions\fP ()"
.br
.RI "\fIInitialize any options defined on this entry \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelMappingEntry\fP ()"
.br
.RI "\fIDefault protected constructor \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLevel\fP \fBLevel\fP\fC [get, set]\fP"
.br
.RI "\fIThe level that is the key for this mapping \fP"
.in -1c
.SH "Detailed Description"
.PP 
An entry in the \fBLevelMapping\fP 

This is an abstract base class for types that are stored in the \fBLevelMapping\fP object\&. 
.PP
<author>Nicko Cadell</author> 
.PP
Definition at line 37 of file LevelMappingEntry\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4net\&.Util\&.LevelMappingEntry\&.LevelMappingEntry ()\fC [protected]\fP"

.PP
Default protected constructor Default protected constructor 
.PP
Definition at line 49 of file LevelMappingEntry\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void log4net\&.Util\&.LevelMappingEntry\&.ActivateOptions ()\fC [virtual]\fP"

.PP
Initialize any options defined on this entry Should be overridden by any classes that need to initialise based on their options 
.PP
Implements \fBlog4net\&.Core\&.IOptionHandler\fP\&.
.PP
Reimplemented in \fBlog4net\&.Appender\&.ColoredConsoleAppender\&.LevelColors\fP, and \fBlog4net\&.Appender\&.AnsiColorTerminalAppender\&.LevelColors\fP\&.
.PP
Definition at line 87 of file LevelMappingEntry\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBLevel\fP log4net\&.Util\&.LevelMappingEntry\&.Level\fC [get]\fP, \fC [set]\fP"

.PP
The level that is the key for this mapping The \fBLevel\fP that is the key for this mapping 
.PP
Get or set the \fBLevel\fP that is the key for this mapping subclass\&. 
.PP
Definition at line 70 of file LevelMappingEntry\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
