.TH "log4net.Repository" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Repository \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBHierarchy\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigurationChangedEventArgs\fP"
.br
.ti -1c
.RI "interface \fBIBasicRepositoryConfigurator\fP"
.br
.RI "\fIBasic Configurator interface for repositories \fP"
.ti -1c
.RI "interface \fBILoggerRepository\fP"
.br
.RI "\fIInterface implemented by logger repositories\&. \fP"
.ti -1c
.RI "interface \fBIXmlRepositoryConfigurator\fP"
.br
.RI "\fIConfigure repository using XML \fP"
.ti -1c
.RI "class \fBLoggerRepositorySkeleton\fP"
.br
.RI "\fIBase implementation of \fBILoggerRepository\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBLoggerRepositoryShutdownEventHandler\fP (object sender, EventArgs e)"
.br
.RI "\fIDelegate used to handle logger repository shutdown event notifications \fP"
.ti -1c
.RI "delegate void \fBLoggerRepositoryConfigurationResetEventHandler\fP (object sender, EventArgs e)"
.br
.RI "\fIDelegate used to handle logger repository configuration reset event notifications \fP"
.ti -1c
.RI "delegate void \fBLoggerRepositoryConfigurationChangedEventHandler\fP (object sender, EventArgs e)"
.br
.RI "\fIDelegate used to handle event notifications for logger repository configuration changes\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void log4net\&.Repository\&.LoggerRepositoryConfigurationChangedEventHandler (objectsender, EventArgse)"

.PP
Delegate used to handle event notifications for logger repository configuration changes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsender\fP The \fBILoggerRepository\fP that has had its configuration changed\&.
.br
\fIe\fP Empty event arguments\&.
.RE
.PP
.PP
Delegate used to handle event notifications for logger repository configuration changes\&. 
.SS "delegate void log4net\&.Repository\&.LoggerRepositoryConfigurationResetEventHandler (objectsender, EventArgse)"

.PP
Delegate used to handle logger repository configuration reset event notifications 
.PP
\fBParameters:\fP
.RS 4
\fIsender\fP The \fBILoggerRepository\fP that has had its configuration reset\&.
.br
\fIe\fP Empty event args
.RE
.PP
.PP
Delegate used to handle logger repository configuration reset event notifications\&. 
.SS "delegate void log4net\&.Repository\&.LoggerRepositoryShutdownEventHandler (objectsender, EventArgse)"

.PP
Delegate used to handle logger repository shutdown event notifications 
.PP
\fBParameters:\fP
.RS 4
\fIsender\fP The \fBILoggerRepository\fP that is shutting down\&.
.br
\fIe\fP Empty event args
.RE
.PP
.PP
Delegate used to handle logger repository shutdown event notifications\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
