.TH "MySql.Data.MySqlClient.BaseTableCache" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.BaseTableCache \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseTableCache\fP (int maxCacheAge)"
.br
.ti -1c
.RI "virtual void \fBAddToCache\fP (string commandText, object resultSet)"
.br
.ti -1c
.RI "virtual object \fBRetrieveFromCache\fP (string commandText, int cacheAge)"
.br
.ti -1c
.RI "void \fBRemoveFromCache\fP (string commandText)"
.br
.ti -1c
.RI "virtual void \fBDump\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBCleanCache\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBMaxCacheAge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file TableCache\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
