.TH "MySql.Data.MySqlClient.Authentication.MySqlNativePasswordPlugin" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.Authentication.MySqlNativePasswordPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMySql\&.Data\&.MySqlClient\&.Authentication\&.MySqlAuthenticationPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGetPassword\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetAuthData\fP (byte[] data)"
.br
.ti -1c
.RI "override byte[] \fBMoreData\fP (byte[] data)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBPluginName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 32 of file NativePasswordPlugins\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
