.TH "Newtonsoft.Json.JsonArrayAttribute" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.JsonArrayAttribute \- 
.PP
Instructs the \fBJsonSerializer\fP how to serialize the collection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.JsonContainerAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonArrayAttribute\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBJsonArrayAttribute\fP class\&. \fP"
.ti -1c
.RI "\fBJsonArrayAttribute\fP (bool allowNullItems)"
.br
.RI "\fIInitializes a new instance of the \fBJsonObjectAttribute\fP class with a flag indicating whether the array can contain null items \fP"
.ti -1c
.RI "\fBJsonArrayAttribute\fP (string id)"
.br
.RI "\fIInitializes a new instance of the \fBJsonArrayAttribute\fP class with the specified container Id\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBAllowNullItems\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether null items are allowed in the collection\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Instructs the \fBJsonSerializer\fP how to serialize the collection\&. 


.PP
Definition at line 34 of file JsonArrayAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.JsonArrayAttribute\&.JsonArrayAttribute ()"

.PP
Initializes a new instance of the \fBJsonArrayAttribute\fP class\&. 
.PP
Definition at line 51 of file JsonArrayAttribute\&.cs\&.
.SS "Newtonsoft\&.Json\&.JsonArrayAttribute\&.JsonArrayAttribute (boolallowNullItems)"

.PP
Initializes a new instance of the \fBJsonObjectAttribute\fP class with a flag indicating whether the array can contain null items 
.PP
\fBParameters:\fP
.RS 4
\fIallowNullItems\fP A flag indicating whether the array can contain null items\&.
.RE
.PP

.PP
Definition at line 59 of file JsonArrayAttribute\&.cs\&.
.SS "Newtonsoft\&.Json\&.JsonArrayAttribute\&.JsonArrayAttribute (stringid)"

.PP
Initializes a new instance of the \fBJsonArrayAttribute\fP class with the specified container Id\&. 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP The container Id\&.
.RE
.PP

.PP
Definition at line 68 of file JsonArrayAttribute\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool Newtonsoft\&.Json\&.JsonArrayAttribute\&.AllowNullItems\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether null items are allowed in the collection\&. \fCtrue\fP if null items are allowed in the collection; otherwise, \fCfalse\fP\&.
.PP
Definition at line 43 of file JsonArrayAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
