.TH "Newtonsoft.Json.Serialization.DiagnosticsTraceWriter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.DiagnosticsTraceWriter \- 
.PP
Represents a trace writer that writes to the application's TraceListener instances\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Serialization\&.ITraceWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTrace\fP (TraceLevel level, string message, Exception ex)"
.br
.RI "\fIWrites the specified trace level, message and optional exception\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TraceLevel \fBLevelFilter\fP\fC [get, set]\fP"
.br
.RI "\fIGets the TraceLevel that will be used to filter the trace messages passed to the writer\&. For example a filter level of \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a trace writer that writes to the application's TraceListener instances\&. 


.PP
Definition at line 11 of file DiagnosticsTraceWriter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Newtonsoft\&.Json\&.Serialization\&.DiagnosticsTraceWriter\&.Trace (TraceLevellevel, stringmessage, Exceptionex)"

.PP
Writes the specified trace level, message and optional exception\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP The TraceLevel at which to write this trace\&.
.br
\fImessage\fP The trace message\&.
.br
\fIex\fP The trace exception\&. This parameter is optional\&.
.RE
.PP

.PP
Implements \fBNewtonsoft\&.Json\&.Serialization\&.ITraceWriter\fP\&.
.PP
Definition at line 46 of file DiagnosticsTraceWriter\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "TraceLevel Newtonsoft\&.Json\&.Serialization\&.DiagnosticsTraceWriter\&.LevelFilter\fC [get]\fP, \fC [set]\fP"

.PP
Gets the TraceLevel that will be used to filter the trace messages passed to the writer\&. For example a filter level of \fCInfo\fP will exclude \fCVerbose\fP messages and include \fCInfo\fP, \fCWarning\fP and \fCError\fP messages\&. 
.PP
The TraceLevel that will be used to filter the trace messages passed to the writer\&. 
.PP
Definition at line 21 of file DiagnosticsTraceWriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
