.TH "Newtonsoft.Json.Serialization.JsonDictionaryContract" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.JsonDictionaryContract \- 
.PP
Contract details for a Type used by the \fBJsonSerializer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Serialization\&.JsonContainerContract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonDictionaryContract\fP (Type underlyingType)"
.br
.RI "\fIInitializes a new instance of the \fBJsonDictionaryContract\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< string, string > \fBPropertyNameResolver\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the property name resolver\&. \fP"
.ti -1c
.RI "Type \fBDictionaryKeyType\fP\fC [get, set]\fP"
.br
.RI "\fIGets the Type of the dictionary keys\&. \fP"
.ti -1c
.RI "Type \fBDictionaryValueType\fP\fC [get, set]\fP"
.br
.RI "\fIGets the Type of the dictionary values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contract details for a Type used by the \fBJsonSerializer\fP\&. 


.PP
Definition at line 41 of file JsonDictionaryContract\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.Serialization\&.JsonDictionaryContract\&.JsonDictionaryContract (TypeunderlyingType)"

.PP
Initializes a new instance of the \fBJsonDictionaryContract\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIunderlyingType\fP The underlying type for the contract\&.
.RE
.PP

.PP
Definition at line 77 of file JsonDictionaryContract\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Type Newtonsoft\&.Json\&.Serialization\&.JsonDictionaryContract\&.DictionaryKeyType\fC [get]\fP, \fC [set]\fP"

.PP
Gets the Type of the dictionary keys\&. The Type of the dictionary keys\&.
.PP
Definition at line 53 of file JsonDictionaryContract\&.cs\&.
.SS "Type Newtonsoft\&.Json\&.Serialization\&.JsonDictionaryContract\&.DictionaryValueType\fC [get]\fP, \fC [set]\fP"

.PP
Gets the Type of the dictionary values\&. The Type of the dictionary values\&.
.PP
Definition at line 58 of file JsonDictionaryContract\&.cs\&.
.SS "Func<string, string> Newtonsoft\&.Json\&.Serialization\&.JsonDictionaryContract\&.PropertyNameResolver\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the property name resolver\&. The property name resolver\&.
.PP
Definition at line 47 of file JsonDictionaryContract\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
