.TH "Newtonsoft.Json.JsonPropertyAttribute" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.JsonPropertyAttribute \- 
.PP
Instructs the \fBJsonSerializer\fP to always serialize the member with the specified name\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonPropertyAttribute\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBJsonPropertyAttribute\fP class\&. \fP"
.ti -1c
.RI "\fBJsonPropertyAttribute\fP (string propertyName)"
.br
.RI "\fIInitializes a new instance of the \fBJsonPropertyAttribute\fP class with the specified name\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBItemConverterType\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the converter used when serializing the property's collection items\&. \fP"
.ti -1c
.RI "\fBNullValueHandling\fP \fBNullValueHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the null value handling used when serializing this property\&. \fP"
.ti -1c
.RI "\fBDefaultValueHandling\fP \fBDefaultValueHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the default value handling used when serializing this property\&. \fP"
.ti -1c
.RI "\fBReferenceLoopHandling\fP \fBReferenceLoopHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the reference loop handling used when serializing this property\&. \fP"
.ti -1c
.RI "\fBObjectCreationHandling\fP \fBObjectCreationHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the object creation handling used when deserializing this property\&. \fP"
.ti -1c
.RI "\fBTypeNameHandling\fP \fBTypeNameHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the type name handling used when serializing this property\&. \fP"
.ti -1c
.RI "bool \fBIsReference\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets whether this property's value is serialized as a reference\&. \fP"
.ti -1c
.RI "int \fBOrder\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the order of serialization and deserialization of a member\&. \fP"
.ti -1c
.RI "\fBRequired\fP \fBRequired\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether this property is required\&. \fP"
.ti -1c
.RI "string \fBPropertyName\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the name of the property\&. \fP"
.ti -1c
.RI "\fBReferenceLoopHandling\fP \fBItemReferenceLoopHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the the reference loop handling used when serializing the property's collection items\&. \fP"
.ti -1c
.RI "\fBTypeNameHandling\fP \fBItemTypeNameHandling\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the the type name handling used when serializing the property's collection items\&. \fP"
.ti -1c
.RI "bool \fBItemIsReference\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets whether this property's collection items are serialized as a reference\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Instructs the \fBJsonSerializer\fP to always serialize the member with the specified name\&. 


.PP
Definition at line 34 of file JsonPropertyAttribute\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.JsonPropertyAttribute\&.JsonPropertyAttribute ()"

.PP
Initializes a new instance of the \fBJsonPropertyAttribute\fP class\&. 
.PP
Definition at line 177 of file JsonPropertyAttribute\&.cs\&.
.SS "Newtonsoft\&.Json\&.JsonPropertyAttribute\&.JsonPropertyAttribute (stringpropertyName)"

.PP
Initializes a new instance of the \fBJsonPropertyAttribute\fP class with the specified name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP Name of the property\&.
.RE
.PP

.PP
Definition at line 185 of file JsonPropertyAttribute\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBDefaultValueHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.DefaultValueHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the default value handling used when serializing this property\&. The default value handling\&.
.PP
Definition at line 71 of file JsonPropertyAttribute\&.cs\&.
.SS "bool Newtonsoft\&.Json\&.JsonPropertyAttribute\&.IsReference\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets whether this property's value is serialized as a reference\&. Whether this property's value is serialized as a reference\&.
.PP
Definition at line 111 of file JsonPropertyAttribute\&.cs\&.
.SS "Type Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ItemConverterType\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the converter used when serializing the property's collection items\&. The collection's items converter\&.
.PP
Definition at line 54 of file JsonPropertyAttribute\&.cs\&.
.SS "bool Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ItemIsReference\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets whether this property's collection items are serialized as a reference\&. Whether this property's collection items are serialized as a reference\&.
.PP
Definition at line 169 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBReferenceLoopHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ItemReferenceLoopHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the the reference loop handling used when serializing the property's collection items\&. The collection's items reference loop handling\&.
.PP
Definition at line 149 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBTypeNameHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ItemTypeNameHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the the type name handling used when serializing the property's collection items\&. The collection's items type name handling\&.
.PP
Definition at line 159 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBNullValueHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.NullValueHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the null value handling used when serializing this property\&. The null value handling\&.
.PP
Definition at line 61 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBObjectCreationHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ObjectCreationHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the object creation handling used when deserializing this property\&. The object creation handling\&.
.PP
Definition at line 91 of file JsonPropertyAttribute\&.cs\&.
.SS "int Newtonsoft\&.Json\&.JsonPropertyAttribute\&.Order\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the order of serialization and deserialization of a member\&. The numeric order of serialization or deserialization\&.
.PP
Definition at line 121 of file JsonPropertyAttribute\&.cs\&.
.SS "string Newtonsoft\&.Json\&.JsonPropertyAttribute\&.PropertyName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the property\&. The name of the property\&.
.PP
Definition at line 142 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBReferenceLoopHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.ReferenceLoopHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the reference loop handling used when serializing this property\&. The reference loop handling\&.
.PP
Definition at line 81 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBRequired\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.Required\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether this property is required\&. A value indicating whether this property is required\&. 
.PP
Definition at line 133 of file JsonPropertyAttribute\&.cs\&.
.SS "\fBTypeNameHandling\fP Newtonsoft\&.Json\&.JsonPropertyAttribute\&.TypeNameHandling\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the type name handling used when serializing this property\&. The type name handling\&.
.PP
Definition at line 101 of file JsonPropertyAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
