.TH "NHibernate.Test.Criteria.DetachedCriteriaSerializable" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.DetachedCriteriaSerializable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAllCriterionAreSerializable\fP ()"
.br
.ti -1c
.RI "void \fBAllProjectionAreSerializable\fP ()"
.br
.ti -1c
.RI "void \fBAllEmbeddedResultTransformersAreSerializable\fP ()"
.br
.ti -1c
.RI "void \fBDetachedCriteriaItSelf\fP ()"
.br
.ti -1c
.RI "void \fBBasicCriterions\fP ()"
.br
.ti -1c
.RI "void \fBLikeCriterions\fP ()"
.br
.ti -1c
.RI "void \fBLogicalCriterions\fP ()"
.br
.ti -1c
.RI "void \fBProjectionsExpressions\fP ()"
.br
.ti -1c
.RI "void \fBJunctions\fP ()"
.br
.ti -1c
.RI "void \fBSubqueriesExpressions\fP ()"
.br
.ti -1c
.RI "void \fBSQLCriterion\fP ()"
.br
.ti -1c
.RI "void \fBSQLProjection\fP ()"
.br
.ti -1c
.RI "void \fBResultTransformes\fP ()"
.br
.ti -1c
.RI "void \fBExecutableCriteria\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file DetachedCriteriaSerializable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
