.TH "NHibernate.Dialect.Function.VarArgsSQLFunction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Function.VarArgsSQLFunction \- 
.PP
Support for slightly more general templating than \fBStandardSQLFunction\fP, with an unlimited number of arguments\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVarArgsSQLFunction\fP (string begin, string sep, string end)"
.br
.ti -1c
.RI "\fBVarArgsSQLFunction\fP (\fBIType\fP type, string begin, string sep, string end)"
.br
.ti -1c
.RI "virtual \fBIType\fP \fBReturnType\fP (\fBIType\fP columnType, \fBIMapping\fP mapping)"
.br
.RI "\fIThe function return type \fP"
.ti -1c
.RI "\fBSqlString\fP \fBRender\fP (IList args, \fBISessionFactoryImplementor\fP factory)"
.br
.RI "\fIRender the function call as SQL\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHasArguments\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBHasParenthesesIfNoArguments\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Support for slightly more general templating than \fBStandardSQLFunction\fP, with an unlimited number of arguments\&. 


.PP
Definition at line 15 of file VarArgsSQLFunction\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSqlString\fP NHibernate\&.Dialect\&.Function\&.VarArgsSQLFunction\&.Render (IListargs, \fBISessionFactoryImplementor\fPfactory)"

.PP
Render the function call as SQL\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP List of arguments
.br
\fIfactory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
SQL fragment for the fuction\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.PP
Definition at line 52 of file VarArgsSQLFunction\&.cs\&.
.SS "virtual \fBIType\fP NHibernate\&.Dialect\&.Function\&.VarArgsSQLFunction\&.ReturnType (\fBIType\fPcolumnType, \fBIMapping\fPmapping)\fC [virtual]\fP"

.PP
The function return type 
.PP
\fBParameters:\fP
.RS 4
\fIcolumnType\fP The type of the first argument
.br
\fImapping\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.PP
Definition at line 37 of file VarArgsSQLFunction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
