.TH "NHibernate.Mapping.ByCode.IConformistHoldersProvider" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IConformistHoldersProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.ClassCustomizer< TEntity >\fP, \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.ComponentCustomizer< TComponent >\fP, \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.JoinedSubclassCustomizer< TEntity >\fP, \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.SubclassCustomizer< TEntity >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.UnionSubclassCustomizer< TEntity >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBICustomizersHolder\fP \fBCustomizersHolder\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIModelExplicitDeclarationsHolder\fP \fBExplicitDeclarationsHolder\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file IConformistHoldersProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
