.TH "NHibernate.Test.NHSpecificTest.NH2976.Employer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2976.Employer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAddEmployee1\fP (\fBEmployee\fP employee)"
.br
.ti -1c
.RI "virtual void \fBAddEmployee2\fP (\fBEmployee\fP employee)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual Guid \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IDictionary< Guid, 
.br
\fBEmployee\fP > \fBEmployees1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IDictionary \fBEmployees2\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Employer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
