.TH "NHibernate.Test.MappingByCode.ConventionModelMapperTests.PropertyToFieldAccessorTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.ConventionModelMapperTests.PropertyToFieldAccessorTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenFieldAccessToField\fP ()"
.br
.ti -1c
.RI "void \fBWhenAutoPropertyNoAccessor\fP ()"
.br
.ti -1c
.RI "void \fBWhenPropertyWithSameBackFieldNoMatch\fP ()"
.br
.ti -1c
.RI "void \fBWhenReadOnlyPropertyWithSameBackFieldNoMatch\fP ()"
.br
.ti -1c
.RI "void \fBWhenPropertyWithoutFieldNoMatch\fP ()"
.br
.ti -1c
.RI "void \fBWhenPropertyWithDifferentBackFieldMatch\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetOnlyPropertyNoMatch\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file PropertyToFieldAccessorTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
