.TH "NHibernate.Linq.NhLinqExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.NhLinqExpression \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.IQueryExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNhLinqExpression\fP (Expression expression, \fBISessionFactoryImplementor\fP sessionFactory)"
.br
.ti -1c
.RI "\fBIASTNode\fP \fBTranslate\fP (\fBISessionFactoryImplementor\fP sessionFactory, bool filter)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "System\&.Type \fBType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList< \fBNamedParameterDescriptor\fP > \fBParameterDescriptors\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "NhLinqExpressionReturnType \fBReturnType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IDictionary< string, Tuple
.br
< object, \fBIType\fP > > \fBParameterValuesByName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBExpressionToHqlTranslationResults\fP \fBExpressionToHqlTranslationResults\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file NhLinqExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
