.TH "NHibernate.Linq.NestedSelects.SelectClauseRewriter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.NestedSelects.SelectClauseRewriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ExpressionTreeVisitor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectClauseRewriter\fP (Expression parameter, ICollection< \fBExpressionHolder\fP > expressions, Expression expression, Dictionary< Expression, Expression > dictionary)"
.br
.ti -1c
.RI "\fBSelectClauseRewriter\fP (Expression parameter, ICollection< \fBExpressionHolder\fP > expressions, Expression expression, int tuple, Dictionary< Expression, Expression > dictionary)"
.br
.ti -1c
.RI "override Expression \fBVisitExpression\fP (Expression expression)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override Expression \fBVisitMemberExpression\fP (MemberExpression expression)"
.br
.ti -1c
.RI "override Expression \fBVisitQuerySourceReferenceExpression\fP (QuerySourceReferenceExpression expression)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file SelectClauseRewriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
