.TH "NHibernate.Linq.Visitors.ResultOperatorProcessors.ProcessResultOperatorReturn" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Visitors.ResultOperatorProcessors.ProcessResultOperatorReturn \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHqlTreeNode\fP \fBTreeNode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Action< \fBIQuery\fP, IDictionary
.br
< string, Tuple< object, \fBIType\fP > > > \fBAdditionalCriteria\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "LambdaExpression \fBListTransformer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "LambdaExpression \fBPostExecuteTransformer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHqlBooleanExpression\fP \fBWhereClause\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHqlGroupBy\fP \fBGroupBy\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHqlTreeNode\fP \fBAdditionalFrom\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ProcessResultOperatorReturn\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
