.TH "NHibernate.Tool.hbm2ddl.DatabaseMetadata" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Tool.hbm2ddl.DatabaseMetadata \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabaseMetadata\fP (DbConnection connection, \fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "\fBDatabaseMetadata\fP (DbConnection connection, \fBDialect\&.Dialect\fP dialect, bool extras)"
.br
.ti -1c
.RI "\fBITableMetadata\fP \fBGetTableMetadata\fP (string name, string schema, string catalog, bool isQuoted)"
.br
.ti -1c
.RI "bool \fBIsSequence\fP (object key)"
.br
.ti -1c
.RI "bool \fBIsTable\fP (object key)"
.br
.ti -1c
.RI "override String \fBToString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file DatabaseMetadata\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
