.TH "NHibernate.Test.MappingByCode.MappersTests.DynamicComponentMapperTests.ListPropertyOnDynamicCompoTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests.DynamicComponentMapperTests.ListPropertyOnDynamicCompoTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenAddThenHas\fP ()"
.br
.ti -1c
.RI "void \fBWhenCustomizeThenCallCustomizer\fP ()"
.br
.ti -1c
.RI "void \fBWhenCustomizeAccessorThenIgnore\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ListPropertyOnDynamicCompoTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
