.TH "NHibernate.DomainModel.NHSpecific.ParentComparer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.NHSpecific.ParentComparer \- 
.PP
Summary description for \fBParentComparer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparer< Parent >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompare\fP (\fBParent\fP x, \fBParent\fP y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBParentComparer\fP\&. 


.PP
Definition at line 11 of file ParentComparer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
