.TH "NHibernate.Test.DynamicProxyTests.InterfaceProxySerializationTests.IMyProxy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicProxyTests.InterfaceProxySerializationTests.IMyProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.DynamicProxyTests\&.InterfaceProxySerializationTests\&.MyProxyImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBThrowDeepException\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file IMyProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
