.TH "NHibernate.AdoNet.NonBatchingBatcherFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.AdoNet.NonBatchingBatcherFactory \- 
.PP
A BatcherFactory implementation which constructs Batcher instances that do not perform batch operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.AdoNet\&.IBatcherFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBIBatcher\fP \fBCreateBatcher\fP (\fBConnectionManager\fP connectionManager, \fBIInterceptor\fP interceptor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A BatcherFactory implementation which constructs Batcher instances that do not perform batch operations\&. 


.PP
Definition at line 9 of file NonBatchingBatcherFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
