.TH "NHibernate.Test.Criteria.Lambda.CriteriaAssertFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.Lambda.CriteriaAssertFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.LambdaFixtureBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDifferentTypes\fP ()"
.br
.ti -1c
.RI "void \fBDifferentAliases\fP ()"
.br
.ti -1c
.RI "void \fBDifferentOperators\fP ()"
.br
.ti -1c
.RI "void \fBDifferentPaths\fP ()"
.br
.ti -1c
.RI "void \fBDifferentValues\fP ()"
.br
.ti -1c
.RI "void \fBDifferentNestedCriterion\fP ()"
.br
.ti -1c
.RI "void \fBDifferentOrder\fP ()"
.br
.ti -1c
.RI "void \fBDifferentSubCriteria\fP ()"
.br
.ti -1c
.RI "void \fBDifferentJoinType\fP ()"
.br
.ti -1c
.RI "void \fBDifferentFetchMode\fP ()"
.br
.ti -1c
.RI "void \fBDifferentLockMode\fP ()"
.br
.ti -1c
.RI "void \fBDifferentProjections\fP ()"
.br
.ti -1c
.RI "void \fBDifferentPropertyName\fP ()"
.br
.ti -1c
.RI "void \fBDifferentSubquery\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file CriteriaAssertFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
