.TH "NHibernate.Test.Cascade.Circle.Route" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Cascade.Circle.Route \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual long \fBRouteId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual long \fBVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBNode\fP > \fBNodes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBVehicle\fP > \fBVehicles\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBTransientField\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Route\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
