.TH "NHibernate.Bytecode.CodeDom.BytecodeProviderImpl.Generator" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Bytecode.CodeDom.BytecodeProviderImpl.Generator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenerator\fP (System\&.Type mappedClass, \fBIGetter\fP[] getters, \fBISetter\fP[] setters)"
.br
.RI "\fIctor \fP"
.ti -1c
.RI "\fBIReflectionOptimizer\fP \fBCreateReflectionOptimizer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file BytecodeProviderImpl\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Bytecode\&.CodeDom\&.BytecodeProviderImpl\&.Generator\&.Generator (System\&.TypemappedClass, \fBIGetter\fP[]getters, \fBISetter\fP[]setters)"

.PP
ctor 
.PP
\fBParameters:\fP
.RS 4
\fImappedClass\fP The target class
.br
\fIsetters\fP Array of setters
.br
\fIgetters\fP Array of getters
.RE
.PP

.PP
Definition at line 80 of file BytecodeProviderImpl\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
