.TH "NHibernate.Test.NHSpecificTest.NH1549" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1549 \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCategoryWithInheritedId\fP"
.br
.ti -1c
.RI "class \fBCategoryWithId\fP"
.br
.ti -1c
.RI "class \fBEntityInt32\fP"
.br
.ti -1c
.RI "class \fBFixture\fP"
.br
.ti -1c
.RI "class \fBProductWithInheritedId\fP"
.br
.ti -1c
.RI "class \fBProductWithId\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
