.TH "NHibernate.Test.NHSpecificTest.NH1574.TeamStorage" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1574.TeamStorage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.SpecializedTeamStorage\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's Name \fP"
.ti -1c
.RI "virtual int \fBEloRanking\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's EloRanking \fP"
.ti -1c
.RI "virtual int \fBMaxElo\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's MaxElo \fP"
.ti -1c
.RI "virtual int \fBMinElo\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's MinElo \fP"
.ti -1c
.RI "virtual DateTime \fBCreationDate\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's CreationDate \fP"
.ti -1c
.RI "virtual int \fBNumberPlayedBattles\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's NumberPlayedBattles \fP"
.ti -1c
.RI "virtual bool \fBLadderActive\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's LadderActive \fP"
.ti -1c
.RI "virtual int \fBLadderPosition\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's LadderPosition \fP"
.ti -1c
.RI "virtual int \fBIsInBattle\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's IsInBattle \fP"
.ti -1c
.RI "virtual int \fBRestUntil\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's RestUntil \fP"
.ti -1c
.RI "virtual int \fBStoppedUntil\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBTeamStorage\fP's StoppedUntil \fP"
.ti -1c
.RI "virtual IList< \fBPrincipal\fP > \fBPrincipals\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Team\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual DateTime NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.CreationDate\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's CreationDate 
.PP
Definition at line 63 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.EloRanking\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's EloRanking 
.PP
Definition at line 36 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.IsInBattle\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's IsInBattle 
.PP
Definition at line 99 of file Team\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.LadderActive\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's LadderActive 
.PP
Definition at line 81 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.LadderPosition\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's LadderPosition 
.PP
Definition at line 90 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.MaxElo\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's MaxElo 
.PP
Definition at line 45 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.MinElo\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's MinElo 
.PP
Definition at line 54 of file Team\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's Name 
.PP
Definition at line 27 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.NumberPlayedBattles\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's NumberPlayedBattles 
.PP
Definition at line 72 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.RestUntil\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's RestUntil 
.PP
Definition at line 108 of file Team\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.TeamStorage\&.StoppedUntil\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBTeamStorage\fP's StoppedUntil 
.PP
Definition at line 117 of file Team\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
