.TH "NHibernate.Event.FlushEvent" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.FlushEvent \- 
.PP
Defines an event class for the flushing of a session\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.AbstractEvent\fP\&.
.PP
Inherited by \fBNHibernate\&.Event\&.AutoFlushEvent\fP, and \fBNHibernate\&.Event\&.DirtyCheckEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlushEvent\fP (\fBIEventSource\fP source)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Defines an event class for the flushing of a session\&. 


.PP
Definition at line 7 of file FlushEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
