.TH "NHibernate.Linq.Visitors.Joiner" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Visitors.Joiner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Linq\&.Visitors\&.IJoiner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Expression \fBAddJoin\fP (Expression expression, string key)"
.br
.ti -1c
.RI "void \fBMakeInnerIfJoined\fP (string key)"
.br
.ti -1c
.RI "bool \fBCanAddJoin\fP (Expression expression)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBNhJoinClause\fP > \fBJoins\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file JoinBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
