.TH "NHibernate.Test.GenericTest.EnumGeneric" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.GenericTest.EnumGeneric \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBA\fP"
.br
.ti -1c
.RI "class \fBEnumGenericFixture\fP"
.br
.RI "\fIhttp://jira.nhibernate.org/browse/NH-1236 \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBB\fP { \fBValue1\fP, \fBValue2\fP, \fBValue3\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
