.TH "NHibernate.Test.UtilityTest.SingletonEnumerableFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UtilityTest.SingletonEnumerableFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDifferentEnumeratorInEachRequest\fP ()"
.br
.ti -1c
.RI "void \fBShouldWorkInForeach\fP ()"
.br
.ti -1c
.RI "void \fBShouldWorkAsEnumerator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file SingletonEnumerableFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
