.TH "NHibernate.Event.IPostInsertEventListener" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.IPostInsertEventListener \- 
.PP
Called after inserting an item in the datastore  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostInsert\fP (\fBPostInsertEvent\fP @event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Called after inserting an item in the datastore 


.PP
Definition at line 4 of file IPostInsertEventListener\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Event\&.IPostInsertEventListener\&.OnPostInsert (\fBPostInsertEvent\fP @event)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIevent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
