.TH "NHibernate.Test.ExpressionTest.Projection.ProjectionReport" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ExpressionTest.Projection.ProjectionReport \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProjectionReport\fP (double avgPay, double maxPay, double minPay)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBMinPay\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBMaxPay\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBAvgPay\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 116 of file ProjectionSqlFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
