.TH "NHibernate.Test.UserCollection.MyList" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UserCollection.MyList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayList\&.
.SH "Detailed Description"
.PP 
Definition at line 6 of file MyList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
