.TH "NHibernate.Proxy.DynamicProxy.IInterceptor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Proxy.DynamicProxy.IInterceptor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Intercept\&.DefaultDynamicLazyFieldInterceptor\fP, \fBNHibernate\&.Proxy\&.DefaultLazyInitializer\fP, \fBNHibernate\&.Test\&.DynamicEntity\&.DataProxyHandler\fP, \fBNHibernate\&.Test\&.DynamicProxyTests\&.InterfaceWithEqualsGethashcodeTests\&.InterceptedMethodsExposer\fP, and \fBNHibernate\&.Test\&.DynamicProxyTests\&.PassThroughInterceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBIntercept\fP (\fBInvocationInfo\fP info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file IInterceptor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
