.TH "NHibernate.Bytecode.Lightweight" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Bytecode.Lightweight \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccessOptimizer\fP"
.br
.ti -1c
.RI "class \fBBytecodeProviderImpl\fP"
.br
.RI "\fIFactory that generate object based on \fBIReflectionOptimizer\fP needed to replace the use of reflection\&. \fP"
.ti -1c
.RI "class \fBReflectionOptimizer\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBSetterCallback\fP (object obj, int index, object value)"
.br
.ti -1c
.RI "delegate object \fBGetterCallback\fP (object obj, int index)"
.br
.ti -1c
.RI "delegate object[] \fBGetPropertyValuesInvoker\fP (object obj, GetterCallback callback)"
.br
.ti -1c
.RI "delegate void \fBSetPropertyValuesInvoker\fP (object obj, object[] values, SetterCallback callback)"
.br
.ti -1c
.RI "delegate object \fBCreateInstanceInvoker\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
