.TH "NHibernate.Test.NHSpecificTest.NH1574.Principal" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1574.Principal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.SpecializedPrincipal\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBot\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's IsBot \fP"
.ti -1c
.RI "virtual int \fBMyStatsId\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's MyStatsId \fP"
.ti -1c
.RI "virtual int \fBEloRanking\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's EloRanking \fP"
.ti -1c
.RI "virtual bool \fBReceiveMail\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's ReceiveMail \fP"
.ti -1c
.RI "virtual int \fBCredits\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Credits \fP"
.ti -1c
.RI "virtual bool \fBLadderActive\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's LadderActive \fP"
.ti -1c
.RI "virtual int \fBLadderPosition\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's LadderPosition \fP"
.ti -1c
.RI "virtual int \fBIsInBattle\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's IsInBattle \fP"
.ti -1c
.RI "virtual int \fBRestUntil\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's RestUntil \fP"
.ti -1c
.RI "virtual int \fBStoppedUntil\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's StoppedUntil \fP"
.ti -1c
.RI "virtual int \fBAvailableVacationTicks\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's AvailableVacationTicks \fP"
.ti -1c
.RI "virtual int \fBVacationStartTick\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's VacationStartTick \fP"
.ti -1c
.RI "virtual int \fBVacationEndtick\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's VacationEndtick \fP"
.ti -1c
.RI "virtual bool \fBAutoStartVacations\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's AutoStartVacations \fP"
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Name \fP"
.ti -1c
.RI "virtual string \fBPassword\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Password \fP"
.ti -1c
.RI "virtual string \fBEmail\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Email \fP"
.ti -1c
.RI "virtual string \fBIp\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Ip \fP"
.ti -1c
.RI "virtual DateTime \fBRegistDate\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's RegistDate \fP"
.ti -1c
.RI "virtual DateTime \fBLastLogin\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's LastLogin \fP"
.ti -1c
.RI "virtual bool \fBApproved\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Approved \fP"
.ti -1c
.RI "virtual bool \fBIsOnline\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's IsOnline \fP"
.ti -1c
.RI "virtual bool \fBLocked\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Locked \fP"
.ti -1c
.RI "virtual string \fBLocale\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's Locale \fP"
.ti -1c
.RI "virtual string \fBConfirmationCode\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's ConfirmationCode \fP"
.ti -1c
.RI "virtual string \fBRawRoles\fP\fC [get, set]\fP"
.br
.RI "\fIGets the \fBPrincipal\fP's RawRoles \fP"
.ti -1c
.RI "virtual \fBSpecializedTeamStorage\fP \fBTeam\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Principal\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Approved\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Approved 
.PP
Definition at line 227 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.AutoStartVacations\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's AutoStartVacations 
.PP
Definition at line 164 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.AvailableVacationTicks\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's AvailableVacationTicks 
.PP
Definition at line 137 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.ConfirmationCode\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's ConfirmationCode 
.PP
Definition at line 263 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Credits\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Credits 
.PP
Definition at line 83 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.EloRanking\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's EloRanking 
.PP
Definition at line 65 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Email\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Email 
.PP
Definition at line 191 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Ip\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Ip 
.PP
Definition at line 200 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.IsBot\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's IsBot 
.PP
Definition at line 47 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.IsInBattle\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's IsInBattle 
.PP
Definition at line 110 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.IsOnline\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's IsOnline 
.PP
Definition at line 236 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.LadderActive\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's LadderActive 
.PP
Definition at line 92 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.LadderPosition\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's LadderPosition 
.PP
Definition at line 101 of file Principal\&.cs\&.
.SS "virtual DateTime NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.LastLogin\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's LastLogin 
.PP
Definition at line 218 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Locale\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Locale 
.PP
Definition at line 254 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Locked\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Locked 
.PP
Definition at line 245 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.MyStatsId\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's MyStatsId 
.PP
Definition at line 56 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Name 
.PP
Definition at line 173 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.Password\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's Password 
.PP
Definition at line 182 of file Principal\&.cs\&.
.SS "virtual string NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.RawRoles\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's RawRoles 
.PP
Definition at line 272 of file Principal\&.cs\&.
.SS "virtual bool NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.ReceiveMail\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's ReceiveMail 
.PP
Definition at line 74 of file Principal\&.cs\&.
.SS "virtual DateTime NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.RegistDate\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's RegistDate 
.PP
Definition at line 209 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.RestUntil\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's RestUntil 
.PP
Definition at line 119 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.StoppedUntil\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's StoppedUntil 
.PP
Definition at line 128 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.VacationEndtick\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's VacationEndtick 
.PP
Definition at line 155 of file Principal\&.cs\&.
.SS "virtual int NHibernate\&.Test\&.NHSpecificTest\&.NH1574\&.Principal\&.VacationStartTick\fC [get]\fP, \fC [set]\fP"

.PP
Gets the \fBPrincipal\fP's VacationStartTick 
.PP
Definition at line 146 of file Principal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
