.TH "NHibernate.Mapping.ByCode.IComponentElementMapper< TComponent >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IComponentElementMapper< TComponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IComponentAttributesMapper< TComponent >\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.ComponentElementCustomizer< TComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProperty< TProperty >\fP (Expression< Func< TComponent, TProperty >> property, Action< \fBIPropertyMapper\fP > mapping)"
.br
.ti -1c
.RI "void \fBProperty< TProperty >\fP (Expression< Func< TComponent, TProperty >> property)"
.br
.ti -1c
.RI "void \fBComponent< TNestedComponent >\fP (Expression< Func< TComponent, TNestedComponent >> property, Action< \fBIComponentElementMapper\fP< TNestedComponent >> mapping)"
.br
.ti -1c
.RI "void \fBManyToOne< TProperty >\fP (Expression< Func< TComponent, TProperty >> property, Action< \fBIManyToOneMapper\fP > mapping)"
.br
.ti -1c
.RI "void \fBManyToOne< TProperty >\fP (Expression< Func< TComponent, TProperty >> property)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file IComponentElementMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
