.TH "NHibernate.Loader.Collection.CollectionJoinWalker" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.Collection.CollectionJoinWalker \- 
.PP
Superclass of walkers for collection initializers 
.PP
\fBSee Also:\fP
.RS 4
\fBCollectionLoader\fP, \fBOneToManyJoinWalker\fP, \fBBasicCollectionJoinWalker\fP
.PP
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Loader\&.JoinWalker\fP\&.
.PP
Inherited by \fBNHibernate\&.Loader\&.Collection\&.BasicCollectionJoinWalker\fP, and \fBNHibernate\&.Loader\&.Collection\&.OneToManyJoinWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionJoinWalker\fP (\fBISessionFactoryImplementor\fP factory, IDictionary< string, \fBIFilter\fP > enabledFilters)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSqlStringBuilder\fP \fBWhereString\fP (string alias, string[] columnNames, \fBSqlString\fP subselect, int batchSize)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Superclass of walkers for collection initializers 
.PP
\fBSee Also:\fP
.RS 4
\fBCollectionLoader\fP, \fBOneToManyJoinWalker\fP, \fBBasicCollectionJoinWalker\fP
.PP
.RE
.PP



.PP
Definition at line 14 of file CollectionJoinWalker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
