.TH "NHibernate.Cfg.Settings" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.Settings \- 
.PP
\fBSettings\fP that affect the behavior of \fBNHibernate\fP at runtime\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSqlStatementLogger\fP \fBSqlStatementLogger\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBMaximumFetchDepth\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IDictionary< string, string > \fBQuerySubstitutions\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBDialect\&.Dialect\fP \fBDialect\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBAdoBatchSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBDefaultBatchFetchSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsScrollableResultSetsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsGetGeneratedKeysEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDefaultSchemaName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBDefaultCatalogName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSessionFactoryName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoCreateSchema\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoDropSchema\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoUpdateSchema\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoValidateSchema\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoQuoteEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsKeywordsImportEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsQueryCacheEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsStructuredCacheEntriesEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsSecondLevelCacheEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCacheRegionPrefix\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsMinimalPutsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsCommentsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsStatisticsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsIdentifierRollbackEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsFlushBeforeCompletionEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsAutoCloseSessionEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ConnectionReleaseMode \fBConnectionReleaseMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBICacheProvider\fP \fBCacheProvider\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIQueryCacheFactory\fP \fBQueryCacheFactory\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIConnectionProvider\fP \fBConnectionProvider\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBITransactionFactory\fP \fBTransactionFactory\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIBatcherFactory\fP \fBBatcherFactory\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIQueryTranslatorFactory\fP \fBQueryTranslatorFactory\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBISQLExceptionConverter\fP \fBSqlExceptionConverter\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsWrapResultSetsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsOrderUpdatesEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsOrderInsertsEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBEntityMode\fP \fBDefaultEntityMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDataDefinitionImplicitCommit\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDataDefinitionInTransactionSupported\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsNamedQueryStartupCheckingEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IsolationLevel \fBIsolationLevel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsOuterJoinFetchEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBILinqToHqlGeneratorsRegistry\fP \fBLinqToHqlGeneratorsRegistry\fP\fC [get, set]\fP"
.br
.RI "\fIGet the registry to provide Hql-Generators for known properties/methods\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBSettings\fP that affect the behavior of \fBNHibernate\fP at runtime\&. 


.PP
Definition at line 17 of file Settings\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBILinqToHqlGeneratorsRegistry\fP NHibernate\&.Cfg\&.Settings\&.LinqToHqlGeneratorsRegistry\fC [get]\fP, \fC [set]\fP"

.PP
Get the registry to provide Hql-Generators for known properties/methods\&. 
.PP
Definition at line 126 of file Settings\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
