.TH "NHibernate.Loader.TopologicalSorter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.TopologicalSorter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTopologicalSorter\fP (int size)"
.br
.ti -1c
.RI "int \fBAddVertex\fP (int vertex)"
.br
.ti -1c
.RI "void \fBAddEdge\fP (int start, int end)"
.br
.ti -1c
.RI "int[] \fBSort\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TopologicalSorter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
