.TH "NHibernate.Test.UtilityTest.TypeNameParserFixture.MyComplexClass< T1, T2, T3 >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UtilityTest.TypeNameParserFixture.MyComplexClass< T1, T2, T3 > \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 203 of file TypeNameParserFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
