.TH "NHibernate.Mapping.ByCode.IDynamicComponentAttributesMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IDynamicComponentAttributesMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IEntityPropertyMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.IDynamicComponentMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.ti -1c
.RI "void \fBUnique\fP (bool unique)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file IDynamicComponentAttributesMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
