.TH "NHibernate.TypeMismatchException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.TypeMismatchException \- 
.PP
Used when a user provided type does not match the expected one  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.HibernateException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeMismatchException\fP (string message)"
.br
.ti -1c
.RI "\fBTypeMismatchException\fP (string message, Exception inner)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeMismatchException\fP (SerializationInfo info, StreamingContext context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used when a user provided type does not match the expected one 


.PP
Definition at line 10 of file TypeMismatchException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
