.TH "NHibernate.Type.GenericMapType< TKey, TValue >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.GenericMapType< TKey, TValue > \- 
.PP
An \fBIType\fP that maps an IDictionary{TKey,TValue} collection to the database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.MapType\fP\&.
.PP
Inherited by \fBNHibernate\&.Type\&.GenericSortedDictionaryType< TKey, TValue >\fP, and \fBNHibernate\&.Type\&.GenericSortedListType< TKey, TValue >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericMapType\fP (string role, string propertyRef)"
.br
.RI "\fIInitializes a new instance of a GenericMapType{TKey, TValue} class for a specific role\&. \fP"
.ti -1c
.RI "override \fBIPersistentCollection\fP \fBInstantiate\fP (\fBISessionImplementor\fP session, \fBICollectionPersister\fP persister, object key)"
.br
.RI "\fIInstantiates a new IPersistentCollection for the map\&. \fP"
.ti -1c
.RI "override \fBIPersistentCollection\fP \fBWrap\fP (\fBISessionImplementor\fP session, object collection)"
.br
.RI "\fIWraps an IDictionary&lt;TKey,TValue&gt; in a PersistentGenericMap&lt;TKey,TValue&gt;\&. \fP"
.ti -1c
.RI "override object \fBReplaceElements\fP (object original, object target, object owner, IDictionary copyCache, \fBISessionImplementor\fP session)"
.br
.ti -1c
.RI "override object \fBInstantiate\fP (int anticipatedSize)"
.br
.RI "\fIInstantiate an empty instance of the 'underlying' collection (not a wrapper), but with the given anticipated size (i\&.e\&. accounting for initial capacity and perhaps load factor)\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAdd\fP (object collection, object element)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override System\&.Type \fBReturnedClass\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBIType\fP that maps an IDictionary{TKey,TValue} collection to the database\&. 


.PP
Definition at line 16 of file GenericMapType\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Type\&.GenericMapType< TKey, TValue >\&.GenericMapType (stringrole, stringpropertyRef)"

.PP
Initializes a new instance of a GenericMapType{TKey, TValue} class for a specific role\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrole\fP The role the persistent collection is in\&.
.br
\fIpropertyRef\fP The name of the property in the owner object containing the collection ID, or  if it is the primary key\&.
.RE
.PP

.PP
Definition at line 26 of file GenericMapType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBIPersistentCollection\fP NHibernate\&.Type\&.GenericMapType< TKey, TValue >\&.Instantiate (\fBISessionImplementor\fPsession, \fBICollectionPersister\fPpersister, objectkey)\fC [virtual]\fP"

.PP
Instantiates a new IPersistentCollection for the map\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The current ISessionImplementor for the map\&.
.br
\fIpersister\fP 
.br
\fIkey\fP Not used\&.
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.CollectionType\fP\&.
.PP
Definition at line 38 of file GenericMapType\&.cs\&.
.SS "override object NHibernate\&.Type\&.GenericMapType< TKey, TValue >\&.Instantiate (intanticipatedSize)\fC [virtual]\fP"

.PP
Instantiate an empty instance of the 'underlying' collection (not a wrapper), but with the given anticipated size (i\&.e\&. accounting for initial capacity and perhaps load factor)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIanticipatedSize\fP The anticipated size of the instantiated collection after we are done populating it\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A newly instantiated collection to be wrapped\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.CollectionType\fP\&.
.PP
Reimplemented in \fBNHibernate\&.Type\&.GenericSortedDictionaryType< TKey, TValue >\fP, and \fBNHibernate\&.Type\&.GenericSortedListType< TKey, TValue >\fP\&.
.PP
Definition at line 93 of file GenericMapType\&.cs\&.
.SS "override \fBIPersistentCollection\fP NHibernate\&.Type\&.GenericMapType< TKey, TValue >\&.Wrap (\fBISessionImplementor\fPsession, objectcollection)\fC [virtual]\fP"

.PP
Wraps an IDictionary&lt;TKey,TValue&gt; in a PersistentGenericMap&lt;TKey,TValue&gt;\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The ISessionImplementor for the collection to be a part of\&.
.br
\fIcollection\fP The unwrapped IDictionary&lt;TKey,TValue&gt;\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An PersistentGenericMap&lt;TKey,TValue&gt; that wraps the non \fBNHibernate\fP IDictionary&lt;TKey,TValue&gt;\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.CollectionType\fP\&.
.PP
Definition at line 57 of file GenericMapType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
