.TH "NHibernate.Test.DialectTest.MsSql2005DialectFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DialectTest.MsSql2005DialectFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetLimitString\fP ()"
.br
.ti -1c
.RI "void \fBOnlyOffsetLimit\fP ()"
.br
.ti -1c
.RI "void \fBNH1187\fP ()"
.br
.ti -1c
.RI "void \fBNH2809\fP ()"
.br
.ti -1c
.RI "void \fBQuotedAndParenthesisStringTokenizerTests_WithComma_InQuotes\fP ()"
.br
.ti -1c
.RI "void \fBQuotedAndParenthesisStringTokenizerTests_WithFunctionCallContainingComma\fP ()"
.br
.ti -1c
.RI "void \fBQuotedStringTokenizerTests\fP ()"
.br
.ti -1c
.RI "void \fBGetIfExistsDropConstraintTest_without_schema\fP ()"
.br
.ti -1c
.RI "void \fBGetIfExistsDropConstraintTest_For_Schema_other_than_dbo\fP ()"
.br
.ti -1c
.RI "void \fBGetLimitStringWithSqlComments\fP ()"
.br
.ti -1c
.RI "void \fBGetLimitStringWithSqlCommonTableExpression\fP ()"
.br
.ti -1c
.RI "void \fBDontReturnLimitStringForStoredProcedureCall\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file MsSql2005DialectFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
