.TH "NHibernate.Event.InitializeCollectionEvent" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.InitializeCollectionEvent \- 
.PP
An event that occurs when a collection wants to be initialized  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.AbstractCollectionEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInitializeCollectionEvent\fP (\fBIPersistentCollection\fP collection, \fBIEventSource\fP source)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An event that occurs when a collection wants to be initialized 


.PP
Definition at line 10 of file InitializeCollectionEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
