.TH "NHibernate.Type.EmbeddedComponentType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.EmbeddedComponentType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.ComponentType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEmbeddedComponentType\fP (\fBComponentMetamodel\fP metamodel)"
.br
.ti -1c
.RI "override object \fBInstantiate\fP (object parent, \fBISessionImplementor\fP session)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsEmbedded\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file EmbeddedComponentType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
