.TH "NHibernate.Id.Enhanced.OptimizerFactory.HiLoOptimizer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Id.Enhanced.OptimizerFactory.HiLoOptimizer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Id\&.Enhanced\&.OptimizerFactory\&.OptimizerSupport\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHiLoOptimizer\fP (System\&.Type returnClass, int incrementSize)"
.br
.ti -1c
.RI "override object \fBGenerate\fP (\fBIAccessCallback\fP callback)"
.br
.RI "\fIGenerate an identifier value accounting for this specific optimization\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override long \fBLastSourceValue\fP\fC [get]\fP"
.br
.RI "\fIExposure intended for testing purposes\&. \fP"
.ti -1c
.RI "long \fBLastValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "long \fBHiValue\fP\fC [get]\fP"
.br
.RI "\fIExposure intended for testing purposes\&. \fP"
.ti -1c
.RI "override bool \fBApplyIncrementSizeToSourceValues\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 99 of file OptimizerFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object NHibernate\&.Id\&.Enhanced\&.OptimizerFactory\&.HiLoOptimizer\&.Generate (\fBIAccessCallback\fPcallback)\fC [virtual]\fP"

.PP
Generate an identifier value accounting for this specific optimization\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcallback\fP Callback to access the underlying value source\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The generated identifier value\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Id\&.Enhanced\&.OptimizerFactory\&.OptimizerSupport\fP\&.
.PP
Definition at line 144 of file OptimizerFactory\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "long NHibernate\&.Id\&.Enhanced\&.OptimizerFactory\&.HiLoOptimizer\&.HiValue\fC [get]\fP"

.PP
Exposure intended for testing purposes\&. 
.PP
Definition at line 134 of file OptimizerFactory\&.cs\&.
.SS "override long NHibernate\&.Id\&.Enhanced\&.OptimizerFactory\&.HiLoOptimizer\&.LastSourceValue\fC [get]\fP"

.PP
Exposure intended for testing purposes\&. 
.PP
Definition at line 121 of file OptimizerFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
