.TH "NHibernate.Test.Hql.Ast.Animal" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Hql.Ast.Animal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.Hql\&.Ast\&.Mammal\fP, and \fBNHibernate\&.Test\&.Hql\&.Ast\&.Reptile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAddOffspring\fP (\fBAnimal\fP offSpring)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual float \fBBodyWeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBAnimal\fP > \fBOffspring\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBAnimal\fP \fBMother\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBAnimal\fP \fBFather\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBZoo\fP \fBZoo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBSerialNumber\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Animal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
