.TH "NHibernate.Test.TypesTest.BinaryTypeFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.TypesTest.BinaryTypeFixture \- 
.PP
Tests for mapping a byte[] Property to a BinaryType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TypesTest\&.TypeFixtureBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEquals\fP ()"
.br
.RI "\fIVerify Equals will correctly determine when the property is dirty\&. \fP"
.ti -1c
.RI "void \fBInsertNull\fP ()"
.br
.RI "\fICertain drivers (ie - Oralce) don't handle writing and reading null byte[] to and from the db consistently\&. Verify if this driver does\&. \fP"
.ti -1c
.RI "void \fBInsertZeroLength\fP ()"
.br
.RI "\fICertain drivers (ie - Oralce) don't handle writing and reading byte[0] to and from the db consistently\&. Verify if this driver does\&. \fP"
.ti -1c
.RI "void \fBReadWrite\fP ()"
.br
.RI "\fI\fBTest\fP the setting of values in \fBParameters\fP and the reading of the values out of the IDataReader\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBTypeName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests for mapping a byte[] Property to a BinaryType\&. 


.PP
Definition at line 15 of file BinaryTypeFixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.TypesTest\&.BinaryTypeFixture\&.Equals ()"

.PP
Verify Equals will correctly determine when the property is dirty\&. 
.PP
Definition at line 27 of file BinaryTypeFixture\&.cs\&.
.SS "void NHibernate\&.Test\&.TypesTest\&.BinaryTypeFixture\&.InsertNull ()"

.PP
Certain drivers (ie - Oralce) don't handle writing and reading null byte[] to and from the db consistently\&. Verify if this driver does\&. 
.PP
Definition at line 44 of file BinaryTypeFixture\&.cs\&.
.SS "void NHibernate\&.Test\&.TypesTest\&.BinaryTypeFixture\&.InsertZeroLength ()"

.PP
Certain drivers (ie - Oralce) don't handle writing and reading byte[0] to and from the db consistently\&. Verify if this driver does\&. 
.PP
Definition at line 78 of file BinaryTypeFixture\&.cs\&.
.SS "void NHibernate\&.Test\&.TypesTest\&.BinaryTypeFixture\&.ReadWrite ()"

.PP
\fBTest\fP the setting of values in \fBParameters\fP and the reading of the values out of the IDataReader\&. 
.PP
Definition at line 116 of file BinaryTypeFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
