.TH "NHibernate.Type.SpecialOneToOneType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.SpecialOneToOneType \- 
.PP
A one-to-one association that maps to specific formula(s) instead of the primary key column of the owning entity\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.OneToOneType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecialOneToOneType\fP (string referencedEntityName, \fBForeignKeyDirection\fP foreignKeyType, string uniqueKeyPropertyName, bool lazy, bool unwrapProxy, string entityName, string propertyName)"
.br
.ti -1c
.RI "override int \fBGetColumnSpan\fP (\fBEngine\&.IMapping\fP mapping)"
.br
.ti -1c
.RI "override \fBSqlTypes\&.SqlType\fP[] \fBSqlTypes\fP (\fBEngine\&.IMapping\fP mapping)"
.br
.ti -1c
.RI "override object \fBHydrate\fP (System\&.Data\&.IDataReader rs, string[] names, \fBEngine\&.ISessionImplementor\fP session, object owner)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseLHSPrimaryKey\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A one-to-one association that maps to specific formula(s) instead of the primary key column of the owning entity\&. 


.PP
Definition at line 10 of file SpecialOneToOneType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
