.TH "NHibernate.Dialect.Schema.FirebirdDataBaseSchema" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Schema.FirebirdDataBaseSchema \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Schema\&.AbstractDataBaseSchema\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirebirdDataBaseSchema\fP (DbConnection connection)"
.br
.ti -1c
.RI "override \fBITableMetadata\fP \fBGetTableMetadata\fP (DataRow rs, bool extras)"
.br
.RI "\fIGet the Table MetaData\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBStoresUpperCaseIdentifiers\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file FirebirdMetaData\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBITableMetadata\fP NHibernate\&.Dialect\&.Schema\&.FirebirdDataBaseSchema\&.GetTableMetadata (DataRowrs, boolextras)\fC [virtual]\fP"

.PP
Get the Table MetaData\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The DataRow resultSet of \fBGetTables\fP\&.
.br
\fIextras\fP Include FKs and indexes
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Dialect\&.Schema\&.AbstractDataBaseSchema\fP\&.
.PP
Definition at line 16 of file FirebirdMetaData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
