.TH "NHibernate.Engine.UnsavedValueFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.UnsavedValueFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIdentifierValue\fP \fBGetUnsavedIdentifierValue\fP (string unsavedValue, \fBIGetter\fP identifierGetter, \fBIType\fP identifierType, ConstructorInfo constructor)"
.br
.RI "\fIReturn an \fBIdentifierValue\fP for the specified unsaved-value\&. If none is specified, guess the unsaved value by instantiating a test instance of the class and reading it's id property, or if that is not possible, using the java default value for the type \fP"
.ti -1c
.RI "static \fBVersionValue\fP \fBGetUnsavedVersionValue\fP (String versionUnsavedValue, \fBIGetter\fP versionGetter, \fBIVersionType\fP versionType, ConstructorInfo constructor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file UnsavedValueFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIdentifierValue\fP NHibernate\&.Engine\&.UnsavedValueFactory\&.GetUnsavedIdentifierValue (stringunsavedValue, \fBIGetter\fPidentifierGetter, \fBIType\fPidentifierType, ConstructorInfoconstructor)\fC [static]\fP"

.PP
Return an \fBIdentifierValue\fP for the specified unsaved-value\&. If none is specified, guess the unsaved value by instantiating a test instance of the class and reading it's id property, or if that is not possible, using the java default value for the type 
.PP
Definition at line 34 of file UnsavedValueFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
