.TH "NHibernate.Linq.Functions.DateTimePropertiesHqlGenerator" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Functions.DateTimePropertiesHqlGenerator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Linq\&.Functions\&.BaseHqlGeneratorForProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBHqlTreeNode\fP \fBBuildHql\fP (MemberInfo member, Expression expression, \fBHqlTreeBuilder\fP treeBuilder, \fBIHqlExpressionVisitor\fP visitor)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file DateTimePropertiesHqlGenerator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
