.TH "NHibernate.Dialect.Function.NoArgSQLFunction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Function.NoArgSQLFunction \- 
.PP
Summary description for \fBNoArgSQLFunction\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.PP
Inherited by NHibernate\&.Dialect\&.FirebirdDialect\&.CastedFunction, NHibernate\&.Dialect\&.FirebirdDialect\&.CurrentTimeStamp, and NHibernate\&.Dialect\&.Oracle8iDialect\&.CurrentTimeStamp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoArgSQLFunction\fP (string name, \fBIType\fP returnType)"
.br
.ti -1c
.RI "\fBNoArgSQLFunction\fP (string name, \fBIType\fP returnType, bool hasParenthesesIfNoArguments)"
.br
.ti -1c
.RI "\fBIType\fP \fBReturnType\fP (\fBIType\fP columnType, \fBIMapping\fP mapping)"
.br
.RI "\fIThe function return type \fP"
.ti -1c
.RI "virtual \fBSqlString\fP \fBRender\fP (IList args, \fBISessionFactoryImplementor\fP factory)"
.br
.RI "\fIRender the function call as SQL\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIType\fP \fBFunctionReturnType\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBHasArguments\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBHasParenthesesIfNoArguments\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBNoArgSQLFunction\fP\&. 


.PP
Definition at line 13 of file NoArgSQLFunction\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSqlString\fP NHibernate\&.Dialect\&.Function\&.NoArgSQLFunction\&.Render (IListargs, \fBISessionFactoryImplementor\fPfactory)\fC [virtual]\fP"

.PP
Render the function call as SQL\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP List of arguments
.br
\fIfactory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
SQL fragment for the fuction\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.PP
Definition at line 45 of file NoArgSQLFunction\&.cs\&.
.SS "\fBIType\fP NHibernate\&.Dialect\&.Function\&.NoArgSQLFunction\&.ReturnType (\fBIType\fPcolumnType, \fBIMapping\fPmapping)"

.PP
The function return type 
.PP
\fBParameters:\fP
.RS 4
\fIcolumnType\fP The type of the first argument
.br
\fImapping\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Dialect\&.Function\&.ISQLFunction\fP\&.
.PP
Definition at line 33 of file NoArgSQLFunction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
