.TH "NHibernate.Test.CfgTest.ConfigurationAddMappingEvents" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.CfgTest.ConfigurationAddMappingEvents \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenSubscribedToBeforeBindThenRaiseEventForEachMapping\fP ()"
.br
.ti -1c
.RI "void \fBWhenSubscribedToAfterBindThenRaiseEventForEachMapping\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file ConfigurationAddMappingEvents\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
