.TH "NHibernate.Test.NHSpecificTest.Futures.TestDriverThatDoesntSupportQueryBatching" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Futures.TestDriverThatDoesntSupportQueryBatching \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Driver\&.SqlClientDriver\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBSupportsMultipleQueries\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file FallbackFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
