.TH "NHibernate.Test.Linq.LinqReadonlyTestsContext" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.LinqReadonlyTestsContext \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateNorthwindDb\fP ()"
.br
.ti -1c
.RI "void \fBDestroyNorthwindDb\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.RI "\fIAssembly to load mapping files from \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file LinqReadonlyTestsContext\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual string NHibernate\&.Test\&.Linq\&.LinqReadonlyTestsContext\&.MappingsAssembly\fC [get]\fP, \fC [protected]\fP"

.PP
Assembly to load mapping files from 
.PP
Definition at line 21 of file LinqReadonlyTestsContext\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
