.TH "NHibernate.Mapping.ITableOwner" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ITableOwner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Mapping\&.JoinedSubclass\fP, \fBNHibernate\&.Mapping\&.RootClass\fP, and \fBNHibernate\&.Mapping\&.UnionSubclass\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTable\fP \fBTable\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ITableOwner\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
