.TH "NHibernate.Test.NHSpecificTest.NH1178.Foo" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1178.Foo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFoo\fP (int number, string word)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBWord\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Foo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
