.TH "NHibernate.Test.CacheTest.QueryKeyFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.CacheTest.QueryKeyFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEqualityWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBNotEqualityWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBHashCodeWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBNotEqualHashCodeWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBToStringWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBToStringWithMoreFilters\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file QueryKeyFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
