.TH "NHibernate.DomainModel.Up" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Up \- 
.PP
Summary description for \fBUp\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.DomainModel\&.Down\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (object other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBId2\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBUp\fP\&. 


.PP
Definition at line 8 of file Up\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool NHibernate\&.DomainModel\&.Up\&.Equals (objectother)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIother\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
.PP
This is important, otherwise the Identifier and Instance don't match inside SessionImpl
.PP
Definition at line 38 of file Up\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
