.TH "NHibernate.Test.MappingByCode.MixAutomapping" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MixAutomapping \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArrayCollectionTests\fP"
.br
.ti -1c
.RI "class \fBBagCollectionTests\fP"
.br
.ti -1c
.RI "class \fBCallCustomConditions\fP"
.br
.ti -1c
.RI "class \fBComponentsTests\fP"
.br
.ti -1c
.RI "class \fBDefaultClassHierarchyRepresentationTests\fP"
.br
.ti -1c
.RI "class \fBDictionaryCollectionTests\fP"
.br
.ti -1c
.RI "class \fBEntityTests\fP"
.br
.ti -1c
.RI "class \fBInheritedVersionTest\fP"
.br
.ti -1c
.RI "class \fBManyToOneTest\fP"
.br
.ti -1c
.RI "class \fBOneToManyTests\fP"
.br
.ti -1c
.RI "class \fBPoidTests\fP"
.br
.ti -1c
.RI "class \fBPolymorphicPropertiesMapping\fP"
.br
.ti -1c
.RI "class \fBPropertiesExclusionTests\fP"
.br
.ti -1c
.RI "class \fBRootEntityTests\fP"
.br
.ti -1c
.RI "class \fBSetCollectionTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
