.TH "NHibernate.Test.NHSpecificTest.NH623.Paragraph" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH623.Paragraph \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH623\&.Element\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParagraph\fP (int elementId, \fBDocument\fP document, string font)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBFont\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file Classes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
