.TH "NHibernate.Test.GenericTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.GenericTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBBagGeneric\fP"
.br
.ti -1c
.RI "package \fBEnumGeneric\fP"
.br
.ti -1c
.RI "package \fBIdBagGeneric\fP"
.br
.ti -1c
.RI "package \fBListGeneric\fP"
.br
.ti -1c
.RI "package \fBMapGeneric\fP"
.br
.ti -1c
.RI "package \fBMethods\fP"
.br
.ti -1c
.RI "package \fBOrderedSetGeneric\fP"
.br
.ti -1c
.RI "package \fBOverall\fP"
.br
.ti -1c
.RI "package \fBSetGeneric\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
