.TH "NHibernate.Hql.Ast.ANTLR.Tree.SelectExpressionList" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.SelectExpressionList \- 
.PP
Common behavior - a node that contains a list of select expressions\&. Author: josh Ported by: Steve Strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.HqlSqlWalkerNode\fP\&.
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.ConstructorNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.SelectClause\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBISelectExpression\fP[] \fBCollectSelectExpressions\fP ()"
.br
.RI "\fIReturns an array of SelectExpressions gathered from the children of the given parent AST node\&. \fP"
.ti -1c
.RI "\fBISelectExpression\fP[] \fBCollectSelectExpressions\fP (bool recurse)"
.br
.RI "\fIReturns an array of SelectExpressions gathered from the children of the given parent AST node\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectExpressionList\fP (IToken token)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Common behavior - a node that contains a list of select expressions\&. Author: josh Ported by: Steve Strong 


.PP
Definition at line 14 of file SelectExpressionList\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISelectExpression\fP [] NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.SelectExpressionList\&.CollectSelectExpressions ()"

.PP
Returns an array of SelectExpressions gathered from the children of the given parent AST node\&. 
.PP
Definition at line 23 of file SelectExpressionList\&.cs\&.
.SS "\fBISelectExpression\fP [] NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.SelectExpressionList\&.CollectSelectExpressions (boolrecurse)"

.PP
Returns an array of SelectExpressions gathered from the children of the given parent AST node\&. 
.PP
Definition at line 31 of file SelectExpressionList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
