.TH "NHibernate.Test.NHSpecificTest.NH2341.ConcreteBA" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2341.ConcreteBA \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2341\&.AbstractBA\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2341\&.ConcreteA\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2341\&.ConcreteB\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
