.TH "NHibernate.Linq.Clauses" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Clauses \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNhHavingClause\fP"
.br
.ti -1c
.RI "class \fBNhJoinClause\fP"
.br
.RI "\fIAll joins are created as outer joins\&. An optimization in WhereJoinDetector finds joins that may be inner joined and calls MakeInner on them\&. QueryModelVisitor's QueryModelVisitor\&.VisitAdditionalFromClause will then emit the correct HQL join\&. \fP"
.ti -1c
.RI "class \fBNhWithClause\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
