.TH "NHibernate.Test.NHSpecificTest.MapFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.MapFixture \- 
.PP
Summary description for MapTest\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestSelect\fP ()"
.br
.ti -1c
.RI "void \fBTestSort\fP ()"
.br
.ti -1c
.RI "void \fBTestInsert\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBAppliesTo\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Summary description for MapTest\&. 


.PP
Definition at line 14 of file MapFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
