.TH "NHibernate.Test.MappingByCode.MappersTests.AbstractPropertyContainerMapperTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests.AbstractPropertyContainerMapperTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCantCreateWithoutHbmMapping\fP ()"
.br
.ti -1c
.RI "void \fBCantCreateWithoutContainerType\fP ()"
.br
.ti -1c
.RI "void \fBCanAddSimpleProperty\fP ()"
.br
.ti -1c
.RI "void \fBCallPropertyMapper\fP ()"
.br
.ti -1c
.RI "void \fBCantAddPropertyOfNotInheritedType\fP ()"
.br
.ti -1c
.RI "void \fBCanAddPropertyOfInheritedType\fP ()"
.br
.ti -1c
.RI "void \fBCallAnyMapper\fP ()"
.br
.ti -1c
.RI "void \fBCallDictionaryMappers\fP ()"
.br
.ti -1c
.RI "void \fBAddDynamicComponentProperty\fP ()"
.br
.ti -1c
.RI "void \fBCallDynamicComponentMapper\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file AbstractPropertyContainerMapperTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
