.TH "NHibernate.Hql.Ast.ANTLR.IErrorReporter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.IErrorReporter \- 
.PP
Implementations will report or handle errors invoked by an \fBANTLR\fP base parser\&. Author: josh Ported by: Steve Strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.IParseErrorHandler\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.SqlGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReportError\fP (RecognitionException e)"
.br
.ti -1c
.RI "void \fBReportError\fP (string s)"
.br
.ti -1c
.RI "void \fBReportWarning\fP (string s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementations will report or handle errors invoked by an \fBANTLR\fP base parser\&. Author: josh Ported by: Steve Strong 


.PP
Definition at line 12 of file IErrorReporter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
