.TH "NHibernate.Properties.CamelCaseStrategy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Properties.CamelCaseStrategy \- 
.PP
Implementation of \fBIFieldNamingStrategy\fP for fields that are the camelCase version of the PropertyName  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Properties\&.IFieldNamingStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetFieldName\fP (string propertyName)"
.br
.RI "\fIConverts the Property's name into a Field name by making the first character lower case\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBIFieldNamingStrategy\fP for fields that are the camelCase version of the PropertyName 


.PP
Definition at line 7 of file CamelCaseStrategy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string NHibernate\&.Properties\&.CamelCaseStrategy\&.GetFieldName (stringpropertyName)"

.PP
Converts the Property's name into a Field name by making the first character lower case\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP The name of the mapped property\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The name of the Field in CamelCase format\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Properties\&.IFieldNamingStrategy\fP\&.
.PP
Definition at line 17 of file CamelCaseStrategy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
