.TH "NHibernate.Test.Linq.QueryCacheableTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.QueryCacheableTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBQueryIsCacheable\fP ()"
.br
.ti -1c
.RI "void \fBQueryIsCacheable2\fP ()"
.br
.ti -1c
.RI "void \fBQueryIsCacheable3\fP ()"
.br
.ti -1c
.RI "void \fBQueryIsCacheableWithRegion\fP ()"
.br
.ti -1c
.RI "void \fBCacheableBeforeOtherClauses\fP ()"
.br
.ti -1c
.RI "void \fBCacheableRegionBeforeOtherClauses\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConfigure\fP (\fBConfiguration\fP cfg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file QueryCacheableTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
