.TH "NHibernate.Test.NHSpecificTest.NH2505.Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2505.Fixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCaseMappingByCode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenQueryConstantEqualToMemberThenDoesNotUseTheCaseConstructor\fP ()"
.br
.ti -1c
.RI "void \fBWhenQueryConstantNotEqualToMemberThenDoesNotUseTheCaseConstructor\fP ()"
.br
.ti -1c
.RI "void \fBWhenQueryComplexEqualToComplexThentUseTheCaseConstructorForBoth\fP ()"
.br
.ti -1c
.RI "void \fBWhenQueryConstantEqualToNullableMemberThenUseTheCaseConstructorForMember\fP ()"
.br
.ti -1c
.RI "void \fBWhenQueryConstantEqualToNullableMemberValueThenDoesNotUseTheCaseConstructorForMember\fP ()"
.br
.ti -1c
.RI "void \fBWhenQueryConstantNotEqualToNullableMemberThenUseTheCaseConstructorForMember\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBHbmMapping\fP \fBGetMappings\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
