.TH "NHibernate.Engine.Query.OrdinalParameterDescriptor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.Query.OrdinalParameterDescriptor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrdinalParameterDescriptor\fP (int ordinalPosition, \fBIType\fP expectedType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBOrdinalPosition\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIType\fP \fBExpectedType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file OrdinalParameterDescriptor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
