.TH "NHibernate.Properties.PascalCaseUnderscoreStrategy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Properties.PascalCaseUnderscoreStrategy \- 
.PP
Implementation of \fBIFieldNamingStrategy\fP for fields that are prefixed with an \fC_\fP and the first character in PropertyName capitalized\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Properties\&.IFieldNamingStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetFieldName\fP (string propertyName)"
.br
.RI "\fIConverts the Property's name into a Field name by making the first character of the \fCpropertyName\fP uppercase and prefixing it with an underscore\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of \fBIFieldNamingStrategy\fP for fields that are prefixed with an \fC_\fP and the first character in PropertyName capitalized\&. 


.PP
Definition at line 7 of file PascalCaseUnderscoreStrategy\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string NHibernate\&.Properties\&.PascalCaseUnderscoreStrategy\&.GetFieldName (stringpropertyName)"

.PP
Converts the Property's name into a Field name by making the first character of the \fCpropertyName\fP uppercase and prefixing it with an underscore\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP The name of the mapped property\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The name of the Field in PascalCase format prefixed with an underscore\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Properties\&.IFieldNamingStrategy\fP\&.
.PP
Definition at line 17 of file PascalCaseUnderscoreStrategy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
