.TH "NHibernate.Linq.Expressions.NhLongCountExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Expressions.NhLongCountExpression \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Linq\&.Expressions\&.NhCountExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNhLongCountExpression\fP (Expression expression)"
.br
.ti -1c
.RI "override Expression \fBCreateNew\fP (Expression expression)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file NhCountExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
