.TH "NHibernate.Test.NHSpecificTest.NH3332.DataTypeDescription" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH3332.DataTypeDescription \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual String \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual Byte[] \fBRowVersionId\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBCulture\fP \fBCulture\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBDataType\fP \fBDataType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file DataTypeDescription\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
