.TH "NHibernate.Cfg.XmlHbmBinding.UnionSubclassBinder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.XmlHbmBinding.UnionSubclassBinder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.XmlHbmBinding\&.ClassBinder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnionSubclassBinder\fP (\fBMappings\fP mappings, \fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "\fBUnionSubclassBinder\fP (\fBClassBinder\fP parent)"
.br
.ti -1c
.RI "void \fBBind\fP (\fBHbmUnionSubclass\fP unionSubclassMapping, IDictionary< string, \fBMetaAttribute\fP > inheritedMetas)"
.br
.ti -1c
.RI "void \fBHandleUnionSubclass\fP (\fBPersistentClass\fP model, \fBHbmUnionSubclass\fP unionSubclassMapping, IDictionary< string, \fBMetaAttribute\fP > inheritedMetas)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file UnionSubclassBinder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
