.TH "NHibernate.Tool.hbm2ddl.IConnectionHelper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Tool.hbm2ddl.IConnectionHelper \- 
.PP
Contract for delegates responsible for managing connection used by the \fBhbm2ddl\fP tools\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Tool\&.hbm2ddl\&.ManagedProviderConnectionHelper\fP, \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionHelper\fP, and \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionProviderConnectionHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPrepare\fP ()"
.br
.RI "\fIPrepare the helper for use\&. \fP"
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.RI "\fIRelease any resources held by this helper\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DbConnection \fBConnection\fP\fC [get]\fP"
.br
.RI "\fIGet a reference to the connection we are using\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contract for delegates responsible for managing connection used by the \fBhbm2ddl\fP tools\&. 


.PP
Definition at line 9 of file IConnectionHelper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Tool\&.hbm2ddl\&.IConnectionHelper\&.Prepare ()"

.PP
Prepare the helper for use\&. 
.PP
Implemented in \fBNHibernate\&.Tool\&.hbm2ddl\&.ManagedProviderConnectionHelper\fP, \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionProviderConnectionHelper\fP, and \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionHelper\fP\&.
.SS "void NHibernate\&.Tool\&.hbm2ddl\&.IConnectionHelper\&.Release ()"

.PP
Release any resources held by this helper\&. 
.PP
Implemented in \fBNHibernate\&.Tool\&.hbm2ddl\&.ManagedProviderConnectionHelper\fP, \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionProviderConnectionHelper\fP, and \fBNHibernate\&.Tool\&.hbm2ddl\&.SuppliedConnectionHelper\fP\&.
.SH "Property Documentation"
.PP 
.SS "DbConnection NHibernate\&.Tool\&.hbm2ddl\&.IConnectionHelper\&.Connection\fC [get]\fP"

.PP
Get a reference to the connection we are using\&. 
.PP
Definition at line 19 of file IConnectionHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
