.TH "NHibernate.Test.PolymorphicGetAndLoad.IMultiGraphNamed" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.PolymorphicGetAndLoad.IMultiGraphNamed \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.PolymorphicGetAndLoad\&.GraphA\fP, and \fBNHibernate\&.Test\&.PolymorphicGetAndLoad\&.GraphB\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
