.TH "NHibernate.Event.Default.DirtyCollectionSearchVisitor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.Default.DirtyCollectionSearchVisitor \- 
.PP
A Visitor that determines if a dirty collection was found\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.Default\&.AbstractVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirtyCollectionSearchVisitor\fP (\fBIEventSource\fP session, bool[] propertyVersionability)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBWasDirtyCollectionFound\fP\fC [get]\fP"
.br
.RI "\fIGets a bool indicating if a dirty collection was found\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A Visitor that determines if a dirty collection was found\&. 


.PD 0

.PP
Reason for dirty collection    If it is a new application-instantiated collection, return true (does not occur anymore!)     If it is a component, recurse\&.     If it is a wrapped collection, ask the collection entry\&.   
.PP
Definition at line 32 of file DirtyCollectionSearchVisitor\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool NHibernate\&.Event\&.Default\&.DirtyCollectionSearchVisitor\&.WasDirtyCollectionFound\fC [get]\fP"

.PP
Gets a bool indicating if a dirty collection was found\&. if a dirty collection was found\&.
.PP
Definition at line 48 of file DirtyCollectionSearchVisitor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
