.TH "NHibernate.Cfg.Loquacious.INamedQueryDefinitionBuilder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.Loquacious.INamedQueryDefinitionBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Cfg\&.Loquacious\&.NamedQueryDefinitionBuilder\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsCacheable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBCacheRegion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBFetchSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBTimeout\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFlushMode\fP \fBFlushMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBQuery\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsReadOnly\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBComment\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBCacheMode\fP \fBCacheMode\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file INamedQueryDefinitionBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
