.TH "NHibernate.Criterion.AndExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.AndExpression \- 
.PP
An \fBLogicalExpression\fP that combines two \fBICriterion\fPs with an \fCand\fP between them\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.LogicalExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndExpression\fP (\fBICriterion\fP lhs, \fBICriterion\fP rhs)"
.br
.RI "\fIInitializes a new instance of the \fBAndExpression\fP class that combines two \fBICriterion\fP\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBOp\fP\fC [get]\fP"
.br
.RI "\fIGet the Sql operator to put between the two \fBICriterion\fPs\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBLogicalExpression\fP that combines two \fBICriterion\fPs with an \fCand\fP between them\&. 


.PP
Definition at line 10 of file AndExpression\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Criterion\&.AndExpression\&.AndExpression (\fBICriterion\fPlhs, \fBICriterion\fPrhs)"

.PP
Initializes a new instance of the \fBAndExpression\fP class that combines two \fBICriterion\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhs\fP The \fBICriterion\fP to use as the left hand side\&.
.br
\fIrhs\fP The \fBICriterion\fP to use as the right hand side\&.
.RE
.PP

.PP
Definition at line 27 of file AndExpression\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string NHibernate\&.Criterion\&.AndExpression\&.Op\fC [get]\fP, \fC [protected]\fP"

.PP
Get the Sql operator to put between the two \fBICriterion\fPs\&. The string '<c>and</c>'
.PP
Definition at line 17 of file AndExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
