.TH "NHibernate.Cfg.MappingSchema.HbmMapping" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmMapping \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.AbstractDecoratable\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmMeta\fP[] \fBmeta\fP"
.br
.ti -1c
.RI "\fBHbmTypedef\fP[] \fBtypedef\fP"
.br
.ti -1c
.RI "\fBHbmImport\fP[] \fBimport\fP"
.br
.ti -1c
.RI "object[] \fBItems\fP"
.br
.ti -1c
.RI "\fBHbmResultSet\fP[] \fBresultset\fP"
.br
.ti -1c
.RI "object[] \fBItems1\fP"
.br
.ti -1c
.RI "\fBHbmFilterDef\fP[] \fBfilterdef\fP"
.br
.ti -1c
.RI "\fBHbmDatabaseObject\fP[] \fBdatabaseobject\fP"
.br
.ti -1c
.RI "string \fBschema\fP"
.br
.ti -1c
.RI "string \fBcatalog\fP"
.br
.ti -1c
.RI "string \fBdefaultcascade\fP"
.br
.ti -1c
.RI "string \fBdefaultaccess\fP"
.br
.ti -1c
.RI "bool \fBdefaultlazy\fP"
.br
.ti -1c
.RI "bool \fBautoimport\fP"
.br
.ti -1c
.RI "string \fBassembly\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHbmDatabaseObject\fP[] \fBDatabaseObjects\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmFilterDef\fP[] \fBFilterDefinitions\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmResultSet\fP[] \fBResultSets\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmTypedef\fP[] \fBTypeDefinitions\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmImport\fP[] \fBImports\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBHbmMeta\fP[] \fBMetadatas\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmClass\fP[] \fBRootClasses\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmSubclass\fP[] \fBSubClasses\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmJoinedSubclass\fP[] \fBJoinedSubclasses\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmUnionSubclass\fP[] \fBUnionSubclasses\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmQuery\fP[] \fBHqlQueries\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmSqlQuery\fP[] \fBSqlQueries\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 4970 of file Hbm\&.generated\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string NHibernate\&.Cfg\&.MappingSchema\&.HbmMapping\&.assembly"

.PP
Definition at line 5038 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
