.TH "NHibernate.Linq.GroupJoin" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.GroupJoin \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAggregatingGroupJoinRewriter\fP"
.br
.RI "\fIAn AggregatingGroupJoin is a query such as: \fP"
.ti -1c
.RI "class \fBGroupJoinAggregateDetectionVisitor\fP"
.br
.ti -1c
.RI "class \fBGroupJoinSelectClauseRewriter\fP"
.br
.ti -1c
.RI "class \fBIsAggregatingResults\fP"
.br
.ti -1c
.RI "class \fBLocateGroupJoinQuerySource\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
