.TH "NHibernate.Test.CompositeId.ClassWithCompositeId" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.CompositeId.ClassWithCompositeId \- 
.PP
Summary description for \fBClassWithCompositeId\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClassWithCompositeId\fP (\fBId\fP id)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBId\fP \fBId\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBOneProperty\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBClassWithCompositeId\fP\&. 


.PP
Definition at line 8 of file ClassWithCompositeId\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
