.TH "NHibernate.Stat" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Stat \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCategorizedStatistics\fP"
.br
.RI "\fIStatistics for a particular 'category' (a named entity, collection role, second level cache region or query)\&. \fP"
.ti -1c
.RI "class \fBCollectionStatistics\fP"
.br
.RI "\fI\fBCollection\fP related statistics \fP"
.ti -1c
.RI "class \fBEntityStatistics\fP"
.br
.RI "\fIEntity related statistics \fP"
.ti -1c
.RI "interface \fBISessionStatistics\fP"
.br
.RI "\fIInformation about the first-level (session) cache for a particular session instance \fP"
.ti -1c
.RI "interface \fBIStatistics\fP"
.br
.RI "\fIStatistics for a particular \fBISessionFactory\fP\&. Beware of metrics, they are dependent of the Stopwatch precision: \fP"
.ti -1c
.RI "interface \fBIStatisticsImplementor\fP"
.br
.RI "\fIStatistics SPI for the \fBNHibernate\fP core \fP"
.ti -1c
.RI "class \fBQueryStatistics\fP"
.br
.RI "\fIQuery statistics (HQL and SQL) \fP"
.ti -1c
.RI "class \fBSecondLevelCacheStatistics\fP"
.br
.RI "\fISecond level cache statistics of a specific region \fP"
.ti -1c
.RI "class \fBSessionStatisticsImpl\fP"
.br
.ti -1c
.RI "class \fBStatisticsImpl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
