.TH "NHibernate.Test.VersionTest.Db.MsSQL" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.VersionTest.Db.MsSQL \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinaryTimestamp\fP"
.br
.ti -1c
.RI "class \fBBar\fP"
.br
.ti -1c
.RI "class \fBFoo\fP"
.br
.ti -1c
.RI "class \fBComplexDomainFixture\fP"
.br
.ti -1c
.RI "class \fBGeneratedBinaryVersionFixture\fP"
.br
.ti -1c
.RI "class \fBSimpleVersioned\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
