.TH "NHibernate.Test.Events.Collections.Association.Bidirectional.OneToMany" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Events.Collections.Association.Bidirectional.OneToMany \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBidirectionalOneToManyBagCollectionEventFixture\fP"
.br
.ti -1c
.RI "class \fBBidirectionalOneToManyBagSubclassCollectionEventFixture\fP"
.br
.ti -1c
.RI "class \fBBidirectionalOneToManySetCollectionEventFixture\fP"
.br
.ti -1c
.RI "class \fBChildWithManyToOne\fP"
.br
.ti -1c
.RI "class \fBParentWithBidirectionalOneToMany\fP"
.br
.ti -1c
.RI "class \fBParentWithBidirectionalOneToManySubclass\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
