.TH "NHibernate.Criterion.OrExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.OrExpression \- 
.PP
An \fBICriterion\fP that combines two \fBICriterion\fPs with an \fC'or'\fP between them\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.LogicalExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrExpression\fP (\fBICriterion\fP lhs, \fBICriterion\fP rhs)"
.br
.RI "\fIInitialize a new instance of the \fBOrExpression\fP class for two \fBICriterion\fPs\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBOp\fP\fC [get]\fP"
.br
.RI "\fIGet the Sql operator to put between the two \fBExpression\fPs\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBICriterion\fP that combines two \fBICriterion\fPs with an \fC'or'\fP between them\&. 


.PP
Definition at line 10 of file OrExpression\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Criterion\&.OrExpression\&.OrExpression (\fBICriterion\fPlhs, \fBICriterion\fPrhs)"

.PP
Initialize a new instance of the \fBOrExpression\fP class for two \fBICriterion\fPs\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhs\fP The \fBICriterion\fP to use as the left hand side\&.
.br
\fIrhs\fP The \fBICriterion\fP to use as the right hand side\&.
.RE
.PP

.PP
Definition at line 18 of file OrExpression\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string NHibernate\&.Criterion\&.OrExpression\&.Op\fC [get]\fP, \fC [protected]\fP"

.PP
Get the Sql operator to put between the two \fBExpression\fPs\&. Returns '<c>or</c>'
.PP
Definition at line 27 of file OrExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
