.TH "NHibernate.Linq.Expressions.NhNewExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Expressions.NhNewExpression \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ExtensionExpression\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNhNewExpression\fP (IList< string > members, IList< Expression > arguments)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override Expression \fBVisitChildren\fP (ExpressionTreeVisitor visitor)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ReadOnlyCollection< Expression > \fBArguments\fP\fC [get]\fP"
.br
.ti -1c
.RI "ReadOnlyCollection< string > \fBMembers\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file NhNewExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
