.TH "NHibernate.Test.CfgTest.Loquacious.ConfigurationFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.CfgTest.Loquacious.ConfigurationFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCompleteConfiguration\fP ()"
.br
.ti -1c
.RI "void \fBUseDbConfigurationStringBuilder\fP ()"
.br
.ti -1c
.RI "void \fBUseConnectionStringName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file ConfigurationFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
