.TH "NHibernate.DomainModel.Container" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Container \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContainerInnerClass\fP"
.br
.ti -1c
.RI "class \fBTernary\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual IList \fBOneToMany\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBManyToMany\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBComponents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBContainerInnerClass\fP > \fBComposites\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBCascades\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBBag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBLazyBag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IDictionary \fBTernaryMap\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBTernary\fP > \fBTernarySet\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Container\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
