.TH "NHibernate.Mapping.ByCode.Impl.CustomizersImpl.JoinCustomizer< TEntity >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.CustomizersImpl.JoinCustomizer< TEntity > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.PropertyContainerCustomizer< TEntity >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IJoinMapper< TEntity >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoinCustomizer\fP (string splitGroupId, \fBIModelExplicitDeclarationsHolder\fP explicitDeclarationsHolder, \fBICustomizersHolder\fP customizersHolder)"
.br
.ti -1c
.RI "void \fBLoader\fP (string namedQueryReference)"
.br
.ti -1c
.RI "void \fBSqlInsert\fP (string sql)"
.br
.ti -1c
.RI "void \fBSqlUpdate\fP (string sql)"
.br
.ti -1c
.RI "void \fBSqlDelete\fP (string sql)"
.br
.ti -1c
.RI "void \fBSubselect\fP (string sql)"
.br
.ti -1c
.RI "void \fBTable\fP (string tableName)"
.br
.ti -1c
.RI "void \fBCatalog\fP (string catalogName)"
.br
.ti -1c
.RI "void \fBSchema\fP (string schemaName)"
.br
.ti -1c
.RI "void \fBKey\fP (Action< \fBIKeyMapper\fP< TEntity >> keyMapping)"
.br
.ti -1c
.RI "void \fBInverse\fP (bool value)"
.br
.ti -1c
.RI "void \fBOptional\fP (bool isOptional)"
.br
.ti -1c
.RI "void \fBFetch\fP (\fBFetchKind\fP fetchMode)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBRegisterSetMapping< TElement >\fP (Expression< Func< TEntity, IEnumerable< TElement >>> property, Action< \fBISetPropertiesMapper\fP< TEntity, TElement >> collectionMapping, Action< \fBICollectionElementRelation\fP< TElement >> mapping)"
.br
.ti -1c
.RI "override void \fBRegisterBagMapping< TElement >\fP (Expression< Func< TEntity, IEnumerable< TElement >>> property, Action< \fBIBagPropertiesMapper\fP< TEntity, TElement >> collectionMapping, Action< \fBICollectionElementRelation\fP< TElement >> mapping)"
.br
.ti -1c
.RI "override void \fBRegisterListMapping< TElement >\fP (Expression< Func< TEntity, IEnumerable< TElement >>> property, Action< \fBIListPropertiesMapper\fP< TEntity, TElement >> collectionMapping, Action< \fBICollectionElementRelation\fP< TElement >> mapping)"
.br
.ti -1c
.RI "override void \fBRegisterMapMapping< TKey, TElement >\fP (Expression< Func< TEntity, IDictionary< TKey, TElement >>> property, Action< \fBIMapPropertiesMapper\fP< TEntity, TKey, TElement >> collectionMapping, Action< \fBIMapKeyRelation\fP< TKey >> keyMapping, Action< \fBICollectionElementRelation\fP< TElement >> mapping)"
.br
.ti -1c
.RI "override void \fBRegisterPropertyMapping< TProperty >\fP (Expression< Func< TEntity, TProperty >> property, Action< \fBIPropertyMapper\fP > mapping)"
.br
.ti -1c
.RI "override void \fBRegisterNoVisiblePropertyMapping\fP (string notVisiblePropertyOrFieldName, System\&.Action< \fBIPropertyMapper\fP > mapping)"
.br
.ti -1c
.RI "override void \fBRegisterComponentMapping< TComponent >\fP (Expression< Func< TEntity, TComponent >> property, Action< \fBIComponentMapper\fP< TComponent >> mapping)"
.br
.ti -1c
.RI "override void \fBRegisterManyToOneMapping< TProperty >\fP (Expression< Func< TEntity, TProperty >> property, Action< \fBIManyToOneMapper\fP > mapping)"
.br
.ti -1c
.RI "override void \fBRegisterAnyMapping< TProperty >\fP (Expression< Func< TEntity, TProperty >> property, System\&.Type idTypeOfMetaType, Action< \fBIAnyMapper\fP > mapping)"
.br
.ti -1c
.RI "override void \fBRegisterIdBagMapping< TElement >\fP (Expression< Func< TEntity, IEnumerable< TElement >>> property, Action< \fBIIdBagPropertiesMapper\fP< TEntity, TElement >> collectionMapping, Action< \fBICollectionElementRelation\fP< TElement >> mapping)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITEntity\fP : \fIclass\fP
.PP
Definition at line 8 of file JoinCustomizer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
