.TH "NHibernate.Hql.Ast.ANTLR.HqlParseEngine" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.HqlParseEngine \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlParseEngine\fP (string hql, bool filter, \fBISessionFactoryImplementor\fP sfi)"
.br
.ti -1c
.RI "\fBIASTNode\fP \fBParse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 437 of file QueryTranslatorImpl\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
