.TH "NHibernate.Test.TypesTest.DateTypeFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.TypesTest.DateTypeFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TypesTest\&.TypeFixtureBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShouldBeDateType\fP ()"
.br
.ti -1c
.RI "void \fBReadWriteNormal\fP ()"
.br
.ti -1c
.RI "void \fBReadWriteBaseValue\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBTypeName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 35 of file DateTypeTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
