.TH "NHibernate.Mapping.ByCode.IComponentAttributesMapper< TComponent >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IComponentAttributesMapper< TComponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IEntityPropertyMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.IComponentElementMapper< TComponent >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IComponentMapper< TComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBParent< TProperty >\fP (Expression< Func< TComponent, TProperty >> parent)"
.br
.ti -1c
.RI "void \fBParent< TProperty >\fP (Expression< Func< TComponent, TProperty >> parent, Action< \fBIComponentParentMapper\fP > parentMapping)"
.br
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.ti -1c
.RI "void \fBLazy\fP (bool isLazy)"
.br
.ti -1c
.RI "void \fBUnique\fP (bool unique)"
.br
.ti -1c
.RI "void \fBClass< TConcrete >\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file IComponentMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
