.TH "NHibernate.Test.Hql.SimpleFunctionsTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Hql.SimpleFunctionsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Hql\&.BaseFunctionFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNoArgFunction\fP ()"
.br
.ti -1c
.RI "void \fBStandardFunction\fP ()"
.br
.ti -1c
.RI "void \fBCastFunc\fP ()"
.br
.ti -1c
.RI "void \fBVarArgsFunction\fP ()"
.br
.ti -1c
.RI "void \fBNvl\fP ()"
.br
.ti -1c
.RI "void \fBPositionSubstring\fP ()"
.br
.ti -1c
.RI "void \fBClassicSum\fP ()"
.br
.ti -1c
.RI "void \fBClassicCount\fP ()"
.br
.ti -1c
.RI "void \fBClassicAvg\fP ()"
.br
.ti -1c
.RI "void \fBClassicAggregate\fP ()"
.br
.ti -1c
.RI "void \fBAnsiSubstring\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file SimpleFunctionsTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
