.TH "NHibernate.Test.MultipleCollectionFetchTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MultipleCollectionFetchTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractMultipleCollectionFetchFixture\fP"
.br
.ti -1c
.RI "class \fBMultipleBagFetchFixture\fP"
.br
.ti -1c
.RI "class \fBMultipleListFetchFixture\fP"
.br
.ti -1c
.RI "class \fBMultipleSetFetchFixture\fP"
.br
.ti -1c
.RI "class \fBPerson\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
