.TH "NHibernate.Test.NHSpecificTest.NH1217.Node" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1217.Node \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1217\&.DomainBase\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1217\&.INode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBIRoot\fP \fBRoot\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual String \fBLabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBIEdge\fP > \fBFromEdges\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBIEdge\fP > \fBToEdges\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file DomainObjects\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
