.TH "NHibernate.Test.NHSpecificTest.NH2278.CustomPersistentIdentifierBag< T >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2278.CustomPersistentIdentifierBag< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Collection\&.Generic\&.PersistentIdentifierBag< T >\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2278\&.ICustomList< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCustomPersistentIdentifierBag\fP (\fBISessionImplementor\fP session)"
.br
.ti -1c
.RI "\fBCustomPersistentIdentifierBag\fP (\fBISessionImplementor\fP session, ICollection< T > coll)"
.br
.ti -1c
.RI "override bool \fBAfterInitialize\fP (\fBNHibernate\&.Persister\&.Collection\&.ICollectionPersister\fP persister)"
.br
.RI "\fICalled after initializing from cache \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file CustomPersistentIdentifierBag\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool NHibernate\&.Test\&.NHSpecificTest\&.NH2278\&.CustomPersistentIdentifierBag< T >\&.AfterInitialize (\fBNHibernate\&.Persister\&.Collection\&.ICollectionPersister\fPpersister)\fC [virtual]\fP"

.PP
Called after initializing from cache 
.PP
\fBReturns:\fP
.RS 4
true if NOT has Queued operations 
.RE
.PP

.PP
Reimplemented from \fBNHibernate\&.Collection\&.AbstractPersistentCollection\fP\&.
.PP
Definition at line 20 of file CustomPersistentIdentifierBag\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
