.TH "NHibernate.DomainModel.Holder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Holder \- 
.PP
Summary description for \fBHolder\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.DomainModel\&.INamed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHolder\fP (string name)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList \fBOnes\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBFoo\fP[] \fBFooArray\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ISet< \fBFoo\fP > \fBFoos\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBHolder\fP \fBOtherHolder\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBHolder\fP\&. 


.PP
Definition at line 10 of file Holder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
