.TH "NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.RootClassMappingStrategyTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.RootClassMappingStrategyTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenRegisteredAsRootThenDoesNotRegisterTheStrategy\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredJoinedSubclassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredJoinedDeepSubclassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredSubclassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredDeepSubclassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredConcreteClassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredDeepConcreteClassThenTheStrategyIsDefinedEvenForRoot\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsRootThenCantRegisterAsSubclass\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsRootThenCantRegisterAsJoinedSubclass\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsRootThenCantRegisterAsUnionSubclass\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsRootThenIsEntity\fP ()"
.br
.ti -1c
.RI "void \fBWhenMultipleRootRegisteredThenThrowsMappingException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RootClassMappingStrategyTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
