.TH "NHibernate.Tuple.Property" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Tuple.Property \- 
.PP
Defines the basic contract of a \fBProperty\fP within the runtime metamodel\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Tuple\&.IdentifierProperty\fP, and \fBNHibernate\&.Tuple\&.StandardProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBProperty\fP (string name, string node, \fBIType\fP type)"
.br
.RI "\fIConstructor for \fBProperty\fP instances\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBNode\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIType\fP \fBType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the basic contract of a \fBProperty\fP within the runtime metamodel\&. 


.PP
Definition at line 10 of file Property\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Tuple\&.Property\&.Property (stringname, stringnode, \fBIType\fPtype)\fC [protected]\fP"

.PP
Constructor for \fBProperty\fP instances\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name by which the property can be referenced within its owner\&.
.br
\fInode\fP The node name to use for XML-based representation of this property\&.
.br
\fItype\fP The Hibernate \fBType\fP of this property\&.
.RE
.PP

.PP
Definition at line 22 of file Property\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
