.TH "NHibernate.Test.FilterTest.ConfigFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.FilterTest.ConfigFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddClassWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBAddFilterDefToClassWithFilters\fP ()"
.br
.ti -1c
.RI "void \fBWrongFilterDefInClass\fP ()"
.br
.ti -1c
.RI "void \fBWrongFilterDefInClassSeconPass\fP ()"
.br
.ti -1c
.RI "void \fBAddClassWithFiltersWithoutFilterDef\fP ()"
.br
.ti -1c
.RI "void \fBClassNoSecondPass\fP ()"
.br
.ti -1c
.RI "void \fBClassConditionInBothSides\fP ()"
.br
.ti -1c
.RI "void \fBDuplicatedFilterDef\fP ()"
.br
.ti -1c
.RI "void \fBMissedFilterDef\fP ()"
.br
.ti -1c
.RI "void \fBFilterDefWithoutReference\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ConfigFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
