.TH "NHibernate.DomainModel.Northwind.Entities.Region" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Northwind.Entities.Region \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.DomainModel\&.Northwind\&.Entities\&.Entity< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegion\fP (string description)"
.br
.ti -1c
.RI "virtual void \fBAddTerritory\fP (\fBTerritory\fP territory)"
.br
.ti -1c
.RI "virtual void \fBRemoveTerritory\fP (\fBTerritory\fP territory)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ReadOnlyCollection
.br
< \fBTerritory\fP > \fBTerritories\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Region\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
