.TH "NHibernate.Test.Pagination" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Pagination \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomDialectFixture\fP"
.br
.ti -1c
.RI "class \fBCustomMsSqlDialect\fP"
.br
.RI "\fIClass to simulate dialects with different binding of limit parameters using an MSSql database \fP"
.ti -1c
.RI "class \fBCustomMsSqlDriver\fP"
.br
.RI "\fIClass to work with \fBCustomMsSqlDialect\fP to allow verification of simulated limit parameters \fP"
.ti -1c
.RI "class \fBDataPoint\fP"
.br
.ti -1c
.RI "class \fBPaginationFixture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
