.TH "NHibernate.Test.NHSpecificTest.NH1217.Root" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1217.Root \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1217\&.DomainBase\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1217\&.IRoot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBINode\fP \fBAddNode\fP (string label)"
.br
.ti -1c
.RI "virtual \fBIEdge\fP \fBAddLink\fP (\fBINode\fP from, \fBINode\fP to, string label)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual String \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBINode\fP > \fBNodes\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file DomainObjects\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
