.TH "NHibernate.Test.DynamicEntity.Person" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicEntity.Person \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.DynamicEntity\&.Customer\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAddress\fP \fBAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ISet< \fBPerson\fP > \fBFamily\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Person\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
