.TH "NHibernate.Test.Bytecode.WrongProxyFactoryFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Bytecode.WrongProxyFactoryFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Bytecode\&.IProxyFactoryFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIProxyFactory\fP \fBBuildProxyFactory\fP ()"
.br
.RI "\fIBuild a proxy factory specifically for handling runtime lazy loading\&. \fP"
.ti -1c
.RI "bool \fBIsInstrumented\fP (System\&.Type entityClass)"
.br
.ti -1c
.RI "bool \fBIsProxy\fP (object entity)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIProxyValidator\fP \fBProxyValidator\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file WrongProxyFactoryFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIProxyFactory\fP NHibernate\&.Test\&.Bytecode\&.WrongProxyFactoryFactory\&.BuildProxyFactory ()"

.PP
Build a proxy factory specifically for handling runtime lazy loading\&. 
.PP
\fBReturns:\fP
.RS 4
The lazy-load proxy factory\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Bytecode\&.IProxyFactoryFactory\fP\&.
.PP
Definition at line 16 of file WrongProxyFactoryFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
