.TH "NHibernate.Engine.ForeignKeys.Nullifier" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.ForeignKeys.Nullifier \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullifier\fP (object self, bool isDelete, bool isEarlyInsert, \fBISessionImplementor\fP session)"
.br
.ti -1c
.RI "void \fBNullifyTransientReferences\fP (object[] values, \fBIType\fP[] types)"
.br
.RI "\fINullify all references to entities that have not yet been inserted in the database, where the foreign key points toward that entity \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ForeignKeys\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Engine\&.ForeignKeys\&.Nullifier\&.NullifyTransientReferences (object[]values, \fBIType\fP[]types)"

.PP
Nullify all references to entities that have not yet been inserted in the database, where the foreign key points toward that entity 
.PP
Definition at line 34 of file ForeignKeys\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
