.TH "NHibernate.Test.NHSpecificTest.NH2195.SQLiteMultiCriteriaTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2195.SQLiteMultiCriteriaTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.BugTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSingleCriteriaQueriesWithIntsShouldExecuteCorrectly\fP ()"
.br
.ti -1c
.RI "void \fBSingleCriteriaQueriesWithStringsShouldExecuteCorrectly\fP ()"
.br
.ti -1c
.RI "void \fBMultiCriteriaQueriesWithIntsShouldExecuteCorrectly\fP ()"
.br
.ti -1c
.RI "void \fBMultiCriteriaQueriesWithStringsShouldExecuteCorrectly\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.ti -1c
.RI "override bool \fBAppliesTo\fP (\fBNHibernate\&.Dialect\&.Dialect\fP dialect)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file SQLiteMultiCriteriaTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
