.TH "NHibernate.Cfg.MappingSchema.IMappingDocumentParser" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.IMappingDocumentParser \- 
.PP
Responsible for converting a Stream of HBM XML into an instance of \fBHbmMapping\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Cfg\&.MappingSchema\&.MappingDocumentParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHbmMapping\fP \fBParse\fP (Stream stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible for converting a Stream of HBM XML into an instance of \fBHbmMapping\fP\&. 


.PP
Definition at line 9 of file IMappingDocumentParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
