.TH "NHibernate.Cfg.MappingSchema.HbmComment" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmComment \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string[] \fBText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 202 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
