.TH "NHibernate.Cfg.MappingSchema.HbmAny" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmAny \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.AbstractDecoratable\fP, \fBNHibernate\&.Cfg\&.MappingSchema\&.IEntityPropertyMapping\fP, \fBNHibernate\&.Cfg\&.MappingSchema\&.IColumnsMapping\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IAnyMapping\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmMeta\fP[] \fBmeta\fP"
.br
.ti -1c
.RI "\fBHbmMetaValue\fP[] \fBmetavalue\fP"
.br
.ti -1c
.RI "\fBHbmColumn\fP[] \fBcolumn\fP"
.br
.ti -1c
.RI "string \fBcolumn1\fP"
.br
.ti -1c
.RI "string \fBidtype\fP"
.br
.ti -1c
.RI "string \fBmetatype\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBaccess\fP"
.br
.ti -1c
.RI "bool \fBinsert\fP"
.br
.ti -1c
.RI "bool \fBupdate\fP"
.br
.ti -1c
.RI "string \fBcascade\fP"
.br
.ti -1c
.RI "string \fBindex\fP"
.br
.ti -1c
.RI "bool \fBoptimisticlock\fP"
.br
.ti -1c
.RI "bool \fBlazy\fP"
.br
.ti -1c
.RI "string \fBnode\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBAccess\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBOptimisticLock\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLazyProperty\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBHbmMeta\fP[] \fBMetadatas\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHbmColumn\fP > \fBColumns\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBMetaType\fP\fC [get]\fP"
.br
.ti -1c
.RI "ICollection< \fBHbmMetaValue\fP > \fBMetaValues\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 11 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
