.TH "NHibernate.DomainModel.ComponentCollection" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.ComponentCollection \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "IList \fBFoos\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the _foos \fP"
.ti -1c
.RI "string \fBStr\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the _str \fP"
.ti -1c
.RI "IList \fBFloats\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the _floats \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ComponentCollection\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IList NHibernate\&.DomainModel\&.ComponentCollection\&.Floats\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the _floats 
.PP
Definition at line 47 of file ComponentCollection\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.ComponentCollection\&.Foos\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the _foos 
.PP
Definition at line 18 of file ComponentCollection\&.cs\&.
.SS "string NHibernate\&.DomainModel\&.ComponentCollection\&.Str\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the _str 
.PP
Definition at line 33 of file ComponentCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
