.TH "NHibernate.Criterion.QueryOver" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.QueryOver \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Criterion\&.QueryOver< TRoot >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBQueryOver\fP< T, T > \fBOf< T >\fP ()"
.br
.ti -1c
.RI "static \fBQueryOver\fP< T, T > \fBOf< T >\fP (\fBExpression\fP< Func< T >> alias)"
.br
.ti -1c
.RI "static \fBQueryOver\fP< T, T > \fBOf< T >\fP (string entityName)"
.br
.ti -1c
.RI "static \fBQueryOver\fP< T, T > \fBOf< T >\fP (string entityName, \fBExpression\fP< Func< T >> alias)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBICriteria\fP \fBcriteria\fP"
.br
.ti -1c
.RI "\fBCriteriaImpl\fP \fBimpl\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBICriteria\fP \fBUnderlyingCriteria\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBICriteria\fP \fBRootCriteria\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBDetachedCriteria\fP \fBDetachedCriteria\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file QueryOver\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
