.TH "NHibernate.Hql.Ast.ANTLR.Tree.IInitializableNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.IInitializableNode \- 
.PP
An interface for initializeable AST nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.HqlSqlWalkerNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (Object param)"
.br
.RI "\fIInitializes the node with the parameter\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An interface for initializeable AST nodes\&. 


.PP
Definition at line 8 of file IInitializableNode\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IInitializableNode\&.Initialize (Objectparam)"

.PP
Initializes the node with the parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparam\fP the initialization parameter\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
