.TH "NHibernate.Test.SystemTransactions.TransactionNotificationFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.SystemTransactions.TransactionNotificationFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRecordingInterceptor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNoTransaction\fP ()"
.br
.ti -1c
.RI "void \fBAfterBegin\fP ()"
.br
.ti -1c
.RI "void \fBComplete\fP ()"
.br
.ti -1c
.RI "void \fBRollback\fP ()"
.br
.ti -1c
.RI "void \fBTwoTransactionScopesInsideOneSession\fP ()"
.br
.ti -1c
.RI "void \fBOneTransactionScopesInsideOneSession\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file TransactionNotificationFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
