.TH "NHibernate.Test.NHSpecificTest.NH251.IDynamicFieldContainer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH251.IDynamicFieldContainer \- 
.PP
The \fBDictionaryAccessor\fP access strategy uses this interface to access properties  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH251\&.CustomAccessDO\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IDictionary \fBFields\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBDictionaryAccessor\fP access strategy uses this interface to access properties 


.PP
Definition at line 12 of file CustomAccessDO\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
