.TH "NHibernate.Test.GenericTest.Overall" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.GenericTest.Overall \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBA< T >\fP"
.br
.RI "\fIThis class is used in \fBFixture\fP with \fCint\fP substituted for \fIT\fP \&. \fP"
.ti -1c
.RI "class \fBB\fP"
.br
.ti -1c
.RI "class \fBFixture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
