.TH "NHibernate.Test.MappingExceptions.MissingDefCtorFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingExceptions.MissingDefCtorFixture \- 
.PP
\fBA\fP TestFixture to verify the Exception thrown when a mapped class is missing the default ctor is readable and understandable\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClassMissingDefaultCtor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP TestFixture to verify the Exception thrown when a mapped class is missing the default ctor is readable and understandable\&. 


.PP
Definition at line 12 of file MissingDefCtorFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
