.TH "NHibernate.DomainModel.MoreStuff" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.MoreStuff \- 
.PP
Summary description for \fBMoreStuff\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBStringId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBIntId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList \fBStuffs\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBMoreStuff\fP\&. 


.PP
Definition at line 10 of file MoreStuff\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
