.TH "NHibernate.Hql.Ast.ANTLR.Tree.AbstractRestrictableStatement" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.AbstractRestrictableStatement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractStatement\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IRestrictableStatement\fP\&.
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.DeleteStatement\fP, \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.QueryNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.UpdateStatement\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractRestrictableStatement\fP (IToken token)"
.br
.ti -1c
.RI "abstract \fBIInternalLogger\fP \fBGetLog\fP ()"
.br
.ti -1c
.RI "abstract int \fBGetWhereClauseParentTokenType\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBFromClause\fP \fBFromClause\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBHasWhereClause\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIASTNode\fP \fBWhereClause\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file AbstractRestrictableStatement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
