.TH "NHibernate.Test.NHSpecificTest.NH318.NotNullPropertyHolder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH318.NotNullPropertyHolder \- 
.PP
Summary description for \fBNotNullPropertyHolder\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "String \fBNotNullProperty\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBNotNullPropertyHolder\fP\&. 


.PP
Definition at line 8 of file NotNullPropertyHolder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
