.TH "NHibernate.DuplicateMappingException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DuplicateMappingException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.MappingException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDuplicateMappingException\fP (string customMessage, string type, string name)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.ti -1c
.RI "\fBDuplicateMappingException\fP (string type, string name)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.ti -1c
.RI "\fBDuplicateMappingException\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class with serialized data\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBType\fP\fC [get]\fP"
.br
.RI "\fIThe type of the duplicated object \fP"
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "\fIThe name of the duplicated object \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file DuplicateMappingException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.DuplicateMappingException\&.DuplicateMappingException (stringcustomMessage, stringtype, stringname)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcustomMessage\fP The message that describes the error\&. 
.br
\fIname\fP The name of the duplicate object
.br
\fItype\fP The type of the duplicate object
.RE
.PP

.PP
Definition at line 34 of file DuplicateMappingException\&.cs\&.
.SS "NHibernate\&.DuplicateMappingException\&.DuplicateMappingException (stringtype, stringname)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP The name of the duplicate object
.br
\fItype\fP The type of the duplicate object
.RE
.PP

.PP
Definition at line 46 of file DuplicateMappingException\&.cs\&.
.SS "NHibernate\&.DuplicateMappingException\&.DuplicateMappingException (SerializationInfoinfo, StreamingContextcontext)"

.PP
Initializes a new instance of the \fBMappingException\fP class with serialized data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP The SerializationInfo that holds the serialized object data about the exception being thrown\&. 
.br
\fIcontext\fP The StreamingContext that contains contextual information about the source or destination\&. 
.RE
.PP

.PP
Definition at line 62 of file DuplicateMappingException\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string NHibernate\&.DuplicateMappingException\&.Name\fC [get]\fP"

.PP
The name of the duplicated object 
.PP
Definition at line 24 of file DuplicateMappingException\&.cs\&.
.SS "string NHibernate\&.DuplicateMappingException\&.Type\fC [get]\fP"

.PP
The type of the duplicated object 
.PP
Definition at line 16 of file DuplicateMappingException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
