.TH "NHibernate.Engine.IdentifierValue.UndefinedClass" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.IdentifierValue.UndefinedClass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Engine\&.IdentifierValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBIsUnsaved\fP (object id)"
.br
.RI "\fIDoes the given identifier belong to a new instance \fP"
.ti -1c
.RI "override object \fBGetDefaultValue\fP (object currentValue)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 110 of file IdentifierValue\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool NHibernate\&.Engine\&.IdentifierValue\&.UndefinedClass\&.IsUnsaved (objectid)\fC [virtual]\fP"

.PP
Does the given identifier belong to a new instance 
.PP
Reimplemented from \fBNHibernate\&.Engine\&.IdentifierValue\fP\&.
.PP
Definition at line 112 of file IdentifierValue\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
