.TH "NHibernate.Exceptions.SqlStateExtracter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Exceptions.SqlStateExtracter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Exceptions\&.ReflectionBasedSqlStateExtracter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBExtractErrorCode\fP (DbException sqle)"
.br
.ti -1c
.RI "string \fBExtractSqlState\fP (DbException sqle)"
.br
.ti -1c
.RI "abstract int \fBExtractSingleErrorCode\fP (DbException sqle)"
.br
.ti -1c
.RI "abstract string \fBExtractSingleSqlState\fP (DbException sqle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file SqlStateExtracter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
