.TH "NHibernate.Properties.IndexPropertyAccessor.IndexGetter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Properties.IndexPropertyAccessor.IndexGetter \- 
.PP
The Getter implementation for index backrefs\&. 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Properties\&.IGetter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexGetter\fP (\fBIndexPropertyAccessor\fP encloser)"
.br
.ti -1c
.RI "object \fBGet\fP (object target)"
.br
.RI "\fIWhen implemented by a class, gets the value of the Property/Field from the object\&. \fP"
.ti -1c
.RI "object \fBGetForInsert\fP (object owner, IDictionary mergeMap, \fBISessionImplementor\fP session)"
.br
.RI "\fIGet the property value from the given owner instance\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "System\&.Type \fBReturnType\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBPropertyName\fP\fC [get]\fP"
.br
.ti -1c
.RI "MethodInfo \fBMethod\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Getter implementation for index backrefs\&.


.PP
Definition at line 68 of file IndexPropertyAccessor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object NHibernate\&.Properties\&.IndexPropertyAccessor\&.IndexGetter\&.Get (objecttarget)"

.PP
When implemented by a class, gets the value of the Property/Field from the object\&. 
.PP
\fBParameters:\fP
.RS 4
\fItarget\fP The object to get the Property/Field value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The value of the Property for the target\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPropertyAccessException\fP\fP Thrown when there is a problem getting the value from the target\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Properties\&.IGetter\fP\&.
.PP
Definition at line 79 of file IndexPropertyAccessor\&.cs\&.
.SS "object NHibernate\&.Properties\&.IndexPropertyAccessor\&.IndexGetter\&.GetForInsert (objectowner, IDictionarymergeMap, \fBISessionImplementor\fPsession)"

.PP
Get the property value from the given owner instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The instance containing the value to be retrieved\&. 
.br
\fImergeMap\fP a map of merged persistent instances to detached instances 
.br
\fIsession\fP The session from which this request originated\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The extracted value\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Properties\&.IGetter\fP\&.
.PP
Definition at line 99 of file IndexPropertyAccessor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
