.TH "NHibernate.Test.ReadOnly.ReadOnlyVersionedNodes" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ReadOnly.ReadOnlyVersionedNodes \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.ReadOnly\&.AbstractReadOnlyTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetReadOnlyTrueAndFalse\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSetReadOnlyTwice\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSetModifiable\fP ()"
.br
.ti -1c
.RI "void \fBUpdateSetReadOnlySetModifiableFailureExpected\fP ()"
.br
.ti -1c
.RI "void \fBSetReadOnlyUpdateSetModifiableFailureExpected\fP ()"
.br
.ti -1c
.RI "void \fBAddNewChildToReadOnlyParent\fP ()"
.br
.ti -1c
.RI "void \fBUpdateParentWithNewChildCommitWithReadOnlyParent\fP ()"
.br
.ti -1c
.RI "void \fBMergeDetachedParentWithNewChildCommitWithReadOnlyParent\fP ()"
.br
.ti -1c
.RI "void \fBGetParentMakeReadOnlyThenMergeDetachedParentWithNewChildC\fP ()"
.br
.ti -1c
.RI "void \fBMergeUnchangedDetachedParentChildren\fP ()"
.br
.ti -1c
.RI "void \fBAddNewParentToReadOnlyChild\fP ()"
.br
.ti -1c
.RI "void \fBUpdateChildWithNewParentCommitWithReadOnlyChild\fP ()"
.br
.ti -1c
.RI "void \fBMergeDetachedChildWithNewParentCommitWithReadOnlyChild\fP ()"
.br
.ti -1c
.RI "void \fBGetChildMakeReadOnlyThenMergeDetachedChildWithNewParent\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file ReadOnlyVersionedNodes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
