.TH "NHibernate.Test.UserCollection.Parameterized.IDefaultableList" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UserCollection.Parameterized.IDefaultableList \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IList\&.
.PP
Inherited by \fBNHibernate\&.Test\&.UserCollection\&.Parameterized\&.DefaultableListImpl\fP, and \fBNHibernate\&.Test\&.UserCollection\&.Parameterized\&.PersistentDefaultableList\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDefaultValue\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file IDefaultableList\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
