.TH "NHibernate.Criterion.InsensitiveLikeExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.InsensitiveLikeExpression \- 
.PP
An \fBICriterion\fP that represents an 'like' constraint that is \fBnot\fP case sensitive\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInsensitiveLikeExpression\fP (\fBIProjection\fP projection, string value, \fBMatchMode\fP matchMode)"
.br
.RI "\fIInitializes a new instance of the \fBInsensitiveLikeExpression\fP class\&. \fP"
.ti -1c
.RI "\fBInsensitiveLikeExpression\fP (\fBIProjection\fP projection, object value)"
.br
.RI "\fIInitializes a new instance of the \fBInsensitiveLikeExpression\fP class\&. \fP"
.ti -1c
.RI "\fBInsensitiveLikeExpression\fP (string propertyName, object value)"
.br
.RI "\fIInitialize a new instance of the \fBInsensitiveLikeExpression\fP class for a named \fBProperty\fP and its value\&. \fP"
.ti -1c
.RI "\fBInsensitiveLikeExpression\fP (string propertyName, string value, \fBMatchMode\fP matchMode)"
.br
.ti -1c
.RI "override \fBSqlString\fP \fBToSqlString\fP (\fBICriteria\fP criteria, \fBICriteriaQuery\fP criteriaQuery, IDictionary< string, \fBIFilter\fP > enabledFilters)"
.br
.RI "\fIRender a SqlString for the expression\&. \fP"
.ti -1c
.RI "override \fBTypedValue\fP[] \fBGetTypedValues\fP (\fBICriteria\fP criteria, \fBICriteriaQuery\fP criteriaQuery)"
.br
.RI "\fIReturn typed values for all parameters in the rendered SQL fragment \fP"
.ti -1c
.RI "\fBTypedValue\fP \fBGetParameterTypedValue\fP (\fBICriteria\fP criteria, \fBICriteriaQuery\fP criteriaQuery)"
.br
.ti -1c
.RI "override \fBIProjection\fP[] \fBGetProjections\fP ()"
.br
.RI "\fIReturn all projections used in this criterion \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIGets a string representation of the \fBAbstractCriterion\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBICriterion\fP that represents an 'like' constraint that is \fBnot\fP case sensitive\&. 


.PP
Definition at line 16 of file InsensitiveLikeExpression\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.InsensitiveLikeExpression (\fBIProjection\fPprojection, stringvalue, \fBMatchMode\fPmatchMode)"

.PP
Initializes a new instance of the \fBInsensitiveLikeExpression\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprojection\fP The projection\&.
.br
\fIvalue\fP The value\&.
.br
\fImatchMode\fP The match mode\&.
.RE
.PP

.PP
Definition at line 28 of file InsensitiveLikeExpression\&.cs\&.
.SS "NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.InsensitiveLikeExpression (\fBIProjection\fPprojection, objectvalue)"

.PP
Initializes a new instance of the \fBInsensitiveLikeExpression\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprojection\fP The projection\&.
.br
\fIvalue\fP The value\&.
.RE
.PP

.PP
Definition at line 39 of file InsensitiveLikeExpression\&.cs\&.
.SS "NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.InsensitiveLikeExpression (stringpropertyName, objectvalue)"

.PP
Initialize a new instance of the \fBInsensitiveLikeExpression\fP class for a named \fBProperty\fP and its value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP The name of the \fBProperty\fP in the class\&.
.br
\fIvalue\fP The value for the \fBProperty\fP\&.
.RE
.PP

.PP
Definition at line 51 of file InsensitiveLikeExpression\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBIProjection\fP [] NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.GetProjections ()\fC [virtual]\fP"

.PP
Return all projections used in this criterion 
.PP
\fBReturns:\fP
.RS 4
An array of \fBIProjection\fP used by the \fBExpression\fP\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.PP
Definition at line 116 of file InsensitiveLikeExpression\&.cs\&.
.SS "override \fBTypedValue\fP [] NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.GetTypedValues (\fBICriteria\fPcriteria, \fBICriteriaQuery\fPcriteriaQuery)\fC [virtual]\fP"

.PP
Return typed values for all parameters in the rendered SQL fragment 
.PP
\fBReturns:\fP
.RS 4
An array of TypedValues for the \fBExpression\fP\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.PP
Definition at line 93 of file InsensitiveLikeExpression\&.cs\&.
.SS "override \fBSqlString\fP NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.ToSqlString (\fBICriteria\fPcriteria, \fBICriteriaQuery\fPcriteriaQuery, IDictionary< string, \fBIFilter\fP >enabledFilters)\fC [virtual]\fP"

.PP
Render a SqlString for the expression\&. 
.PP
\fBReturns:\fP
.RS 4
A SqlString that contains a valid Sql fragment\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.PP
Definition at line 62 of file InsensitiveLikeExpression\&.cs\&.
.SS "override string NHibernate\&.Criterion\&.InsensitiveLikeExpression\&.ToString ()\fC [virtual]\fP"

.PP
Gets a string representation of the \fBAbstractCriterion\fP\&. 
.PP
\fBReturns:\fP
.RS 4
A String that shows the contents of the \fBAbstractCriterion\fP\&. 
.RE
.PP
.PP
This is not a well formed Sql fragment\&. It is useful for logging what the \fBAbstractCriterion\fP looks like\&. 
.PP
Implements \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.PP
Definition at line 125 of file InsensitiveLikeExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
