.TH "NHibernate.Mapping.ByCode.IClassAttributesMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IClassAttributesMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IEntityAttributesMapper\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IEntitySqlsMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.IClassMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBId\fP (Action< \fBIIdMapper\fP > idMapper)"
.br
.ti -1c
.RI "void \fBId\fP (MemberInfo idProperty, Action< \fBIIdMapper\fP > idMapper)"
.br
.ti -1c
.RI "void \fBComponentAsId\fP (MemberInfo idProperty, Action< \fBIComponentAsIdMapper\fP > idMapper)"
.br
.ti -1c
.RI "void \fBComposedId\fP (Action< \fBIComposedIdMapper\fP > idPropertiesMapping)"
.br
.ti -1c
.RI "void \fBDiscriminator\fP (Action< \fBIDiscriminatorMapper\fP > discriminatorMapping)"
.br
.ti -1c
.RI "void \fBDiscriminatorValue\fP (object value)"
.br
.ti -1c
.RI "void \fBTable\fP (string tableName)"
.br
.ti -1c
.RI "void \fBCatalog\fP (string catalogName)"
.br
.ti -1c
.RI "void \fBSchema\fP (string schemaName)"
.br
.ti -1c
.RI "void \fBMutable\fP (bool isMutable)"
.br
.ti -1c
.RI "void \fBVersion\fP (MemberInfo versionProperty, Action< \fBIVersionMapper\fP > versionMapping)"
.br
.ti -1c
.RI "void \fBNaturalId\fP (Action< \fBINaturalIdMapper\fP > naturalIdMapping)"
.br
.ti -1c
.RI "void \fBCache\fP (Action< \fBICacheMapper\fP > cacheMapping)"
.br
.ti -1c
.RI "void \fBFilter\fP (string filterName, Action< \fBIFilterMapper\fP > filterMapping)"
.br
.ti -1c
.RI "void \fBWhere\fP (string whereClause)"
.br
.ti -1c
.RI "void \fBSchemaAction\fP (SchemaAction action)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file IClassMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
