.TH "NHibernate.Cfg.MappingSchema.IPropertiesContainerMapping" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.IPropertiesContainerMapping \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Cfg\&.MappingSchema\&.HbmJoin\fP, \fBNHibernate\&.Cfg\&.MappingSchema\&.HbmNaturalId\fP, \fBNHibernate\&.Cfg\&.MappingSchema\&.IComponentMapping\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IEntityMapping\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable
.br
< \fBIEntityPropertyMapping\fP > \fBProperties\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file IPropertiesContainerMapping\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
