.TH "NHibernate.Test.NHSpecificTest.ElementsEnums" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.ElementsEnums \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractIntEnumsBagFixture\fP"
.br
.ti -1c
.RI "class \fBIntEnumsBagFixture\fP"
.br
.ti -1c
.RI "class \fBIntEnumsBagNoNameFixture\fP"
.br
.ti -1c
.RI "class \fBIntEnumsBagPartialNameFixture\fP"
.br
.ti -1c
.RI "class \fBSimpleWithEnums\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSomething\fP { \fBA\fP, \fBB\fP, \fBC\fP, \fBD\fP, \fBE\fP, \fBF\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
