.TH "NHibernate.Dialect.Function.StandardSafeSQLFunction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Function.StandardSafeSQLFunction \- 
.PP
Provides a standard implementation that supports the majority of the HQL functions that are translated to SQL\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Function\&.StandardSQLFunction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardSafeSQLFunction\fP (string name, int allowedArgsCount)"
.br
.RI "\fIInitializes a new instance of the \fBStandardSafeSQLFunction\fP class\&. \fP"
.ti -1c
.RI "\fBStandardSafeSQLFunction\fP (string name, \fBIType\fP typeValue, int allowedArgsCount)"
.br
.RI "\fIInitializes a new instance of the \fBStandardSafeSQLFunction\fP class\&. \fP"
.ti -1c
.RI "override \fBSqlString\fP \fBRender\fP (System\&.Collections\&.IList args, \fBNHibernate\&.Engine\&.ISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provides a standard implementation that supports the majority of the HQL functions that are translated to SQL\&. 

The \fBDialect\fP and its sub-classes use this class to provide details required for processing of the associated function\&. 
.PP
Definition at line 18 of file StandardSafeSQLFunction\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Dialect\&.Function\&.StandardSafeSQLFunction\&.StandardSafeSQLFunction (stringname, intallowedArgsCount)"

.PP
Initializes a new instance of the \fBStandardSafeSQLFunction\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP SQL function name\&.
.br
\fIallowedArgsCount\fP Exact number of arguments expected\&.
.RE
.PP

.PP
Definition at line 26 of file StandardSafeSQLFunction\&.cs\&.
.SS "NHibernate\&.Dialect\&.Function\&.StandardSafeSQLFunction\&.StandardSafeSQLFunction (stringname, \fBIType\fPtypeValue, intallowedArgsCount)"

.PP
Initializes a new instance of the \fBStandardSafeSQLFunction\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP SQL function name\&.
.br
\fItypeValue\fP Return type for the fuction\&.
.br
\fIallowedArgsCount\fP Exact number of arguments expected\&.
.RE
.PP

.PP
Definition at line 38 of file StandardSafeSQLFunction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
