.TH "NHibernate.Criterion.Lambda.QueryOverOrderBuilder< TRoot, TSubType >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.Lambda.QueryOverOrderBuilder< TRoot, TSubType > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.Lambda\&.QueryOverOrderBuilderBase< TReturn, TRoot, TSubType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryOverOrderBuilder\fP (\fBQueryOver\fP< TRoot, TSubType > root, \fBExpression\fP< Func< TSubType, object >> path)"
.br
.ti -1c
.RI "\fBQueryOverOrderBuilder\fP (\fBQueryOver\fP< TRoot, TSubType > root, \fBExpression\fP< Func< object >> path, bool isAlias)"
.br
.ti -1c
.RI "\fBQueryOverOrderBuilder\fP (\fBQueryOver\fP< TRoot, TSubType > root, \fBExpressionProcessor\&.ProjectionInfo\fP projection)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file QueryOverOrderBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
