.TH "NHibernate.Mapping.ByCode.PropertyToField" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.PropertyToField \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static FieldInfo \fBGetBackFieldInfo\fP (PropertyInfo subject)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static IDictionary< string, 
.br
\fBIFieldNamingStrategy\fP > \fBDefaultStrategies\fP\fC [get]\fP"
.br
.RI "\fIDictionary containing the embedded strategies to find a field giving a property name\&. The key is the 'partial-name' of the strategy used in XML mapping\&. The value is an instance of the strategy\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file PropertyToField\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IDictionary<string, \fBIFieldNamingStrategy\fP> NHibernate\&.Mapping\&.ByCode\&.PropertyToField\&.DefaultStrategies\fC [static]\fP, \fC [get]\fP"

.PP
Dictionary containing the embedded strategies to find a field giving a property name\&. The key is the 'partial-name' of the strategy used in XML mapping\&. The value is an instance of the strategy\&. 
.PP
Definition at line 26 of file PropertyToField\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
