.TH "NHibernate.Hql.Ast.ANTLR.Tree.AbstractStatement" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.AbstractStatement \- 
.PP
Convenience implementation of Statement to centralize common functionality\&. Author: Steve Ebersole Ported by: Steve Strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.HqlSqlWalkerNode\fP, \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IDisplayableNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IStatement\fP\&.
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractRestrictableStatement\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.InsertStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBGetDisplayText\fP ()"
.br
.RI "\fIReturns additional display text for the AST node\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractStatement\fP (IToken token)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract bool \fBNeedsExecutor\fP\fC [get]\fP"
.br
.ti -1c
.RI "abstract int \fBStatementType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Convenience implementation of Statement to centralize common functionality\&. Author: Steve Ebersole Ported by: Steve Strong 


.PP
Definition at line 13 of file AbstractStatement\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "String NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractStatement\&.GetDisplayText ()"

.PP
Returns additional display text for the AST node\&. 
.PP
\fBReturns:\fP
.RS 4
The additional display text\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IDisplayableNode\fP\&.
.PP
Definition at line 33 of file AbstractStatement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
