.TH "NHibernate.Test.DynamicEntity.Tuplizer.EntityNameInterceptor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicEntity.Tuplizer.EntityNameInterceptor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.EmptyInterceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetEntityName\fP (object entity)"
.br
.RI "\fIGet the entity name for a persistent or transient instance\fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file EntityNameInterceptor\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string NHibernate\&.Test\&.DynamicEntity\&.Tuplizer\&.EntityNameInterceptor\&.GetEntityName (objectentity)\fC [virtual]\fP"

.PP
Get the entity name for a persistent or transient instance
.PP
\fBParameters:\fP
.RS 4
\fIentity\fP an entity instance 
.RE
.PP
\fBReturns:\fP
.RS 4
the name of the entity 
.RE
.PP

.PP
Reimplemented from \fBNHibernate\&.EmptyInterceptor\fP\&.
.PP
Definition at line 5 of file EntityNameInterceptor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
