.TH "NHibernate.SqlCommand.ANSICaseFragment" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.ANSICaseFragment \- 
.PP
An ANSI SQL CASE expression\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.SqlCommand\&.CaseFragment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBANSICaseFragment\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "override string \fBToSqlStringFragment\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An ANSI SQL CASE expression\&. 

\fCcase when \&.\&.\&. then \&.\&.\&. end as \&.\&.\&.\fP 
.PP
This class looks StringHelper\&.SqlParameter safe\&.\&.\&.
.PP
Definition at line 10 of file ANSICaseFragment\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
