.TH "NHibernate.Exceptions.LockAcquisitionException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Exceptions.LockAcquisitionException \- 
.PP
Implementation of \fBADOException\fP indicating a problem acquiring lock on the database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.ADOException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLockAcquisitionException\fP (SerializationInfo info, StreamingContext context)"
.br
.ti -1c
.RI "\fBLockAcquisitionException\fP (string message, Exception innerException, string sql)"
.br
.ti -1c
.RI "\fBLockAcquisitionException\fP (string message, Exception innerException)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implementation of \fBADOException\fP indicating a problem acquiring lock on the database\&. 


.PP
Definition at line 11 of file LockAcquisitionException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
