.TH "NHibernate.Type.TimeAsTimeSpanType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.TimeAsTimeSpanType \- 
.PP
Maps a System\&.TimeSpan Property to an DbType\&.Time column This is an extra way to map a DbType\&.Time\&. You already have \fBTimeType\fP but mapping against a DateTime\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.PrimitiveType\fP, and \fBNHibernate\&.Type\&.IVersionType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, int index)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, string name)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override void \fBSet\fP (IDbCommand st, object value, int index)"
.br
.RI "\fIWhen implemented by a class, put the value from the mapped Property into to the IDbCommand\&. \fP"
.ti -1c
.RI "override string \fBToString\fP (object val)"
.br
.RI "\fIA representation of the value to be embedded in an XML element \fP"
.ti -1c
.RI "object \fBNext\fP (object current, \fBISessionImplementor\fP session)"
.br
.RI "\fIWhen implemented by a class, increments the version\&. \fP"
.ti -1c
.RI "virtual object \fBSeed\fP (\fBISessionImplementor\fP session)"
.br
.RI "\fIWhen implemented by a class, gets an initial version\&. \fP"
.ti -1c
.RI "object \fBStringToObject\fP (string xml)"
.br
.ti -1c
.RI "override object \fBFromStringValue\fP (string xml)"
.br
.ti -1c
.RI "override string \fBObjectToSQLString\fP (object value, \fBDialect\&.Dialect\fP dialect)"
.br
.RI "\fIWhen implemented by a class, return a String representation of the value, suitable for embedding in an SQL statement \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBReturnedClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "IComparer \fBComparator\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBPrimitiveClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "override object \fBDefaultValue\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Maps a System\&.TimeSpan Property to an DbType\&.Time column This is an extra way to map a DbType\&.Time\&. You already have \fBTimeType\fP but mapping against a DateTime\&. 


.PP
Definition at line 16 of file TimeAsTimeSpanType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object NHibernate\&.Type\&.TimeAsTimeSpanType\&.Get (IDataReaderrs, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIindex\fP The index of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 30 of file TimeAsTimeSpanType\&.cs\&.
.SS "override object NHibernate\&.Type\&.TimeAsTimeSpanType\&.Get (IDataReaderrs, stringname)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIname\fP The name of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP
.PP
Most implementors just call the \fBGet(IDataReader, int)\fP overload of this method\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 46 of file TimeAsTimeSpanType\&.cs\&.
.SS "object NHibernate\&.Type\&.TimeAsTimeSpanType\&.Next (objectcurrent, \fBISessionImplementor\fPsession)"

.PP
When implemented by a class, increments the version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcurrent\fP The current version
.br
\fIsession\fP The current session, if available\&.
.RE
.PP
\fBReturns:\fP
.RS 4
an instance of the \fBIType\fP that has been incremented\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Definition at line 80 of file TimeAsTimeSpanType\&.cs\&.
.SS "override string NHibernate\&.Type\&.TimeAsTimeSpanType\&.ObjectToSQLString (objectvalue, \fBDialect\&.Dialect\fPdialect)\fC [virtual]\fP"

.PP
When implemented by a class, return a String representation of the value, suitable for embedding in an SQL statement 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The object to convert to a string for the SQL statement\&.
.br
\fIdialect\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
A string that containts a well formed SQL Statement\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.PrimitiveType\fP\&.
.PP
Definition at line 117 of file TimeAsTimeSpanType\&.cs\&.
.SS "virtual object NHibernate\&.Type\&.TimeAsTimeSpanType\&.Seed (\fBISessionImplementor\fPsession)\fC [virtual]\fP"

.PP
When implemented by a class, gets an initial version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The current session, if available\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of the type\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Definition at line 85 of file TimeAsTimeSpanType\&.cs\&.
.SS "override void NHibernate\&.Type\&.TimeAsTimeSpanType\&.Set (IDbCommandcmd, objectvalue, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, put the value from the mapped Property into to the IDbCommand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP The IDbCommand to put the value into\&.
.br
\fIvalue\fP The object that contains the value\&.
.br
\fIindex\fP The index of the IDbDataParameter to start writing the values to\&.
.RE
.PP
.PP
Implementors do not need to handle possibility of null values because this will only be called from \fBNullSafeSet(IDbCommand, object, int)\fP after it has checked for nulls\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 62 of file TimeAsTimeSpanType\&.cs\&.
.SS "override string NHibernate\&.Type\&.TimeAsTimeSpanType\&.ToString (objectval)\fC [virtual]\fP"

.PP
A representation of the value to be embedded in an XML element 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP The object that contains the values\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An Xml formatted string\&.
.RE
.PP
.PP
This just calls Object\&.ToString so if there is a possibility of this \fBPrimitiveType\fP having any characters that need to be encoded then this method should be overridden\&. 
.PP
Reimplemented from \fBNHibernate\&.Type\&.PrimitiveType\fP\&.
.PP
Definition at line 73 of file TimeAsTimeSpanType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
