.TH "NHibernate.Test.ReadOnly.TextHolder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ReadOnly.TextHolder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextHolder\fP (string text)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBSupportedForDialect\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.RI "\fIReturn true if the dialect supports the 'text' type\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBTheText\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file TextHolder\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool NHibernate\&.Test\&.ReadOnly\&.TextHolder\&.SupportedForDialect (\fBDialect\&.Dialect\fPdialect)\fC [static]\fP"

.PP
Return true if the dialect supports the 'text' type\&. 
.PP
Definition at line 11 of file TextHolder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
