.TH "NHibernate.Hql.Ast.ANTLR.Tree.IsNullLogicOperatorNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.IsNullLogicOperatorNode \- 
.PP
Represents a 'is null' check\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractNullnessCheckNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsNullLogicOperatorNode\fP (IToken token)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBExpansionConnectorType\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBExpansionConnectorText\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents a 'is null' check\&. 


.PP
Definition at line 10 of file IsNullLogicOperatorNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
