.TH "NHibernate.Loader.Custom.EntityFetchReturn" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.Custom.EntityFetchReturn \- 
.PP
Specifically a fetch return that refers to an entity association\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Loader\&.Custom\&.FetchReturn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityFetchReturn\fP (string alias, \fBIEntityAliases\fP entityAliases, \fBNonScalarReturn\fP owner, string ownerProperty, \fBLockMode\fP lockMode)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIEntityAliases\fP \fBEntityAliases\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specifically a fetch return that refers to an entity association\&. 


.PP
Definition at line 4 of file EntityFetchReturn\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
