.TH "NHibernate.Test.Linq.CasingTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.CasingTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBToUpper\fP ()"
.br
.ti -1c
.RI "void \fBToUpperInvariant\fP ()"
.br
.ti -1c
.RI "void \fBToLower\fP ()"
.br
.ti -1c
.RI "void \fBToLowerInvariant\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CasingTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
