.TH "NHibernate.FKUnmatchingColumnsException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.FKUnmatchingColumnsException \- 
.PP
Indicates that an expected getter or setter method could not be found on a class  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.MappingException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFKUnmatchingColumnsException\fP (string message)"
.br
.ti -1c
.RI "\fBFKUnmatchingColumnsException\fP (string message, Exception innerException)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFKUnmatchingColumnsException\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "\fIInitializes a new instance of the \fBPropertyNotFoundException\fP class with serialized data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Indicates that an expected getter or setter method could not be found on a class 


.PP
Definition at line 10 of file FKUnmatchingColumnsException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.FKUnmatchingColumnsException\&.FKUnmatchingColumnsException (stringmessage)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.RE
.PP

.PP
Definition at line 16 of file FKUnmatchingColumnsException\&.cs\&.
.SS "NHibernate\&.FKUnmatchingColumnsException\&.FKUnmatchingColumnsException (stringmessage, ExceptioninnerException)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.br
\fIinnerException\fP The exception that is the cause of the current exception\&. If the innerException parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception\&. 
.RE
.PP

.PP
Definition at line 31 of file FKUnmatchingColumnsException\&.cs\&.
.SS "NHibernate\&.FKUnmatchingColumnsException\&.FKUnmatchingColumnsException (SerializationInfoinfo, StreamingContextcontext)\fC [protected]\fP"

.PP
Initializes a new instance of the \fBPropertyNotFoundException\fP class with serialized data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP The SerializationInfo that holds the serialized object data about the exception being thrown\&. 
.br
\fIcontext\fP The StreamingContext that contains contextual information about the source or destination\&. 
.RE
.PP

.PP
Definition at line 47 of file FKUnmatchingColumnsException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
