.TH "NHibernate.Test.NHSpecificTest.NH3160.DialectNotSupportingUniqueKeyword" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH3160.DialectNotSupportingUniqueKeyword \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.GenericDialect\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBSupportsUnique\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBSupportsUniqueConstraintInCreateAlterTable\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file DialectNotSupportingUniqueKeyword\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
