.TH "NHibernate.Test.DynamicProxyTests.GenericMethodsTests.IMyInterface" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicProxyTests.GenericMethodsTests.IMyInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Test\&.DynamicProxyTests\&.GenericMethodsTests\&.GenericMethodShouldBeProxied\&.MyDerivedClass\&.
.SH "Detailed Description"
.PP 
Definition at line 3 of file IMyInterface\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
