.TH "NHibernate.Cfg.MappingSchema.HbmJoin" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmJoin \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.IEntitySqlsMapping\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IPropertiesContainerMapping\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmSubselect\fP \fBsubselect\fP"
.br
.ti -1c
.RI "\fBHbmComment\fP \fBcomment\fP"
.br
.ti -1c
.RI "\fBHbmKey\fP \fBkey\fP"
.br
.ti -1c
.RI "object[] \fBItems\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqlinsert\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqlupdate\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqldelete\fP"
.br
.ti -1c
.RI "string \fBtable\fP"
.br
.ti -1c
.RI "string \fBschema\fP"
.br
.ti -1c
.RI "string \fBcatalog\fP"
.br
.ti -1c
.RI "string \fBsubselect1\fP"
.br
.ti -1c
.RI "\fBHbmJoinFetch\fP \fBfetch\fP"
.br
.ti -1c
.RI "bool \fBinverse\fP"
.br
.ti -1c
.RI "bool \fBoptional\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHbmLoader\fP \fBSqlLoader\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlInsert\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlUpdate\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlDelete\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBSubselect\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable
.br
< \fBIEntityPropertyMapping\fP > \fBProperties\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 3788 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
