.TH "NHibernate.AdoNet.IBatcherFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.AdoNet.IBatcherFactory \- 
.PP
Factory for IBatcher instances\&. 

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.AdoNet\&.MySqlClientBatchingBatcherFactory\fP, \fBNHibernate\&.AdoNet\&.NonBatchingBatcherFactory\fP, \fBNHibernate\&.AdoNet\&.OracleDataClientBatchingBatcherFactory\fP, \fBNHibernate\&.AdoNet\&.SqlClientBatchingBatcherFactory\fP, \fBNHibernate\&.Test\&.Insertordering\&.InsertOrderingFixture\&.StatsBatcherFactory\fP, and \fBNHibernate\&.Test\&.Linq\&.QueryTimeoutTests\&.TimeoutCatchingNonBatchingBatcherFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIBatcher\fP \fBCreateBatcher\fP (\fBConnectionManager\fP connectionManager, \fBIInterceptor\fP interceptor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Factory for IBatcher instances\&.


.PP
Definition at line 6 of file IBatcherFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
