.TH "NHibernate.Test.NHSpecificTest.Futures" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Futures \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestDriverThatDoesntSupportQueryBatching\fP"
.br
.ti -1c
.RI "class \fBFallbackFixture\fP"
.br
.RI "\fII'm using a \fBDriver\fP which derives from SqlClientDriver to return false for the SupportsMultipleQueries property\&. This is purely to test the way \fBNHibernate\fP will behave when the driver that's being used does not support multiple queries\&.\&.\&. so even though the test is using MsSql, it's only relevant for databases that don't support multiple queries but this way it's just much easier to test this \fP"
.ti -1c
.RI "class \fBFutureCriteriaFixture\fP"
.br
.ti -1c
.RI "class \fBFutureFixture\fP"
.br
.ti -1c
.RI "class \fBFutureQueryFixture\fP"
.br
.ti -1c
.RI "class \fBFutureQueryOverFixture\fP"
.br
.ti -1c
.RI "class \fBLinqFutureFixture\fP"
.br
.ti -1c
.RI "class \fBLinqToFutureValueFixture\fP"
.br
.ti -1c
.RI "class \fBPerson\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
