.TH "NHibernate.Mapping.Map" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.Map \- 
.PP
A map has a primary key consisting of the key columns  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.IndexedCollection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMap\fP (\fBPersistentClass\fP owner)"
.br
.RI "\fIInitializes a new instance of the \fBMap\fP class\&. \fP"
.ti -1c
.RI "override void \fBCreateAllKeys\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsMap\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBCollectionType\fP \fBCollectionType\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBCollectionType\fP \fBDefaultCollectionType\fP\fC [get]\fP"
.br
.RI "\fIGets the appropriate CollectionType that is specialized for this list mapping\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A map has a primary key consisting of the key columns 


.IP "\(bu" 2
index columns\&. 
.PP

.PP
Definition at line 12 of file Map\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Mapping\&.Map\&.Map (\fBPersistentClass\fPowner)"

.PP
Initializes a new instance of the \fBMap\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIowner\fP The \fBPersistentClass\fP that contains this map mapping\&.
.RE
.PP

.PP
Definition at line 18 of file Map\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override \fBCollectionType\fP NHibernate\&.Mapping\&.Map\&.DefaultCollectionType\fC [get]\fP"

.PP
Gets the appropriate CollectionType that is specialized for this list mapping\&. 
.PP
Definition at line 60 of file Map\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
