.TH "NHibernate.Test.NHSpecificTest.NH1584.Male" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1584.Male \- 
.PP
This class assumes that all male cats have a tabby coat pattern (which is not true)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1584\&.Cat\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual \fBTabby\fP \fBCoat\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class assumes that all male cats have a tabby coat pattern (which is not true)\&. 


.PP
Definition at line 6 of file Male\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
