.TH "NHibernate.Test.Linq.ReadonlyTestCase" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.ReadonlyTestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP, and \fBNHibernate\&.Test\&.Linq\&.ParameterisedQueries\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCreateSchema\fP ()"
.br
.ti -1c
.RI "override void \fBDropSchema\fP ()"
.br
.ti -1c
.RI "override bool \fBCheckDatabaseWasCleaned\fP ()"
.br
.ti -1c
.RI "override void \fBApplyCacheSettings\fP (\fBConfiguration\fP configuration)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file ReadonlyTestCase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
