.TH "NHibernate.Type.PersistentEnumType.IEnumConverter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.PersistentEnumType.IEnumConverter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Type\&.PersistentEnumType\&.AbstractEnumConverter< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBToObject\fP (System\&.Type enumClass, object code)"
.br
.ti -1c
.RI "object \fBToEnumValue\fP (object value)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSqlType\fP \fBSqlType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file PersistentEnumType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
