.TH "NHibernate.Test.TypesTest.TypeFactoryFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.TypesTest.TypeFactoryFixture \- 
.PP
\fBTest\fP Fixture for TypeFactory\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenericPropertyClass\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMyEnum\fP { \fBOne\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetGuidSingleton\fP ()"
.br
.RI "\fI\fBTest\fP that calling GetGuidType multiple times returns the exact same GuidType object by reference\&. \fP"
.ti -1c
.RI "void \fBGetStringWithDiffLength\fP ()"
.br
.RI "\fI\fBTest\fP that Strings with different lengths return different StringTypes\&. \fP"
.ti -1c
.RI "void \fBGetNullableGeneric\fP ()"
.br
.RI "\fI\fBTest\fP that Nullable<> wrappers around structs are returning the correct NH IType\&. \fP"
.ti -1c
.RI "void \fBMultiThreadAccess\fP ()"
.br
.ti -1c
.RI "void \fBHoldQualifiedTypes\fP ()"
.br
.ti -1c
.RI "void \fBWhenUseEnumThenReturnGenericEnumType\fP ()"
.br
.ti -1c
.RI "void \fBWhenUseNullableEnumThenReturnGenericEnumType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTest\fP Fixture for TypeFactory\&. 


.PP
Definition at line 14 of file TypeFactoryFixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.TypesTest\&.TypeFactoryFixture\&.GetGuidSingleton ()"

.PP
\fBTest\fP that calling GetGuidType multiple times returns the exact same GuidType object by reference\&. 
.PP
Definition at line 28 of file TypeFactoryFixture\&.cs\&.
.SS "void NHibernate\&.Test\&.TypesTest\&.TypeFactoryFixture\&.GetNullableGeneric ()"

.PP
\fBTest\fP that Nullable<> wrappers around structs are returning the correct NH IType\&. 
.PP
Definition at line 53 of file TypeFactoryFixture\&.cs\&.
.SS "void NHibernate\&.Test\&.TypesTest\&.TypeFactoryFixture\&.GetStringWithDiffLength ()"

.PP
\fBTest\fP that Strings with different lengths return different StringTypes\&. 
.PP
Definition at line 40 of file TypeFactoryFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
