.TH "NHibernate.Persister.Collection.ElementPropertyMapping" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Persister.Collection.ElementPropertyMapping \- 
.PP
Summary description for \fBElementPropertyMapping\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Persister\&.Entity\&.IPropertyMapping\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementPropertyMapping\fP (string[] elementColumns, \fBIType\fP type)"
.br
.ti -1c
.RI "\fBIType\fP \fBToType\fP (string propertyName)"
.br
.RI "\fIGiven a component path expression, get the type of the property \fP"
.ti -1c
.RI "bool \fBTryToType\fP (string propertyName, out \fBIType\fP outType)"
.br
.RI "\fIGiven a component path expression, get the type of the property\&. \fP"
.ti -1c
.RI "string[] \fBToColumns\fP (string alias, string propertyName)"
.br
.RI "\fIGiven a query alias and a property path, return the qualified column name \fP"
.ti -1c
.RI "string[] \fBToColumns\fP (string propertyName)"
.br
.RI "\fIGiven a property path, return the corresponding column name(s)\&.\fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIType\fP \fBType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBElementPropertyMapping\fP\&. 


.PP
Definition at line 11 of file ElementPropertyMapping\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string [] NHibernate\&.Persister\&.Collection\&.ElementPropertyMapping\&.ToColumns (stringalias, stringpropertyName)"

.PP
Given a query alias and a property path, return the qualified column name 
.PP
\fBParameters:\fP
.RS 4
\fIalias\fP 
.br
\fIpropertyName\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Persister\&.Entity\&.IPropertyMapping\fP\&.
.PP
Definition at line 50 of file ElementPropertyMapping\&.cs\&.
.SS "string [] NHibernate\&.Persister\&.Collection\&.ElementPropertyMapping\&.ToColumns (stringpropertyName)"

.PP
Given a property path, return the corresponding column name(s)\&.
.PP
Implements \fBNHibernate\&.Persister\&.Entity\&.IPropertyMapping\fP\&.
.PP
Definition at line 62 of file ElementPropertyMapping\&.cs\&.
.SS "\fBIType\fP NHibernate\&.Persister\&.Collection\&.ElementPropertyMapping\&.ToType (stringpropertyName)"

.PP
Given a component path expression, get the type of the property 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Persister\&.Entity\&.IPropertyMapping\fP\&.
.PP
Definition at line 24 of file ElementPropertyMapping\&.cs\&.
.SS "bool NHibernate\&.Persister\&.Collection\&.ElementPropertyMapping\&.TryToType (stringpropertyName, out \fBIType\fPtype)"

.PP
Given a component path expression, get the type of the property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP 
.br
\fItype\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true if a type was found, false if not
.RE
.PP

.PP
Implements \fBNHibernate\&.Persister\&.Entity\&.IPropertyMapping\fP\&.
.PP
Definition at line 36 of file ElementPropertyMapping\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
