.TH "NHibernate.Engine.JoinSequence.ISelector" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.JoinSequence.ISelector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Hql\&.Ast\&.ANTLR\&.Util\&.JoinProcessor\&.JoinSequenceSelector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIncludeSubclasses\fP (string alias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 312 of file JoinSequence\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
