.TH "NHibernate.Test.Linq.RegresstionTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.RegresstionTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHierarchicalQueries_InlineConstant\fP ()"
.br
.RI "\fIhttp://aspzone.com/tech/nhibernate-linq-troubles/ \fP"
.ti -1c
.RI "void \fBHierarchicalQueries_Variable\fP ()"
.br
.ti -1c
.RI "void \fBCanUseNullConstantAndRestriction\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file RegresstionTests\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.Linq\&.RegresstionTests\&.HierarchicalQueries_InlineConstant ()"

.PP
http://aspzone.com/tech/nhibernate-linq-troubles/ 
.PP
Definition at line 14 of file RegresstionTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
