.TH "NHibernate.DomainModel.NHSpecific.NullableInt32Converter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.NHSpecific.NullableInt32Converter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TypeConverter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanConvertFrom\fP (ITypeDescriptorContext context, System\&.Type sourceType)"
.br
.ti -1c
.RI "override bool \fBCanConvertTo\fP (ITypeDescriptorContext context, System\&.Type destinationType)"
.br
.ti -1c
.RI "override object \fBConvertFrom\fP (ITypeDescriptorContext context, CultureInfo culture, object value)"
.br
.ti -1c
.RI "override object \fBConvertTo\fP (ITypeDescriptorContext context, CultureInfo culture, object value, System\&.Type destinationType)"
.br
.ti -1c
.RI "override object \fBCreateInstance\fP (ITypeDescriptorContext context, IDictionary propertyValues)"
.br
.ti -1c
.RI "override bool \fBGetCreateInstanceSupported\fP (ITypeDescriptorContext context)"
.br
.ti -1c
.RI "override 
.br
PropertyDescriptorCollection \fBGetProperties\fP (ITypeDescriptorContext context, object value, Attribute[] attributes)"
.br
.ti -1c
.RI "override bool \fBGetPropertiesSupported\fP (ITypeDescriptorContext context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file NullableInt32Converter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
