.TH "NHibernate.Test.PolymorphicGetAndLoad.PolymorphicGetAndLoadTest.ScenarioWithB" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.PolymorphicGetAndLoad.PolymorphicGetAndLoadTest.ScenarioWithB \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScenarioWithB\fP (\fBISessionFactory\fP factory)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBB\fP \fBB\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file PolymorphicGetAndLoadTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
