.TH "NHibernate.Mapping.ByCode.IComponentMapper< TComponent >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IComponentMapper< TComponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IComponentAttributesMapper< TComponent >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IPropertyContainerMapper< TEntity >\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.ComponentCustomizer< TComponent >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITComponent\fP : \fIclass\fP
.PP
Definition at line 31 of file IComponentMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
