.TH "NHibernate.Test.NHSpecificTest.NH1689.DomainClass" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1689.DomainClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual IList< TargetType > \fBGetListOfTargetType< TargetType >\fP (string someArg)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DomainClass\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
