.TH "NHibernate.Cfg.ConfigurationSchema" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.ConfigurationSchema \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCfgXmlHelper\fP"
.br
.RI "\fIHelper to parse hibernate-configuration XmlNode\&. \fP"
.ti -1c
.RI "class \fBClassCacheConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a class-cache XML node\&. \fP"
.ti -1c
.RI "class \fBCollectionCacheConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a collection-cache XML node\&. \fP"
.ti -1c
.RI "class \fBEventConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a event XML node\&. \fP"
.ti -1c
.RI "class \fBHibernateConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for hibernate-configuration section\&. \fP"
.ti -1c
.RI "class \fBListenerConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a listener XML node \fP"
.ti -1c
.RI "class \fBMappingConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a mapping XML node \fP"
.ti -1c
.RI "class \fBSessionFactoryConfiguration\fP"
.br
.RI "\fI\fBConfiguration\fP parsed values for a session-factory XML node\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBClassCacheInclude\fP { \fBClassCacheInclude\&.All\fP, \fBClassCacheInclude\&.NonLazy\fP }"
.br
.RI "\fIValues for class-cache include\&. \fP"
.ti -1c
.RI "enum \fBBytecodeProviderType\fP { \fBBytecodeProviderType\&.Codedom\fP, \fBBytecodeProviderType\&.Lcg\fP, \fBBytecodeProviderType\&.Null\fP }"
.br
.RI "\fIValues for bytecode-provider system property\&. \fP"
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNHibernate\&.Cfg\&.ConfigurationSchema\&.BytecodeProviderType\fP"

.PP
Values for bytecode-provider system property\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICodedom \fP\fP
Xml value: codedom
.TP
\fB\fILcg \fP\fP
Xml value: lcg
.TP
\fB\fINull \fP\fP
Xml value: null
.PP
Definition at line 11 of file HibernateConfiguration\&.cs\&.
.SS "enum \fBNHibernate\&.Cfg\&.ConfigurationSchema\&.ClassCacheInclude\fP"

.PP
Values for class-cache include\&. Not implemented in \fBCache\fP\&.
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAll \fP\fP
Xml value: all
.TP
\fB\fINonLazy \fP\fP
Xml value: non-lazy
.PP
Definition at line 10 of file ClassCacheConfiguration\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
