.TH "Renci.SshNet.Security.Cryptography.RIPEMD160Hash" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Security.Cryptography.RIPEMD160Hash \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits HashAlgorithm\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.RI "\fIInitializes an implementation of the T:System\&.Security\&.Cryptography\&.HashAlgorithm class\&. \fP"
.ti -1c
.RI "\fBRIPEMD160Hash\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBRIPEMD160Hash\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBHashCore\fP (byte[] array, int ibStart, int cbSize)"
.br
.ti -1c
.RI "override byte[] \fBHashFinal\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBHashSize\fP\fC [get]\fP"
.br
.RI "\fIGets the size, in bits, of the computed hash code\&. \fP"
.ti -1c
.RI "override int \fBInputBlockSize\fP\fC [get]\fP"
.br
.RI "\fIGets the input block size\&. \fP"
.ti -1c
.RI "override int \fBOutputBlockSize\fP\fC [get]\fP"
.br
.RI "\fIGets the output block size\&. \fP"
.ti -1c
.RI "override bool \fBCanReuseTransform\fP\fC [get]\fP"
.br
.RI "\fIGets a value indicating whether the current transform can be reused\&. \fP"
.ti -1c
.RI "override bool \fBCanTransformMultipleBlocks\fP\fC [get]\fP"
.br
.RI "\fIGets a value indicating whether multiple blocks can be transformed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 



.PP
Definition at line 12 of file RIPEMD160Hash\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.RIPEMD160Hash ()"

.PP
Initializes a new instance of the \fBRIPEMD160Hash\fP class\&. 
.PP
Definition at line 156 of file RIPEMD160Hash\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.Initialize ()"

.PP
Initializes an implementation of the T:System\&.Security\&.Cryptography\&.HashAlgorithm class\&. 
.PP
Definition at line 148 of file RIPEMD160Hash\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override bool Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.CanReuseTransform\fC [get]\fP"

.PP
Gets a value indicating whether the current transform can be reused\&. 
.PP
\fBReturns:\fP
.RS 4
Always true\&.
.RE
.PP

.PP
Definition at line 64 of file RIPEMD160Hash\&.cs\&.
.SS "override bool Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.CanTransformMultipleBlocks\fC [get]\fP"

.PP
Gets a value indicating whether multiple blocks can be transformed\&. 
.PP
\fBReturns:\fP
.RS 4
true if multiple blocks can be transformed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 76 of file RIPEMD160Hash\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.HashSize\fC [get]\fP"

.PP
Gets the size, in bits, of the computed hash code\&. 
.PP
\fBReturns:\fP
.RS 4
The size, in bits, of the computed hash code\&.
.RE
.PP

.PP
Definition at line 28 of file RIPEMD160Hash\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.InputBlockSize\fC [get]\fP"

.PP
Gets the input block size\&. 
.PP
\fBReturns:\fP
.RS 4
The input block size\&.
.RE
.PP

.PP
Definition at line 40 of file RIPEMD160Hash\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.RIPEMD160Hash\&.OutputBlockSize\fC [get]\fP"

.PP
Gets the output block size\&. 
.PP
\fBReturns:\fP
.RS 4
The output block size\&.
.RE
.PP

.PP
Definition at line 52 of file RIPEMD160Hash\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
