.TH "Renci.SshNet.CipherInfo" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.CipherInfo \- 
.PP
Holds information about key size and cipher to use  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCipherInfo\fP (int keySize, Func< byte[], byte[], \fBCipher\fP > cipher)"
.br
.RI "\fIInitializes a new instance of the \fBCipherInfo\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBKeySize\fP\fC [get, set]\fP"
.br
.RI "\fIGets the size of the key\&. \fP"
.ti -1c
.RI "Func< byte[], byte[], \fBCipher\fP > \fBCipher\fP\fC [get, set]\fP"
.br
.RI "\fIGets the cipher\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Holds information about key size and cipher to use 


.PP
Definition at line 12 of file CipherInfo\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.CipherInfo\&.CipherInfo (intkeySize, Func< byte[], byte[], \fBCipher\fP >cipher)"

.PP
Initializes a new instance of the \fBCipherInfo\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkeySize\fP Size of the key\&.
.br
\fIcipher\fP The cipher\&.
.RE
.PP

.PP
Definition at line 32 of file CipherInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Func<byte[], byte[], \fBCipher\fP> Renci\&.SshNet\&.CipherInfo\&.Cipher\fC [get]\fP, \fC [set]\fP"

.PP
Gets the cipher\&. 
.PP
Definition at line 25 of file CipherInfo\&.cs\&.
.SS "int Renci\&.SshNet\&.CipherInfo\&.KeySize\fC [get]\fP, \fC [set]\fP"

.PP
Gets the size of the key\&. The size of the key\&. 
.PP
Definition at line 20 of file CipherInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
