.TH "Renci.SshNet.Security.Cryptography.SHA384Hash" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Security.Cryptography.SHA384Hash \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Security\&.Cryptography\&.SHA2HashBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override byte[] \fBHashFinal\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBHashSize\fP\fC [get]\fP"
.br
.RI "\fIGets the size, in bits, of the computed hash code\&. \fP"
.ti -1c
.RI "override int \fBInputBlockSize\fP\fC [get]\fP"
.br
.RI "\fIWhen overridden in a derived class, gets the input block size\&. \fP"
.ti -1c
.RI "override int \fBOutputBlockSize\fP\fC [get]\fP"
.br
.RI "\fIWhen overridden in a derived class, gets the output block size\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file SHA384Hash\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.SHA384Hash\&.HashSize\fC [get]\fP"

.PP
Gets the size, in bits, of the computed hash code\&. 
.PP
\fBReturns:\fP
.RS 4
The size, in bits, of the computed hash code\&.
.RE
.PP

.PP
Definition at line 18 of file SHA384Hash\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.SHA384Hash\&.InputBlockSize\fC [get]\fP"

.PP
When overridden in a derived class, gets the input block size\&. 
.PP
\fBReturns:\fP
.RS 4
The input block size\&.
.RE
.PP

.PP
Definition at line 30 of file SHA384Hash\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.Cryptography\&.SHA384Hash\&.OutputBlockSize\fC [get]\fP"

.PP
When overridden in a derived class, gets the output block size\&. 
.PP
\fBReturns:\fP
.RS 4
The output block size\&.
.RE
.PP

.PP
Definition at line 42 of file SHA384Hash\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
