.TH "Renci.SshNet.Messages.Transport.KeyExchangeInitMessage" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Messages.Transport.KeyExchangeInitMessage \- 
.PP
Represents SSH_MSG_KEXINIT message\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Messages\&.Message\fP, and \fBRenci\&.SshNet\&.Messages\&.Transport\&.IKeyExchangedAllowed\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyExchangeInitMessage\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBKeyExchangeInitMessage\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBLoadData\fP ()"
.br
.RI "\fICalled when type specific data need to be loaded\&. \fP"
.ti -1c
.RI "override void \fBSaveData\fP ()"
.br
.RI "\fICalled when type specific data need to be saved\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[] \fBCookie\fP\fC [get, set]\fP"
.br
.RI "\fIGets session cookie\&. \fP"
.ti -1c
.RI "string[] \fBKeyExchangeAlgorithms\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported key exchange algorithms\&. \fP"
.ti -1c
.RI "string[] \fBServerHostKeyAlgorithms\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported server host key algorithms\&. \fP"
.ti -1c
.RI "string[] \fBEncryptionAlgorithmsClientToServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported encryption algorithms client to server\&. \fP"
.ti -1c
.RI "string[] \fBEncryptionAlgorithmsServerToClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported encryption algorithms server to client\&. \fP"
.ti -1c
.RI "string[] \fBMacAlgorithmsClientToServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported hash algorithms client to server\&. \fP"
.ti -1c
.RI "string[] \fBMacAlgorithmsServerToClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported hash algorithms server to client\&. \fP"
.ti -1c
.RI "string[] \fBCompressionAlgorithmsClientToServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported compression algorithms client to server\&. \fP"
.ti -1c
.RI "string[] \fBCompressionAlgorithmsServerToClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported compression algorithms server to client\&. \fP"
.ti -1c
.RI "string[] \fBLanguagesClientToServer\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported languages client to server\&. \fP"
.ti -1c
.RI "string[] \fBLanguagesServerToClient\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets supported languages server to client\&. \fP"
.ti -1c
.RI "bool \fBFirstKexPacketFollows\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether first key exchange packet follows\&. \fP"
.ti -1c
.RI "UInt32 \fBReserved\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the reserved value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents SSH_MSG_KEXINIT message\&. 


.PP
Definition at line 11 of file KeyExchangeInitMessage\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.KeyExchangeInitMessage ()"

.PP
Initializes a new instance of the \fBKeyExchangeInitMessage\fP class\&. 
.PP
Definition at line 18 of file KeyExchangeInitMessage\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.LoadData ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when type specific data need to be loaded\&. 
.PP
Implements \fBRenci\&.SshNet\&.Common\&.SshData\fP\&.
.PP
Definition at line 133 of file KeyExchangeInitMessage\&.cs\&.
.SS "override void Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.SaveData ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when type specific data need to be saved\&. 
.PP
Implements \fBRenci\&.SshNet\&.Common\&.SshData\fP\&.
.PP
Definition at line 155 of file KeyExchangeInitMessage\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.CompressionAlgorithmsClientToServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported compression algorithms client to server\&. Supported compression algorithms client to server\&. 
.PP
Definition at line 86 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.CompressionAlgorithmsServerToClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported compression algorithms server to client\&. Supported compression algorithms server to client\&. 
.PP
Definition at line 94 of file KeyExchangeInitMessage\&.cs\&.
.SS "byte [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.Cookie\fC [get]\fP, \fC [set]\fP"

.PP
Gets session cookie\&. 
.PP
Definition at line 30 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.EncryptionAlgorithmsClientToServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported encryption algorithms client to server\&. Supported encryption algorithms client to server\&. 
.PP
Definition at line 54 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.EncryptionAlgorithmsServerToClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported encryption algorithms server to client\&. Supported encryption algorithms server to client\&. 
.PP
Definition at line 62 of file KeyExchangeInitMessage\&.cs\&.
.SS "bool Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.FirstKexPacketFollows\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether first key exchange packet follows\&. \fCtrue\fP if first key exchange packet follows; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 118 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.KeyExchangeAlgorithms\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported key exchange algorithms\&. Supported key exchange algorithms\&. 
.PP
Definition at line 38 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.LanguagesClientToServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported languages client to server\&. Supported languages client to server\&. 
.PP
Definition at line 102 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.LanguagesServerToClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported languages server to client\&. The languages server to client\&. 
.PP
Definition at line 110 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.MacAlgorithmsClientToServer\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported hash algorithms client to server\&. Supported hash algorithms client to server\&. 
.PP
Definition at line 70 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.MacAlgorithmsServerToClient\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported hash algorithms server to client\&. Supported hash algorithms server to client\&. 
.PP
Definition at line 78 of file KeyExchangeInitMessage\&.cs\&.
.SS "UInt32 Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.Reserved\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the reserved value\&. The reserved value\&. 
.PP
Definition at line 126 of file KeyExchangeInitMessage\&.cs\&.
.SS "string [] Renci\&.SshNet\&.Messages\&.Transport\&.KeyExchangeInitMessage\&.ServerHostKeyAlgorithms\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets supported server host key algorithms\&. Supported server host key algorithms\&. 
.PP
Definition at line 46 of file KeyExchangeInitMessage\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
