.TH "Renci.SshNet.Security.RsaKey" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Security.RsaKey \- 
.PP
Contains RSA private and public key  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Security\&.Key\fP, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRsaKey\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBRsaKey\fP class\&. \fP"
.ti -1c
.RI "\fBRsaKey\fP (byte[] data)"
.br
.RI "\fIInitializes a new instance of the \fBRsaKey\fP class\&. \fP"
.ti -1c
.RI "\fBRsaKey\fP (\fBBigInteger\fP modulus, \fBBigInteger\fP exponent, \fBBigInteger\fP d, \fBBigInteger\fP p, \fBBigInteger\fP q, \fBBigInteger\fP inverseQ)"
.br
.RI "\fIInitializes a new instance of the \fBRsaKey\fP class\&. \fP"
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "\fIPerforms application-defined tasks associated with freeing, releasing, or resetting unmanaged ResourceMessages\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.RI "\fIReleases unmanaged and - optionally - managed resources \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBigInteger\fP \fBModulus\fP\fC [get]\fP"
.br
.RI "\fIGets the modulus\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBExponent\fP\fC [get]\fP"
.br
.RI "\fIGets the exponent\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBD\fP\fC [get]\fP"
.br
.RI "\fIGets the D\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBP\fP\fC [get]\fP"
.br
.RI "\fIGets the P\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBQ\fP\fC [get]\fP"
.br
.RI "\fIGets the Q\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBDP\fP\fC [get]\fP"
.br
.RI "\fIGets the DP\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBDQ\fP\fC [get]\fP"
.br
.RI "\fIGets the DQ\&. \fP"
.ti -1c
.RI "\fBBigInteger\fP \fBInverseQ\fP\fC [get]\fP"
.br
.RI "\fIGets the inverse Q\&. \fP"
.ti -1c
.RI "override int \fBKeyLength\fP\fC [get]\fP"
.br
.RI "\fIGets the length of the key\&. \fP"
.ti -1c
.RI "override \fBDigitalSignature\fP \fBDigitalSignature\fP\fC [get]\fP"
.br
.RI "\fIGets the digital signature\&. \fP"
.ti -1c
.RI "override \fBBigInteger\fP[] \fBPublic\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the public\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Contains RSA private and public key 


.PP
Definition at line 13 of file RsaKey\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Security\&.RsaKey\&.RsaKey ()"

.PP
Initializes a new instance of the \fBRsaKey\fP class\&. 
.PP
Definition at line 175 of file RsaKey\&.cs\&.
.SS "Renci\&.SshNet\&.Security\&.RsaKey\&.RsaKey (byte[]data)"

.PP
Initializes a new instance of the \fBRsaKey\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP DER encoded private key data\&.
.RE
.PP

.PP
Definition at line 184 of file RsaKey\&.cs\&.
.SS "Renci\&.SshNet\&.Security\&.RsaKey\&.RsaKey (\fBBigInteger\fPmodulus, \fBBigInteger\fPexponent, \fBBigInteger\fPd, \fBBigInteger\fPp, \fBBigInteger\fPq, \fBBigInteger\fPinverseQ)"

.PP
Initializes a new instance of the \fBRsaKey\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImodulus\fP The modulus\&.
.br
\fIexponent\fP The exponent\&.
.br
\fId\fP The d\&.
.br
\fIp\fP The p\&.
.br
\fIq\fP The q\&.
.br
\fIinverseQ\fP The inverse Q\&.
.RE
.PP

.PP
Definition at line 200 of file RsaKey\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Renci\&.SshNet\&.Security\&.RsaKey\&.Dispose ()"

.PP
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged ResourceMessages\&. 
.PP
Definition at line 226 of file RsaKey\&.cs\&.
.SS "virtual void Renci\&.SshNet\&.Security\&.RsaKey\&.Dispose (booldisposing)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Releases unmanaged and - optionally - managed resources 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP \fCtrue\fP to release both managed and unmanaged resources; \fCfalse\fP to release only unmanaged ResourceMessages\&.
.RE
.PP

.PP
Definition at line 237 of file RsaKey\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.D\fC [get]\fP"

.PP
Gets the D\&. 
.PP
Definition at line 41 of file RsaKey\&.cs\&.
.SS "override \fBDigitalSignature\fP Renci\&.SshNet\&.Security\&.RsaKey\&.DigitalSignature\fC [get]\fP, \fC [protected]\fP"

.PP
Gets the digital signature\&. 
.PP
Definition at line 140 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.DP\fC [get]\fP"

.PP
Gets the DP\&. 
.PP
Definition at line 83 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.DQ\fC [get]\fP"

.PP
Gets the DQ\&. 
.PP
Definition at line 97 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.Exponent\fC [get]\fP"

.PP
Gets the exponent\&. 
.PP
Definition at line 30 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.InverseQ\fC [get]\fP"

.PP
Gets the inverse Q\&. 
.PP
Definition at line 111 of file RsaKey\&.cs\&.
.SS "override int Renci\&.SshNet\&.Security\&.RsaKey\&.KeyLength\fC [get]\fP"

.PP
Gets the length of the key\&. The length of the key\&. 
.PP
Definition at line 128 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.Modulus\fC [get]\fP"

.PP
Gets the modulus\&. 
.PP
Definition at line 19 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.P\fC [get]\fP"

.PP
Gets the P\&. 
.PP
Definition at line 55 of file RsaKey\&.cs\&.
.SS "override \fBBigInteger\fP [] Renci\&.SshNet\&.Security\&.RsaKey\&.Public\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the public\&. The public\&. 
.PP
Definition at line 158 of file RsaKey\&.cs\&.
.SS "\fBBigInteger\fP Renci\&.SshNet\&.Security\&.RsaKey\&.Q\fC [get]\fP"

.PP
Gets the Q\&. 
.PP
Definition at line 69 of file RsaKey\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
