.TH "Renci.SshNet.Common.AuthenticationEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Common.AuthenticationEventArgs \- 
.PP
Base class for authentication events\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.PP
Inherited by \fBRenci\&.SshNet\&.Common\&.AuthenticationBannerEventArgs\fP, \fBRenci\&.SshNet\&.Common\&.AuthenticationPasswordChangeEventArgs\fP, and \fBRenci\&.SshNet\&.Common\&.AuthenticationPromptEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthenticationEventArgs\fP (string username)"
.br
.RI "\fIInitializes a new instance of the \fBAuthenticationEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUsername\fP\fC [get, set]\fP"
.br
.RI "\fIGets the username\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base class for authentication events\&. 


.PP
Definition at line 12 of file AuthenticationEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Common\&.AuthenticationEventArgs\&.AuthenticationEventArgs (stringusername)"

.PP
Initializes a new instance of the \fBAuthenticationEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP The username\&.
.RE
.PP

.PP
Definition at line 23 of file AuthenticationEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Renci\&.SshNet\&.Common\&.AuthenticationEventArgs\&.Username\fC [get]\fP, \fC [set]\fP"

.PP
Gets the username\&. 
.PP
Definition at line 17 of file AuthenticationEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
