.TH "Renci.SshNet.Messages.Connection.RequestInfo" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Messages.Connection.RequestInfo \- 
.PP
Represents type specific information for channel request\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Common\&.SshData\fP\&.
.PP
Inherited by Renci\&.SshNet\&.Messages\&.Connection\&.BreakRequestInfo, \fBRenci\&.SshNet\&.Messages\&.Connection\&.EndOfWriteRequestInfo\fP, Renci\&.SshNet\&.Messages\&.Connection\&.EnvironmentVariableRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.ExecRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.ExitSignalRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.ExitStatusRequestInfo, \fBRenci\&.SshNet\&.Messages\&.Connection\&.KeepAliveRequestInfo\fP, Renci\&.SshNet\&.Messages\&.Connection\&.PseudoTerminalRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.ShellRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.SignalRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.SubsystemRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.WindowChangeRequestInfo, Renci\&.SshNet\&.Messages\&.Connection\&.X11ForwardingRequestInfo, and Renci\&.SshNet\&.Messages\&.Connection\&.XonXoffRequestInfo\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBLoadData\fP ()"
.br
.RI "\fICalled when type specific data need to be loaded\&. \fP"
.ti -1c
.RI "override void \fBSaveData\fP ()"
.br
.RI "\fICalled when type specific data need to be saved\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract string \fBRequestName\fP\fC [get]\fP"
.br
.RI "\fIGets the name of the request\&. \fP"
.ti -1c
.RI "bool \fBWantReply\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether reply message is needed\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents type specific information for channel request\&. 


.PP
Definition at line 8 of file RequestInfo\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Renci\&.SshNet\&.Messages\&.Connection\&.RequestInfo\&.LoadData ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when type specific data need to be loaded\&. 
.PP
Implements \fBRenci\&.SshNet\&.Common\&.SshData\fP\&.
.PP
Definition at line 29 of file RequestInfo\&.cs\&.
.SS "override void Renci\&.SshNet\&.Messages\&.Connection\&.RequestInfo\&.SaveData ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Called when type specific data need to be saved\&. 
.PP
Implements \fBRenci\&.SshNet\&.Common\&.SshData\fP\&.
.PP
Definition at line 37 of file RequestInfo\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "abstract string Renci\&.SshNet\&.Messages\&.Connection\&.RequestInfo\&.RequestName\fC [get]\fP"

.PP
Gets the name of the request\&. The name of the request\&. 
.PP
Definition at line 16 of file RequestInfo\&.cs\&.
.SS "bool Renci\&.SshNet\&.Messages\&.Connection\&.RequestInfo\&.WantReply\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether reply message is needed\&. \fCtrue\fP if reply message is needed; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 24 of file RequestInfo\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
