.TH "Renci.SshNet.Security.KeyExchangeDiffieHellmanGroupExchangeSha256" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Security.KeyExchangeDiffieHellmanGroupExchangeSha256 \- 
.PP
Represents 'diffie-hellman-group-exchange-sha256' algorithm implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Security\&.KeyExchangeDiffieHellman\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBStart\fP (\fBSession\fP session, \fBKeyExchangeInitMessage\fP message)"
.br
.RI "\fIStarts key exchange algorithm \fP"
.ti -1c
.RI "override void \fBFinish\fP ()"
.br
.RI "\fIFinishes key exchange algorithm\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override byte[] \fBCalculateHash\fP ()"
.br
.RI "\fICalculates key exchange hash value\&. \fP"
.ti -1c
.RI "override byte[] \fBHash\fP (byte[] hashBytes)"
.br
.RI "\fIHashes the specified data bytes\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.RI "\fIGets algorithm name\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents 'diffie-hellman-group-exchange-sha256' algorithm implementation\&. 


.PP
Definition at line 17 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override byte [] Renci\&.SshNet\&.Security\&.KeyExchangeDiffieHellmanGroupExchangeSha256\&.CalculateHash ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Calculates key exchange hash value\&. 
.PP
\fBReturns:\fP
.RS 4
\fBKey\fP exchange hash\&. 
.RE
.PP

.PP
Implements \fBRenci\&.SshNet\&.Security\&.KeyExchange\fP\&.
.PP
Definition at line 62 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.
.SS "override void Renci\&.SshNet\&.Security\&.KeyExchangeDiffieHellmanGroupExchangeSha256\&.Finish ()\fC [virtual]\fP"

.PP
Finishes key exchange algorithm\&. 
.PP
Reimplemented from \fBRenci\&.SshNet\&.Security\&.KeyExchange\fP\&.
.PP
Definition at line 49 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.
.SS "override byte [] Renci\&.SshNet\&.Security\&.KeyExchangeDiffieHellmanGroupExchangeSha256\&.Hash (byte[]hashBytes)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Hashes the specified data bytes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhashBytes\fP Data to hash\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Hashed bytes 
.RE
.PP

.PP
Reimplemented from \fBRenci\&.SshNet\&.Security\&.KeyExchange\fP\&.
.PP
Definition at line 91 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.
.SS "override void Renci\&.SshNet\&.Security\&.KeyExchangeDiffieHellmanGroupExchangeSha256\&.Start (\fBSession\fPsession, \fBKeyExchangeInitMessage\fPmessage)\fC [virtual]\fP"

.PP
Starts key exchange algorithm 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The session\&.
.br
\fImessage\fP \fBKey\fP exchange init message\&.
.RE
.PP

.PP
Reimplemented from \fBRenci\&.SshNet\&.Security\&.KeyExchangeDiffieHellman\fP\&.
.PP
Definition at line 32 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string Renci\&.SshNet\&.Security\&.KeyExchangeDiffieHellmanGroupExchangeSha256\&.Name\fC [get]\fP"

.PP
Gets algorithm name\&. 
.PP
Definition at line 23 of file KeyExchangeDiffieHellmanGroupExchangeSha256\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
