//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.Common.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.Common.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: {0}, Name: {1}, OrgUnit: ({2}), Size: {3} Bytes. ähnelt.
        /// </summary>
        internal static string COMPONENT_TO_STRING {
            get {
                return ResourceManager.GetString("COMPONENT_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrypt bytes. ähnelt.
        /// </summary>
        internal static string DECRYPT {
            get {
                return ResourceManager.GetString("DECRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encrypt bytes ähnelt.
        /// </summary>
        internal static string ENCRYPT {
            get {
                return ResourceManager.GetString("ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity has size of {0} Bytes. ähnelt.
        /// </summary>
        internal static string ENTITY_SIZE_OF {
            get {
                return ResourceManager.GetString("ENTITY_SIZE_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while detecting size: {0}. ähnelt.
        /// </summary>
        internal static string ENTITY_SIZEOF_ERROR {
            get {
                return ResourceManager.GetString("ENTITY_SIZEOF_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: {0}, Size: {1} Bytes. ähnelt.
        /// </summary>
        internal static string ENTITY_TO_STRING {
            get {
                return ResourceManager.GetString("ENTITY_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SMTP server: {0}, SMTP port: {1}, Mail from: {2}, Size: {3} Bytes. ähnelt.
        /// </summary>
        internal static string MAILNOTIFIERSETTINGS_TO_STRING {
            get {
                return ResourceManager.GetString("MAILNOTIFIERSETTINGS_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HomePath: {0}, NutchPath: {1}, NutchCommand: {2}, NutchClients: {3}, CrawlDepth: {4}, CrawlTopN: {5}, SolrServer: {6}, JavaHome: {7}, CertificatePath: {8}, Prefix: {9}, CrawlRequest: {10}, SeedFileName: {11}, PrefixFileName: {12}, BaseUrlPath: {13}, BaseCrawlPath: {14}, PathFormatTwo: {15}, PathFormatThree: {16}, PathFormatFour: {17}, PrefixFormat: {18}, Size: {19} Bytes ähnelt.
        /// </summary>
        internal static string NUTCHCONTROLLERSETTINGS_TO_STRING {
            get {
                return ResourceManager.GetString("NUTCHCONTROLLERSETTINGS_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: {0}, UserId: {1}, Name: {2}, OrgUnitConfig: ({3}), Size: {4} Bytes. ähnelt.
        /// </summary>
        internal static string ORGUNIT_TO_STRING {
            get {
                return ResourceManager.GetString("ORGUNIT_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: {0}, URLs: {1}, Urls active: {2}, Mails: {3}, Mails active: {4}, Schedule every {5} days at ({6}), Scheduler active: {7}, Size: {8} Bytes. ähnelt.
        /// </summary>
        internal static string ORGUNITCONFIG_TO_STRING {
            get {
                return ResourceManager.GetString("ORGUNITCONFIG_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID: {0}, Component: {1}, Title: {2}, URL: {3}, Content: {4}, Time: {5}, Size: {6} Bytes. ähnelt.
        /// </summary>
        internal static string RESULT_TO_STRING {
            get {
                return ResourceManager.GetString("RESULT_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host: {0}, Port: {1}, Collection: {2}, FilterQuery: {3}, RequestFormat: {4}, QueryFormat {5}, Size: {6} Bytes. ähnelt.
        /// </summary>
        internal static string SOLRSEARCHCLIENTSETTINGS_TO_STRING {
            get {
                return ResourceManager.GetString("SOLRSEARCHCLIENTSETTINGS_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Http address: {0}, Http port {1}, NetTcp address: {2}, NetTcp port: {3}, Certificate path: {4}, Size: {5} Bytes. ähnelt.
        /// </summary>
        internal static string WCF_SETTINGS_TO_STRING {
            get {
                return ResourceManager.GetString("WCF_SETTINGS_TO_STRING", resourceCulture);
            }
        }
    }
}
