//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.Common.Nutch.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.Common.Nutch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crawl request was send: {0} ähnelt.
        /// </summary>
        internal static string CRAWL_REQUEST_SENT {
            get {
                return ResourceManager.GetString("CRAWL_REQUEST_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The directory {0} could not be created. ähnelt.
        /// </summary>
        internal static string LOG_DIRECTORY_CREATION_ERROR {
            get {
                return ResourceManager.GetString("LOG_DIRECTORY_CREATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} at {1} successfully created. ähnelt.
        /// </summary>
        internal static string LOG_DIRECTORY_CREATION_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_DIRECTORY_CREATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading from file {0}, error was: {1} ähnelt.
        /// </summary>
        internal static string LOG_FILE_READING_ERROR {
            get {
                return ResourceManager.GetString("LOG_FILE_READING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File {0} successfully read. ähnelt.
        /// </summary>
        internal static string LOG_FILE_READING_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_FILE_READING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while writing to file {0}, error was: {1}. ähnelt.
        /// </summary>
        internal static string LOG_FILE_WRITING_ERROR {
            get {
                return ResourceManager.GetString("LOG_FILE_WRITING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Url {0} successfully written. ähnelt.
        /// </summary>
        internal static string LOG_FILE_WRITING_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_FILE_WRITING_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New prefix {0} added. ähnelt.
        /// </summary>
        internal static string LOG_PREFIX_ADDED {
            get {
                return ResourceManager.GetString("LOG_PREFIX_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prefix file does not exist, create it. ähnelt.
        /// </summary>
        internal static string LOG_PREFIX_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_PREFIX_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NutchManager does not exist, create one ähnelt.
        /// </summary>
        internal static string NUTCHMANAGER_NO_MANAGER_FOUND {
            get {
                return ResourceManager.GetString("NUTCHMANAGER_NO_MANAGER_FOUND", resourceCulture);
            }
        }
    }
}
