//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.Common.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.Common.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instance saved successfully in database. ähnelt.
        /// </summary>
        internal static string DBMANAGER_ADD_ENTITY {
            get {
                return ResourceManager.GetString("DBMANAGER_ADD_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New component [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_COMPONENT {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_COMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New org unit [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_ORGUNIT {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_ORGUNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New org unit configuration [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_ORGUNITCONFIG {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_ORGUNITCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New result [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_RESULT {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New scheduler [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_SCHEDULER {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_SCHEDULER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New source [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_SOURCE {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New systemservice [{0}] created. ähnelt.
        /// </summary>
        internal static string DBMANAGER_CREATE_SYSTEMSERVICE {
            get {
                return ResourceManager.GetString("DBMANAGER_CREATE_SYSTEMSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted entity [{0}] ähnelt.
        /// </summary>
        internal static string DBMANAGER_DELETE_ENTITY {
            get {
                return ResourceManager.GetString("DBMANAGER_DELETE_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load this entities [{0}] eager from database. ähnelt.
        /// </summary>
        internal static string DBMANAGER_EAGER_LOAD_THIS_ENTITIES {
            get {
                return ResourceManager.GetString("DBMANAGER_EAGER_LOAD_THIS_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got components: [{0}] by GUID: [{1}]. ähnelt.
        /// </summary>
        internal static string DBMANAGER_GET_COMPONENT_BY_ORGUNIT_ID {
            get {
                return ResourceManager.GetString("DBMANAGER_GET_COMPONENT_BY_ORGUNIT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got entity of type [{0}] with values [{1}] by GUID [{2}] ähnelt.
        /// </summary>
        internal static string DBMANAGER_GET_ENTITY {
            get {
                return ResourceManager.GetString("DBMANAGER_GET_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got org unit [{0}] by id [{1}] ähnelt.
        /// </summary>
        internal static string DBMANAGER_GET_ORGUNIT_BY_USERID {
            get {
                return ResourceManager.GetString("DBMANAGER_GET_ORGUNIT_BY_USERID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DBManager does not exist, create one. ähnelt.
        /// </summary>
        internal static string DBMANAGER_NO_MANAGER_FOUND {
            get {
                return ResourceManager.GetString("DBMANAGER_NO_MANAGER_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instance updated successfully in database. ähnelt.
        /// </summary>
        internal static string DBMANAGER_UPDATE_ENTITY {
            get {
                return ResourceManager.GetString("DBMANAGER_UPDATE_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NHibernate successfully configured. ähnelt.
        /// </summary>
        internal static string DBSESSION_NHIBERNATE_CONFIG_READY {
            get {
                return ResourceManager.GetString("DBSESSION_NHIBERNATE_CONFIG_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open new session. ähnelt.
        /// </summary>
        internal static string DBSESSION_OPEN_SESSION {
            get {
                return ResourceManager.GetString("DBSESSION_OPEN_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during time initialisation, error was:\n{0} ähnelt.
        /// </summary>
        internal static string ERROR_TIME_INIT {
            get {
                return ResourceManager.GetString("ERROR_TIME_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job dispatcher timer reached zero. ähnelt.
        /// </summary>
        internal static string LOG_DISPATCHER_ZERO {
            get {
                return ResourceManager.GetString("LOG_DISPATCHER_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetch jobs from database. ähnelt.
        /// </summary>
        internal static string LOG_FETCH_JOBS_FROM_DB {
            get {
                return ResourceManager.GetString("LOG_FETCH_JOBS_FROM_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Got SchdulerTimer from database:[{0}] ähnelt.
        /// </summary>
        internal static string LOG_GOT_SCHEDULER_LIST_FROM_DB {
            get {
                return ResourceManager.GetString("LOG_GOT_SCHEDULER_LIST_FROM_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instanciate a new scheduler. ähnelt.
        /// </summary>
        internal static string LOG_INSTANCIATE_NEW_SCHEDULER {
            get {
                return ResourceManager.GetString("LOG_INSTANCIATE_NEW_SCHEDULER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job dispatcher timer restarted. ähnelt.
        /// </summary>
        internal static string LOG_RESTART_DISPATCHER {
            get {
                return ResourceManager.GetString("LOG_RESTART_DISPATCHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add SchedulerTimer [{0}] ähnelt.
        /// </summary>
        internal static string LOG_SCHEDULER_ADD {
            get {
                return ResourceManager.GetString("LOG_SCHEDULER_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The SchedulerTimer already exists. ähnelt.
        /// </summary>
        internal static string LOG_SCHEDULER_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("LOG_SCHEDULER_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start service {0}. ähnelt.
        /// </summary>
        internal static string LOG_START_SERVICE {
            get {
                return ResourceManager.GetString("LOG_START_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop service {0}. ähnelt.
        /// </summary>
        internal static string LOG_STOP_SERVICE {
            get {
                return ResourceManager.GetString("LOG_STOP_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured in countdown [{0}], message was: [{1}]. ähnelt.
        /// </summary>
        internal static string LOG_TIME_VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("LOG_TIME_VALIDATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search started with query: [{0}]. ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_SEARCH_STARTED {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_SEARCH_STARTED", resourceCulture);
            }
        }
    }
}
