//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.Common.SolrClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.Common.SolrClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Issue {0} found on website: {1}, content: {2} at {3} ähnelt.
        /// </summary>
        internal static string RESULT_TO_STRING {
            get {
                return ResourceManager.GetString("RESULT_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Connection ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_CLOSE_CONNECTION {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_CLOSE_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Established to host: [{0}] ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_CONNECTION_ESTABLISHED {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_CONNECTION_ESTABLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message was send: [{0}] ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_MESSAGE_SENT {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_MESSAGE_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received a request for a solr query: [{0}] ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_REQUEST_RECEIVED {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_REQUEST_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message from host: [{0}] received with content: [{1}] ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_RESULT_RECEIVED {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_RESULT_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Socket to host: [{0}] closed. ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_SOCKET_CLOSED {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_SOCKET_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for response from Solr. ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_TRY_GET_RESPONSE {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_TRY_GET_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to Connect to host: [{0}] ähnelt.
        /// </summary>
        internal static string SOLR_CLIENT_UNABLE_TO_CONNECT {
            get {
                return ResourceManager.GetString("SOLR_CLIENT_UNABLE_TO_CONNECT", resourceCulture);
            }
        }
    }
}
