//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWebCrawler")]
public interface IWebCrawler
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebCrawler/StartSearch", ReplyAction="http://tempuri.org/IWebCrawler/StartSearchResponse")]
    string StartSearch();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWebCrawlerChannel : IWebCrawler, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WebCrawlerClient : System.ServiceModel.ClientBase<IWebCrawler>, IWebCrawler
{
    
    public WebCrawlerClient()
    {
    }
    
    public WebCrawlerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WebCrawlerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebCrawlerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WebCrawlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string StartSearch()
    {
        return base.Channel.StartSearch();
    }
}
