//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICrawlControler")]
public interface ICrawlControler
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlControler/StartSearch", ReplyAction="http://tempuri.org/ICrawlControler/StartSearchResponse")]
    string StartSearch();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlControler/ShutDownWebCrawler", ReplyAction="http://tempuri.org/ICrawlControler/ShutDownWebCrawlerResponse")]
    bool ShutDownWebCrawler();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICrawlControlerChannel : ICrawlControler, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CrawlControlerClient : System.ServiceModel.ClientBase<ICrawlControler>, ICrawlControler
{
    
    public CrawlControlerClient()
    {
    }
    
    public CrawlControlerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CrawlControlerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControlerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControlerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string StartSearch()
    {
        return base.Channel.StartSearch();
    }
    
    public bool ShutDownWebCrawler()
    {
        return base.Channel.ShutDownWebCrawler();
    }
}
