//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18033
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICrawlController")]
public interface ICrawlController
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartSearch", ReplyAction="http://tempuri.org/ICrawlController/StartSearchResponse")]
    void StartSearch(string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartServices", ReplyAction="http://tempuri.org/ICrawlController/StartServicesResponse")]
    void StartServices();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StopServices", ReplyAction="http://tempuri.org/ICrawlController/StopServicesResponse")]
    void StopServices();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICrawlControllerChannel : ICrawlController, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CrawlControllerClient : System.ServiceModel.ClientBase<ICrawlController>, ICrawlController
{
    
    public CrawlControllerClient()
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void StartSearch(string query)
    {
        base.Channel.StartSearch(query);
    }
    
    public void StartServices()
    {
        base.Channel.StartServices();
    }
    
    public void StopServices()
    {
        base.Channel.StopServices();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDBManager")]
public interface IDBManager
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/AddEntity", ReplyAction="http://tempuri.org/IDBManager/AddEntityResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Component))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Source))]
    void AddEntity(object entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/UpdateEntity", ReplyAction="http://tempuri.org/IDBManager/UpdateEntityResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Component))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Source))]
    void UpdateEntity(object entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/GetComponent", ReplyAction="http://tempuri.org/IDBManager/GetComponentResponse")]
    HSA.InfoSys.DBManager.Data.Component GetComponent(System.Guid componentGuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/GetSource", ReplyAction="http://tempuri.org/IDBManager/GetSourceResponse")]
    HSA.InfoSys.DBManager.Data.Source GetSource(System.Guid sourceGuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/CreateComponent", ReplyAction="http://tempuri.org/IDBManager/CreateComponentResponse")]
    HSA.InfoSys.DBManager.Data.Component CreateComponent(string name, string category);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBManager/CreateSource", ReplyAction="http://tempuri.org/IDBManager/CreateSourceResponse")]
    HSA.InfoSys.DBManager.Data.Source CreateSource(string sourceURL);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDBManagerChannel : IDBManager, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DBManagerClient : System.ServiceModel.ClientBase<IDBManager>, IDBManager
{
    
    public DBManagerClient()
    {
    }
    
    public DBManagerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DBManagerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DBManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DBManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddEntity(object entity)
    {
        base.Channel.AddEntity(entity);
    }
    
    public void UpdateEntity(object entity)
    {
        base.Channel.UpdateEntity(entity);
    }
    
    public HSA.InfoSys.DBManager.Data.Component GetComponent(System.Guid componentGuid)
    {
        return base.Channel.GetComponent(componentGuid);
    }
    
    public HSA.InfoSys.DBManager.Data.Source GetSource(System.Guid sourceGuid)
    {
        return base.Channel.GetSource(sourceGuid);
    }
    
    public HSA.InfoSys.DBManager.Data.Component CreateComponent(string name, string category)
    {
        return base.Channel.CreateComponent(name, category);
    }
    
    public HSA.InfoSys.DBManager.Data.Source CreateSource(string sourceURL)
    {
        return base.Channel.CreateSource(sourceURL);
    }
}
namespace HSA.InfoSys.DBManager.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.datacontract.org/2004/07/HSA.InfoSys.DBManager.Data")]
    public partial class Component : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryField;
        
        private System.Guid ComponentGUIDField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ComponentGUID
        {
            get
            {
                return this.ComponentGUIDField;
            }
            set
            {
                this.ComponentGUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schemas.datacontract.org/2004/07/HSA.InfoSys.DBManager.Data")]
    public partial class Source : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid SourceGUIDField;
        
        private string URLField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SourceGUID
        {
            get
            {
                return this.SourceGUIDField;
            }
            set
            {
                this.SourceGUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }
}
