//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.WCFProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/HSA.InfoSys.DBManager.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Component))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HSA.InfoSys.DBManager.Data.Source))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid EntityIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EntityId
        {
            get
            {
                return this.EntityIdField;
            }
            set
            {
                this.EntityIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Component", Namespace="http://schemas.datacontract.org/2004/07/HSA.InfoSys.DBManager.Data")]
    public partial class Component : HSA.InfoSys.DBManager.Data.Entity
    {
        
        private string CategoryField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schemas.datacontract.org/2004/07/HSA.InfoSys.DBManager.Data")]
    public partial class Source : HSA.InfoSys.DBManager.Data.Entity
    {
        
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this.URLField;
            }
            set
            {
                this.URLField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICrawlController")]
public interface ICrawlController
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartSearch", ReplyAction="http://tempuri.org/ICrawlController/StartSearchResponse")]
    void StartSearch(string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StartServices", ReplyAction="http://tempuri.org/ICrawlController/StartServicesResponse")]
    void StartServices();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/StopServices", ReplyAction="http://tempuri.org/ICrawlController/StopServicesResponse")]
    void StopServices();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/AddEntity", ReplyAction="http://tempuri.org/ICrawlController/AddEntityResponse")]
    System.Guid AddEntity(HSA.InfoSys.DBManager.Data.Entity entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/UpdateEntity", ReplyAction="http://tempuri.org/ICrawlController/UpdateEntityResponse")]
    System.Guid UpdateEntity(HSA.InfoSys.DBManager.Data.Entity entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/GetEntity", ReplyAction="http://tempuri.org/ICrawlController/GetEntityResponse")]
    HSA.InfoSys.DBManager.Data.Entity GetEntity(System.Guid entityGuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/CreateComponent", ReplyAction="http://tempuri.org/ICrawlController/CreateComponentResponse")]
    HSA.InfoSys.DBManager.Data.Component CreateComponent(string name, string category);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawlController/CreateSource", ReplyAction="http://tempuri.org/ICrawlController/CreateSourceResponse")]
    HSA.InfoSys.DBManager.Data.Source CreateSource(string sourceURL);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICrawlControllerChannel : ICrawlController, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CrawlControllerClient : System.ServiceModel.ClientBase<ICrawlController>, ICrawlController
{
    
    public CrawlControllerClient()
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CrawlControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void StartSearch(string query)
    {
        base.Channel.StartSearch(query);
    }
    
    public void StartServices()
    {
        base.Channel.StartServices();
    }
    
    public void StopServices()
    {
        base.Channel.StopServices();
    }
    
    public System.Guid AddEntity(HSA.InfoSys.DBManager.Data.Entity entity)
    {
        return base.Channel.AddEntity(entity);
    }
    
    public System.Guid UpdateEntity(HSA.InfoSys.DBManager.Data.Entity entity)
    {
        return base.Channel.UpdateEntity(entity);
    }
    
    public HSA.InfoSys.DBManager.Data.Entity GetEntity(System.Guid entityGuid)
    {
        return base.Channel.GetEntity(entityGuid);
    }
    
    public HSA.InfoSys.DBManager.Data.Component CreateComponent(string name, string category)
    {
        return base.Channel.CreateComponent(name, category);
    }
    
    public HSA.InfoSys.DBManager.Data.Source CreateSource(string sourceURL)
    {
        return base.Channel.CreateSource(sourceURL);
    }
}
