//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSA.InfoSys.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSA.InfoSys.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common error: {0}. ähnelt.
        /// </summary>
        internal static string LOG_COMMON_ERROR {
            get {
                return ResourceManager.GetString("LOG_COMMON_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not contact the service: {0}. ähnelt.
        /// </summary>
        internal static string LOG_COMMUNICATION_ERROR {
            get {
                return ResourceManager.GetString("LOG_COMMUNICATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; und &apos;{1}&apos; stimmen nicht überein. ähnelt.
        /// </summary>
        internal static string PROPERTIE_MATCH_NOT_EQUAL {
            get {
                return ResourceManager.GetString("PROPERTIE_MATCH_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Kennwort entspricht nicht dem Bestätigungskennwort. ähnelt.
        /// </summary>
        internal static string REGISTER_MODEL_PASSWORD_MISSMATCH {
            get {
                return ResourceManager.GetString("REGISTER_MODEL_PASSWORD_MISSMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Systems ähnelt.
        /// </summary>
        internal static string TEST_LABLE1 {
            get {
                return ResourceManager.GetString("TEST_LABLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für diese E-Mail-Adresse ist bereits ein Benutzername vorhanden. Geben Sie eine andere E-Mail-Adresse ein. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_MAIL_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_MAIL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene E-Mail-Adresse ist ungültig. Überprüfen Sie den Wert, und wiederholen Sie den Vorgang. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_MAIL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_MAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Kennwortabrufantwort ist ungültig. Überprüfen Sie den Wert, und wiederholen Sie den Vorgang. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_PASSWORD_CALL_INVALID {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_PASSWORD_CALL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das angegebene Kennwort ist ungültig. Geben Sie einen gültigen Kennwortwert ein. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vom Authentifizierungsanbieter wurde ein Fehler zurückgegeben. Überprüfen Sie die Eingabe, und wiederholen Sie den Vorgang. Sollte das Problem weiterhin bestehen, wenden Sie sich an den zuständigen Systemadministrator. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_PROVIDER_ERROR {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_PROVIDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Kennwortabruffrage ist ungültig. Überprüfen Sie den Wert, und wiederholen Sie den Vorgang. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_QUESTION_INVALID {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_QUESTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannter Fehler. Überprüfen Sie die Eingabe, und wiederholen Sie den Vorgang. Sollte das Problem weiterhin bestehen, wenden Sie sich an den zuständigen Systemadministrator. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_UNKOWN_ERROR {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_UNKOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Benutzername ist bereits vorhanden. Geben Sie einen anderen Benutzernamen ein. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_USER_EXISTS {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_USER_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Benutzererstellungsanforderung wurde abgebrochen. Überprüfen Sie die Eingabe, und wiederholen Sie den Vorgang. Sollte das Problem weiterhin bestehen, wenden Sie sich an den zuständigen Systemadministrator. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_USER_REJECTED {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_USER_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Benutzername ist ungültig. Überprüfen Sie den Wert, und wiederholen Sie den Vorgang. ähnelt.
        /// </summary>
        internal static string VALIDATE_ERROR_USERNAME_INVALID {
            get {
                return ResourceManager.GetString("VALIDATE_ERROR_USERNAME_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; muss mindestens {1} Zeichen lang sein. ähnelt.
        /// </summary>
        internal static string VALIDATE_PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("VALIDATE_PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value must not be empty. ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_EXCEPTION {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_MAIL {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Password ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_NEW_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old Password ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_PASSWORD {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string VALIDATE_USER_ARG_USERNAME {
            get {
                return ResourceManager.GetString("VALIDATE_USER_ARG_USERNAME", resourceCulture);
            }
        }
    }
}
