.TH "C:/Users/michael/Development/HSA.InfoSys/3rdparty/nhibernate-core/src/NHibernate/Cfg/Loquacious Directory Reference" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/michael/Development/HSA.InfoSys/3rdparty/nhibernate-core/src/NHibernate/Cfg/Loquacious Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCacheConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBDbIntegrationConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBDbIntegrationConfigurationProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBEntityCacheConfigurationProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBFluentSessionFactoryConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBatcherConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBICacheConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBICollectionFactoryConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBICommandsConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIConnectionConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDbIntegrationConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDbIntegrationConfigurationProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDbSchemaIntegrationConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIEntityCacheConfigurationProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBIFluentSessionFactoryConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIMappingsConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBINamedQueryDefinitionBuilder\&.cs\fP"
.br
.ti -1c
.RI "file \fBIProxyConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBIQueryCacheConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBITransactionConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBITypeDefConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBMappingsConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBProxyConfiguration\&.cs\fP"
.br
.in -1c
