.TH "HSA.InfoSys.Common.Entities.OrgUnitConfig" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Entities.OrgUnitConfig \- 
.PP
This represents the OrgUnitConfiguration  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHSA\&.InfoSys\&.Common\&.Entities\&.Entity\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIReturns a System\&.String that represents this instance\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBURLs\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the URL which should be used for crawling for the \fBOrgUnit\fP\&. \fP"
.ti -1c
.RI "virtual string \fBEmails\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the Email\&. The email addresses we want send the results\&. \fP"
.ti -1c
.RI "virtual bool \fBEmailActive\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether email notification is enabled or not\&. If active emails will be send to the owners\&. \fP"
.ti -1c
.RI "virtual int \fBDays\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the Days\&. Defines for example that the search starts every third day\&. \fP"
.ti -1c
.RI "virtual int \fBTime\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the Time\&. Defines the time the search must start\&. \fP"
.ti -1c
.RI "virtual bool \fBSchedulerActive\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether the scheduler is active or not\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This represents the OrgUnitConfiguration 


.PP
Definition at line 16 of file OrgUnitConfig\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.ToString ()"

.PP
Returns a System\&.String that represents this instance\&. 
.PP
\fBReturns:\fP
.RS 4
A System\&.String that represents this instance\&. 
.RE
.PP

.PP
Definition at line 84 of file OrgUnitConfig\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual int HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.Days\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Days\&. Defines for example that the search starts every third day\&. The Days\&. 
.PP
Definition at line 57 of file OrgUnitConfig\&.cs\&.
.SS "virtual bool HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.EmailActive\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether email notification is enabled or not\&. If active emails will be send to the owners\&. The EmailNotification\&. 
.PP
Definition at line 46 of file OrgUnitConfig\&.cs\&.
.SS "virtual string HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.Emails\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Email\&. The email addresses we want send the results\&. The Email\&. 
.PP
Definition at line 36 of file OrgUnitConfig\&.cs\&.
.SS "virtual bool HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.SchedulerActive\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether the scheduler is active or not\&. The SchedulerActive\&. 
.PP
Definition at line 76 of file OrgUnitConfig\&.cs\&.
.SS "virtual int HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.Time\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Time\&. Defines the time the search must start\&. The Time for crawling\&. 
.PP
Definition at line 67 of file OrgUnitConfig\&.cs\&.
.SS "virtual string HSA\&.InfoSys\&.Common\&.Entities\&.OrgUnitConfig\&.URLs\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the URL which should be used for crawling for the \fBOrgUnit\fP\&. The URL\&. 
.PP
Definition at line 26 of file OrgUnitConfig\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
