.TH "HSA.InfoSys.Common.Services.WCFServices.SolrController" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Services.WCFServices.SolrController \- 
.PP
In this class are all methods implemented for controlling Solr\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHSA\&.InfoSys\&.Common\&.Services\&.Service\fP, and \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.ISolrController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSearchForOrgUnit\fP (Guid orgUnitGUID)"
.br
.RI "\fISearches for all components of an org unit\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSolrController\fP \fBSolrFactory\fP (\fBDbManager\fP dbManager)"
.br
.RI "\fIThe Solr controller\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBRun\fP ()"
.br
.RI "\fIRuns this service\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
In this class are all methods implemented for controlling Solr\&. 


.PP
Definition at line 16 of file SolrController\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.SolrController\&.Run ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Runs this service\&. 
.PP
Implements \fBHSA\&.InfoSys\&.Common\&.Services\&.Service\fP\&.
.PP
Definition at line 70 of file SolrController\&.cs\&.
.SS "void HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.SolrController\&.SearchForOrgUnit (GuidorgUnitGUID)"

.PP
Searches for all components of an org unit\&. 
.PP
\fBParameters:\fP
.RS 4
\fIorgUnitGUID\fP The org unit GUID\&.
.RE
.PP

.PP
Implements \fBHSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.ISolrController\fP\&.
.PP
Definition at line 52 of file SolrController\&.cs\&.
.SS "static \fBSolrController\fP HSA\&.InfoSys\&.Common\&.Services\&.WCFServices\&.SolrController\&.SolrFactory (\fBDbManager\fPdbManager)\fC [static]\fP"

.PP
The Solr controller\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdbManager\fP The db manager\&.
.RE
.PP
\fBReturns:\fP
.RS 4
an instance of the Solr controller\&.
.RE
.PP

.PP
Definition at line 43 of file SolrController\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
