.TH "HSA.InfoSys.Gui.Models.RegisterModel" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Gui.Models.RegisterModel \- 
.PP
This class provides the functionality for registration\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUserName\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the name of the user\&. \fP"
.ti -1c
.RI "string \fBEmail\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the email\&. \fP"
.ti -1c
.RI "string \fBPassword\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the password\&. \fP"
.ti -1c
.RI "string \fBConfirmPassword\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the confirm password\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class provides the functionality for registration\&. 


.PP
Definition at line 15 of file RegisterModel\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string HSA\&.InfoSys\&.Gui\&.Models\&.RegisterModel\&.ConfirmPassword\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the confirm password\&. The confirm password\&. 
.PP
Definition at line 59 of file RegisterModel\&.cs\&.
.SS "string HSA\&.InfoSys\&.Gui\&.Models\&.RegisterModel\&.Email\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the email\&. The email\&. 
.PP
Definition at line 36 of file RegisterModel\&.cs\&.
.SS "string HSA\&.InfoSys\&.Gui\&.Models\&.RegisterModel\&.Password\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the password\&. The password\&. 
.PP
Definition at line 48 of file RegisterModel\&.cs\&.
.SS "string HSA\&.InfoSys\&.Gui\&.Models\&.RegisterModel\&.UserName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the name of the user\&. The name of the user\&. 
.PP
Definition at line 25 of file RegisterModel\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
