.TH "HSA.InfoSys.Gui.Models.FormsAuthenticationService" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Gui.Models.FormsAuthenticationService \- 
.PP
This class checks the values of the web form\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHSA\&.InfoSys\&.Gui\&.Models\&.IFormsAuthenticationService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSignIn\fP (string userName, bool createPersistentCookie)"
.br
.RI "\fIUser log in\&. \fP"
.ti -1c
.RI "void \fBSignOut\fP ()"
.br
.RI "\fIUser log out\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class checks the values of the web form\&. 


.PP
Definition at line 14 of file FormsAuthenticationService\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void HSA\&.InfoSys\&.Gui\&.Models\&.FormsAuthenticationService\&.SignIn (stringuserName, boolcreatePersistentCookie)"

.PP
User log in\&. 
.PP
\fBParameters:\fP
.RS 4
\fIuserName\fP Name of the user\&.
.br
\fIcreatePersistentCookie\fP if set to \fCtrue\fP [create persistent cookie]\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fISystem\&.ArgumentException\fP The value must not be empty\&.
.RE
.PP

.PP
Implements \fBHSA\&.InfoSys\&.Gui\&.Models\&.IFormsAuthenticationService\fP\&.
.PP
Definition at line 22 of file FormsAuthenticationService\&.cs\&.
.SS "void HSA\&.InfoSys\&.Gui\&.Models\&.FormsAuthenticationService\&.SignOut ()"

.PP
User log out\&. 
.PP
Implements \fBHSA\&.InfoSys\&.Gui\&.Models\&.IFormsAuthenticationService\fP\&.
.PP
Definition at line 37 of file FormsAuthenticationService\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
