.TH "HSA.InfoSys.CrawlerServiceController" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.CrawlerServiceController \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServiceController\fP"
.br
.RI "\fIThis class provides control functionality for the crawler service\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
