.TH "HSA.InfoSys.Common.Services.LocalServices.CountdownTime" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSA.InfoSys.Common.Services.LocalServices.CountdownTime \- 
.PP
This class represents the time object\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCountdownTime\fP (DateTime repeatIn, Guid id, bool repeat)"
.br
.RI "\fIInitializes a new instance of the \fBCountdownTime\fP class\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIReturns a System\&.String that represents this instance\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBRepeatIn\fP\fC [get, set]\fP"
.br
.RI "\fIGets the duration\&. \fP"
.ti -1c
.RI "bool \fBRepeat\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value indicating whether this \fBCountdownTime\fP is repeat\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class represents the time object\&. 


.PP
Definition at line 13 of file CountdownTime\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HSA\&.InfoSys\&.Common\&.Services\&.LocalServices\&.CountdownTime\&.CountdownTime (DateTimerepeatIn, Guidid, boolrepeat)"

.PP
Initializes a new instance of the \fBCountdownTime\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrepeatIn\fP The repeat in\&.
.br
\fIid\fP The id\&.
.br
\fIrepeat\fP if set to \fCtrue\fP [repeat]\&.
.RE
.PP

.PP
Definition at line 21 of file CountdownTime\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override string HSA\&.InfoSys\&.Common\&.Services\&.LocalServices\&.CountdownTime\&.ToString ()"

.PP
Returns a System\&.String that represents this instance\&. 
.PP
\fBReturns:\fP
.RS 4
A System\&.String that represents this instance\&. 
.RE
.PP

.PP
Definition at line 61 of file CountdownTime\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool HSA\&.InfoSys\&.Common\&.Services\&.LocalServices\&.CountdownTime\&.Repeat\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether this \fBCountdownTime\fP is repeat\&. \fCtrue\fP if repeat; otherwise, \fCfalse\fP\&. 
.PP
Definition at line 45 of file CountdownTime\&.cs\&.
.SS "DateTime HSA\&.InfoSys\&.Common\&.Services\&.LocalServices\&.CountdownTime\&.RepeatIn\fC [get]\fP, \fC [set]\fP"

.PP
Gets the duration\&. The duration\&. 
.PP
Definition at line 37 of file CountdownTime\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
