.TH "log4net.Util.PatternParser" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Util.PatternParser \- 
.PP
Most of the work of the PatternLayout class is delegated to the \fBPatternParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPatternParser\fP (string pattern)"
.br
.RI "\fIConstructor \fP"
.ti -1c
.RI "\fBPatternConverter\fP \fBParse\fP ()"
.br
.RI "\fIParses the pattern into a chain of pattern converters\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Hashtable \fBPatternConverters\fP\fC [get]\fP"
.br
.RI "\fIGet the converter registry used by this parser \fP"
.in -1c
.SH "Detailed Description"
.PP 
Most of the work of the PatternLayout class is delegated to the \fBPatternParser\fP class\&. 

The \fC\fBPatternParser\fP\fP processes a pattern string and returns a chain of \fBPatternConverter\fP objects\&. 
.PP
<author>Nicko Cadell</author> <author>Gert Driesen</author> 
.PP
Definition at line 47 of file PatternParser\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4net\&.Util\&.PatternParser\&.PatternParser (stringpattern)"

.PP
Constructor 
.PP
\fBParameters:\fP
.RS 4
\fIpattern\fP The pattern to parse\&.
.RE
.PP
.PP
Initializes a new instance of the \fBPatternParser\fP class with the specified pattern string\&. 
.PP
Definition at line 61 of file PatternParser\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPatternConverter\fP log4net\&.Util\&.PatternParser\&.Parse ()"

.PP
Parses the pattern into a chain of pattern converters\&. 
.PP
\fBReturns:\fP
.RS 4
The head of a chain of pattern converters\&.
.RE
.PP
.PP
Parses the pattern into a chain of pattern converters\&. 
.PP
Definition at line 79 of file PatternParser\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "Hashtable log4net\&.Util\&.PatternParser\&.PatternConverters\fC [get]\fP"

.PP
Get the converter registry used by this parser The converter registry used by this parser 
.PP
Get the converter registry used by this parser 
.PP
Definition at line 104 of file PatternParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
