.TH "log4net.Util.TypeConverters" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Util.TypeConverters \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBooleanConverter\fP"
.br
.RI "\fIType converter for Boolean\&. \fP"
.ti -1c
.RI "class \fBConversionNotSupportedException\fP"
.br
.RI "\fIException base type for conversion errors\&. \fP"
.ti -1c
.RI "class \fBConverterRegistry\fP"
.br
.RI "\fIRegister of type converters for specific types\&. \fP"
.ti -1c
.RI "class \fBEncodingConverter\fP"
.br
.RI "\fISupports conversion from string to Encoding type\&. \fP"
.ti -1c
.RI "interface \fBIConvertFrom\fP"
.br
.RI "\fIInterface supported by type converters \fP"
.ti -1c
.RI "interface \fBIConvertTo\fP"
.br
.RI "\fIInterface supported by type converters \fP"
.ti -1c
.RI "class \fBIPAddressConverter\fP"
.br
.RI "\fISupports conversion from string to IPAddress type\&. \fP"
.ti -1c
.RI "class \fBPatternLayoutConverter\fP"
.br
.RI "\fISupports conversion from string to PatternLayout type\&. \fP"
.ti -1c
.RI "class \fBPatternStringConverter\fP"
.br
.RI "\fIConvert between string and \fBPatternString\fP \fP"
.ti -1c
.RI "class \fBTypeConverter\fP"
.br
.RI "\fISupports conversion from string to Type type\&. \fP"
.ti -1c
.RI "class \fBTypeConverterAttribute\fP"
.br
.RI "\fIAttribute used to associate a type converter \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
