.TH "log4net.Appender.EventLogAppender.Level2EventLogEntryType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Appender.EventLogAppender.Level2EventLogEntryType \- 
.PP
A class to act as a mapping between the level that a logging call is made at and the color it should be displayed as\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Util\&.LevelMappingEntry\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "EventLogEntryType \fBEventLogEntryType\fP\fC [get, set]\fP"
.br
.RI "\fIThe \fBEventLogEntryType\fP for this entry \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A class to act as a mapping between the level that a logging call is made at and the color it should be displayed as\&. 

Defines the mapping between a level and its event log entry type\&. 
.PP
Definition at line 584 of file EventLogAppender\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "EventLogEntryType log4net\&.Appender\&.EventLogAppender\&.Level2EventLogEntryType\&.EventLogEntryType\fC [get]\fP, \fC [set]\fP"

.PP
The \fBEventLogEntryType\fP for this entry Required property\&. The \fBEventLogEntryType\fP for this entry 
.PP
Definition at line 598 of file EventLogAppender\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
