.TH "log4net.Appender.TraceAppender" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Appender.TraceAppender \- 
.PP
Appends log events to the System\&.Diagnostics\&.Trace system\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Appender\&.AppenderSkeleton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTraceAppender\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBTraceAppender\fP\&. \fP"
.ti -1c
.RI "\fBTraceAppender\fP (\fBILayout\fP layout)"
.br
.RI "\fIInitializes a new instance of the \fBTraceAppender\fP with a specified layout\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAppend\fP (\fBLoggingEvent\fP loggingEvent)"
.br
.RI "\fIWrites the logging event to the System\&.Diagnostics\&.Trace system\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBImmediateFlush\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value that indicates whether the appender will flush at the end of each write\&. \fP"
.ti -1c
.RI "\fBPatternLayout\fP \fBCategory\fP\fC [get, set]\fP"
.br
.RI "\fIThe category parameter sent to the Trace method\&. \fP"
.ti -1c
.RI "override bool \fBRequiresLayout\fP\fC [get]\fP"
.br
.RI "\fIThis appender requires a \fBLayout\fP to be set\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Appends log events to the System\&.Diagnostics\&.Trace system\&. 

The application configuration file can be used to control what listeners are actually used\&. See the MSDN documentation for the System\&.Diagnostics\&.Trace class for details on configuring the trace system\&. 
.PP
Events are written using the \fCSystem\&.Diagnostics\&.Trace\&.Write(string,string)\fP method\&. The event's logger name is the default value for the category parameter of the Write method\&. 
.PP
\fBCompact Framework\fP
.br
 The Compact Framework does not support the System\&.Diagnostics\&.Trace class for any operation except \fCAssert\fP\&. When using the Compact Framework this appender will write to the System\&.Diagnostics\&.Debug system rather than the Trace system\&. This appender will therefore behave like the \fBDebugAppender\fP\&. 
.PP
<author>Douglas de la Torre</author> <author>Nicko Cadell</author> <author>Gert Driesen</author> <author>Ron Grabowski</author> 
.PP
Definition at line 54 of file TraceAppender\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4net\&.Appender\&.TraceAppender\&.TraceAppender ()"

.PP
Initializes a new instance of the \fBTraceAppender\fP\&. Default constructor\&. 
.PP
Definition at line 66 of file TraceAppender\&.cs\&.
.SS "log4net\&.Appender\&.TraceAppender\&.TraceAppender (\fBILayout\fPlayout)"

.PP
Initializes a new instance of the \fBTraceAppender\fP with a specified layout\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlayout\fP The layout to use with this appender\&.
.RE
.PP
.PP
Obsolete constructor\&. 
.PP
Definition at line 81 of file TraceAppender\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void log4net\&.Appender\&.TraceAppender\&.Append (\fBLoggingEvent\fPloggingEvent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Writes the logging event to the System\&.Diagnostics\&.Trace system\&. 
.PP
\fBParameters:\fP
.RS 4
\fIloggingEvent\fP The event to log\&.
.RE
.PP
.PP
Writes the logging event to the System\&.Diagnostics\&.Trace system\&. 
.PP
Implements \fBlog4net\&.Appender\&.AppenderSkeleton\fP\&.
.PP
Definition at line 144 of file TraceAppender\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBPatternLayout\fP log4net\&.Appender\&.TraceAppender\&.Category\fC [get]\fP, \fC [set]\fP"

.PP
The category parameter sent to the Trace method\&. Defaults to logger which will use the logger name of the current LoggingEvent as the category parameter\&. 
.PP
Definition at line 126 of file TraceAppender\&.cs\&.
.SS "bool log4net\&.Appender\&.TraceAppender\&.ImmediateFlush\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value that indicates whether the appender will flush at the end of each write\&. The default behavior is to flush at the end of each write\&. If the option is set to<c>false, then the underlying stream can defer writing to physical medium to a later time\&. 
.PP
Avoiding the flush operation at the end of each append results in a performance gain of 10 to 20 percent\&. However, there is safety trade-off involved in skipping flushing\&. Indeed, when flushing is skipped, then it is likely that the last few log events will not be recorded on disk when the application exits\&. This is a high price to pay even for a 20% performance gain\&. 
.PP
Definition at line 109 of file TraceAppender\&.cs\&.
.SS "override bool log4net\&.Appender\&.TraceAppender\&.RequiresLayout\fC [get]\fP, \fC [protected]\fP"

.PP
This appender requires a \fBLayout\fP to be set\&. \fCtrue\fP
.PP
This appender requires a \fBLayout\fP to be set\&. 
.PP
Definition at line 178 of file TraceAppender\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
