.TH "log4net.Layout.XmlLayout" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Layout.XmlLayout \- 
.PP
\fBLayout\fP that formats the log events as XML elements\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlog4net\&.Layout\&.XmlLayoutBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXmlLayout\fP ()"
.br
.RI "\fIConstructs an \fBXmlLayout\fP \fP"
.ti -1c
.RI "\fBXmlLayout\fP (bool locationInfo)"
.br
.RI "\fIConstructs an \fBXmlLayout\fP\&. \fP"
.ti -1c
.RI "override void \fBActivateOptions\fP ()"
.br
.RI "\fIInitialize layout options \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBFormatXml\fP (XmlWriter writer, \fBLoggingEvent\fP loggingEvent)"
.br
.RI "\fIDoes the actual writing of the XML\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPrefix\fP\fC [get, set]\fP"
.br
.RI "\fIThe prefix to use for all element names \fP"
.ti -1c
.RI "bool \fBBase64EncodeMessage\fP\fC [get, set]\fP"
.br
.RI "\fISet whether or not to base64 encode the message\&. \fP"
.ti -1c
.RI "bool \fBBase64EncodeProperties\fP\fC [get, set]\fP"
.br
.RI "\fISet whether or not to base64 encode the property values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBLayout\fP that formats the log events as XML elements\&. 

The output of the \fBXmlLayout\fP consists of a series of \fBlog4net\fP:event elements\&. It does not output a complete well-formed XML file\&. The output is designed to be included as an \fIexternal entity\fP in a separate file to form a correct XML file\&. 
.PP
For example, if \fCabc\fP is the name of the file where the \fBXmlLayout\fP output goes, then a well-formed XML file would be: 
.PP
.PP
.nf
&lt;?xml version="1\&.0" ?&gt;

&lt;!DOCTYPE log4net:events SYSTEM "log4net-events\&.dtd" [&lt;!ENTITY data SYSTEM "abc"&gt;]&gt;

&lt;log4net:events version="1\&.2" xmlns:log4net="http://logging\&.apache\&.org/log4net/schemas/log4net-events-1\&.2&gt;
    &amp;data;
&lt;/log4net:events&gt;
.fi
.PP
 
.PP
This approach enforces the independence of the \fBXmlLayout\fP and the appender where it is embedded\&. 
.PP
The \fCversion\fP attribute helps components to correctly interpret output generated by \fBXmlLayout\fP\&. The value of this attribute should be '1\&.2' for release 1\&.2 and later\&. 
.PP
Alternatively the \fCHeader\fP and \fCFooter\fP properties can be configured to output the correct XML header, open tag and close tag\&. When setting the \fCHeader\fP and \fCFooter\fP properties it is essential that the underlying data store not be appendable otherwise the data will become invalid XML\&. 
.PP
<author>Nicko Cadell</author> <author>Gert Driesen</author> 
.PP
Definition at line 72 of file XMLLayout\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "log4net\&.Layout\&.XmlLayout\&.XmlLayout ()"

.PP
Constructs an \fBXmlLayout\fP 
.PP
Definition at line 79 of file XMLLayout\&.cs\&.
.SS "log4net\&.Layout\&.XmlLayout\&.XmlLayout (boollocationInfo)"

.PP
Constructs an \fBXmlLayout\fP\&. The \fBLocationInfo\fP option takes a boolean value\&. By default, it is set to false which means there will be no location information output by this layout\&. If the the option is set to true, then the file name and line number of the statement at the origin of the log statement will be output\&. 
.PP
If you are embedding this layout within an SmtpAppender then make sure to set the \fBLocationInfo\fP option of that appender as well\&. 
.PP
Definition at line 100 of file XMLLayout\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void log4net\&.Layout\&.XmlLayout\&.ActivateOptions ()\fC [virtual]\fP"

.PP
Initialize layout options This is part of the IOptionHandler delayed object activation scheme\&. The \fBActivateOptions\fP method must be called on this object after the configuration properties have been set\&. Until \fBActivateOptions\fP is called this object is in an undefined state and must not be used\&. 
.PP
If any of the configuration properties are modified then \fBActivateOptions\fP must be called again\&. 
.PP
Builds a cache of the element names 
.PP
Implements \fBlog4net\&.Layout\&.LayoutSkeleton\fP\&.
.PP
Definition at line 187 of file XMLLayout\&.cs\&.
.SS "override void log4net\&.Layout\&.XmlLayout\&.FormatXml (XmlWriterwriter, \fBLoggingEvent\fPloggingEvent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Does the actual writing of the XML\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwriter\fP The writer to use to output the event to\&.
.br
\fIloggingEvent\fP The event to write\&.
.RE
.PP
.PP
Override the base class \fBXmlLayoutBase\&.FormatXml\fP method to write the LoggingEvent to the XmlWriter\&. 
.PP
Implements \fBlog4net\&.Layout\&.XmlLayoutBase\fP\&.
.PP
Definition at line 218 of file XMLLayout\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool log4net\&.Layout\&.XmlLayout\&.Base64EncodeMessage\fC [get]\fP, \fC [set]\fP"

.PP
Set whether or not to base64 encode the message\&. By default the log message will be written as text to the xml output\&. This can cause problems when the message contains binary data\&. By setting this to true the contents of the message will be base64 encoded\&. If this is set then invalid character replacement (see \fBXmlLayoutBase\&.InvalidCharReplacement\fP) will not be performed on the log message\&. 
.PP
Definition at line 139 of file XMLLayout\&.cs\&.
.SS "bool log4net\&.Layout\&.XmlLayout\&.Base64EncodeProperties\fC [get]\fP, \fC [set]\fP"

.PP
Set whether or not to base64 encode the property values\&. By default the properties will be written as text to the xml output\&. This can cause problems when one or more properties contain binary data\&. By setting this to true the values of the properties will be base64 encoded\&. If this is set then invalid character replacement (see \fBXmlLayoutBase\&.InvalidCharReplacement\fP) will not be performed on the property values\&. 
.PP
Definition at line 158 of file XMLLayout\&.cs\&.
.SS "string log4net\&.Layout\&.XmlLayout\&.Prefix\fC [get]\fP, \fC [set]\fP"

.PP
The prefix to use for all element names The default prefix is \fB\fBlog4net\fP\fP\&. Set this property to change the prefix\&. If the prefix is set to an empty string then no prefix will be written\&. 
.PP
Definition at line 119 of file XMLLayout\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
