.TH "log4net.Util.ThreadContextStacks" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log4net.Util.ThreadContextStacks \- 
.PP
Implementation of Stacks collection for the \fBlog4net\&.ThreadContext\fP  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBThreadContextStack\fP \fBthis[string key]\fP\fC [get]\fP"
.br
.RI "\fIGets the named thread context stack \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Stacks collection for the \fBlog4net\&.ThreadContext\fP 

Implementation of Stacks collection for the \fBlog4net\&.ThreadContext\fP 
.PP
<author>Nicko Cadell</author> 
.PP
Definition at line 34 of file ThreadContextStacks\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBThreadContextStack\fP log4net\&.Util\&.ThreadContextStacks\&.this[string key]\fC [get]\fP"

.PP
Gets the named thread context stack The named stack 
.PP
Gets the named thread context stack 
.PP
Definition at line 69 of file ThreadContextStacks\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
