.TH "MySql.Data.MySqlClient.MySqlScript" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.MySqlScript \- 
.PP
Provides a class capable of executing a SQL script containing multiple SQL statements including CREATE PROCEDURE statements that require changing the delimiter  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMySqlScript\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBMySqlScript\fP class\&. \fP"
.ti -1c
.RI "\fBMySqlScript\fP (\fBMySqlConnection\fP connection)"
.br
.RI "\fIInitializes a new instance of the \fBMySqlScript\fP class\&. \fP"
.ti -1c
.RI "\fBMySqlScript\fP (string query)"
.br
.RI "\fIInitializes a new instance of the \fBMySqlScript\fP class\&. \fP"
.ti -1c
.RI "\fBMySqlScript\fP (\fBMySqlConnection\fP connection, string query)"
.br
.RI "\fIInitializes a new instance of the \fBMySqlScript\fP class\&. \fP"
.ti -1c
.RI "int \fBExecute\fP ()"
.br
.RI "\fIExecutes this instance\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMySqlConnection\fP \fBConnection\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the connection\&. \fP"
.ti -1c
.RI "string \fBQuery\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the query\&. \fP"
.ti -1c
.RI "string \fBDelimiter\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the delimiter\&. \fP"
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "\fBMySqlStatementExecutedEventHandler\fP \fBStatementExecuted\fP"
.br
.ti -1c
.RI "\fBMySqlScriptErrorEventHandler\fP \fBError\fP"
.br
.ti -1c
.RI "EventHandler \fBScriptCompleted\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a class capable of executing a SQL script containing multiple SQL statements including CREATE PROCEDURE statements that require changing the delimiter 


.PP
Definition at line 38 of file MySqlScript\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MySql\&.Data\&.MySqlClient\&.MySqlScript\&.MySqlScript ()"

.PP
Initializes a new instance of the \fBMySqlScript\fP class\&. 
.PP
Definition at line 54 of file MySqlScript\&.cs\&.
.SS "MySql\&.Data\&.MySqlClient\&.MySqlScript\&.MySqlScript (\fBMySqlConnection\fPconnection)"

.PP
Initializes a new instance of the \fBMySqlScript\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconnection\fP The connection\&.
.RE
.PP

.PP
Definition at line 64 of file MySqlScript\&.cs\&.
.SS "MySql\&.Data\&.MySqlClient\&.MySqlScript\&.MySqlScript (stringquery)"

.PP
Initializes a new instance of the \fBMySqlScript\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIquery\fP The query\&.
.RE
.PP

.PP
Definition at line 75 of file MySqlScript\&.cs\&.
.SS "MySql\&.Data\&.MySqlClient\&.MySqlScript\&.MySqlScript (\fBMySqlConnection\fPconnection, stringquery)"

.PP
Initializes a new instance of the \fBMySqlScript\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconnection\fP The connection\&.
.br
\fIquery\fP The query\&.
.RE
.PP

.PP
Definition at line 87 of file MySqlScript\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "int MySql\&.Data\&.MySqlClient\&.MySqlScript\&.Execute ()"

.PP
Executes this instance\&. 
.PP
\fBReturns:\fP
.RS 4
The number of statements executed as part of the script\&.
.RE
.PP

.PP
Definition at line 136 of file MySqlScript\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBMySqlConnection\fP MySql\&.Data\&.MySqlClient\&.MySqlScript\&.Connection\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the connection\&. The connection\&.
.PP
Definition at line 103 of file MySqlScript\&.cs\&.
.SS "string MySql\&.Data\&.MySqlClient\&.MySqlScript\&.Delimiter\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the delimiter\&. The delimiter\&.
.PP
Definition at line 123 of file MySqlScript\&.cs\&.
.SS "string MySql\&.Data\&.MySqlClient\&.MySqlScript\&.Query\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the query\&. The query\&.
.PP
Definition at line 113 of file MySqlScript\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
