.TH "MySql.Data.MySqlClient.MySqlError" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.MySqlError \- 
.PP
Collection of error codes that can be returned by the server  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMySqlError\fP (string level, int code, string message)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLevel\fP\fC [get]\fP"
.br
.RI "\fIError level \fP"
.ti -1c
.RI "int \fBCode\fP\fC [get]\fP"
.br
.RI "\fIError code \fP"
.ti -1c
.RI "string \fBMessage\fP\fC [get]\fP"
.br
.RI "\fIError message \fP"
.in -1c
.SH "Detailed Description"
.PP 
Collection of error codes that can be returned by the server 


.PP
Definition at line 28 of file MySqlError\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MySql\&.Data\&.MySqlClient\&.MySqlError\&.MySqlError (stringlevel, intcode, stringmessage)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP 
.br
\fIcode\fP 
.br
\fImessage\fP 
.RE
.PP

.PP
Definition at line 38 of file MySqlError\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int MySql\&.Data\&.MySqlClient\&.MySqlError\&.Code\fC [get]\fP"

.PP
Error code 
.PP
Definition at line 57 of file MySqlError\&.cs\&.
.SS "string MySql\&.Data\&.MySqlClient\&.MySqlError\&.Level\fC [get]\fP"

.PP
Error level 
.PP
Definition at line 49 of file MySqlError\&.cs\&.
.SS "string MySql\&.Data\&.MySqlClient\&.MySqlError\&.Message\fC [get]\fP"

.PP
Error message 
.PP
Definition at line 65 of file MySqlError\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
