.TH "MySql.Data.MySqlClient.GenericConfigurationElementCollection< T >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.GenericConfigurationElementCollection< T > \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits ConfigurationElementCollection, and IEnumerable< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new IEnumerator< T > \fBGetEnumerator\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override ConfigurationElement \fBCreateNewElement\fP ()"
.br
.ti -1c
.RI "override object \fBGetElementKey\fP (ConfigurationElement element)"
.br
.in -1c
.SH "Detailed Description"
.PP 



.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIConfigurationElement\fP
.TP
\fIT\fP : \fInew()\fP
.PP
Definition at line 108 of file MySqlConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
