.TH "MySql.Data.MySqlClient.Authentication.SecHandle" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.Authentication.SecHandle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBdwLower\fP"
.br
.ti -1c
.RI "IntPtr \fBdwUpper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 353 of file WindowsAuthenticationPlugin\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
