.TH "MySql.Data.MySqlClient.Authentication.SECURITY_HANDLE" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.Authentication.SECURITY_HANDLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSECURITY_HANDLE\fP (int dummy)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBLowPart\fP"
.br
.ti -1c
.RI "IntPtr \fBHighPart\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 413 of file WindowsAuthenticationPlugin\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
