.TH "MySql.Data.MySqlClient.MySqlRowUpdatingEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Data.MySqlClient.MySqlRowUpdatingEventArgs \- 
.PP
Provides data for the RowUpdating event\&. This class cannot be inherited\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits RowUpdatingEventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMySqlRowUpdatingEventArgs\fP (DataRow row, IDbCommand command, StatementType statementType, DataTableMapping tableMapping)"
.br
.RI "\fIInitializes a new instance of the \fBMySqlRowUpdatingEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "new \fBMySqlCommand\fP \fBCommand\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the \fBMySqlCommand\fP to execute when performing the Update\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides data for the RowUpdating event\&. This class cannot be inherited\&. 


.PP
Definition at line 328 of file dataadapter\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MySql\&.Data\&.MySqlClient\&.MySqlRowUpdatingEventArgs\&.MySqlRowUpdatingEventArgs (DataRowrow, IDbCommandcommand, StatementTypestatementType, DataTableMappingtableMapping)"

.PP
Initializes a new instance of the \fBMySqlRowUpdatingEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrow\fP The DataRow to DbDataAdapter\&.Update(DataSet)\&.
.br
\fIcommand\fP The IDbCommand to execute during DbDataAdapter\&.Update(DataSet)\&.
.br
\fIstatementType\fP One of the StatementType values that specifies the type of query executed\&.
.br
\fItableMapping\fP The DataTableMapping sent through an DbDataAdapter\&.Update(DataSet)\&.
.RE
.PP

.PP
Definition at line 338 of file dataadapter\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "new \fBMySqlCommand\fP MySql\&.Data\&.MySqlClient\&.MySqlRowUpdatingEventArgs\&.Command\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the \fBMySqlCommand\fP to execute when performing the Update\&. 
.PP
Definition at line 347 of file dataadapter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
