.TH "MySql.Web.SessionState" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySql.Web.SessionState \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMySqlSessionStateStore\fP"
.br
.RI "\fIThis class allows ASP\&.NET applications to store and manage session state information in a MySQL database\&. Expired session data is periodically deleted from the database\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
