.TH "Newtonsoft.Json.Linq.IJEnumerable< out T >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Linq.IJEnumerable< out T > \- 
.PP
Represents a collection of \fBJToken\fP objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEnumerable< T >\&.
.PP
Inherited by \fBNewtonsoft\&.Json\&.Linq\&.JEnumerable< T >\fP, and \fBNewtonsoft\&.Json\&.Linq\&.JToken\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IJEnumerable< \fBJToken\fP > \fBthis[object key]\fP\fC [get]\fP"
.br
.RI "\fIGets the IJEnumerable{JToken} with the specified key\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a collection of \fBJToken\fP objects\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP The type of token
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBJToken\fP\fP
.PP
Definition at line 34 of file IJEnumerable\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IJEnumerable<\fBJToken\fP> Newtonsoft\&.Json\&.Linq\&.IJEnumerable< out T >\&.this[object key]\fC [get]\fP"

.PP
Gets the IJEnumerable{JToken} with the specified key\&. 
.PP
Definition at line 44 of file IJEnumerable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
