.TH "Newtonsoft.Json.Serialization.JsonISerializableContract" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.JsonISerializableContract \- 
.PP
Contract details for a Type used by the \fBJsonSerializer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Serialization\&.JsonContainerContract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonISerializableContract\fP (Type underlyingType)"
.br
.RI "\fIInitializes a new instance of the \fBJsonISerializableContract\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ObjectConstructor< object > \fBISerializableCreator\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the ISerializable object constructor\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contract details for a Type used by the \fBJsonSerializer\fP\&. 


.PP
Definition at line 34 of file JsonISerializableContract\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.Serialization\&.JsonISerializableContract\&.JsonISerializableContract (TypeunderlyingType)"

.PP
Initializes a new instance of the \fBJsonISerializableContract\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIunderlyingType\fP The underlying type for the contract\&.
.RE
.PP

.PP
Definition at line 46 of file JsonISerializableContract\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "ObjectConstructor<object> Newtonsoft\&.Json\&.Serialization\&.JsonISerializableContract\&.ISerializableCreator\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the ISerializable object constructor\&. The ISerializable object constructor\&.
.PP
Definition at line 40 of file JsonISerializableContract\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
