.TH "Newtonsoft.Json.Serialization.JsonStringContract" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.JsonStringContract \- 
.PP
Contract details for a Type used by the \fBJsonSerializer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Serialization\&.JsonPrimitiveContract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonStringContract\fP (Type underlyingType)"
.br
.RI "\fIInitializes a new instance of the \fBJsonStringContract\fP class\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Contract details for a Type used by the \fBJsonSerializer\fP\&. 


.PP
Definition at line 33 of file JsonStringContract\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.Serialization\&.JsonStringContract\&.JsonStringContract (TypeunderlyingType)"

.PP
Initializes a new instance of the \fBJsonStringContract\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIunderlyingType\fP The underlying type for the contract\&.
.RE
.PP

.PP
Definition at line 39 of file JsonStringContract\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
