.TH "Newtonsoft.Json.Serialization.ITraceWriter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.ITraceWriter \- 
.PP
Represents a trace writer\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNewtonsoft\&.Json\&.Serialization\&.DiagnosticsTraceWriter\fP, and \fBNewtonsoft\&.Json\&.Serialization\&.MemoryTraceWriter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTrace\fP (TraceLevel level, string message, Exception ex)"
.br
.RI "\fIWrites the specified trace level, message and optional exception\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TraceLevel \fBLevelFilter\fP\fC [get]\fP"
.br
.RI "\fIGets the TraceLevel that will be used to filter the trace messages passed to the writer\&. For example a filter level of \fP"
.in -1c
.SH "Detailed Description"
.PP 
Represents a trace writer\&. 


.PP
Definition at line 9 of file ITraceWriter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void Newtonsoft\&.Json\&.Serialization\&.ITraceWriter\&.Trace (TraceLevellevel, stringmessage, Exceptionex)"

.PP
Writes the specified trace level, message and optional exception\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP The TraceLevel at which to write this trace\&.
.br
\fImessage\fP The trace message\&.
.br
\fIex\fP The trace exception\&. This parameter is optional\&.
.RE
.PP

.PP
Implemented in \fBNewtonsoft\&.Json\&.Serialization\&.DiagnosticsTraceWriter\fP, and \fBNewtonsoft\&.Json\&.Serialization\&.MemoryTraceWriter\fP\&.
.SH "Property Documentation"
.PP 
.SS "TraceLevel Newtonsoft\&.Json\&.Serialization\&.ITraceWriter\&.LevelFilter\fC [get]\fP"

.PP
Gets the TraceLevel that will be used to filter the trace messages passed to the writer\&. For example a filter level of \fCInfo\fP will exclude \fCVerbose\fP messages and include \fCInfo\fP, \fCWarning\fP and \fCError\fP messages\&. 
.PP
The TraceLevel that will be used to filter the trace messages passed to the writer\&.
.PP
Definition at line 17 of file ITraceWriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
