.TH "Newtonsoft.Json.Serialization.JsonObjectContract" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Serialization.JsonObjectContract \- 
.PP
Contract details for a Type used by the \fBJsonSerializer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Serialization\&.JsonContainerContract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonObjectContract\fP (Type underlyingType)"
.br
.RI "\fIInitializes a new instance of the \fBJsonObjectContract\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMemberSerialization\fP \fBMemberSerialization\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the object member serialization\&. \fP"
.ti -1c
.RI "\fBRequired\fP \fBItemRequired\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets a value that indicates whether the object's properties are required\&. \fP"
.ti -1c
.RI "\fBJsonPropertyCollection\fP \fBProperties\fP\fC [get, set]\fP"
.br
.RI "\fIGets the object's properties\&. \fP"
.ti -1c
.RI "\fBJsonPropertyCollection\fP \fBConstructorParameters\fP\fC [get, set]\fP"
.br
.RI "\fIGets the constructor parameters required for any non-default constructor \fP"
.ti -1c
.RI "ConstructorInfo \fBOverrideConstructor\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the override constructor used to create the object\&. This is set when a constructor is marked up using the JsonConstructor attribute\&. \fP"
.ti -1c
.RI "ConstructorInfo \fBParametrizedConstructor\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the parametrized constructor used to create the object\&. \fP"
.ti -1c
.RI "ExtensionDataSetter \fBExtensionDataSetter\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the extension data setter\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Contract details for a Type used by the \fBJsonSerializer\fP\&. 


.PP
Definition at line 38 of file JsonObjectContract\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.JsonObjectContract (TypeunderlyingType)"

.PP
Initializes a new instance of the \fBJsonObjectContract\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIunderlyingType\fP The underlying type for the contract\&.
.RE
.PP

.PP
Definition at line 118 of file JsonObjectContract\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBJsonPropertyCollection\fP Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.ConstructorParameters\fC [get]\fP, \fC [set]\fP"

.PP
Gets the constructor parameters required for any non-default constructor 
.PP
Definition at line 63 of file JsonObjectContract\&.cs\&.
.SS "ExtensionDataSetter Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.ExtensionDataSetter\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the extension data setter\&. 
.PP
Definition at line 82 of file JsonObjectContract\&.cs\&.
.SS "\fBRequired\fP Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.ItemRequired\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value that indicates whether the object's properties are required\&. A value indicating whether the object's properties are required\&. 
.PP
Definition at line 52 of file JsonObjectContract\&.cs\&.
.SS "\fBMemberSerialization\fP Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.MemberSerialization\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the object member serialization\&. The member object serialization\&.
.PP
Definition at line 44 of file JsonObjectContract\&.cs\&.
.SS "ConstructorInfo Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.OverrideConstructor\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the override constructor used to create the object\&. This is set when a constructor is marked up using the JsonConstructor attribute\&. The override constructor\&.
.PP
Definition at line 71 of file JsonObjectContract\&.cs\&.
.SS "ConstructorInfo Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.ParametrizedConstructor\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the parametrized constructor used to create the object\&. The parametrized constructor\&.
.PP
Definition at line 77 of file JsonObjectContract\&.cs\&.
.SS "\fBJsonPropertyCollection\fP Newtonsoft\&.Json\&.Serialization\&.JsonObjectContract\&.Properties\fC [get]\fP, \fC [set]\fP"

.PP
Gets the object's properties\&. The object's properties\&.
.PP
Definition at line 58 of file JsonObjectContract\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
