.TH "Newtonsoft.Json.Converters.IsoDateTimeConverter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Newtonsoft.Json.Converters.IsoDateTimeConverter \- 
.PP
Converts a \fBDateTime\fP to and from the ISO 8601 date format (e\&.g\&. 2008-04-12T12:53Z)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNewtonsoft\&.Json\&.Converters\&.DateTimeConverterBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWriteJson\fP (\fBJsonWriter\fP writer, object value, \fBJsonSerializer\fP serializer)"
.br
.RI "\fIWrites the JSON representation of the object\&. \fP"
.ti -1c
.RI "override object \fBReadJson\fP (\fBJsonReader\fP reader, Type objectType, object existingValue, \fBJsonSerializer\fP serializer)"
.br
.RI "\fIReads the JSON representation of the object\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTimeStyles \fBDateTimeStyles\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the date time styles used when converting a date to and from JSON\&. \fP"
.ti -1c
.RI "string \fBDateTimeFormat\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the date time format used when converting a date to and from JSON\&. \fP"
.ti -1c
.RI "CultureInfo \fBCulture\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the culture used when converting a date to and from JSON\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Converts a \fBDateTime\fP to and from the ISO 8601 date format (e\&.g\&. 2008-04-12T12:53Z)\&. 


.PP
Definition at line 35 of file IsoDateTimeConverter\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object Newtonsoft\&.Json\&.Converters\&.IsoDateTimeConverter\&.ReadJson (\fBJsonReader\fPreader, TypeobjectType, objectexistingValue, \fBJsonSerializer\fPserializer)\fC [virtual]\fP"

.PP
Reads the JSON representation of the object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIreader\fP The \fBJsonReader\fP to read from\&.
.br
\fIobjectType\fP Type of the object\&.
.br
\fIexistingValue\fP The existing value of object being read\&.
.br
\fIserializer\fP The calling serializer\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The object value\&.
.RE
.PP

.PP
Implements \fBNewtonsoft\&.Json\&.JsonConverter\fP\&.
.PP
Definition at line 120 of file IsoDateTimeConverter\&.cs\&.
.SS "override void Newtonsoft\&.Json\&.Converters\&.IsoDateTimeConverter\&.WriteJson (\fBJsonWriter\fPwriter, objectvalue, \fBJsonSerializer\fPserializer)\fC [virtual]\fP"

.PP
Writes the JSON representation of the object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwriter\fP The \fBJsonWriter\fP to write to\&.
.br
\fIvalue\fP The value\&.
.br
\fIserializer\fP The calling serializer\&.
.RE
.PP

.PP
Implements \fBNewtonsoft\&.Json\&.JsonConverter\fP\&.
.PP
Definition at line 79 of file IsoDateTimeConverter\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "CultureInfo Newtonsoft\&.Json\&.Converters\&.IsoDateTimeConverter\&.Culture\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the culture used when converting a date to and from JSON\&. The culture used when converting a date to and from JSON\&.
.PP
Definition at line 68 of file IsoDateTimeConverter\&.cs\&.
.SS "string Newtonsoft\&.Json\&.Converters\&.IsoDateTimeConverter\&.DateTimeFormat\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the date time format used when converting a date to and from JSON\&. The date time format used when converting a date to and from JSON\&.
.PP
Definition at line 58 of file IsoDateTimeConverter\&.cs\&.
.SS "DateTimeStyles Newtonsoft\&.Json\&.Converters\&.IsoDateTimeConverter\&.DateTimeStyles\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the date time styles used when converting a date to and from JSON\&. The date time styles used when converting a date to and from JSON\&.
.PP
Definition at line 48 of file IsoDateTimeConverter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
