.TH "NHibernate.Collection.PersistentMap.ClearDelayedOperation" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Collection.PersistentMap.ClearDelayedOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Collection\&.AbstractPersistentCollection\&.IDelayedOperation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClearDelayedOperation\fP (\fBPersistentMap\fP enclosingInstance)"
.br
.ti -1c
.RI "void \fBOperate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBAddedInstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "object \fBOrphan\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 415 of file PersistentMap\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
