.TH "NHibernate.Test.NHSpecificTest.NH1291AnonExample.NH1291AnonExampleFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1291AnonExample.NH1291AnonExampleFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.BugTestCase\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHomeAnon\fP"
.br
.ti -1c
.RI "class \fBPersonIQAnon\fP"
.br
.ti -1c
.RI "class \fBPersonNameAnon\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCanCreateAnonExampleForInt\fP ()"
.br
.ti -1c
.RI "void \fBCanCreateAnonExampleForStringLikeCompare\fP ()"
.br
.ti -1c
.RI "void \fBCanQueryUsingSavedRelations\fP ()"
.br
.ti -1c
.RI "void \fBCanQueryUsingAnonRelations\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBBugNumber\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file NH1291AnonExampleFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
