.TH "NHibernate.Proxy.DefaultLazyInitializer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Proxy.DefaultLazyInitializer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Proxy\&.Poco\&.BasicLazyInitializer\fP, and \fBNHibernate\&.Proxy\&.DynamicProxy\&.IInterceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultLazyInitializer\fP (string entityName, System\&.Type persistentClass, object id, MethodInfo getIdentifierMethod, MethodInfo setIdentifierMethod, \fBIAbstractComponentType\fP componentIdType, \fBISessionImplementor\fP session)"
.br
.ti -1c
.RI "object \fBIntercept\fP (\fBInvocationInfo\fP info)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file DefaultLazyInitializer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
