.TH "NHibernate.Test.NHSpecificTest.NH1694.Orders" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1694.Orders \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBStatus\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBUser\fP \fBUser\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
