.TH "NHibernate.Mapping.ByCode.IPlainPropertyContainerMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IPlainPropertyContainerMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IBasePlainPropertyContainerMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.IPropertyContainerMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOneToOne\fP (MemberInfo property, Action< \fBIOneToOneMapper\fP > mapping)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file IPlainPropertyContainerMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
