.TH "NHibernate.Test.ConnectionTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ConnectionTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAggressiveReleaseTest\fP"
.br
.ti -1c
.RI "class \fBConnectionManagementTestCase\fP"
.br
.ti -1c
.RI "class \fBOther\fP"
.br
.ti -1c
.RI "class \fBSilly\fP"
.br
.ti -1c
.RI "class \fBThreadLocalCurrentSessionTest\fP"
.br
.ti -1c
.RI "class \fBTestableThreadLocalContext\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
