.TH "NHibernate.Test.Criteria.Animal" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.Animal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.Criteria\&.Reptile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimal\fP (string description, float bodyWeight)"
.br
.ti -1c
.RI "virtual void \fBAddOffspring\fP (\fBAnimal\fP offspring)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual float \fBBodyWeight\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBAnimal\fP > \fBOffspring\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBAnimal\fP \fBMother\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBAnimal\fP \fBFather\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBSerialNumber\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBHowHappyIsHe\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Animal\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
