.TH "NHibernate.Event.AbstractPostDatabaseOperationEvent" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.AbstractPostDatabaseOperationEvent \- 
.PP
Represents an operation we performed against the database\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.AbstractEvent\fP, and \fBNHibernate\&.Event\&.IPostDatabaseOperationEventArgs\fP\&.
.PP
Inherited by \fBNHibernate\&.Event\&.PostDeleteEvent\fP, \fBNHibernate\&.Event\&.PostInsertEvent\fP, and \fBNHibernate\&.Event\&.PostUpdateEvent\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractPostDatabaseOperationEvent\fP (\fBIEventSource\fP source, object entity, object id, \fBIEntityPersister\fP persister)"
.br
.RI "\fIConstructs an event containing the pertinent information\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBEntity\fP\fC [get, set]\fP"
.br
.RI "\fIThe entity involved in the database operation\&. \fP"
.ti -1c
.RI "object \fBId\fP\fC [get, set]\fP"
.br
.RI "\fIThe id to be used in the database operation\&. \fP"
.ti -1c
.RI "\fBIEntityPersister\fP \fBPersister\fP\fC [get, set]\fP"
.br
.RI "\fIThe persister for the \fBEntity\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents an operation we performed against the database\&. 


.PP
Definition at line 10 of file AbstractPostDatabaseOperationEvent\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Event\&.AbstractPostDatabaseOperationEvent\&.AbstractPostDatabaseOperationEvent (\fBIEventSource\fPsource, objectentity, objectid, \fBIEntityPersister\fPpersister)\fC [protected]\fP"

.PP
Constructs an event containing the pertinent information\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsource\fP The session from which the event originated\&. 
.br
\fIentity\fP The entity to be invloved in the database operation\&. 
.br
\fIid\fP The entity id to be invloved in the database operation\&. 
.br
\fIpersister\fP The entity's persister\&. 
.RE
.PP

.PP
Definition at line 17 of file AbstractPostDatabaseOperationEvent\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "object NHibernate\&.Event\&.AbstractPostDatabaseOperationEvent\&.Entity\fC [get]\fP, \fC [set]\fP"

.PP
The entity involved in the database operation\&. 
.PP
Definition at line 26 of file AbstractPostDatabaseOperationEvent\&.cs\&.
.SS "object NHibernate\&.Event\&.AbstractPostDatabaseOperationEvent\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
The id to be used in the database operation\&. 
.PP
Definition at line 29 of file AbstractPostDatabaseOperationEvent\&.cs\&.
.SS "\fBIEntityPersister\fP NHibernate\&.Event\&.AbstractPostDatabaseOperationEvent\&.Persister\fC [get]\fP, \fC [set]\fP"

.PP
The persister for the \fBEntity\fP\&. 
.PP
Definition at line 34 of file AbstractPostDatabaseOperationEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
