.TH "NHibernate.Util.ParserException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Util.ParserException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParserException\fP (string message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file TypeNameParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
