.TH "NHibernate.Test.Component.Basic.Person" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Component.Basic.Person \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP (String name, DateTime dob, String address)"
.br
.ti -1c
.RI "virtual void \fBChangeAddress\fP (String add)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DateTime \fBDob\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBCurrentAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBPreviousAddress\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual int \fBYob\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual double \fBHeightInches\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Person\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
