.TH "NHibernate.Collection.AbstractPersistentCollection.IDelayedOperation" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Collection.AbstractPersistentCollection.IDelayedOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Collection\&.PersistentBag\&.ClearDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentBag\&.SimpleAddDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.AddDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.ClearDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.RemoveDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.SetDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.SimpleAddDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentList\&.SimpleRemoveDelayedOperation\fP, \fBNHibernate\&.Collection\&.PersistentMap\&.ClearDelayedOperation\fP, and \fBNHibernate\&.Collection\&.PersistentMap\&.PutDelayedOperation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOperate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object \fBAddedInstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "object \fBOrphan\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file AbstractPersistentCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
