.TH "NHibernate.Cfg.MappingSchema.HbmVersion" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmVersion \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.AbstractDecoratable\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IColumnsMapping\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmMeta\fP[] \fBmeta\fP"
.br
.ti -1c
.RI "\fBHbmColumn\fP[] \fBcolumn\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBnode\fP"
.br
.ti -1c
.RI "string \fBaccess\fP"
.br
.ti -1c
.RI "string \fBcolumn1\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBunsavedvalue\fP"
.br
.ti -1c
.RI "\fBHbmVersionGeneration\fP \fBgenerated\fP"
.br
.ti -1c
.RI "bool \fBinsert\fP"
.br
.ti -1c
.RI "bool \fBinsertSpecified\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBHbmMeta\fP[] \fBMetadatas\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHbmColumn\fP > \fBColumns\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 3675 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
