.TH "NHibernate.Test.NHSpecificTest.EmptyMappingsFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.EmptyMappingsFixture \- 
.PP
This fixture contains no mappings, it is thus faster and can be used to run tests for basic features that don't require any mapping files to function\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBeginWithIsolationLevel\fP ()"
.br
.ti -1c
.RI "void \fBReconnectAfterClose\fP ()"
.br
.ti -1c
.RI "void \fBInvalidQuery\fP ()"
.br
.ti -1c
.RI "void \fBNullInterceptor\fP ()"
.br
.ti -1c
.RI "void \fBDisconnectShouldNotCloseUserSuppliedConnection\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This fixture contains no mappings, it is thus faster and can be used to run tests for basic features that don't require any mapping files to function\&. 


.PP
Definition at line 15 of file EmptyMappingsFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
