.TH "NHibernate.Proxy.DynamicProxy.IProxyAssemblyBuilder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Proxy.DynamicProxy.IProxyAssemblyBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Proxy\&.DynamicProxy\&.DefaultProxyAssemblyBuilder\fP, and \fBNHibernate\&.Test\&.DynamicProxyTests\&.PeVerifyFixture\&.SavingProxyAssemblyBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "AssemblyBuilder \fBDefineDynamicAssembly\fP (AppDomain appDomain, AssemblyName name)"
.br
.ti -1c
.RI "ModuleBuilder \fBDefineDynamicModule\fP (AssemblyBuilder assemblyBuilder, string moduleName)"
.br
.ti -1c
.RI "void \fBSave\fP (AssemblyBuilder assemblyBuilder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file IProxyAssemblyBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
