.TH "NHibernate.Test.NHSpecificTest.NH2280.OrganisationCode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2280.OrganisationCode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual DateTime \fBStartDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBCode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBOrganisationCodeKey\fP \fBKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBOrganisation\fP \fBOrganisation\fP\fC [get, set]\fP"
.br
.RI "\fINeed comments for intellisense\&. \fP"
.ti -1c
.RI "virtual DateTime \fBEndDate\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file OrganisationCode\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual \fBOrganisation\fP NHibernate\&.Test\&.NHSpecificTest\&.NH2280\&.OrganisationCode\&.Organisation\fC [get]\fP, \fC [set]\fP"

.PP
Need comments for intellisense\&. 
.PP
Definition at line 34 of file OrganisationCode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
