.TH "NHibernate.Test.DynamicProxyTests.PeVerifyFixture.ClassWithPrivateDefaultConstructor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicProxyTests.PeVerifyFixture.ClassWithPrivateDefaultConstructor \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 95 of file PeVerifyFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
