.TH "NHibernate.Test.MappingByCode.NatureDemo.Naturalness.Lizard" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.NatureDemo.Naturalness.Lizard \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.MappingByCode\&.NatureDemo\&.Naturalness\&.Reptile\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file Reptile\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
