.TH "NHibernate.Param.DynamicFilterParameterSpecification" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Param.DynamicFilterParameterSpecification \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Param\&.IParameterSpecification\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamicFilterParameterSpecification\fP (string filterName, string parameterName, \fBIType\fP expectedDefinedType, int?collectionSpan)"
.br
.RI "\fIConstructs a parameter specification for a particular filter parameter\&. \fP"
.ti -1c
.RI "void \fBBind\fP (IDbCommand command, IList< \fBParameter\fP > sqlQueryParametersList, \fBQueryParameters\fP queryParameters, \fBISessionImplementor\fP session)"
.br
.RI "\fIBind the appropriate value into the given command\&. \fP"
.ti -1c
.RI "void \fBBind\fP (IDbCommand command, IList< \fBParameter\fP > multiSqlQueryParametersList, int singleSqlParametersOffset, IList< \fBParameter\fP > sqlQueryParametersList, \fBQueryParameters\fP queryParameters, \fBISessionImplementor\fP session)"
.br
.RI "\fIBind the appropriate value into the given command\&. \fP"
.ti -1c
.RI "string \fBRenderDisplayInfo\fP ()"
.br
.RI "\fIRender this parameter into displayable info (for logging, etc)\&. \fP"
.ti -1c
.RI "IEnumerable< string > \fBGetIdsForBackTrack\fP (\fBIMapping\fP sessionFactory)"
.br
.RI "\fIAn string array to unique identify this parameter-span inside an \fBNHibernate\&.SqlCommand\&.SqlString\fP\&. \fP"
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBDynamicFilterParameterSpecification\fP other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFilterParameterFullName\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIType\fP \fBElementType\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIType\fP \fBExpectedType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file DynamicFilterParameterSpecification\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Param\&.DynamicFilterParameterSpecification\&.DynamicFilterParameterSpecification (stringfilterName, stringparameterName, \fBIType\fPexpectedDefinedType, int?collectionSpan)"

.PP
Constructs a parameter specification for a particular filter parameter\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilterName\fP The name of the filter
.br
\fIparameterName\fP The name of the parameter
.br
\fIexpectedDefinedType\fP The paremeter type specified on the filter metadata
.br
\fIcollectionSpan\fP 
.RE
.PP

.PP
Definition at line 29 of file DynamicFilterParameterSpecification\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Param\&.DynamicFilterParameterSpecification\&.Bind (IDbCommandcommand, IList< \fBParameter\fP >sqlQueryParametersList, \fBQueryParameters\fPqueryParameters, \fBISessionImplementor\fPsession)"

.PP
Bind the appropriate value into the given command\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP The command into which the value should be bound\&.
.br
\fIsqlQueryParametersList\fP The list of Sql query parameter in the exact sequence they are present in the query\&.
.br
\fIqueryParameters\fP The defined values for the current query execution\&.
.br
\fIsession\fP The session against which the current execution is occuring\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Param\&.IParameterSpecification\fP\&.
.PP
Definition at line 38 of file DynamicFilterParameterSpecification\&.cs\&.
.SS "void NHibernate\&.Param\&.DynamicFilterParameterSpecification\&.Bind (IDbCommandcommand, IList< \fBParameter\fP >multiSqlQueryParametersList, intsingleSqlParametersOffset, IList< \fBParameter\fP >sqlQueryParametersList, \fBQueryParameters\fPqueryParameters, \fBISessionImplementor\fPsession)"

.PP
Bind the appropriate value into the given command\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcommand\fP The command into which the value should be bound\&.
.br
\fImultiSqlQueryParametersList\fP The parameter-list of the whole query of the command\&.
.br
\fIsingleSqlParametersOffset\fP The offset from where start the list of IDataParameter in the given \fIcommand\fP  for the query where this \fBIParameterSpecification\fP was used\&. 
.br
\fIsqlQueryParametersList\fP The list of Sql query parameter in the exact sequence they are present in the query where this \fBIParameterSpecification\fP was used\&.
.br
\fIqueryParameters\fP The defined values for the query where this \fBIParameterSpecification\fP was used\&.
.br
\fIsession\fP The session against which the current execution is occuring\&.
.RE
.PP
.PP
Suppose the \fIcommand\fP  is composed by two queries\&. The \fIsingleSqlParametersOffset\fP  for the first query is zero\&. If the first query in \fIcommand\fP  has 12 parameters (size of its SqlType array) the offset to bind all \fBIParameterSpecification\fPs of the second query in the \fIcommand\fP  is 12 (for the first query we are using from 0 to 11)\&. 
.PP
Implements \fBNHibernate\&.Param\&.IParameterSpecification\fP\&.
.PP
Definition at line 43 of file DynamicFilterParameterSpecification\&.cs\&.
.SS "IEnumerable<string> NHibernate\&.Param\&.DynamicFilterParameterSpecification\&.GetIdsForBackTrack (\fBIMapping\fPsessionFactory)"

.PP
An string array to unique identify this parameter-span inside an \fBNHibernate\&.SqlCommand\&.SqlString\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsessionFactory\fP The session-factory (used only because required by IType)\&.
.RE
.PP
.PP
The each id-for-backtrack is supposed to be unique in the context of a query\&. 
.PP
The number of elements returned depend on the column-span of the ExpectedType\&. 
.PP
Implements \fBNHibernate\&.Param\&.IParameterSpecification\fP\&.
.PP
Definition at line 76 of file DynamicFilterParameterSpecification\&.cs\&.
.SS "string NHibernate\&.Param\&.DynamicFilterParameterSpecification\&.RenderDisplayInfo ()"

.PP
Render this parameter into displayable info (for logging, etc)\&. 
.PP
\fBReturns:\fP
.RS 4
The displayable info
.RE
.PP

.PP
Implements \fBNHibernate\&.Param\&.IParameterSpecification\fP\&.
.PP
Definition at line 71 of file DynamicFilterParameterSpecification\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
