.TH "NHibernate.Linq.Visitors.NameGenerator" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Visitors.NameGenerator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameGenerator\fP (QueryModel model)"
.br
.ti -1c
.RI "string \fBGetNewName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file NameGenerator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
