.TH "NHibernate.Test.MappingByCode.MappersTests.ClassMapperTests.ComponetAsIdTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests.ClassMapperTests.ComponetAsIdTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenClassWithComponentIdThenTheIdIsConpositeId\fP ()"
.br
.ti -1c
.RI "void \fBWhenComponentIdCustomizedMoreThanOnceThenMerge\fP ()"
.br
.ti -1c
.RI "void \fBWhenMapExternalMemberAsComponentIdThenThrows\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file ComponetAsIdTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
