.TH "NHibernate.Test.Legacy.MultiTableTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Legacy.MultiTableTest \- 
.PP
Summary description for \fBMultiTableTest\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFetchManyToOne\fP ()"
.br
.ti -1c
.RI "void \fBJoins\fP ()"
.br
.ti -1c
.RI "void \fBJoinOpenBug\fP ()"
.br
.ti -1c
.RI "void \fBSubclassCollection\fP ()"
.br
.ti -1c
.RI "void \fBCollectionOnly\fP ()"
.br
.ti -1c
.RI "void \fBQueries\fP ()"
.br
.ti -1c
.RI "void \fBConstraints\fP ()"
.br
.ti -1c
.RI "void \fBMultiTable\fP ()"
.br
.ti -1c
.RI "void \fBMultiTableGeneratedId\fP ()"
.br
.ti -1c
.RI "void \fBMultiTableCollections\fP ()"
.br
.ti -1c
.RI "void \fBMultiTableManyToOne\fP ()"
.br
.ti -1c
.RI "void \fBMultiTableNativeId\fP ()"
.br
.ti -1c
.RI "void \fBCollection\fP ()"
.br
.ti -1c
.RI "void \fBOneToOne\fP ()"
.br
.ti -1c
.RI "void \fBCollectionPointer\fP ()"
.br
.ti -1c
.RI "void \fBDynamicUpdate\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Summary description for \fBMultiTableTest\fP\&. 


.PP
Definition at line 14 of file MultiTableTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
