.TH "NHibernate.Test.SqlCommandTest.SqlDeleteBuilderFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.SqlCommandTest.SqlDeleteBuilderFixture \- 
.PP
Tests all of the functionallity of the \fBSqlDeleteBuilderFixture\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeleteSqlStringTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests all of the functionallity of the \fBSqlDeleteBuilderFixture\fP 


.PP
Definition at line 15 of file SqlDeleteBuilderFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
