.TH "NHibernate.Cfg.MappingSchema.HbmCompositeElement" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmCompositeElement \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.AbstractDecoratable\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IComponentMapping\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmMeta\fP[] \fBmeta\fP"
.br
.ti -1c
.RI "\fBHbmParent\fP \fBparent\fP"
.br
.ti -1c
.RI "object[] \fBItems\fP"
.br
.ti -1c
.RI "string \fBnode\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmParent\fP \fBParent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBEmbeddedNode\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBHbmMeta\fP[] \fBMetadatas\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable
.br
< \fBIEntityPropertyMapping\fP > \fBProperties\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 595 of file Hbm\&.generated\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "string NHibernate\&.Cfg\&.MappingSchema\&.HbmCompositeElement\&.node"

.PP
Definition at line 613 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
