.TH "NHibernate.Test.MappingExceptions.AddClassFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingExceptions.AddClassFixture \- 
.PP
Summary description for \fBAddClassFixture\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClassMissingMappingFile\fP ()"
.br
.ti -1c
.RI "void \fBAddClassNotFound\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBAddClassFixture\fP\&. 


.PP
Definition at line 11 of file AddClassFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
