.TH "NHibernate.Mapping.IndexedCollection" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.IndexedCollection \- 
.PP
Indexed collections include IList, IDictionary, Arrays and primitive Arrays\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.Collection\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.List\fP, and \fBNHibernate\&.Mapping\&.Map\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCreatePrimaryKey\fP ()"
.br
.ti -1c
.RI "override void \fBValidate\fP (\fBIMapping\fP mapping)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBDefaultIndexColumnName\fP = 'idx'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexedCollection\fP (\fBPersistentClass\fP owner)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSimpleValue\fP \fBIndex\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "override bool \fBIsIndexed\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsList\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBIndexNodeName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Indexed collections include IList, IDictionary, Arrays and primitive Arrays\&. 


.PP
Definition at line 12 of file IndexedCollection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
