.TH "NHibernate.Mapping.ByCode.IPlainPropertyContainerMapper< TContainer >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IPlainPropertyContainerMapper< TContainer > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IBasePlainPropertyContainerMapper< TContainer >\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.IPropertyContainerMapper< TEntity >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOneToOne< TProperty >\fP (Expression< Func< TContainer, TProperty >> property, Action< \fBIOneToOneMapper\fP > mapping)"
.br
.ti -1c
.RI "void \fBOneToOne< TProperty >\fP (string notVisiblePropertyOrFieldName, Action< \fBIOneToOneMapper\fP > mapping)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file IPlainPropertyContainerMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
