.TH "NHibernate.Test.Linq.PagingTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.PagingTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPageBetweenProjections\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningNestedAnonymous\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningNestedClass\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningOrderedNestedAnonymous\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningOrderedNestedClass\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningOrderedConstrainedNestedAnonymous\fP ()"
.br
.ti -1c
.RI "void \fBPageBetweenProjectionsReturningOrderedConstrainedNestedClass\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseOrderedNestedAnonymous\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseOrderedNestedAnonymousEquivalent\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseOrderedNestedClass\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseOrderedNestedClassEquivalent\fP ()"
.br
.ti -1c
.RI "void \fBCustomers1to5\fP ()"
.br
.ti -1c
.RI "void \fBCustomers11to20\fP ()"
.br
.ti -1c
.RI "void \fBCustomers11to20And21to30ShouldNoCacheQuery\fP ()"
.br
.ti -1c
.RI "void \fBCustomersChainedTake\fP ()"
.br
.ti -1c
.RI "void \fBCustomersChainedSkip\fP ()"
.br
.ti -1c
.RI "void \fBCountAfterTakeShouldReportTheCorrectNumber\fP ()"
.br
.ti -1c
.RI "void \fBOrderedPagedProductsWithOuterProjection\fP ()"
.br
.ti -1c
.RI "void \fBOrderedPagedProductsWithInnerProjection\fP ()"
.br
.ti -1c
.RI "void \fBDescendingOrderedPagedProductsWithOuterProjection\fP ()"
.br
.ti -1c
.RI "void \fBDescendingOrderedPagedProductsWithInnerProjection\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClause\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseResort\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithInnerAndOuterWhereClauses\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseEquivalent\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseAndProjection\fP ()"
.br
.ti -1c
.RI "void \fBPagedProductsWithOuterWhereClauseAndComplexProjection\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file PagingTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
