.TH "NHibernate.Criterion.GtPropertyExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.GtPropertyExpression \- 
.PP
An \fBICriterion\fP that represents an 'greater than' constraint between two properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.PropertyExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGtPropertyExpression\fP (string lhsPropertyName, \fBIProjection\fP rhsProjection)"
.br
.RI "\fIInitializes a new instance of the \fBGtPropertyExpression\fP class\&. \fP"
.ti -1c
.RI "\fBGtPropertyExpression\fP (\fBIProjection\fP lhsProjection, \fBIProjection\fP rhsProjection)"
.br
.RI "\fIInitializes a new instance of the \fBGtPropertyExpression\fP class\&. \fP"
.ti -1c
.RI "\fBGtPropertyExpression\fP (\fBIProjection\fP lhsProjection, string rhsPropertyName)"
.br
.RI "\fIInitializes a new instance of the \fBGtPropertyExpression\fP class\&. \fP"
.ti -1c
.RI "\fBGtPropertyExpression\fP (string lhsPropertyName, string rhsPropertyName)"
.br
.RI "\fIInitializes a new instance of the \fBGtPropertyExpression\fP class that compares two mapped properties using an 'greater than' constraint\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBOp\fP\fC [get]\fP"
.br
.RI "\fIGet the Sql operator to use for the \fBLtPropertyExpression\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBICriterion\fP that represents an 'greater than' constraint between two properties\&. 


.PP
Definition at line 10 of file GtPropertyExpression\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Criterion\&.GtPropertyExpression\&.GtPropertyExpression (stringlhsPropertyName, \fBIProjection\fPrhsProjection)"

.PP
Initializes a new instance of the \fBGtPropertyExpression\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhsPropertyName\fP Name of the LHS property\&.
.br
\fIrhsProjection\fP The RHS projection\&.
.RE
.PP

.PP
Definition at line 17 of file GtPropertyExpression\&.cs\&.
.SS "NHibernate\&.Criterion\&.GtPropertyExpression\&.GtPropertyExpression (\fBIProjection\fPlhsProjection, \fBIProjection\fPrhsProjection)"

.PP
Initializes a new instance of the \fBGtPropertyExpression\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhsProjection\fP The LHS projection\&.
.br
\fIrhsProjection\fP The RHS projection\&.
.RE
.PP

.PP
Definition at line 26 of file GtPropertyExpression\&.cs\&.
.SS "NHibernate\&.Criterion\&.GtPropertyExpression\&.GtPropertyExpression (\fBIProjection\fPlhsProjection, stringrhsPropertyName)"

.PP
Initializes a new instance of the \fBGtPropertyExpression\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhsProjection\fP The projection\&.
.br
\fIrhsPropertyName\fP Name of the RHS property\&.
.RE
.PP

.PP
Definition at line 35 of file GtPropertyExpression\&.cs\&.
.SS "NHibernate\&.Criterion\&.GtPropertyExpression\&.GtPropertyExpression (stringlhsPropertyName, stringrhsPropertyName)"

.PP
Initializes a new instance of the \fBGtPropertyExpression\fP class that compares two mapped properties using an 'greater than' constraint\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlhsPropertyName\fP The name of the \fBProperty\fP to use as the left hand side\&.
.br
\fIrhsPropertyName\fP The name of the \fBProperty\fP to use as the right hand side\&.
.RE
.PP

.PP
Definition at line 45 of file GtPropertyExpression\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string NHibernate\&.Criterion\&.GtPropertyExpression\&.Op\fC [get]\fP, \fC [protected]\fP"

.PP
Get the Sql operator to use for the \fBLtPropertyExpression\fP\&. The string '<c> &lt; </c>'
.PP
Definition at line 55 of file GtPropertyExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
