.TH "NHibernate.DomainModel.Northwind.Entities.User" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Northwind.Entities.User \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.DomainModel\&.Northwind\&.Entities\&.IUser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP (string name, DateTime registeredAt)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual int \fBInvalidLoginAttempts\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DateTime \fBRegisteredAt\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DateTime \fBLastLoginDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBUserComponent\fP \fBComponent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBRole\fP \fBRole\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual FeatureSet \fBFeatures\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual EnumStoredAsString \fBEnum1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual EnumStoredAsInt32 \fBEnum2\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file User\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
