.TH "NHibernate.Cache.Entry.UnstructuredCacheEntry" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cache.Entry.UnstructuredCacheEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cache\&.Entry\&.ICacheEntryStructure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBStructure\fP (object item)"
.br
.ti -1c
.RI "object \fBDestructure\fP (object map, \fBISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file UnstructuredCacheEntry\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
