.TH "NHibernate.Test.TypesTest.ByteTypeFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.TypesTest.ByteTypeFixture \- 
.PP
The Unit Tests for the ByteType\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TypesTest\&.TypeFixtureBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEquals\fP ()"
.br
.RI "\fIVerify Equals will correctly determine when the property is dirty\&. \fP"
.ti -1c
.RI "void \fBReadWrite\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBTypeName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The Unit Tests for the ByteType\&. 


.PP
Definition at line 11 of file ByteTypeFixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.TypesTest\&.ByteTypeFixture\&.Equals ()"

.PP
Verify Equals will correctly determine when the property is dirty\&. 
.PP
Definition at line 23 of file ByteTypeFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
