.TH "NHibernate.Linq.Visitors.LeftJoinRewriter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Visitors.LeftJoinRewriter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QueryModelVisitorBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBVisitAdditionalFromClause\fP (AdditionalFromClause fromClause, QueryModel queryModel, int index)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBReWrite\fP (QueryModel queryModel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file LeftJoinRewriter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
