.TH "NHibernate.Type.DateType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.DateType \- 
.PP
Maps the Year, Month, and Day of a System\&.DateTime Property to a DbType\&.Date column  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.PrimitiveType\fP, \fBNHibernate\&.Type\&.IIdentifierType\fP, \fBNHibernate\&.Type\&.ILiteralType\fP, and \fBNHibernate\&.UserTypes\&.IParameterizedType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateType\fP ()"
.br
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, int index)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, string name)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override void \fBSet\fP (IDbCommand st, object value, int index)"
.br
.RI "\fIWhen implemented by a class, put the value from the mapped Property into to the IDbCommand\&. \fP"
.ti -1c
.RI "override bool \fBIsEqual\fP (object x, object y)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP (object x, \fBEntityMode\fP entityMode)"
.br
.RI "\fIGet a hashcode, consistent with persistence 'equality'\fP"
.ti -1c
.RI "override string \fBToString\fP (object val)"
.br
.RI "\fIA representation of the value to be embedded in an XML element \fP"
.ti -1c
.RI "override object \fBFromStringValue\fP (string xml)"
.br
.RI "\fIParse the XML representation of an instance \fP"
.ti -1c
.RI "object \fBStringToObject\fP (string xml)"
.br
.RI "\fIWhen implemented by a class, converts the xml string from the mapping file to the \&.NET object\&. \fP"
.ti -1c
.RI "override string \fBObjectToSQLString\fP (object value, \fBDialect\&.Dialect\fP dialect)"
.br
.RI "\fIWhen implemented by a class, return a string representation of the value, suitable for embedding in an SQL statement \fP"
.ti -1c
.RI "void \fBSetParameterValues\fP (IDictionary< string, string > parameters)"
.br
.RI "\fIGets called by Hibernate to pass the configured type parameters to the implementation\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBBaseValueParameterName\fP = 'BaseValue'"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly DateTime \fBBaseDateValue\fP = new DateTime(1753, 01, 01)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBReturnedClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBPrimitiveClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "override object \fBDefaultValue\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Maps the Year, Month, and Day of a System\&.DateTime Property to a DbType\&.Date column 


.PP
Definition at line 14 of file DateType\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Type\&.DateType\&.DateType ()"

.PP

.PP
Definition at line 21 of file DateType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object NHibernate\&.Type\&.DateType\&.FromStringValue (stringxml)\fC [virtual]\fP"

.PP
Parse the XML representation of an instance 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP XML string to parse, guaranteed to be non-empty
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 108 of file DateType\&.cs\&.
.SS "override object NHibernate\&.Type\&.DateType\&.Get (IDataReaderrs, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIindex\fP The index of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 31 of file DateType\&.cs\&.
.SS "override object NHibernate\&.Type\&.DateType\&.Get (IDataReaderrs, stringname)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIname\fP The name of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP
.PP
Most implementors just call the \fBGet(IDataReader, int)\fP overload of this method\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 44 of file DateType\&.cs\&.
.SS "override int NHibernate\&.Type\&.DateType\&.GetHashCode (objectx, \fBEntityMode\fPentityMode)"

.PP
Get a hashcode, consistent with persistence 'equality'
.PP
\fBParameters:\fP
.RS 4
\fIx\fP 
.br
\fIentityMode\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IType\fP\&.
.PP
Definition at line 90 of file DateType\&.cs\&.
.SS "override string NHibernate\&.Type\&.DateType\&.ObjectToSQLString (objectvalue, \fBDialect\&.Dialect\fPdialect)"

.PP
When implemented by a class, return a string representation of the value, suitable for embedding in an SQL statement 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The object to convert to a string for the SQL statement\&.
.br
\fIdialect\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
A string that contains a well formed SQL Statement\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.ILiteralType\fP\&.
.PP
Definition at line 128 of file DateType\&.cs\&.
.SS "override void NHibernate\&.Type\&.DateType\&.Set (IDbCommandcmd, objectvalue, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, put the value from the mapped Property into to the IDbCommand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP The IDbCommand to put the value into\&.
.br
\fIvalue\fP The object that contains the value\&.
.br
\fIindex\fP The index of the IDbDataParameter to start writing the values to\&.
.RE
.PP
.PP
Implementors do not need to handle possibility of null values because this will only be called from \fBNullSafeSet(IDbCommand, object, int)\fP after it has checked for nulls\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 54 of file DateType\&.cs\&.
.SS "void NHibernate\&.Type\&.DateType\&.SetParameterValues (IDictionary< string, string >parameters)"

.PP
Gets called by Hibernate to pass the configured type parameters to the implementation\&. 
.PP
Implements \fBNHibernate\&.UserTypes\&.IParameterizedType\fP\&.
.PP
Definition at line 133 of file DateType\&.cs\&.
.SS "object NHibernate\&.Type\&.DateType\&.StringToObject (stringxml)"

.PP
When implemented by a class, converts the xml string from the mapping file to the \&.NET object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP The value of \fCdiscriminator-value\fP or \fCunsaved-value\fP attribute\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The string converted to the object\&.
.RE
.PP
.PP
This method needs to be able to handle any string\&. It should not just call System\&.Type\&.Parse without verifying that it is a parsable value for the System\&.Type\&. 
.PP
Implements \fBNHibernate\&.Type\&.IIdentifierType\fP\&.
.PP
Definition at line 113 of file DateType\&.cs\&.
.SS "override string NHibernate\&.Type\&.DateType\&.ToString (objectval)\fC [virtual]\fP"

.PP
A representation of the value to be embedded in an XML element 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP The object that contains the values\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An Xml formatted string\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 103 of file DateType\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string NHibernate\&.Type\&.DateType\&.Name\fC [get]\fP"

.PP

.PP
Definition at line 27 of file DateType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
