.TH "NHibernate.Test.ConnectionTest.AggressiveReleaseTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ConnectionTest.AggressiveReleaseTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.ConnectionTest\&.ConnectionManagementTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerializationOnAfterStatementAggressiveRelease\fP ()"
.br
.ti -1c
.RI "void \fBSerializationFailsOnAfterStatementAggressiveReleaseWithOpenResources\fP ()"
.br
.ti -1c
.RI "void \fBQueryIteration\fP ()"
.br
.ti -1c
.RI "void \fBSuppliedConnection\fP ()"
.br
.ti -1c
.RI "void \fBConnectionMaintanenceDuringFlush\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConfigure\fP (\fBConfiguration\fP cfg)"
.br
.ti -1c
.RI "override \fBISession\fP \fBGetSessionUnderTest\fP ()"
.br
.ti -1c
.RI "void \fBReconnect\fP (\fBISession\fP session)"
.br
.ti -1c
.RI "override void \fBPrepare\fP ()"
.br
.ti -1c
.RI "override void \fBDone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file AggressiveReleaseTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
