.TH "NHibernate.Test.Operations" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Operations \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractOperationTestCase\fP"
.br
.ti -1c
.RI "class \fBAddress\fP"
.br
.ti -1c
.RI "class \fBCompetition\fP"
.br
.ti -1c
.RI "class \fBCompetitor\fP"
.br
.ti -1c
.RI "class \fBEmployee\fP"
.br
.ti -1c
.RI "class \fBEmployer\fP"
.br
.ti -1c
.RI "class \fBMergeFixture\fP"
.br
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBNumberedNode\fP"
.br
.ti -1c
.RI "class \fBPerson\fP"
.br
.ti -1c
.RI "class \fBPersonalDetails\fP"
.br
.ti -1c
.RI "class \fBTimestampedEntity\fP"
.br
.ti -1c
.RI "class \fBVersionedEntity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
