.TH "NHibernate.Mapping.ByCode.Impl.ComponentMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.ComponentMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.AbstractPropertyContainerMapper\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IComponentMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentMapper\fP (\fBHbmComponent\fP component, System\&.Type componentType, MemberInfo declaringTypeMember, \fBHbmMapping\fP mapDoc)"
.br
.ti -1c
.RI "\fBComponentMapper\fP (\fBHbmComponent\fP component, System\&.Type componentType, \fBIAccessorPropertyMapper\fP accessorMapper, \fBHbmMapping\fP mapDoc)"
.br
.ti -1c
.RI "void \fBParent\fP (MemberInfo parent)"
.br
.ti -1c
.RI "void \fBParent\fP (MemberInfo parent, Action< \fBIComponentParentMapper\fP > parentMapping)"
.br
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.ti -1c
.RI "void \fBLazy\fP (bool isLazy)"
.br
.ti -1c
.RI "void \fBUnique\fP (bool unique)"
.br
.ti -1c
.RI "void \fBClass\fP (System\&.Type componentType)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.ti -1c
.RI "void \fBOptimisticLock\fP (bool takeInConsiderationForOptimisticLock)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddProperty\fP (object property)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file ComponentMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
