.TH "NHibernate.Hql.Ast.ANTLR.Tree.InLogicOperatorNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.InLogicOperatorNode \- 
.PP
Author: Steve Ebersole Ported by: Steve Strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.BinaryLogicOperatorNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IBinaryOperatorNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInLogicOperatorNode\fP (IToken token)"
.br
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.RI "\fIPerforms the operator node initialization by seeking out any parameter nodes and setting their expected type, if possible\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Author: Steve Ebersole Ported by: Steve Strong 


.PP
Definition at line 12 of file InLogicOperatorNode\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.InLogicOperatorNode\&.Initialize ()\fC [virtual]\fP"

.PP
Performs the operator node initialization by seeking out any parameter nodes and setting their expected type, if possible\&. 
.PP
Reimplemented from \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.BinaryLogicOperatorNode\fP\&.
.PP
Definition at line 24 of file InLogicOperatorNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
