.TH "NHibernate.Test.NHSpecificTest.Dates.DateTime2Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Dates.DateTime2Fixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.Dates\&.FixtureBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSavingAndRetrievingTest\fP ()"
.br
.ti -1c
.RI "void \fBSaveMillisecond\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override DbType \fBAppliesTo\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file DateTime2Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
