.TH "NHibernate.Test.NHSpecificTest.Dates" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Dates \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAllDates\fP"
.br
.ti -1c
.RI "class \fBDateFixture\fP"
.br
.ti -1c
.RI "class \fBDateTime2Fixture\fP"
.br
.ti -1c
.RI "class \fBDateTimeAssert\fP"
.br
.RI "\fIUseful assert to work with datetimes types\&. \fP"
.ti -1c
.RI "class \fBDateTimeOffsetFixture\fP"
.br
.ti -1c
.RI "class \fBDateTimeOffsetQueryFixture\fP"
.br
.ti -1c
.RI "class \fBFixtureBase\fP"
.br
.ti -1c
.RI "class \fBTimeAsTimeSpanFixture\fP"
.br
.ti -1c
.RI "class \fBTimeFixture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
