.TH "NHibernate.Engine.NamedSQLQueryDefinition" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.NamedSQLQueryDefinition \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Engine\&.NamedQueryDefinition\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamedSQLQueryDefinition\fP (string query, \fBINativeSQLQueryReturn\fP[] queryReturns, IList< string > querySpaces, bool cacheable, string cacheRegion, int timeout, int fetchSize, \fBFlushMode\fP flushMode, \fBCacheMode\fP?cacheMode, bool readOnly, string comment, IDictionary< string, string > parameterTypes, bool callable)"
.br
.ti -1c
.RI "\fBNamedSQLQueryDefinition\fP (string query, string resultSetRef, IList< string > querySpaces, bool cacheable, string cacheRegion, int timeout, int fetchSize, \fBFlushMode\fP flushMode, \fBCacheMode\fP?cacheMode, bool readOnly, string comment, IDictionary< string, string > parameterTypes, bool callable)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBINativeSQLQueryReturn\fP[] \fBQueryReturns\fP\fC [get]\fP"
.br
.ti -1c
.RI "IList< string > \fBQuerySpaces\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsCallable\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBResultSetRef\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file NamedSQLQueryDefinition\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
