.TH "NHibernate.Driver.FirebirdClientDriver" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Driver.FirebirdClientDriver \- 
.PP
A \fBNHibernate\fP \fBDriver\fP for using the Firebird data provider located in \fCFirebirdSql\&.Data\&.FirebirdClient\fP assembly\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Driver\&.ReflectionBasedDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirebirdClientDriver\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBFirebirdClientDriver\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseNamedPrefixInSql\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBUseNamedPrefixInParameter\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBNamedPrefix\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBNHibernate\fP \fBDriver\fP for using the Firebird data provider located in \fCFirebirdSql\&.Data\&.FirebirdClient\fP assembly\&. 


.PP
Definition at line 7 of file FirebirdClientDriver\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Driver\&.FirebirdClientDriver\&.FirebirdClientDriver ()"

.PP
Initializes a new instance of the \fBFirebirdClientDriver\fP class\&. 
.PP
\fBExceptions:\fP
.RS 4
\fI\fBHibernateException\fP\fP Thrown when the \fCFirebirdSql\&.Data\&.Firebird\fP assembly can not be loaded\&. 
.RE
.PP

.PP
Definition at line 15 of file FirebirdClientDriver\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
