.TH "NHibernate.Mapping.ByCode.Impl.CustomizersImpl.DynamicComponentCustomizer< TComponent >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.CustomizersImpl.DynamicComponentCustomizer< TComponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.PropertyContainerCustomizer< TEntity >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IDynamicComponentMapper< TComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDynamicComponentCustomizer\fP (\fBIModelExplicitDeclarationsHolder\fP explicitDeclarationsHolder, \fBICustomizersHolder\fP customizersHolder, \fBPropertyPath\fP propertyPath)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.ti -1c
.RI "void \fBOptimisticLock\fP (bool takeInConsiderationForOptimisticLock)"
.br
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.ti -1c
.RI "void \fBUnique\fP (bool unique)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITComponent\fP : \fIclass\fP
.PP
Definition at line 5 of file DynamicComponentCustomizer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
