.TH "NHibernate.Hql.Ast.ANTLR.WithClauseVisitor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.WithClauseVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Util\&.IVisitationStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWithClauseVisitor\fP (\fBFromElement\fP fromElement)"
.br
.ti -1c
.RI "void \fBVisit\fP (\fBIASTNode\fP node)"
.br
.ti -1c
.RI "\fBFromElement\fP \fBGetReferencedFromElement\fP ()"
.br
.ti -1c
.RI "String \fBGetJoinAlias\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1102 of file HqlSqlWalker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
