.TH "NHibernate.Test.EngineTest.NativeSQLQuerySpecificationTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.EngineTest.NativeSQLQuerySpecificationTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEquality\fP ()"
.br
.ti -1c
.RI "void \fBHashCode\fP ()"
.br
.ti -1c
.RI "void \fBWhenChangeReturns_NotEqual\fP ()"
.br
.ti -1c
.RI "void \fBWhenChangeReturns_NotEqualHashCode\fP ()"
.br
.ti -1c
.RI "void \fBWhenChangeSpace_NotEqual\fP ()"
.br
.ti -1c
.RI "void \fBWhenChangeSpace_NotEqualHashCode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file NativeSQLQuerySpecificationTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
