.TH "NHibernate.Test.SqlCommandTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.SqlCommandTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSqlDeleteBuilderFixture\fP"
.br
.RI "\fITests all of the functionallity of the \fBSqlDeleteBuilderFixture\fP \fP"
.ti -1c
.RI "class \fBSqlInsertBuilderFixture\fP"
.br
.RI "\fITests all of the functionallity of the SqlInsertBulder \fP"
.ti -1c
.RI "class \fBSqlSelectBuilderFixture\fP"
.br
.RI "\fITests all of the functionallity of the SqlSelectBuilderTest \fP"
.ti -1c
.RI "class \fBSqlSimpleSelectBuilderFixture\fP"
.br
.RI "\fITests all of the functionallity of the SqlInsertBulder \fP"
.ti -1c
.RI "class \fBSqlStringBuilderFixture\fP"
.br
.RI "\fISummary description for \fBSqlStringBuilderFixture\fP\&. \fP"
.ti -1c
.RI "class \fBSqlStringFixture\fP"
.br
.RI "\fISummary description for \fBSqlStringFixture\fP\&. \fP"
.ti -1c
.RI "class \fBSqlStringParameterFixture\fP"
.br
.ti -1c
.RI "class \fBSqlTokenizerFixture\fP"
.br
.ti -1c
.RI "class \fBSqlUpdateBuilderFixture\fP"
.br
.RI "\fITests all of the functionallity of the SqlUpdateBuilder \fP"
.ti -1c
.RI "class \fBTemplateFixture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
