.TH "NHibernate.Event.IDatabaseEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.IDatabaseEventArgs \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Event\&.AbstractEvent\fP, \fBNHibernate\&.Event\&.IPostDatabaseOperationEventArgs\fP, and \fBNHibernate\&.Event\&.IPreDatabaseOperationEventArgs\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIEventSource\fP \fBSession\fP\fC [get]\fP"
.br
.RI "\fIReturns the session event source for this event\&. This is the underlying session from which this event was generated\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file IDatabaseEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "\fBIEventSource\fP NHibernate\&.Event\&.IDatabaseEventArgs\&.Session\fC [get]\fP"

.PP
Returns the session event source for this event\&. This is the underlying session from which this event was generated\&. 
.PP
Definition at line 9 of file IDatabaseEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
