.TH "NHibernate.Test.IdGen.Enhanced.OptimizerTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.IdGen.Enhanced.OptimizerTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestBasicNoOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestBasicHiLoOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestBasicPooledOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestSubsequentPooledOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestBasicPooledLoOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestSubsequentPooledLoOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestRecoveredPooledOptimizerUsage\fP ()"
.br
.ti -1c
.RI "void \fBTestRecoveredPooledLoOptimizerUsage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file OptimizerTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
