.TH "NHibernate.Test.EntityModeTest.Xml.Accessors.XmlAccessorFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.EntityModeTest.Xml.Accessors.XmlAccessorFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCompanyElementGeneration\fP ()"
.br
.ti -1c
.RI "void \fBLongAttributeExtraction\fP ()"
.br
.ti -1c
.RI "void \fBLongElementAttributeExtraction\fP ()"
.br
.ti -1c
.RI "void \fBStringElementExtraction\fP ()"
.br
.ti -1c
.RI "void \fBStringTextExtraction\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static XmlElement \fBdom\fP = GenerateTestElement()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file XmlAccessorFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
