.TH "NHibernate.Test.NHSpecificTest.NH2733.Specification< T >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2733.Specification< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecification\fP (Expression< Func< T, bool >> predicate)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Expression< Func< T, bool > > \fBPredicate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Expression \fBExpression\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
