.TH "NHibernate.Dialect.Schema.MsSqlCeForeignKeyMetadata" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Schema.MsSqlCeForeignKeyMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Schema\&.AbstractForeignKeyMetadata\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMsSqlCeForeignKeyMetadata\fP (DataRow rs)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 83 of file MsSqlCeMetaData\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
