.TH "NHibernate.Test.ConnectionTest.TestableThreadLocalContext" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ConnectionTest.TestableThreadLocalContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Context\&.ThreadLocalSessionContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestableThreadLocalContext\fP (\fBISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsSessionBound\fP (\fBISession\fP session)"
.br
.ti -1c
.RI "static bool \fBHasBind\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 70 of file ThreadLocalCurrentSessionTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
