.TH "NHibernate.Test.Ado.BatcherFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Ado.BatcherFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOneRoundTripInserts\fP ()"
.br
.ti -1c
.RI "void \fBOneRoundTripUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSqlClientOneRoundTripForUpdateAndInsert\fP ()"
.br
.ti -1c
.RI "void \fBBatchedoutputShouldBeFormatted\fP ()"
.br
.ti -1c
.RI "void \fBOneRoundTripDelete\fP ()"
.br
.ti -1c
.RI "void \fBSqlLog\fP ()"
.br
.ti -1c
.RI "void \fBAbstractBatcherLog\fP ()"
.br
.ti -1c
.RI "void \fBSqlLogShouldGetBatchCommandNotification\fP ()"
.br
.ti -1c
.RI "void \fBAbstractBatcherLogFormattedSql\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConfigure\fP (\fBConfiguration\fP configuration)"
.br
.ti -1c
.RI "override bool \fBAppliesTo\fP (\fBEngine\&.ISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file BatcherFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
