.TH "NHibernate.Cache.Entry.CollectionCacheEntry" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cache.Entry.CollectionCacheEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionCacheEntry\fP (\fBIPersistentCollection\fP collection, \fBICollectionPersister\fP persister)"
.br
.ti -1c
.RI "virtual void \fBAssemble\fP (\fBIPersistentCollection\fP collection, \fBICollectionPersister\fP persister, object owner)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual object[] \fBState\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file CollectionCacheEntry\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
