.TH "NHibernate.Test.NHSpecificTest.NH266.Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH266.Fixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBaseClassLoad\fP ()"
.br
.ti -1c
.RI "void \fBSpecificSubclass\fP ()"
.br
.RI "\fIThis is testing problems that existed in 0\&.8\&.0-2 with extra 'AND' being added to the sql when there was a discriminator-value\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file Fixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH266\&.Fixture\&.SpecificSubclass ()"

.PP
This is testing problems that existed in 0\&.8\&.0-2 with extra 'AND' being added to the sql when there was a discriminator-value\&. 
.PP
Definition at line 92 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
