.TH "NHibernate.Event.PostCollectionUpdateEvent" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.PostCollectionUpdateEvent \- 
.PP
An event that occurs after a collection is updated  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.AbstractCollectionEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPostCollectionUpdateEvent\fP (\fBICollectionPersister\fP collectionPersister, \fBIPersistentCollection\fP collection, \fBIEventSource\fP source)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An event that occurs after a collection is updated 


.PP
Definition at line 9 of file PostCollectionUpdateEvent\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
