.TH "NHibernate.Test.NHSpecificTest.BasicSerializableFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.BasicSerializableFixture \- 
.PP
TestFixture for \fCtype='Serializable'\fP in use by classes\&. It test a Property that is mapped specifically by \fCtype='Serializable'\fP and another Property whose type is a class that is serializable\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTestCRUD\fP ()"
.br
.RI "\fIThis contains portions of FumTest\&.CompositeIDs that deal with \fCtype='Serializable'\fP and replacements Foo\&.NullBlob, and Foo\&.Blob\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
TestFixture for \fCtype='Serializable'\fP in use by classes\&. It test a Property that is mapped specifically by \fCtype='Serializable'\fP and another Property whose type is a class that is serializable\&. 


.PP
Definition at line 14 of file BasicSerializableFixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.BasicSerializableFixture\&.TestCRUD ()"

.PP
This contains portions of FumTest\&.CompositeIDs that deal with \fCtype='Serializable'\fP and replacements Foo\&.NullBlob, and Foo\&.Blob\&. 
.PP
Definition at line 26 of file BasicSerializableFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
