.TH "NHibernate.Test.NHSpecificTest.NH3182.Mammal" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH3182.Mammal \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH3182\&.Animal\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH3182\&.Cat\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH3182\&.Dog\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBPregnant\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DateTime \fBBirthDate\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
