.TH "NHibernate.UserTypes.ILoggableUserType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.UserTypes.ILoggableUserType \- 
.PP
Marker interface for user types which want to perform custom logging of their corresponding values  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToLoggableString\fP (object value, \fBISessionFactoryImplementor\fP factory)"
.br
.RI "\fIGenerate a loggable string representation of the collection (value)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Marker interface for user types which want to perform custom logging of their corresponding values 


.PP
Definition at line 9 of file ILoggableUserType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string NHibernate\&.UserTypes\&.ILoggableUserType\&.ToLoggableString (objectvalue, \fBISessionFactoryImplementor\fPfactory)"

.PP
Generate a loggable string representation of the collection (value)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The collection to be logged; guaranteed to be non-null and initialized\&. 
.br
\fIfactory\fP The factory\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The loggable string representation\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
