.TH "NHibernate.Test.NHSpecificTest.NH2208.Referred" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2208.Referred \- 
.PP
a class mapping for the table: \fBReferred\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2208\&.SubOfReferred\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual Int32 \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual String \fBP1\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a class mapping for the table: \fBReferred\fP 


.PP
Definition at line 17 of file Referred\&.generated\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual Int32 NHibernate\&.Test\&.NHSpecificTest\&.NH2208\&.Referred\&.Id\fC [get]\fP, \fC [set]\fP"

.PP

.PP
Definition at line 30 of file Referred\&.generated\&.cs\&.
.SS "virtual String NHibernate\&.Test\&.NHSpecificTest\&.NH2208\&.Referred\&.P1\fC [get]\fP, \fC [set]\fP"

.PP

.PP
Definition at line 38 of file Referred\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
