.TH "NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.SubclassMappingStrategyTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.SubclassMappingStrategyTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenRegisteredAsSubclassThenIsRegistered\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsDeepSubclassThenIsRegistered\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsSubclassThenCantRegisterAsJoinedSubclass\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsSubclassThenCantRegisterAsUnionSubclass\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisteredAsSubclassThenIsEntity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SubclassMappingStrategyTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
