.TH "NHibernate.Criterion.IsNotEmptyExpression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.IsNotEmptyExpression \- 
.PP
An \fBICriterion\fP that represents non-empty association constraint\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.AbstractEmptinessExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIsNotEmptyExpression\fP (string propertyName)"
.br
.ti -1c
.RI "override \fBIProjection\fP[] \fBGetProjections\fP ()"
.br
.RI "\fIReturn all projections used in this criterion \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBExcludeEmpty\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An \fBICriterion\fP that represents non-empty association constraint\&. 


.PP
Definition at line 9 of file IsNotEmptyExpression\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBIProjection\fP [] NHibernate\&.Criterion\&.IsNotEmptyExpression\&.GetProjections ()\fC [virtual]\fP"

.PP
Return all projections used in this criterion 
.PP
\fBReturns:\fP
.RS 4
An array of \fBIProjection\fP used by the \fBExpression\fP\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Criterion\&.AbstractCriterion\fP\&.
.PP
Definition at line 21 of file IsNotEmptyExpression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
