.TH "NHibernate.Id.Insert.IdentifierGeneratingInsert" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Id.Insert.IdentifierGeneratingInsert \- 
.PP
Nothing more than a distinguishing subclass of \fBInsert\fP used to indicate intent\&. Some subclasses of this also provided some additional functionality or semantic to the genernated SQL statement string\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.SqlCommand\&.SqlInsertBuilder\fP\&.
.PP
Inherited by \fBNHibernate\&.Id\&.Insert\&.InsertSelectIdentityInsert\fP, and \fBNHibernate\&.Id\&.Insert\&.NoCommentsInsert\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdentifierGeneratingInsert\fP (\fBISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Nothing more than a distinguishing subclass of \fBInsert\fP used to indicate intent\&. Some subclasses of this also provided some additional functionality or semantic to the genernated SQL statement string\&. 


.PP
Definition at line 12 of file IdentifierGeneratingInsert\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
