.TH "NHibernate.Linq.ExpressionToHqlTranslationResults" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.ExpressionToHqlTranslationResults \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpressionToHqlTranslationResults\fP (\fBHqlTreeNode\fP statement, IList< LambdaExpression > itemTransformers, IList< LambdaExpression > listTransformers, IList< LambdaExpression > postExecuteTransformers, List< Action< \fBIQuery\fP, IDictionary< string, Tuple< object, \fBIType\fP >>>> additionalCriteria)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHqlTreeNode\fP \fBStatement\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBResultTransformer\fP \fBResultTransformer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Delegate \fBPostExecuteTransformer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "List< Action< \fBIQuery\fP, 
.br
IDictionary< string, Tuple
.br
< object, \fBIType\fP > > > > \fBAdditionalCriteria\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ExpressionToHqlTranslationResults\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
