.TH "NHibernate.Proxy.DefaultProxyFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Proxy.DefaultProxyFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Proxy\&.AbstractProxyFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBINHibernateProxy\fP \fBGetProxy\fP (object id, \fBISessionImplementor\fP session)"
.br
.RI "\fICreate a new proxy \fP"
.ti -1c
.RI "override object \fBGetFieldInterceptionProxy\fP (object instanceToWrap)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBIInternalLogger\fP \fBlog\fP = LoggerProvider\&.LoggerFor(typeof (\fBDefaultProxyFactory\fP))"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file DefaultProxyFactory\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBINHibernateProxy\fP NHibernate\&.Proxy\&.DefaultProxyFactory\&.GetProxy (objectid, \fBISessionImplementor\fPsession)\fC [virtual]\fP"

.PP
Create a new proxy 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP The id value for the proxy to be generated\&.
.br
\fIsession\fP The session to which the generated proxy will be associated\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The generated proxy\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBHibernateException\fP\fP Indicates problems generating requested proxy\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Proxy\&.AbstractProxyFactory\fP\&.
.PP
Definition at line 13 of file DefaultProxyFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
