.TH "NHibernate.Test.NHSpecificTest.NH2898.BinaryFormatterCache" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2898.BinaryFormatterCache \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cache\&.ICache\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinaryFormatterCache\fP (string regionName)"
.br
.ti -1c
.RI "object \fBGet\fP (object key)"
.br
.RI "\fIGet the object from the \fBCache\fP \fP"
.ti -1c
.RI "void \fBPut\fP (object key, object value)"
.br
.ti -1c
.RI "void \fBRemove\fP (object key)"
.br
.RI "\fIRemove an item from the \fBCache\fP\&. \fP"
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "\fIClear the \fBCache\fP \fP"
.ti -1c
.RI "void \fBDestroy\fP ()"
.br
.RI "\fIClean up\&. \fP"
.ti -1c
.RI "void \fBLock\fP (object key)"
.br
.RI "\fIIf this is a clustered cache, lock the item \fP"
.ti -1c
.RI "void \fBUnlock\fP (object key)"
.br
.RI "\fIIf this is a clustered cache, unlock the item \fP"
.ti -1c
.RI "long \fBNextTimestamp\fP ()"
.br
.RI "\fIGenerate a timestamp \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBTimeout\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBRegionName\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file BinaryFormatterCache\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Clear ()"

.PP
Clear the \fBCache\fP 
.PP
\fBExceptions:\fP
.RS 4
\fICacheException\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 46 of file BinaryFormatterCache\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Destroy ()"

.PP
Clean up\&. 
.PP
\fBExceptions:\fP
.RS 4
\fICacheException\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 51 of file BinaryFormatterCache\&.cs\&.
.SS "object NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Get (objectkey)"

.PP
Get the object from the \fBCache\fP 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 18 of file BinaryFormatterCache\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Lock (objectkey)"

.PP
If this is a clustered cache, lock the item 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP The Key of the Item in the \fBCache\fP to lock\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fICacheException\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 55 of file BinaryFormatterCache\&.cs\&.
.SS "long NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.NextTimestamp ()"

.PP
Generate a timestamp 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 65 of file BinaryFormatterCache\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Put (objectkey, objectvalue)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIkey\fP 
.br
\fIvalue\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 31 of file BinaryFormatterCache\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Remove (objectkey)"

.PP
Remove an item from the \fBCache\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP The Key of the Item in the \fBCache\fP to remove\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fICacheException\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 41 of file BinaryFormatterCache\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH2898\&.BinaryFormatterCache\&.Unlock (objectkey)"

.PP
If this is a clustered cache, unlock the item 
.PP
\fBParameters:\fP
.RS 4
\fIkey\fP The Key of the Item in the \fBCache\fP to unlock\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fICacheException\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICache\fP\&.
.PP
Definition at line 60 of file BinaryFormatterCache\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
