.TH "NHibernate.Test.NHSpecificTest.NH1391.PersonWithAllTypes" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1391.PersonWithAllTypes \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1391\&.Person\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual IList< \fBDog\fP > \fBDogsNonGeneric\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBSivasKangal\fP > \fBSivasKangalsNonGeneric\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBCat\fP > \fBCatsNonGeneric\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBDog\fP > \fBDogsGeneric\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBSivasKangal\fP > \fBSivasKangalsGeneric\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList< \fBCat\fP > \fBCatsGeneric\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file PersonWithAllTypes\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
