.TH "NHibernate.Hql.Ast.ANTLR.Tree.HqlSqlWalkerTreeAdaptor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.HqlSqlWalkerTreeAdaptor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.ASTTreeAdaptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlSqlWalkerTreeAdaptor\fP (object walker)"
.br
.ti -1c
.RI "override object \fBCreate\fP (IToken payload)"
.br
.ti -1c
.RI "override object \fBErrorNode\fP (ITokenStream input, IToken start, IToken stop, RecognitionException e)"
.br
.ti -1c
.RI "override object \fBDupNode\fP (object t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file HqlSqlWalkerTreeAdapter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
