.TH "NHibernate.Test.ProxyTest.AProxy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ProxyTest.AProxy \- 
.PP
Summary description for \fBAProxy\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBAProxy\fP\&. 


.PP
Definition at line 8 of file AProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
