.TH "NHibernate.Mapping.MetaAttribute" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.MetaAttribute \- 
.PP
A meta attribute is a named value or values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetaAttribute\fP (string name)"
.br
.ti -1c
.RI "void \fBAddValue\fP (string value)"
.br
.ti -1c
.RI "void \fBAddValues\fP (IEnumerable< string > range)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "IList< string > \fBValues\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsMultiValued\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A meta attribute is a named value or values\&. 


.PP
Definition at line 11 of file MetaAttribute\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
