.TH "NHibernate.Loader.Custom.Sql.SQLQueryParser.ParameterSubstitutionRecognizer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.Custom.Sql.SQLQueryParser.ParameterSubstitutionRecognizer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Engine\&.Query\&.ParameterParser\&.IRecognizer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterSubstitutionRecognizer\fP (\fBISessionFactoryImplementor\fP factory)"
.br
.ti -1c
.RI "void \fBOutParameter\fP (int position)"
.br
.ti -1c
.RI "void \fBOrdinalParameter\fP (int position)"
.br
.ti -1c
.RI "void \fBNamedParameter\fP (string name, int position)"
.br
.ti -1c
.RI "void \fBJpaPositionalParameter\fP (string name, int position)"
.br
.ti -1c
.RI "void \fBOther\fP (char character)"
.br
.ti -1c
.RI "void \fBOther\fP (string sqlPart)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable
.br
< \fBIParameterSpecification\fP > \fBParametersSpecifications\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 253 of file SQLQueryParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
