.TH "NHibernate.DomainModel.Northwind.Entities.Territory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Northwind.Entities.Territory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.DomainModel\&.Northwind\&.Entities\&.Entity< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerritory\fP (string description)"
.br
.ti -1c
.RI "virtual void \fBAddEmployee\fP (\fBEmployee\fP employee)"
.br
.ti -1c
.RI "virtual void \fBRemoveEmployee\fP (\fBEmployee\fP employee)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBDescription\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBRegion\fP \fBRegion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ReadOnlyCollection
.br
< \fBEmployee\fP > \fBEmployees\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Territory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
