.TH "NHibernate.Test.NHSpecificTest.NH1691.DeepComponent" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1691.DeepComponent \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBProp1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBProp2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBProp3\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBProp4\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBComponent\fP \fBComponent\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
