.TH "NHibernate.SqlCommand.Template" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.Template \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBRenderWhereStringTemplate\fP (string sqlWhereString, \fBDialect\&.Dialect\fP dialect, \fBSQLFunctionRegistry\fP functionRegistry)"
.br
.ti -1c
.RI "static string \fBRenderWhereStringTemplate\fP (string sqlWhereString, string placeholder, \fBDialect\&.Dialect\fP dialect, \fBSQLFunctionRegistry\fP functionRegistry)"
.br
.ti -1c
.RI "static string \fBRenderOrderByStringTemplate\fP (string sqlOrderByString, \fBDialect\&.Dialect\fP dialect, \fBSQLFunctionRegistry\fP functionRegistry)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly string \fBPlaceholder\fP = '$PlaceHolder$'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Template\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
