.TH "NHibernate.Stat.SessionStatisticsImpl" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Stat.SessionStatisticsImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Stat\&.ISessionStatistics\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSessionStatisticsImpl\fP (\fBISessionImplementor\fP session)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBEntityCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCollectionCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "IList< \fBEntityKey\fP > \fBEntityKeys\fP\fC [get]\fP"
.br
.ti -1c
.RI "IList< \fBCollectionKey\fP > \fBCollectionKeys\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SessionStatisticsImpl\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
