.TH "NHibernate.Test.MappingByCode.MappersTests.JoinMapperTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests.JoinMapperTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenCreateWithEmptySplitGroupThenThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenCreateWithNullHbmJoinThenThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenCreateThenSetDefaultTableName\fP ()"
.br
.ti -1c
.RI "void \fBCanSetTable\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetTableNameEmptyThenThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenTableNameChangesValueThenNotify\fP ()"
.br
.ti -1c
.RI "void \fBCanSetCatalog\fP ()"
.br
.ti -1c
.RI "void \fBCanSetSchema\fP ()"
.br
.ti -1c
.RI "void \fBCanSetSqlInsert\fP ()"
.br
.ti -1c
.RI "void \fBSetSqlUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSetSqlDelete\fP ()"
.br
.ti -1c
.RI "void \fBCanSetSqlSubselect\fP ()"
.br
.ti -1c
.RI "void \fBCanSetInverse\fP ()"
.br
.ti -1c
.RI "void \fBCanSetOptional\fP ()"
.br
.ti -1c
.RI "void \fBCanSetFetch\fP ()"
.br
.ti -1c
.RI "void \fBCallKeyMapper\fP ()"
.br
.ti -1c
.RI "void \fBWhenCallKeyMapperThenKeyMapperIsNotNull\fP ()"
.br
.ti -1c
.RI "void \fBWhenCallKeyMapperMoreThanOnceThenKeyMapperIsTheSame\fP ()"
.br
.ti -1c
.RI "void \fBWhenAddPropertyThenAddItem\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file JoinMapperTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
