.TH "NHibernate.Test.QueryTest.DetachedQueryFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.QueryTest.DetachedQueryFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPropertiesSet\fP ()"
.br
.ti -1c
.RI "void \fBCopyToTest\fP ()"
.br
.ti -1c
.RI "void \fBOverrideTest\fP ()"
.br
.ti -1c
.RI "void \fBExecutableQuery\fP ()"
.br
.ti -1c
.RI "void \fBExecutableNamedQuery\fP ()"
.br
.ti -1c
.RI "void \fBResultTransformer\fP ()"
.br
.ti -1c
.RI "void \fBSerializable\fP ()"
.br
.ti -1c
.RI "void \fBPerformanceDiffSimplyQuery\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBtotalFoo\fP = 15"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file DetachedQueryFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
