.TH "NHibernate.Mapping.ByCode.Impl.GeneratorMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.GeneratorMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IGeneratorMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneratorMapper\fP (\fBHbmGenerator\fP generator)"
.br
.ti -1c
.RI "void \fBParams\fP (object generatorParameters)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file GeneratorMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
