.TH "NHibernate.Cfg.MappingSchema.HbmSubclass" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmSubclass \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.AbstractDecoratable\fP, \fBNHibernate\&.Cfg\&.MappingSchema\&.IEntityMapping\fP, and \fBNHibernate\&.Cfg\&.MappingSchema\&.IEntityDiscriminableMapping\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmMeta\fP[] \fBmeta\fP"
.br
.ti -1c
.RI "\fBHbmTuplizer\fP[] \fBtuplizer\fP"
.br
.ti -1c
.RI "\fBHbmSynchronize\fP[] \fBsynchronize\fP"
.br
.ti -1c
.RI "object[] \fBItems\fP"
.br
.ti -1c
.RI "\fBHbmJoin\fP[] \fBjoin\fP"
.br
.ti -1c
.RI "\fBHbmSubclass\fP[] \fBsubclass1\fP"
.br
.ti -1c
.RI "\fBHbmLoader\fP \fBloader\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqlinsert\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqlupdate\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBsqldelete\fP"
.br
.ti -1c
.RI "\fBHbmResultSet\fP[] \fBresultset\fP"
.br
.ti -1c
.RI "object[] \fBItems1\fP"
.br
.ti -1c
.RI "string \fBentityname\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBproxy\fP"
.br
.ti -1c
.RI "string \fBdiscriminatorvalue\fP"
.br
.ti -1c
.RI "bool \fBdynamicupdate\fP"
.br
.ti -1c
.RI "bool \fBdynamicinsert\fP"
.br
.ti -1c
.RI "bool \fBselectbeforeupdate\fP"
.br
.ti -1c
.RI "string \fBextends\fP"
.br
.ti -1c
.RI "bool \fBlazy\fP"
.br
.ti -1c
.RI "bool \fBlazySpecified\fP"
.br
.ti -1c
.RI "bool \fBabstract\fP"
.br
.ti -1c
.RI "bool \fBabstractSpecified\fP"
.br
.ti -1c
.RI "string \fBpersister\fP"
.br
.ti -1c
.RI "string \fBbatchsize\fP"
.br
.ti -1c
.RI "string \fBnode\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBHbmJoin\fP > \fBJoins\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHbmSubclass\fP > \fBSubclasses\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBHbmMeta\fP[] \fBMetadatas\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBEntityName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBNode\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBProxy\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBUseLazy\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmTuplizer\fP[] \fBTuplizers\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBDynamicUpdate\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBDynamicInsert\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBBatchSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBSelectBeforeUpdate\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBPersister\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsAbstract\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmSynchronize\fP[] \fBSynchronize\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBDiscriminatorValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmLoader\fP \fBSqlLoader\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlInsert\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlUpdate\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmCustomSQL\fP \fBSqlDelete\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBSubselect\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable
.br
< \fBIEntityPropertyMapping\fP > \fBProperties\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
Definition at line 4497 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
