.TH "NHibernate.Dialect.Function.AnsiTrimFunction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Function.AnsiTrimFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Function\&.SQLFunctionTemplate\fP, and \fBNHibernate\&.Dialect\&.Function\&.IFunctionGrammar\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file AnsiTrimFunction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
