.TH "NHibernate.Test.NHSpecificTest.NH1642.TrafficRule" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1642.TrafficRule \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1642\&.AbstractRule\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual DateTime \fBeffectiveStartDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual DateTime \fBeffectiveEndDate\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBTrafficRuleSet\fP \fBruleSet\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file TrafficRule\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
