.TH "NHibernate.Test.MappingByCode.TypeExtensionsTests.GetPropertyOrFieldMatchingNameTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.TypeExtensionsTests.GetPropertyOrFieldMatchingNameTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenNullTypeThenThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskNullThenNull\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskNotExistentThenNull\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivateFieldThenFindIt\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivateFieldWithBlanksThenFindIt\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivatePropertyThenFindIt\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskProtectedPropertyThenFindIt\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskMethodThenNull\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivateFieldOnInheritedThenFindItOnInherited\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivatePropertyOnInheritedThenFindItOnInherited\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPrivatePropertyOfBaseOnInheritedThenFindItOnBase\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPropertyOfInterfaceThenFindIt\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPropertyOfExplicitInterfaceThenFindItOnInterface\fP ()"
.br
.ti -1c
.RI "void \fBWhenAskPropertyOfImplementedInterfaceThenFindItOnType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file GetPropertyOrFieldMatchingNameTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
