.TH "NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.path_return" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.HqlSqlWalker.path_return \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TreeRuleReturnScope\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBp\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override object \fBTree\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4674 of file HqlSqlWalker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
