.TH "NHibernate.Engine.SubselectFetch" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.SubselectFetch \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubselectFetch\fP (string alias, \fBILoadable\fP loadable, \fBQueryParameters\fP queryParameters, ISet< \fBEntityKey\fP > resultingEntityKeys)"
.br
.ti -1c
.RI "\fBSqlString\fP \fBToSubselectString\fP (string ukname)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBQueryParameters\fP \fBQueryParameters\fP\fC [get]\fP"
.br
.ti -1c
.RI "ISet< \fBEntityKey\fP > \fBResult\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file SubselectFetch\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
