.TH "NHibernate.Hql.Ast.HqlTreeNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.HqlTreeNode \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.HqlExpression\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlFetch\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlFetchJoin\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlInList\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlLeft\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlLeftFetchJoin\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlLeftJoin\fP, and \fBNHibernate\&.Hql\&.Ast\&.HqlStatement\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearChildren\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlTreeNode\fP (int type, string text, \fBIASTFactory\fP factory, IEnumerable< \fBHqlTreeNode\fP > children)"
.br
.ti -1c
.RI "\fBHqlTreeNode\fP (int type, string text, \fBIASTFactory\fP factory, params \fBHqlTreeNode\fP[] children)"
.br
.ti -1c
.RI "void \fBSetText\fP (string text)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIASTFactory\fP \fBFactory\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHqlTreeNode\fP > \fBNodesPreOrder\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHqlTreeNode\fP > \fBNodesPostOrder\fP\fC [get]\fP"
.br
.ti -1c
.RI "IEnumerable< \fBHqlTreeNode\fP > \fBChildren\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file HqlTreeNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
