.TH "NHibernate.Engine.Loading.LoadingCollectionEntry" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.Loading.LoadingCollectionEntry \- 
.PP
Represents a collection currently being loaded\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadingCollectionEntry\fP (IDataReader resultSet, \fBICollectionPersister\fP persister, object key, \fBIPersistentCollection\fP collection)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IDataReader \fBResultSet\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBICollectionPersister\fP \fBPersister\fP\fC [get]\fP"
.br
.ti -1c
.RI "object \fBKey\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIPersistentCollection\fP \fBCollection\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a collection currently being loaded\&. 


.PP
Definition at line 12 of file LoadingCollectionEntry\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
