.TH "NHibernate.Type.CurrencyType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.CurrencyType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.DecimalType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CurrencyType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
