.TH "NHibernate.Test.NHSpecificTest.NH1579.Fruit" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1579.Fruit \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1579\&.Entity\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1579\&.Apple\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1579\&.Orange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFruit\fP (\fBEntity\fP container)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEntity\fP \fBContainer\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Fruit\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
