.TH "NHibernate.Type.LocalDateTimeType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.LocalDateTimeType \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.AbstractDateTimeSpecificKindType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override DateTimeKind \fBDateTimeKind\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file LocalDateTimeType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
