.TH "NHibernate.Mapping.ByCode.IComponentParentMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IComponentParentMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IAccessorPropertyMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.ComponentParentMapper\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file IComponentParentMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
