.TH "NHibernate.Test.MappingByCode.MappersTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBClassMapperTests\fP"
.br
.ti -1c
.RI "package \fBDynamicComponentMapperTests\fP"
.br
.ti -1c
.RI "package \fBJoinedSubclassMapperTests\fP"
.br
.ti -1c
.RI "package \fBSubclassMapperTests\fP"
.br
.ti -1c
.RI "package \fBUnionSubclassMapperTests\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractPropertyContainerMapperTest\fP"
.br
.ti -1c
.RI "class \fBAnyMapperTest\fP"
.br
.ti -1c
.RI "class \fBCollectionIdMapperTests\fP"
.br
.ti -1c
.RI "class \fBComponentAsIdTests\fP"
.br
.ti -1c
.RI "class \fBComposedIdMapperTests\fP"
.br
.ti -1c
.RI "class \fBFakeUserCollectionType\fP"
.br
.ti -1c
.RI "class \fBIdBagMapperTest\fP"
.br
.ti -1c
.RI "class \fBIdMapperTest\fP"
.br
.ti -1c
.RI "class \fBJoinMapperTests\fP"
.br
.ti -1c
.RI "class \fBManyToOneMapperTest\fP"
.br
.ti -1c
.RI "class \fBNaturalIdMapperTest\fP"
.br
.ti -1c
.RI "class \fBOneToOneMapperTest\fP"
.br
.ti -1c
.RI "class \fBPropertyMapperTest\fP"
.br
.ti -1c
.RI "class \fBMyType\fP"
.br
.ti -1c
.RI "class \fBMyCompoType\fP"
.br
.ti -1c
.RI "class \fBSubclassMapperWithJoinPropertiesTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
