.TH "NHibernate.Test.ConnectionStringTest.NamedConnectionStringFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ConnectionStringTest.NamedConnectionStringFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInvalidNamedConnectedStringThrows\fP ()"
.br
.ti -1c
.RI "void \fBConnectionStringInSettingsOverrideNamedConnectionSTring\fP ()"
.br
.ti -1c
.RI "void \fBCanGetNamedConnectionStringFromConfiguration\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file NamedConnectionStringFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
