.TH "NHibernate.Persister.Collection.CompositeElementPropertyMapping" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Persister.Collection.CompositeElementPropertyMapping \- 
.PP
Summary description for \fBCompositeElementPropertyMapping\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Persister\&.Entity\&.AbstractPropertyMapping\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompositeElementPropertyMapping\fP (string[] elementColumns, string[] elementFormulaTemplates, \fBIAbstractComponentType\fP compositeType, \fBIMapping\fP factory)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBIType\fP \fBType\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBEntityName\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Summary description for \fBCompositeElementPropertyMapping\fP\&. 


.PP
Definition at line 10 of file CompositeElementPropertyMapping\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
