.TH "NHibernate.Mapping.ByCode.IVersionMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IVersionMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IAccessorPropertyMapper\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IColumnsMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.VersionMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBType\fP (\fBIVersionType\fP persistentType)"
.br
.ti -1c
.RI "void \fBType< TPersistentType >\fP ()"
.br
.ti -1c
.RI "void \fBType\fP (System\&.Type persistentType)"
.br
.ti -1c
.RI "void \fBUnsavedValue\fP (object value)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool useInInsert)"
.br
.ti -1c
.RI "void \fBGenerated\fP (\fBVersionGeneration\fP generatedByDb)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file IVersionMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
