.TH "NHibernate.Hql.Ast.ANTLR.Tree.HqlSqlWalkerTreeNodeStream" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.HqlSqlWalkerTreeNodeStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits CommonTreeNodeStream\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlSqlWalkerTreeNodeStream\fP (object tree)"
.br
.ti -1c
.RI "void \fBInsertChild\fP (\fBIASTNode\fP parent, \fBIASTNode\fP child)"
.br
.RI "\fIInsert a new node into both the \fBTree\fP and the Node Array\&. Add DOWN and UP nodes if needed\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file HqlSqlWalkerTreeNodeStream\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.HqlSqlWalkerTreeNodeStream\&.InsertChild (\fBIASTNode\fPparent, \fBIASTNode\fPchild)"

.PP
Insert a new node into both the \fBTree\fP and the Node Array\&. Add DOWN and UP nodes if needed\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP The parent node
.br
\fIchild\fP The child node
.RE
.PP

.PP
Definition at line 16 of file HqlSqlWalkerTreeNodeStream\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
