.TH "NHibernate.Event.Default.DefaultInitializeCollectionEventListener" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.Default.DefaultInitializeCollectionEventListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Event\&.IInitializeCollectionEventListener\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.InitializeCollectionListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnInitializeCollection\fP (\fBInitializeCollectionEvent\fP @event)"
.br
.RI "\fIcalled by a collection that wants to initialize itself\fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file DefaultInitializeCollectionEventListener\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void NHibernate\&.Event\&.Default\&.DefaultInitializeCollectionEventListener\&.OnInitializeCollection (\fBInitializeCollectionEvent\fP @event)\fC [virtual]\fP"

.PP
called by a collection that wants to initialize itself
.PP
Implements \fBNHibernate\&.Event\&.IInitializeCollectionEventListener\fP\&.
.PP
Reimplemented in \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.InitializeCollectionListener\fP\&.
.PP
Definition at line 19 of file DefaultInitializeCollectionEventListener\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
