.TH "NHibernate.Util.SerializationHelper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Util.SerializationHelper \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte[] \fBSerialize\fP (object obj)"
.br
.ti -1c
.RI "static object \fBDeserialize\fP (byte[] data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file SerializationHelper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
