.TH "NHibernate.SqlCommand.QuerySelect" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.QuerySelect \- 
.PP
Summary description for \fBQuerySelect\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuerySelect\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "void \fBAddSelectFragmentString\fP (\fBSqlString\fP fragment)"
.br
.ti -1c
.RI "void \fBAddSelectColumn\fP (string columnName, string alias)"
.br
.ti -1c
.RI "void \fBSetWhereTokens\fP (IEnumerable tokens)"
.br
.ti -1c
.RI "void \fBSetGroupByTokens\fP (IEnumerable tokens)"
.br
.ti -1c
.RI "void \fBSetOrderByTokens\fP (IEnumerable tokens)"
.br
.ti -1c
.RI "void \fBSetHavingTokens\fP (IEnumerable tokens)"
.br
.ti -1c
.RI "void \fBAddOrderBy\fP (string orderBySql)"
.br
.RI "\fIAdds a string containing a valid 'order by' sql statement to this \fBQuerySelect\fP \fP"
.ti -1c
.RI "\fBSqlString\fP \fBToQuerySqlString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBJoinFragment\fP \fBJoinFragment\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBDistinct\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBQuerySelect\fP\&. 


.PP
Definition at line 11 of file QuerySelect\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.SqlCommand\&.QuerySelect\&.QuerySelect (\fBDialect\&.Dialect\fPdialect)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIdialect\fP 
.RE
.PP

.PP
Definition at line 99 of file QuerySelect\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.AddOrderBy (stringorderBySql)"

.PP
Adds a string containing a valid 'order by' sql statement to this \fBQuerySelect\fP 
.PP
\fBParameters:\fP
.RS 4
\fIorderBySql\fP The 'order by' sql statement\&.
.RE
.PP

.PP
Definition at line 197 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.AddSelectColumn (stringcolumnName, stringalias)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIcolumnName\fP 
.br
\fIalias\fP 
.RE
.PP

.PP
Definition at line 139 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.AddSelectFragmentString (\fBSqlString\fPfragment)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIfragment\fP 
.RE
.PP

.PP
Definition at line 114 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.SetGroupByTokens (IEnumerabletokens)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fItokens\fP 
.RE
.PP

.PP
Definition at line 166 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.SetHavingTokens (IEnumerabletokens)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fItokens\fP 
.RE
.PP

.PP
Definition at line 186 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.SetOrderByTokens (IEnumerabletokens)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fItokens\fP 
.RE
.PP

.PP
Definition at line 176 of file QuerySelect\&.cs\&.
.SS "void NHibernate\&.SqlCommand\&.QuerySelect\&.SetWhereTokens (IEnumerabletokens)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fItokens\fP 
.RE
.PP

.PP
Definition at line 155 of file QuerySelect\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "bool NHibernate\&.SqlCommand\&.QuerySelect\&.Distinct\fC [get]\fP, \fC [set]\fP"

.PP

.PP
Definition at line 146 of file QuerySelect\&.cs\&.
.SS "\fBJoinFragment\fP NHibernate\&.SqlCommand\&.QuerySelect\&.JoinFragment\fC [get]\fP"

.PP

.PP
Definition at line 106 of file QuerySelect\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
