.TH "NHibernate.Test.Events.Collections.CollectionListeners.AbstractListener" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Events.Collections.CollectionListeners.AbstractListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.IListener\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PostCollectionRecreateListener\fP, \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PostCollectionRemoveListener\fP, \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PostCollectionUpdateListener\fP, \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PreCollectionRecreateListener\fP, \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PreCollectionRemoveListener\fP, and \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PreCollectionUpdateListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddEvent\fP (\fBAbstractCollectionEvent\fP @event, \fBIListener\fP listener)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractListener\fP (\fBCollectionListeners\fP listeners)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file CollectionListeners\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
