.TH "NHibernate.MappingException" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.MappingException \- 
.PP
An exception that usually occurs at configuration time, rather than runtime, as a result of something screwy in the O-R mappings  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.HibernateException\fP\&.
.PP
Inherited by \fBNHibernate\&.Cfg\&.HibernateConfigException\fP, \fBNHibernate\&.DuplicateMappingException\fP, \fBNHibernate\&.FKUnmatchingColumnsException\fP, \fBNHibernate\&.InvalidProxyTypeException\fP, and \fBNHibernate\&.PropertyNotFoundException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMappingException\fP (string message)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.ti -1c
.RI "\fBMappingException\fP (Exception innerException)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.ti -1c
.RI "\fBMappingException\fP (string message, Exception innerException)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMappingException\fP (SerializationInfo info, StreamingContext context)"
.br
.RI "\fIInitializes a new instance of the \fBMappingException\fP class with serialized data\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An exception that usually occurs at configuration time, rather than runtime, as a result of something screwy in the O-R mappings 


.PP
Definition at line 11 of file MappingException\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.MappingException\&.MappingException (stringmessage)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.RE
.PP

.PP
Definition at line 17 of file MappingException\&.cs\&.
.SS "NHibernate\&.MappingException\&.MappingException (ExceptioninnerException)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinnerException\fP The exception that is the cause of the current exception\&. If the innerException parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception\&. 
.RE
.PP

.PP
Definition at line 30 of file MappingException\&.cs\&.
.SS "NHibernate\&.MappingException\&.MappingException (stringmessage, ExceptioninnerException)"

.PP
Initializes a new instance of the \fBMappingException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&. 
.br
\fIinnerException\fP The exception that is the cause of the current exception\&. If the innerException parameter is not a null reference, the current exception is raised in a catch block that handles the inner exception\&. 
.RE
.PP

.PP
Definition at line 44 of file MappingException\&.cs\&.
.SS "NHibernate\&.MappingException\&.MappingException (SerializationInfoinfo, StreamingContextcontext)\fC [protected]\fP"

.PP
Initializes a new instance of the \fBMappingException\fP class with serialized data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP The SerializationInfo that holds the serialized object data about the exception being thrown\&. 
.br
\fIcontext\fP The StreamingContext that contains contextual information about the source or destination\&. 
.RE
.PP

.PP
Definition at line 60 of file MappingException\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
