.TH "NHibernate.LoggerProvider" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.LoggerProvider \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetLoggersFactory\fP (\fBILoggerFactory\fP loggerFactory)"
.br
.ti -1c
.RI "static \fBIInternalLogger\fP \fBLoggerFor\fP (string keyName)"
.br
.ti -1c
.RI "static \fBIInternalLogger\fP \fBLoggerFor\fP (System\&.Type type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file Logging\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
