.TH "NHibernate.DomainModel.CompositeElement" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.CompositeElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompositeElement\fP ()"
.br
.RI "\fIDefault constructor for class \fBCompositeElement\fP \fP"
.ti -1c
.RI "\fBCompositeElement\fP (String foo, String bar)"
.br
.RI "\fIConstructor for class \fBCompositeElement\fP \fP"
.ti -1c
.RI "int \fBCompareTo\fP (object obj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "String \fBFoo\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for foo \fP"
.ti -1c
.RI "String \fBBar\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for bar \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file CompositeElement\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.DomainModel\&.CompositeElement\&.CompositeElement ()"

.PP
Default constructor for class \fBCompositeElement\fP 
.PP
Definition at line 20 of file CompositeElement\&.cs\&.
.SS "NHibernate\&.DomainModel\&.CompositeElement\&.CompositeElement (Stringfoo, Stringbar)"

.PP
Constructor for class \fBCompositeElement\fP 
.PP
\fBParameters:\fP
.RS 4
\fIfoo\fP Initial foo value
.br
\fIbar\fP Initial bar value
.RE
.PP

.PP
Definition at line 29 of file CompositeElement\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "String NHibernate\&.DomainModel\&.CompositeElement\&.Bar\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for bar 
.PP
Definition at line 52 of file CompositeElement\&.cs\&.
.SS "String NHibernate\&.DomainModel\&.CompositeElement\&.Foo\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for foo 
.PP
Definition at line 43 of file CompositeElement\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
