.TH "NHibernate.Test.ReadOnly.ReadOnlyCriteriaQueryTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.ReadOnly.ReadOnlyCriteriaQueryTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.ReadOnly\&.AbstractReadOnlyTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBModifiableSessionDefaultCriteria\fP ()"
.br
.ti -1c
.RI "void \fBModifiableSessionReadOnlyCriteria\fP ()"
.br
.ti -1c
.RI "void \fBModifiableSessionModifiableCriteria\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlySessionDefaultCriteria\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlySessionReadOnlyCriteria\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlySessionModifiableCriteria\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlyCriteriaReturnsModifiableExistingEntity\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlyCriteriaReturnsExistingModifiableProxyNotInit\fP ()"
.br
.ti -1c
.RI "void \fBReadOnlyCriteriaReturnsExistingModifiableProxyInit\fP ()"
.br
.ti -1c
.RI "void \fBModifiableCriteriaReturnsExistingReadOnlyEntity\fP ()"
.br
.ti -1c
.RI "void \fBModifiableCriteriaReturnsExistingReadOnlyProxyNotInit\fP ()"
.br
.ti -1c
.RI "void \fBModifiableCriteriaReturnsExistingReadOnlyProxyInit\fP ()"
.br
.ti -1c
.RI "void \fBSubselect\fP ()"
.br
.ti -1c
.RI "void \fBDetachedCriteria\fP ()"
.br
.ti -1c
.RI "void \fBTwoAliasesCache\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConfigure\fP (\fBConfiguration\fP configuration)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ReadOnlyCriteriaQueryTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
