.TH "NHibernate.DomainModel.Category" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Category \- 
.PP
Summary description for \fBCategory\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly string \fBRootCategory\fP = '/'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList \fBSubcategories\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBAssignable\fP \fBAssignable\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBCategory\fP\&. 


.PP
Definition at line 9 of file Category\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
