.TH "NHibernate.Mapping.ByCode.PropertyGeneration" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.PropertyGeneration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.PropertyGeneration\&.AlwaysPropertyGeneration\fP, \fBNHibernate\&.Mapping\&.ByCode\&.PropertyGeneration\&.InsertPropertyGeneration\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.PropertyGeneration\&.NeverPropertyGeneration\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlwaysPropertyGeneration\fP"
.br
.ti -1c
.RI "class \fBInsertPropertyGeneration\fP"
.br
.ti -1c
.RI "class \fBNeverPropertyGeneration\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPropertyGeneration\fP \fBNever\fP = new \fBNeverPropertyGeneration\fP()"
.br
.ti -1c
.RI "static \fBPropertyGeneration\fP \fBInsert\fP = new \fBInsertPropertyGeneration\fP()"
.br
.ti -1c
.RI "static \fBPropertyGeneration\fP \fBAlways\fP = new \fBAlwaysPropertyGeneration\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PropertyGeneration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
