.TH "NHibernate.Cache.ReadWriteCache.ILockable" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cache.ReadWriteCache.ILockable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Cache\&.CachedItem\fP, and \fBNHibernate\&.Cache\&.CacheLock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCacheLock\fP \fBLock\fP (long timeout, int id)"
.br
.ti -1c
.RI "bool \fBIsGettable\fP (long txTimestamp)"
.br
.ti -1c
.RI "bool \fBIsPuttable\fP (long txTimestamp, object newVersion, IComparer comparator)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsLock\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file ReadWriteCache\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
