.TH "NHibernate.Test.Criteria.MaterialUnit" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.MaterialUnit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMaterialUnit\fP (\fBMaterialUnitable\fP material, string serialNumber)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMaterialUnitable\fP \fBMaterial\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBSerialNumber\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file MaterialResource\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
