.TH "NHibernate.Mapping.ByCode.IIdMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IIdMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IAccessorPropertyMapper\fP\&.
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.IdMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGenerator\fP (\fBIGeneratorDef\fP generator)"
.br
.ti -1c
.RI "void \fBGenerator\fP (\fBIGeneratorDef\fP generator, Action< \fBIGeneratorMapper\fP > generatorMapping)"
.br
.ti -1c
.RI "void \fBType\fP (\fBIIdentifierType\fP persistentType)"
.br
.ti -1c
.RI "void \fBUnsavedValue\fP (object value)"
.br
.ti -1c
.RI "void \fBColumn\fP (string name)"
.br
.ti -1c
.RI "void \fBLength\fP (int length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file IIdMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
