.TH "NHibernate.Test.Linq.ParameterisedQueries" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.ParameterisedQueries \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.ReadonlyTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIdentical_Expressions_Return_The_Same_Key\fP ()"
.br
.ti -1c
.RI "void \fBExpressions_Differing_Only_By_Constants_Return_The_Same_Key\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Where_Clauses_Return_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Select_Properties_Return_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Select_Types_Return_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Select_Member_Initialisation_Returns_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Conditionals_Return_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Unary_Operation_Returns_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_OfType_Returns_Different_Keys\fP ()"
.br
.ti -1c
.RI "void \fBDifferent_Null_Returns_Different_Keys\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file ParameterisedQueries\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
