.TH "NHibernate.Test.Subclass.SubclassOne" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Subclass.SubclassOne \- 
.PP
Summary description for JoinedSubclassOne\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Subclass\&.SubclassBase\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBOneTestLong\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for JoinedSubclassOne\&. 


.PP
Definition at line 8 of file SubclassOne\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
