.TH "NHibernate.Type.DateTimeType" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Type.DateTimeType \- 
.PP
Maps a System\&.DateTime Property to a DbType\&.DateTime column that stores date & time down to the accuracy of a second\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Type\&.PrimitiveType\fP, \fBNHibernate\&.Type\&.IIdentifierType\fP, \fBNHibernate\&.Type\&.ILiteralType\fP, and \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Inherited by \fBNHibernate\&.Type\&.AbstractDateTimeSpecificKindType\fP, and \fBNHibernate\&.Type\&.DateTime2Type\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateTimeType\fP ()"
.br
.ti -1c
.RI "\fBDateTimeType\fP (\fBSqlType\fP sqlTypeDateTime)"
.br
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, int index)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override object \fBGet\fP (IDataReader rs, string name)"
.br
.RI "\fIWhen implemented by a class, gets the object in the IDataReader for the Property\&. \fP"
.ti -1c
.RI "override void \fBSet\fP (IDbCommand st, object value, int index)"
.br
.RI "\fIWhen implemented by a class, put the value from the mapped Property into to the IDbCommand\&. \fP"
.ti -1c
.RI "virtual object \fBNext\fP (object current, \fBISessionImplementor\fP session)"
.br
.RI "\fIWhen implemented by a class, increments the version\&. \fP"
.ti -1c
.RI "virtual object \fBSeed\fP (\fBISessionImplementor\fP session)"
.br
.RI "\fIWhen implemented by a class, gets an initial version\&. \fP"
.ti -1c
.RI "override bool \fBIsEqual\fP (object x, object y)"
.br
.RI "\fIAre the two version values considered equal? \fP"
.ti -1c
.RI "override int \fBGetHashCode\fP (object x, \fBEntityMode\fP entityMode)"
.br
.RI "\fIGet a hashcode, consistent with persistence 'equality'\fP"
.ti -1c
.RI "override string \fBToString\fP (object val)"
.br
.RI "\fIA representation of the value to be embedded in an XML element \fP"
.ti -1c
.RI "object \fBStringToObject\fP (string xml)"
.br
.RI "\fIWhen implemented by a class, converts the xml string from the mapping file to the \&.NET object\&. \fP"
.ti -1c
.RI "override object \fBFromStringValue\fP (string xml)"
.br
.ti -1c
.RI "override string \fBObjectToSQLString\fP (object value, \fBDialect\&.Dialect\fP dialect)"
.br
.RI "\fIWhen implemented by a class, return a string representation of the value, suitable for embedding in an SQL statement \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBReturnedClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual IComparer \fBComparator\fP\fC [get]\fP"
.br
.ti -1c
.RI "override System\&.Type \fBPrimitiveClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "override object \fBDefaultValue\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Maps a System\&.DateTime Property to a DbType\&.DateTime column that stores date & time down to the accuracy of a second\&. 

This only stores down to a second, so if you are looking for the most accurate date and time storage your provider can give you use the \fBTimestampType\fP\&. or the \fBTicksType\fP 
.PP
Definition at line 20 of file DateTimeType\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Type\&.DateTimeType\&.DateTimeType ()"

.PP

.PP
Definition at line 25 of file DateTimeType\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override object NHibernate\&.Type\&.DateTimeType\&.Get (IDataReaderrs, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIindex\fP The index of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 39 of file DateTimeType\&.cs\&.
.SS "override object NHibernate\&.Type\&.DateTimeType\&.Get (IDataReaderrs, stringname)\fC [virtual]\fP"

.PP
When implemented by a class, gets the object in the IDataReader for the Property\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrs\fP The IDataReader that contains the value\&.
.br
\fIname\fP The name of the field to get the value from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An object with the value from the database\&.
.RE
.PP
.PP
Most implementors just call the \fBGet(IDataReader, int)\fP overload of this method\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 52 of file DateTimeType\&.cs\&.
.SS "override int NHibernate\&.Type\&.DateTimeType\&.GetHashCode (objectx, \fBEntityMode\fPentityMode)"

.PP
Get a hashcode, consistent with persistence 'equality'
.PP
\fBParameters:\fP
.RS 4
\fIx\fP 
.br
\fIentityMode\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IType\fP\&.
.PP
Definition at line 114 of file DateTimeType\&.cs\&.
.SS "override bool NHibernate\&.Type\&.DateTimeType\&.IsEqual (objectx, objecty)"

.PP
Are the two version values considered equal? 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP One value to check\&. 
.br
\fIy\fP The other value to check\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the values are equal, false otherwise\&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Definition at line 81 of file DateTimeType\&.cs\&.
.SS "virtual object NHibernate\&.Type\&.DateTimeType\&.Next (objectcurrent, \fBISessionImplementor\fPsession)\fC [virtual]\fP"

.PP
When implemented by a class, increments the version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcurrent\fP The current version
.br
\fIsession\fP The current session, if available\&.
.RE
.PP
\fBReturns:\fP
.RS 4
an instance of the \fBIType\fP that has been incremented\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Definition at line 71 of file DateTimeType\&.cs\&.
.SS "override string NHibernate\&.Type\&.DateTimeType\&.ObjectToSQLString (objectvalue, \fBDialect\&.Dialect\fPdialect)"

.PP
When implemented by a class, return a string representation of the value, suitable for embedding in an SQL statement 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The object to convert to a string for the SQL statement\&.
.br
\fIdialect\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
A string that contains a well formed SQL Statement\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.ILiteralType\fP\&.
.PP
Definition at line 157 of file DateTimeType\&.cs\&.
.SS "virtual object NHibernate\&.Type\&.DateTimeType\&.Seed (\fBISessionImplementor\fPsession)\fC [virtual]\fP"

.PP
When implemented by a class, gets an initial version\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The current session, if available\&.
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of the type\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.IVersionType\fP\&.
.PP
Definition at line 76 of file DateTimeType\&.cs\&.
.SS "override void NHibernate\&.Type\&.DateTimeType\&.Set (IDbCommandcmd, objectvalue, intindex)\fC [virtual]\fP"

.PP
When implemented by a class, put the value from the mapped Property into to the IDbCommand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcmd\fP The IDbCommand to put the value into\&.
.br
\fIvalue\fP The object that contains the value\&.
.br
\fIindex\fP The index of the IDbDataParameter to start writing the values to\&.
.RE
.PP
.PP
Implementors do not need to handle possibility of null values because this will only be called from \fBNullSafeSet(IDbCommand, object, int)\fP after it has checked for nulls\&. 
.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 62 of file DateTimeType\&.cs\&.
.SS "object NHibernate\&.Type\&.DateTimeType\&.StringToObject (stringxml)"

.PP
When implemented by a class, converts the xml string from the mapping file to the \&.NET object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIxml\fP The value of \fCdiscriminator-value\fP or \fCunsaved-value\fP attribute\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The string converted to the object\&.
.RE
.PP
.PP
This method needs to be able to handle any string\&. It should not just call System\&.Type\&.Parse without verifying that it is a parsable value for the System\&.Type\&. 
.PP
Implements \fBNHibernate\&.Type\&.IIdentifierType\fP\&.
.PP
Definition at line 137 of file DateTimeType\&.cs\&.
.SS "override string NHibernate\&.Type\&.DateTimeType\&.ToString (objectval)\fC [virtual]\fP"

.PP
A representation of the value to be embedded in an XML element 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP The object that contains the values\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
An Xml formatted string\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Type\&.NullableType\fP\&.
.PP
Definition at line 132 of file DateTimeType\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "override string NHibernate\&.Type\&.DateTimeType\&.Name\fC [get]\fP"

.PP

.PP
Definition at line 35 of file DateTimeType\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
