.TH "NHibernate.Engine.RowSelection" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.RowSelection \- 
.PP
Information to determine how to run an IDbCommand and what records to return from the IDataReader\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly int \fBNoValue\fP = -1"
.br
.RI "\fIIndicates that the no value has been set on the Property\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBFirstRow\fP\fC [get, set]\fP"
.br
.RI "\fIGets or Sets the Index of the First Row to Select \fP"
.ti -1c
.RI "int \fBMaxRows\fP\fC [get, set]\fP"
.br
.RI "\fIGets or Sets the Maximum Number of Rows to Select \fP"
.ti -1c
.RI "int \fBTimeout\fP\fC [get, set]\fP"
.br
.RI "\fIGets or Sets the Timeout of the \fBQuery\fP \fP"
.ti -1c
.RI "int \fBFetchSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBDefinesLimits\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information to determine how to run an IDbCommand and what records to return from the IDataReader\&. 


.PP
Definition at line 10 of file RowSelection\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly int NHibernate\&.Engine\&.RowSelection\&.NoValue = -1\fC [static]\fP"

.PP
Indicates that the no value has been set on the Property\&. 
.PP
Definition at line 15 of file RowSelection\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int NHibernate\&.Engine\&.RowSelection\&.FirstRow\fC [get]\fP, \fC [set]\fP"

.PP
Gets or Sets the Index of the First Row to Select The Index of the First Rows to Select
.PP
Defaults to 0 unless specifically set\&.
.PP
Definition at line 28 of file RowSelection\&.cs\&.
.SS "int NHibernate\&.Engine\&.RowSelection\&.MaxRows\fC [get]\fP, \fC [set]\fP"

.PP
Gets or Sets the Maximum Number of Rows to Select The Maximum Number of Rows to Select
.PP
Defaults to NoValue unless specifically set\&.
.PP
Definition at line 39 of file RowSelection\&.cs\&.
.SS "int NHibernate\&.Engine\&.RowSelection\&.Timeout\fC [get]\fP, \fC [set]\fP"

.PP
Gets or Sets the Timeout of the \fBQuery\fP The \fBQuery\fP Timeout
.PP
Defaults to NoValue unless specifically set\&.
.PP
Definition at line 50 of file RowSelection\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
