.TH "NHibernate.Test.MappingTest.NonReflectiveBinderFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingTest.NonReflectiveBinderFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP ()"
.br
.ti -1c
.RI "void \fBTearDown\fP ()"
.br
.ti -1c
.RI "void \fBMetaInheritance\fP ()"
.br
.ti -1c
.RI "void \fBNonMutatedInheritance\fP ()"
.br
.ti -1c
.RI "void \fBComparator\fP ()"
.br
.ti -1c
.RI "void \fBReadSubClasses\fP ()"
.br
.ti -1c
.RI "void \fBXmlSerialization\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file NonReflectiveBinderFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
