.TH "NHibernate.Test.NHSpecificTest.NH0000.ByCodeFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH0000.ByCodeFixture \- 
.PP
\fBFixture\fP using 'by code' mappings  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCaseMappingByCode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBYourTestName\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBHbmMapping\fP \fBGetMappings\fP ()"
.br
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBFixture\fP using 'by code' mappings 

This fixture is identical to \fBFixture\fP except the \fBEntity\fP mapping is performed by code in the GetMappings method, and does not require the \fCMappings\&.hbm\&.xml\fP file\&. Use this approach if you prefer\&. 
.PP
Definition at line 17 of file FixtureByCode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
