.TH "NHibernate.Hql.Ast.ANTLR.Tree.ASTFactory" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.ASTFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IASTFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBASTFactory\fP (ITreeAdaptor adaptor)"
.br
.ti -1c
.RI "\fBIASTNode\fP \fBCreateNode\fP (int type, string text, params \fBIASTNode\fP[] children)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ASTFactory\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
