.TH "NHibernate.Criterion.Expression" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.Expression \- 
.PP
This class is semi-deprecated\&. Use \fBRestrictions\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Criterion\&.Restrictions\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (\fBSqlString\fP sql, object[] values, \fBIType\fP[] types)"
.br
.RI "\fIApply a constraint expressed in SQL, with the given SQL parameters \fP"
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (\fBSqlString\fP sql, object value, \fBIType\fP type)"
.br
.RI "\fIApply a constraint expressed in SQL, with the given SQL parameter \fP"
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (string sql, object value, \fBIType\fP type)"
.br
.RI "\fIApply a constraint expressed in SQL, with the given SQL parameter \fP"
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (string sql, object[] values, \fBIType\fP[] types)"
.br
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (\fBSqlString\fP sql)"
.br
.RI "\fIApply a constraint expressed in SQL \fP"
.ti -1c
.RI "static \fBAbstractCriterion\fP \fBSql\fP (string sql)"
.br
.RI "\fIApply a constraint expressed in SQL \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class is semi-deprecated\&. Use \fBRestrictions\fP\&. 


.PP
\fBSee Also:\fP
.RS 4
\fBRestrictions\fP
.PP
.RE
.PP

.PP
Definition at line 11 of file Expression\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBAbstractCriterion\fP NHibernate\&.Criterion\&.Expression\&.Sql (\fBSqlString\fPsql, object[]values, \fBIType\fP[]types)\fC [static]\fP"

.PP
Apply a constraint expressed in SQL, with the given SQL parameters 
.PP
\fBParameters:\fP
.RS 4
\fIsql\fP 
.br
\fIvalues\fP 
.br
\fItypes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 25 of file Expression\&.cs\&.
.SS "static \fBAbstractCriterion\fP NHibernate\&.Criterion\&.Expression\&.Sql (\fBSqlString\fPsql, objectvalue, \fBIType\fPtype)\fC [static]\fP"

.PP
Apply a constraint expressed in SQL, with the given SQL parameter 
.PP
\fBParameters:\fP
.RS 4
\fIsql\fP 
.br
\fIvalue\fP 
.br
\fItype\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 37 of file Expression\&.cs\&.
.SS "static \fBAbstractCriterion\fP NHibernate\&.Criterion\&.Expression\&.Sql (stringsql, objectvalue, \fBIType\fPtype)\fC [static]\fP"

.PP
Apply a constraint expressed in SQL, with the given SQL parameter 
.PP
Definition at line 45 of file Expression\&.cs\&.
.SS "static \fBAbstractCriterion\fP NHibernate\&.Criterion\&.Expression\&.Sql (\fBSqlString\fPsql)\fC [static]\fP"

.PP
Apply a constraint expressed in SQL 
.PP
\fBParameters:\fP
.RS 4
\fIsql\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 60 of file Expression\&.cs\&.
.SS "static \fBAbstractCriterion\fP NHibernate\&.Criterion\&.Expression\&.Sql (stringsql)\fC [static]\fP"

.PP
Apply a constraint expressed in SQL 
.PP
\fBParameters:\fP
.RS 4
\fIsql\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 70 of file Expression\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
