.TH "NHibernate.Test.NHSpecificTest.NH464.DateRange" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH464.DateRange \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDateRange\fP (DateTime start, DateTime end)"
.br
.ti -1c
.RI "bool \fBContains\fP (DateTime date)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBDateRange\fP \fBInfinite\fP = new \fBDateRange\fP(new DateTime(2001, 1, 1), new DateTime(2050, 12, 31))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBStart\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "DateTime \fBEnd\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file DateRange\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
