.TH "NHibernate.Test.NHSpecificTest.NH372.Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH372.Fixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.BugTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBComponentFieldNotInserted\fP ()"
.br
.ti -1c
.RI "void \fBComponentFieldNotInserted_Dynamic\fP ()"
.br
.ti -1c
.RI "void \fBComponentFieldNotUpdated\fP ()"
.br
.ti -1c
.RI "void \fBComponentFieldNotUpdated_Dynamic\fP ()"
.br
.ti -1c
.RI "void \fBSubComponentFieldNotInserted\fP ()"
.br
.ti -1c
.RI "void \fBSubComponentFieldNotInserted_Dynamic\fP ()"
.br
.ti -1c
.RI "void \fBSubComponentFieldNotUpdated\fP ()"
.br
.ti -1c
.RI "void \fBSubComponentFieldNotUpdated_Dynamic\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBisDynamic\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBBugNumber\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
