.TH "NHibernate.Hql.Ast.ANTLR.Tree.UnaryLogicOperatorNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.UnaryLogicOperatorNode \- 
.PP
Represents a unary operator node\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.HqlSqlWalkerNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IUnaryOperatorNode\fP\&.
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractNullnessCheckNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnaryLogicOperatorNode\fP (IToken token)"
.br
.ti -1c
.RI "virtual void \fBInitialize\fP ()"
.br
.RI "\fICalled by the tree walker during hql-sql semantic analysis after the operator sub-tree is completely built\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIASTNode\fP \fBOperand\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBIType\fP \fBDataType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a unary operator node\&. 

Author: Steve Ebersole Ported by: Steve Strong 
.PP
Definition at line 14 of file UnaryLogicOperatorNode\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.UnaryLogicOperatorNode\&.Initialize ()\fC [virtual]\fP"

.PP
Called by the tree walker during hql-sql semantic analysis after the operator sub-tree is completely built\&. 
.PP
Implements \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IOperatorNode\fP\&.
.PP
Reimplemented in \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.AbstractNullnessCheckNode\fP\&.
.PP
Definition at line 25 of file UnaryLogicOperatorNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
