.TH "NHibernate.Mapping.IFilterable" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.IFilterable \- 
.PP
Defines mapping elements to which filters may be applied\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Mapping\&.Collection\fP, \fBNHibernate\&.Mapping\&.PersistentClass\fP, and \fBNHibernate\&.Test\&.FilterTest\&.FilterSecondPassArgsFixture\&.FakeFilterable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddFilter\fP (string name, string condition)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IDictionary< string, string > \fBFilterMap\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines mapping elements to which filters may be applied\&. 


.PP
Definition at line 8 of file IFilterable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
