.TH "NHibernate.Mapping.ByCode.Impl.CustomizersImpl.ComponentElementCustomizer< TComponent >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.CustomizersImpl.ComponentElementCustomizer< TComponent > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IComponentElementMapper< TComponent >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComponentElementCustomizer\fP (\fBIModelExplicitDeclarationsHolder\fP explicitDeclarationsHolder, \fBPropertyPath\fP propertyPath, \fBICustomizersHolder\fP customizersHolder)"
.br
.ti -1c
.RI "void \fBParent< TProperty >\fP (Expression< Func< TComponent, TProperty >> parent)"
.br
.ti -1c
.RI "void \fBParent< TProperty >\fP (Expression< Func< TComponent, TProperty >> parent, Action< \fBIComponentParentMapper\fP > parentMapping)"
.br
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.ti -1c
.RI "void \fBLazy\fP (bool isLazy)"
.br
.ti -1c
.RI "void \fBUnique\fP (bool unique)"
.br
.ti -1c
.RI "void \fBClass< TConcrete >\fP ()"
.br
.ti -1c
.RI "void \fBProperty< TProperty >\fP (Expression< Func< TComponent, TProperty >> property, Action< \fBIPropertyMapper\fP > mapping)"
.br
.ti -1c
.RI "void \fBProperty< TProperty >\fP (Expression< Func< TComponent, TProperty >> property)"
.br
.ti -1c
.RI "void \fBComponent< TNestedComponent >\fP (Expression< Func< TComponent, TNestedComponent >> property, Action< \fBIComponentElementMapper\fP< TNestedComponent >> mapping)"
.br
.ti -1c
.RI "void \fBManyToOne< TProperty >\fP (Expression< Func< TComponent, TProperty >> property, Action< \fBIManyToOneMapper\fP > mapping)"
.br
.ti -1c
.RI "void \fBManyToOne< TProperty >\fP (Expression< Func< TComponent, TProperty >> property)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.ti -1c
.RI "void \fBOptimisticLock\fP (bool takeInConsiderationForOptimisticLock)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ComponentElementCustomizer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
