.TH "NHibernate.Test.MappingByCode.MappersTests.SubclassMapperTests.TablesSincronizationTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.MappersTests.SubclassMapperTests.TablesSincronizationTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenSetSyncWithNullThenDoesNotThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetSyncMixedWithNullAndEmptyThenAddOnlyValid\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetMoreSyncThenAddAll\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetMoreThenOnceThenAddAll\fP ()"
.br
.ti -1c
.RI "void \fBWhenSetMoreThenOnceThenDoesNotDuplicate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file TablesSincronizationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
