.TH "NHibernate.Mapping.ByCode.Impl.CustomizersImpl.JoinedSubclassCustomizer< TEntity >" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.CustomizersImpl.JoinedSubclassCustomizer< TEntity > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.CustomizersImpl\&.PropertyContainerCustomizer< TEntity >\fP, \fBNHibernate\&.Mapping\&.ByCode\&.IJoinedSubclassMapper< TEntity >\fP, and \fBNHibernate\&.Mapping\&.ByCode\&.IConformistHoldersProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoinedSubclassCustomizer\fP (\fBIModelExplicitDeclarationsHolder\fP explicitDeclarationsHolder, \fBICustomizersHolder\fP customizersHolder)"
.br
.ti -1c
.RI "void \fBKey\fP (Action< \fBIKeyMapper\fP< TEntity >> keyMapping)"
.br
.ti -1c
.RI "void \fBSchemaAction\fP (SchemaAction action)"
.br
.ti -1c
.RI "void \fBEntityName\fP (string value)"
.br
.ti -1c
.RI "void \fBProxy\fP (System\&.Type proxy)"
.br
.ti -1c
.RI "void \fBLazy\fP (bool value)"
.br
.ti -1c
.RI "void \fBDynamicUpdate\fP (bool value)"
.br
.ti -1c
.RI "void \fBDynamicInsert\fP (bool value)"
.br
.ti -1c
.RI "void \fBBatchSize\fP (int value)"
.br
.ti -1c
.RI "void \fBSelectBeforeUpdate\fP (bool value)"
.br
.ti -1c
.RI "void \fBPersister< T >\fP ()"
.br
.ti -1c
.RI "void \fBSynchronize\fP (params string[] table)"
.br
.ti -1c
.RI "void \fBLoader\fP (string namedQueryReference)"
.br
.ti -1c
.RI "void \fBSqlInsert\fP (string sql)"
.br
.ti -1c
.RI "void \fBSqlUpdate\fP (string sql)"
.br
.ti -1c
.RI "void \fBSqlDelete\fP (string sql)"
.br
.ti -1c
.RI "void \fBSubselect\fP (string sql)"
.br
.ti -1c
.RI "void \fBTable\fP (string tableName)"
.br
.ti -1c
.RI "void \fBCatalog\fP (string catalogName)"
.br
.ti -1c
.RI "void \fBSchema\fP (string schemaName)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITEntity\fP : \fIclass\fP
.PP
Definition at line 6 of file JoinedSubclassCustomizer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
