.TH "NHibernate.Loader.Entity.CascadeEntityJoinWalker" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.Entity.CascadeEntityJoinWalker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Loader\&.AbstractEntityJoinWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCascadeEntityJoinWalker\fP (\fBIOuterJoinLoadable\fP persister, \fBCascadingAction\fP action, \fBISessionFactoryImplementor\fP factory)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBIsJoinedFetchEnabled\fP (\fBIAssociationType\fP type, \fBFetchMode\fP config, \fBCascadeStyle\fP cascadeStyle)"
.br
.RI "\fIThe superclass deliberately excludes collections \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsTooManyCollections\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBComment\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file CascadeEntityJoinWalker\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool NHibernate\&.Loader\&.Entity\&.CascadeEntityJoinWalker\&.IsJoinedFetchEnabled (\fBIAssociationType\fPtype, \fBFetchMode\fPconfig, \fBCascadeStyle\fPcascadeStyle)\fC [protected]\fP, \fC [virtual]\fP"

.PP
The superclass deliberately excludes collections 
.PP
Reimplemented from \fBNHibernate\&.Loader\&.AbstractEntityJoinWalker\fP\&.
.PP
Definition at line 25 of file CascadeEntityJoinWalker\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
