.TH "NHibernate.SqlCommand.WhereBuilder" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.WhereBuilder \- 
.PP
Allows us to construct SQL WHERE fragments  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.SqlCommand\&.SqlBaseBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWhereBuilder\fP (\fBDialect\&.Dialect\fP dialect, \fBISessionFactoryImplementor\fP factory)"
.br
.ti -1c
.RI "\fBSqlString\fP \fBWhereClause\fP (string alias, string[] columnNames, \fBIType\fP whereType)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Allows us to construct SQL WHERE fragments 


.PP
Definition at line 9 of file WhereBuilder\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
