.TH "NHibernate.SqlCommand" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBParser\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlias\fP"
.br
.RI "\fIAliases tables and fields for Sql Statements\&. \fP"
.ti -1c
.RI "class \fBANSICaseFragment\fP"
.br
.RI "\fIAn ANSI SQL CASE expression\&. \fP"
.ti -1c
.RI "class \fBANSIJoinFragment\fP"
.br
.RI "\fIAn ANSI-style Join\&. \fP"
.ti -1c
.RI "class \fBCaseFragment\fP"
.br
.RI "\fIAbstract SQL case fragment renderer \fP"
.ti -1c
.RI "class \fBConditionalFragment\fP"
.br
.ti -1c
.RI "class \fBDecodeCaseFragment\fP"
.br
.RI "\fIAn Oracle-style DECODE function\&. \fP"
.ti -1c
.RI "class \fBDisjunctionFragment\fP"
.br
.ti -1c
.RI "class \fBForUpdateFragment\fP"
.br
.RI "\fIRepresents an SQL \fCfor update of \&.\&.\&. nowait\fP statement \fP"
.ti -1c
.RI "class \fBInformixJoinFragment\fP"
.br
.RI "\fIAn Informix-style (theta) Join \fP"
.ti -1c
.RI "class \fBInFragment\fP"
.br
.RI "\fIRepresents an \fC\&.\&.\&. in (\&.\&.\&.)\fP expression \fP"
.ti -1c
.RI "class \fBInsertSelect\fP"
.br
.ti -1c
.RI "interface \fBISqlStringBuilder\fP"
.br
.ti -1c
.RI "interface \fBISqlStringVisitor\fP"
.br
.ti -1c
.RI "class \fBJoinFragment\fP"
.br
.RI "\fIRepresents a SQL \fCJOIN\fP \fP"
.ti -1c
.RI "class \fBOracleJoinFragment\fP"
.br
.RI "\fIAn Oracle-style (theta) Join \fP"
.ti -1c
.RI "class \fBParameter\fP"
.br
.RI "\fIA placeholder for an ADO\&.NET parameter in an \fBSqlString\fP\&. \fP"
.ti -1c
.RI "class \fBQueryJoinFragment\fP"
.br
.RI "\fISummary description for \fBQueryJoinFragment\fP\&. \fP"
.ti -1c
.RI "class \fBQuerySelect\fP"
.br
.RI "\fISummary description for \fBQuerySelect\fP\&. \fP"
.ti -1c
.RI "class \fBSelectFragment\fP"
.br
.RI "\fIRepresents part of an SQL \fCSELECT\fP clause \fP"
.ti -1c
.RI "class \fBSqlBaseBuilder\fP"
.br
.RI "\fIThe base class for all of the SqlBuilders\&. \fP"
.ti -1c
.RI "interface \fBISqlCommand\fP"
.br
.ti -1c
.RI "class \fBSqlCommandImpl\fP"
.br
.ti -1c
.RI "class \fBSqlCommandInfo\fP"
.br
.ti -1c
.RI "class \fBSqlDeleteBuilder\fP"
.br
.RI "\fIA class that builds an \fCDELETE\fP sql statement\&. \fP"
.ti -1c
.RI "class \fBSqlInsertBuilder\fP"
.br
.RI "\fIA class that builds an \fCINSERT\fP sql statement\&. \fP"
.ti -1c
.RI "class \fBSqlSelectBuilder\fP"
.br
.RI "\fIBuilds a \fCSELECT\fP SQL statement\&. \fP"
.ti -1c
.RI "class \fBSqlSimpleSelectBuilder\fP"
.br
.RI "\fISummary description for \fBSqlSimpleSelectBuilder\fP\&. \fP"
.ti -1c
.RI "class \fBSqlString\fP"
.br
.RI "\fIThis is a non-modifiable SQL statement that is ready to be prepared and sent to the Database for execution\&. \fP"
.ti -1c
.RI "class \fBSqlStringBuilder\fP"
.br
.RI "\fIThe \fBSqlStringBuilder\fP is used to construct a \fBSqlString\fP\&. \fP"
.ti -1c
.RI "class \fBSqlStringHelper\fP"
.br
.RI "\fIHelper methods for \fBSqlString\fP\&. \fP"
.ti -1c
.RI "class \fBSqlUpdateBuilder\fP"
.br
.RI "\fIA class that builds an \fCUPDATE\fP sql statement\&. \fP"
.ti -1c
.RI "class \fBSubselectClauseExtractor\fP"
.br
.RI "\fIGiven an SQL SELECT statement, parse it to extract clauses starting with \fCFROM\fP, up to and not including \fCORDER BY\fP (known collectively as a subselect clause)\&. \fP"
.ti -1c
.RI "class \fBTemplate\fP"
.br
.ti -1c
.RI "class \fBWhereBuilder\fP"
.br
.RI "\fIAllows us to construct SQL WHERE fragments \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBJoinType\fP { \fBNone\fP = -666, \fBInnerJoin\fP = 0, \fBFullJoin\fP = 4, \fBLeftOuterJoin\fP = 1, \fBRightOuterJoin\fP = 2 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNHibernate\&.SqlCommand\&.JoinType\fP"

.PP

.PP
Definition at line 6 of file JoinFragment\&.cs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
