.TH "NHibernate.DomainModel.GlarchProxy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.GlarchProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.DomainModel\&.Glarch\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVersion\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBDerivedVersion\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBGlarchProxy\fP \fBNext\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "short \fBOrder\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList \fBStrings\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IDictionary \fBDynaBean\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ISet< string > \fBStringSets\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "IList \fBFooComponents\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBGlarchProxy\fP[] \fBProxyArray\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ISet< \fBGlarchProxy\fP > \fBProxySet\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBMultiplicity\fP \fBMultiple\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "object \fBAny\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file GlarchProxy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
