.TH "NHibernate.Mapping.Join" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.Join \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ISqlCustomizable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddProperty\fP (\fBProperty\fP prop)"
.br
.ti -1c
.RI "bool \fBContainsProperty\fP (\fBProperty\fP prop)"
.br
.ti -1c
.RI "void \fBCreateForeignKey\fP ()"
.br
.ti -1c
.RI "void \fBCreatePrimaryKey\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "void \fBSetCustomSQLInsert\fP (string sql, bool callable, \fBExecuteUpdateResultCheckStyle\fP checkStyle)"
.br
.ti -1c
.RI "void \fBSetCustomSQLDelete\fP (string sql, bool callable, \fBExecuteUpdateResultCheckStyle\fP checkStyle)"
.br
.ti -1c
.RI "void \fBSetCustomSQLUpdate\fP (string sql, bool callable, \fBExecuteUpdateResultCheckStyle\fP checkStyle)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IEnumerable< \fBProperty\fP > \fBPropertyIterator\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual \fBTable\fP \fBTable\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBIKeyValue\fP \fBKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual \fBPersistentClass\fP \fBPersistentClass\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPropertySpan\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSqlString\fP \fBCustomSQLInsert\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSqlString\fP \fBCustomSQLDelete\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBSqlString\fP \fBCustomSQLUpdate\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsCustomInsertCallable\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsCustomDeleteCallable\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsCustomUpdateCallable\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBExecuteUpdateResultCheckStyle\fP \fBCustomSQLInsertCheckStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBExecuteUpdateResultCheckStyle\fP \fBCustomSQLDeleteCheckStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBExecuteUpdateResultCheckStyle\fP \fBCustomSQLUpdateCheckStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSequentialSelect\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsInverse\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsLazy\fP\fC [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOptional\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Join\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
