.TH "NHibernate.Hql.Ast.HqlConstant" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.HqlConstant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.HqlExpression\fP\&.
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.HqlDecimalConstant\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlDoubleConstant\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlFalse\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlFloatConstant\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlIntegerConstant\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlNull\fP, \fBNHibernate\&.Hql\&.Ast\&.HqlStringConstant\fP, and \fBNHibernate\&.Hql\&.Ast\&.HqlTrue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlConstant\fP (\fBIASTFactory\fP factory, int type, string value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 379 of file HqlTreeNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
