.TH "NHibernate.Transaction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Transaction \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdoNetTransactionFactory\fP"
.br
.ti -1c
.RI "class \fBAdoNetWithDistributedTransactionFactory\fP"
.br
.ti -1c
.RI "class \fBAdoTransaction\fP"
.br
.RI "\fIWraps an ADO\&.NET IDbTransaction to implement the \fBITransaction\fP interface\&. \fP"
.ti -1c
.RI "interface \fBISynchronization\fP"
.br
.RI "\fIA mimic to the javax\&.transaction\&.Synchronization callback to enable \fBITransaction\&.RegisterSynchronization\fP \fP"
.ti -1c
.RI "interface \fBITransactionContext\fP"
.br
.RI "\fIThis is used as a marker interface for the different transaction context required for each session \fP"
.ti -1c
.RI "interface \fBITransactionFactory\fP"
.br
.RI "\fIAn abstract factory for \fBITransaction\fP instances\&. Concrete implementations are specified by \fCtransaction\&.factory_class\fP configuration property\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
