.TH "NHibernate.Loader.Custom.Sql.SQLQueryParser.IParserContext" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Loader.Custom.Sql.SQLQueryParser.IParserContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Loader\&.Custom\&.Sql\&.SQLCustomQuery\&.ParserContext\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsEntityAlias\fP (string aliasName)"
.br
.ti -1c
.RI "\fBISqlLoadable\fP \fBGetEntityPersisterByAlias\fP (string alias)"
.br
.ti -1c
.RI "string \fBGetEntitySuffixByAlias\fP (string alias)"
.br
.ti -1c
.RI "bool \fBIsCollectionAlias\fP (string aliasName)"
.br
.ti -1c
.RI "\fBISqlLoadableCollection\fP \fBGetCollectionPersisterByAlias\fP (string alias)"
.br
.ti -1c
.RI "string \fBGetCollectionSuffixByAlias\fP (string alias)"
.br
.ti -1c
.RI "IDictionary< string, string[]> \fBGetPropertyResultsMapByAlias\fP (string alias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file SQLQueryParser\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
