.TH "NHibernate.Test.NHSpecificTest.NH720.FooCacheProvider" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH720.FooCacheProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cache\&.ICacheProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBICache\fP \fBBuildCache\fP (string regionName, IDictionary< string, string > properties)"
.br
.RI "\fIConfigure the cache \fP"
.ti -1c
.RI "long \fBNextTimestamp\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP (IDictionary< string, string > properties)"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBICache\fP \fBBuildCacheStatic\fP (string regionName, IDictionary< string, string > properties)"
.br
.ti -1c
.RI "static bool \fBRegionExists\fP (string regionName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBRegionCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Domain\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBICache\fP NHibernate\&.Test\&.NHSpecificTest\&.NH720\&.FooCacheProvider\&.BuildCache (stringregionName, IDictionary< string, string >properties)"

.PP
Configure the cache 
.PP
\fBParameters:\fP
.RS 4
\fIregionName\fP the name of the cache region
.br
\fIproperties\fP configuration settings
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICacheProvider\fP\&.
.PP
Definition at line 54 of file Domain\&.cs\&.
.SS "long NHibernate\&.Test\&.NHSpecificTest\&.NH720\&.FooCacheProvider\&.NextTimestamp ()"

.PP

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICacheProvider\fP\&.
.PP
Definition at line 71 of file Domain\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH720\&.FooCacheProvider\&.Start (IDictionary< string, string >properties)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIproperties\fP 
.RE
.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICacheProvider\fP\&.
.PP
Definition at line 78 of file Domain\&.cs\&.
.SS "void NHibernate\&.Test\&.NHSpecificTest\&.NH720\&.FooCacheProvider\&.Stop ()"

.PP

.PP
Implements \fBNHibernate\&.Cache\&.ICacheProvider\fP\&.
.PP
Definition at line 83 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
