.TH "NHibernate.Stat.IStatisticsImplementor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Stat.IStatisticsImplementor \- 
.PP
Statistics SPI for the \fBNHibernate\fP core  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Stat\&.StatisticsImpl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOpenSession\fP ()"
.br
.ti -1c
.RI "void \fBCloseSession\fP ()"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "void \fBConnect\fP ()"
.br
.ti -1c
.RI "void \fBLoadEntity\fP (string entityName, TimeSpan time)"
.br
.ti -1c
.RI "void \fBFetchEntity\fP (string entityName, TimeSpan time)"
.br
.ti -1c
.RI "void \fBUpdateEntity\fP (string entityName, TimeSpan time)"
.br
.ti -1c
.RI "void \fBInsertEntity\fP (string entityName, TimeSpan time)"
.br
.ti -1c
.RI "void \fBDeleteEntity\fP (string entityName, TimeSpan time)"
.br
.ti -1c
.RI "void \fBLoadCollection\fP (string role, TimeSpan time)"
.br
.ti -1c
.RI "void \fBFetchCollection\fP (string role, TimeSpan time)"
.br
.ti -1c
.RI "void \fBUpdateCollection\fP (string role, TimeSpan time)"
.br
.ti -1c
.RI "void \fBRecreateCollection\fP (string role, TimeSpan time)"
.br
.ti -1c
.RI "void \fBRemoveCollection\fP (string role, TimeSpan time)"
.br
.ti -1c
.RI "void \fBSecondLevelCachePut\fP (string regionName)"
.br
.ti -1c
.RI "void \fBSecondLevelCacheHit\fP (string regionName)"
.br
.ti -1c
.RI "void \fBSecondLevelCacheMiss\fP (string regionName)"
.br
.ti -1c
.RI "void \fBQueryExecuted\fP (string hql, int rows, TimeSpan time)"
.br
.ti -1c
.RI "void \fBQueryCacheHit\fP (string hql, string regionName)"
.br
.ti -1c
.RI "void \fBQueryCacheMiss\fP (string hql, string regionName)"
.br
.ti -1c
.RI "void \fBQueryCachePut\fP (string hql, string regionName)"
.br
.ti -1c
.RI "void \fBEndTransaction\fP (bool success)"
.br
.ti -1c
.RI "void \fBCloseStatement\fP ()"
.br
.ti -1c
.RI "void \fBPrepareStatement\fP ()"
.br
.ti -1c
.RI "void \fBOptimisticFailure\fP (string entityName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Statistics SPI for the \fBNHibernate\fP core 


.PP
Definition at line 5 of file IStatisticsImplementor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
