.TH "NHibernate.Hql.Ast.ANTLR.Tree.CollectionFunction" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.CollectionFunction \- 
.PP
Represents 'elements()' or 'indices()'\&. Author: josh Ported by: Steve strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.MethodNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IDisplayableNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionFunction\fP (IToken token)"
.br
.ti -1c
.RI "override void \fBResolve\fP (bool inSelect)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPrepareSelectColumns\fP (String[] selectColumns)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Represents 'elements()' or 'indices()'\&. Author: josh Ported by: Steve strong 


.PP
Definition at line 12 of file CollectionFunction\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
