.TH "NHibernate.Test.DynamicEntity.DataProxyHandler" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DynamicEntity.DataProxyHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Proxy\&.DynamicProxy\&.IInterceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataProxyHandler\fP (string entityName, object id)"
.br
.ti -1c
.RI "object \fBIntercept\fP (\fBInvocationInfo\fP info)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBEntityName\fP\fC [get]\fP"
.br
.ti -1c
.RI "Hashtable \fBData\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file DataProxyHandler\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
