.TH "NHibernate.Bytecode.NullBytecodeProvider" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Bytecode.NullBytecodeProvider \- 
.PP
A \fBIBytecodeProvider\fP implementation that returns , disabling reflection optimization\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Bytecode\&.AbstractBytecodeProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBIReflectionOptimizer\fP \fBGetReflectionOptimizer\fP (System\&.Type clazz, \fBIGetter\fP[] getters, \fBISetter\fP[] setters)"
.br
.RI "\fIRetrieve the \fBIReflectionOptimizer\fP delegate for this provider capable of generating reflection optimization components\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBIBytecodeProvider\fP implementation that returns , disabling reflection optimization\&. 


.PP
Definition at line 9 of file NullBytecodeProvider\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBIReflectionOptimizer\fP NHibernate\&.Bytecode\&.NullBytecodeProvider\&.GetReflectionOptimizer (System\&.Typeclazz, \fBIGetter\fP[]getters, \fBISetter\fP[]setters)\fC [virtual]\fP"

.PP
Retrieve the \fBIReflectionOptimizer\fP delegate for this provider capable of generating reflection optimization components\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclazz\fP The class to be reflected upon\&.
.br
\fIgetters\fP All property getters to be accessed via reflection\&.
.br
\fIsetters\fP All property setters to be accessed via reflection\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The reflection optimization delegate\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Bytecode\&.AbstractBytecodeProvider\fP\&.
.PP
Definition at line 13 of file NullBytecodeProvider\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
