.TH "NHibernate.Mapping.ByCode.LazyRelation" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.LazyRelation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Mapping\&.ByCode\&.LazyRelation\&.LazyNoProxy, NHibernate\&.Mapping\&.ByCode\&.LazyRelation\&.LazyProxy, and NHibernate\&.Mapping\&.ByCode\&.LazyRelation\&.NoLazyRelation\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBHbmLaziness\fP \fBToHbm\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLazyRelation\fP \fBProxy\fP = new LazyProxy()"
.br
.ti -1c
.RI "static \fBLazyRelation\fP \fBNoProxy\fP = new LazyNoProxy()"
.br
.ti -1c
.RI "static \fBLazyRelation\fP \fBNoLazy\fP = new NoLazyRelation()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Lazy\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
