.TH "NHibernate.Hql.Ast.ANTLR.Tree.IExpectedTypeAwareNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.IExpectedTypeAwareNode \- 
.PP
Interface for nodes which wish to be made aware of any determined 'expected
type' based on the context within they appear in the query\&. Author: Steve Ebersole Ported by: Steve Strong  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.BooleanLiteralNode\fP, \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.JavaConstantNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.ParameterNode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIType\fP \fBExpectedType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for nodes which wish to be made aware of any determined 'expected
type' based on the context within they appear in the query\&. Author: Steve Ebersole Ported by: Steve Strong 


.PP
Definition at line 11 of file IExpectedTypeAwareNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
