.TH "NHibernate.Cfg.MappingSchema.HbmLoadCollection" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmLoadCollection \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmReturnProperty\fP[] \fBreturnproperty\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBrole\fP"
.br
.ti -1c
.RI "\fBHbmLockMode\fP \fBlockmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 4072 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
