.TH "NHibernate.Test.UtilityTest.LRUMapFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UtilityTest.LRUMapFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPutWithSizeLimit\fP ()"
.br
.ti -1c
.RI "void \fBPutWithNoSizeLimit\fP ()"
.br
.ti -1c
.RI "void \fBPutAndRemove\fP ()"
.br
.ti -1c
.RI "void \fBRemoveEmpty\fP ()"
.br
.ti -1c
.RI "void \fBGetEntrySet\fP ()"
.br
.ti -1c
.RI "void \fBPutWithSizeLimitOfZero\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file LRUMapFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
