.TH "NHibernate.Mapping.ByCode.Impl.OneToOneMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.OneToOneMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IOneToOneMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneToOneMapper\fP (MemberInfo member, \fBHbmOneToOne\fP oneToOne)"
.br
.ti -1c
.RI "\fBOneToOneMapper\fP (MemberInfo member, \fBIAccessorPropertyMapper\fP accessorMapper, \fBHbmOneToOne\fP oneToOne)"
.br
.ti -1c
.RI "void \fBCascade\fP (\fBCascade\fP cascadeStyle)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.ti -1c
.RI "void \fBOptimisticLock\fP (bool takeInConsiderationForOptimisticLock)"
.br
.ti -1c
.RI "void \fBLazy\fP (\fBLazyRelation\fP lazyRelation)"
.br
.ti -1c
.RI "void \fBConstrained\fP (bool value)"
.br
.ti -1c
.RI "void \fBPropertyReference\fP (MemberInfo propertyInTheOtherSide)"
.br
.ti -1c
.RI "void \fBFormula\fP (string formula)"
.br
.ti -1c
.RI "void \fBForeignKey\fP (string foreignKeyName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file OneToOneMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
