.TH "NHibernate.SqlCommand.ForUpdateFragment" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.ForUpdateFragment \- 
.PP
Represents an SQL \fCfor update of \&.\&.\&. nowait\fP statement  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForUpdateFragment\fP (\fBDialect\&.Dialect\fP dialect)"
.br
.ti -1c
.RI "\fBForUpdateFragment\fP (\fBDialect\&.Dialect\fP dialect, IDictionary< string, \fBLockMode\fP > lockModes, IDictionary< string, string[]> keyColumnNames)"
.br
.ti -1c
.RI "\fBForUpdateFragment\fP \fBAddTableAlias\fP (string alias)"
.br
.ti -1c
.RI "string \fBToSqlStringFragment\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsNoWaitEnabled\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an SQL \fCfor update of \&.\&.\&. nowait\fP statement 


.PP
Definition at line 11 of file ForUpdateFragment\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
