.TH "NHibernate.SqlCommand.OracleJoinFragment" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.OracleJoinFragment \- 
.PP
An Oracle-style (theta) Join  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.SqlCommand\&.JoinFragment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAddJoin\fP (string tableName, string alias, string[] fkColumns, string[] pkColumns, \fBJoinType\fP joinType)"
.br
.ti -1c
.RI "override void \fBAddJoin\fP (string tableName, string alias, string[] fkColumns, string[] pkColumns, \fBJoinType\fP joinType, \fBSqlString\fP on)"
.br
.ti -1c
.RI "override void \fBAddJoins\fP (\fBSqlString\fP fromFragment, \fBSqlString\fP whereFragment)"
.br
.ti -1c
.RI "override void \fBAddCrossJoin\fP (string tableName, string alias)"
.br
.ti -1c
.RI "override bool \fBAddCondition\fP (string condition)"
.br
.ti -1c
.RI "override bool \fBAddCondition\fP (\fBSqlString\fP condition)"
.br
.ti -1c
.RI "override void \fBAddFromFragmentString\fP (\fBSqlString\fP fromFragmentString)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBSqlString\fP \fBToFromFragmentString\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBSqlString\fP \fBToWhereFragmentString\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An Oracle-style (theta) Join 


.PP
Definition at line 11 of file OracleJoinFragment\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
