.TH "NHibernate.Cfg.Loquacious.IProxyConfigurationProperties" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.Loquacious.IProxyConfigurationProperties \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by NHibernate\&.Cfg\&.Loquacious\&.ProxyConfigurationProperties\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProxyFactoryFactory< TProxyFactoryFactory >\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBValidation\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file IProxyConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
