.TH "NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.JoinedSubclassSequenceRegistrationTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.ExplicitlyDeclaredModelTests.JoinedSubclassSequenceRegistrationTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenRegisterJoinedSubclassBeforeRootThenIsRegistered\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisterJoinedSubclassWithNoRootThenThrows\fP ()"
.br
.ti -1c
.RI "void \fBWhenRegisterJoinedSubclassWithNoRootThenCanAskForIsEntity\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file JoinedSubclassSequenceRegistrationTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
