.TH "NHibernate.Test.MappingByCode.TypeExtensionsTests.CompatibilityWithCandidatePersistentMembers" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.TypeExtensionsTests.CompatibilityWithCandidatePersistentMembers \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetFirstPropertyOfTypeShouldUseSameConceptsOfCandidatePersistentMembersProvider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file CompatibilityWithCandidatePersistentMembers\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
