.TH "NHibernate.Test.NHSpecificTest.NH2583" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2583 \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractMassTestingFixture\fP"
.br
.ti -1c
.RI "class \fBMyRef1\fP"
.br
.ti -1c
.RI "class \fBMyRef2\fP"
.br
.ti -1c
.RI "class \fBMyRef3\fP"
.br
.ti -1c
.RI "class \fBMyBO\fP"
.br
.ti -1c
.RI "class \fBInnerJoinFixture\fP"
.br
.ti -1c
.RI "class \fBManualTestFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingMoreOperatorsFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingNotAndDeMorganFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingOneOrTreeFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingOrderByFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingSelectFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingThreeOrTreesSideBySideFixture\fP"
.br
.ti -1c
.RI "class \fBMassTestingTwoOrTreesSideBySideFixture\fP"
.br
.ti -1c
.RI "class \fBSelfJoinTestFixture\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIgnore\fP { \fBIgnore\fP }"
.br
.ti -1c
.RI "enum \fBTK\fP { \fBValueNull\fP, \fBZero\fP, \fBOne\fP }"
.br
.ti -1c
.RI "enum \fBTBO1_I\fP { \fBNull\fP, \fBValueNull\fP, \fBZero\fP, \fBOne\fP }"
.br
.ti -1c
.RI "enum \fBTBO2_J\fP { \fBNull\fP, \fBValueNull\fP, \fBZero\fP, \fBOne\fP }"
.br
.ti -1c
.RI "enum \fBTBO1_BO2_J\fP { \fBNull\fP, \fBBO1\fP, \fBValueNull\fP, \fBZero\fP, \fBOne\fP }"
.br
.ti -1c
.RI "enum \fBTBO1_BO3_L\fP { \fBNull\fP, \fBBO1\fP, \fBValueNull\fP, \fBZero\fP, \fBOne\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
