.TH "NHibernate.Hql.Ast.ANTLR.Tree.BetweenOperatorNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.BetweenOperatorNode \- 
.PP
Contract for nodes representing logcial BETWEEN (ternary) operators\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.SqlNode\fP, and \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IOperatorNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBetweenOperatorNode\fP (IToken token)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.RI "\fICalled by the tree walker during hql-sql semantic analysis after the operator sub-tree is completely built\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBIType\fP \fBDataType\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contract for nodes representing logcial BETWEEN (ternary) operators\&. 


.PP
Definition at line 11 of file BetweenOperatorNode\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.BetweenOperatorNode\&.Initialize ()"

.PP
Called by the tree walker during hql-sql semantic analysis after the operator sub-tree is completely built\&. 
.PP
Implements \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.IOperatorNode\fP\&.
.PP
Definition at line 18 of file BetweenOperatorNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
