.TH "NHibernate.Mapping.Set" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.Set \- 
.PP
A \fBSet\fP with no nullable element columns will have a primary key consisting of all table columns (ie - key columns + element columns)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.Collection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSet\fP (\fBPersistentClass\fP owner)"
.br
.ti -1c
.RI "override void \fBCreatePrimaryKey\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsSet\fP\fC [get]\fP"
.br
.ti -1c
.RI "override \fBCollectionType\fP \fBDefaultCollectionType\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBSet\fP with no nullable element columns will have a primary key consisting of all table columns (ie - key columns + element columns)\&. 


.PP
Definition at line 13 of file Set\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
