.TH "NHibernate.Event.IPostCollectionRecreateEventListener" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Event.IPostCollectionRecreateEventListener \- 
.PP
Called after recreating a collection  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.Events\&.Collections\&.CollectionListeners\&.PostCollectionRecreateListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostRecreateCollection\fP (\fBPostCollectionRecreateEvent\fP @event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Called after recreating a collection 


.PP
Definition at line 4 of file IPostCollectionRecreateEventListener\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
