.TH "NHibernate.DomainModel.Componentizable" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Componentizable \- 
.PP
Summary description for \fBComponentizable\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fB_nickName\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBComponent\fP \fBComponent\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBNickName\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Summary description for \fBComponentizable\fP\&. 


.PP
Definition at line 8 of file Componentizable\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
