.TH "NHibernate.Test.Linq.LinqQuerySamples" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.LinqQuerySamples \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDLinq1\fP ()"
.br
.ti -1c
.RI "void \fBDLinq1b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq10\fP ()"
.br
.ti -1c
.RI "void \fBDLinq11\fP ()"
.br
.ti -1c
.RI "void \fBDLinq12\fP ()"
.br
.ti -1c
.RI "void \fBDLinq12b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq12c\fP ()"
.br
.ti -1c
.RI "void \fBDLinq12d\fP ()"
.br
.ti -1c
.RI "void \fBDLinq13\fP ()"
.br
.ti -1c
.RI "void \fBDLinq14\fP ()"
.br
.ti -1c
.RI "void \fBDLinq15\fP ()"
.br
.ti -1c
.RI "void \fBDLinq16\fP ()"
.br
.ti -1c
.RI "void \fBDLinq17\fP ()"
.br
.ti -1c
.RI "void \fBDLinq17b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq17c\fP ()"
.br
.ti -1c
.RI "void \fBDLinq18\fP ()"
.br
.ti -1c
.RI "void \fBDLinq19\fP ()"
.br
.ti -1c
.RI "void \fBDLinq2\fP ()"
.br
.ti -1c
.RI "void \fBDLinq20\fP ()"
.br
.ti -1c
.RI "void \fBDLinq21\fP ()"
.br
.ti -1c
.RI "void \fBDLinq22\fP ()"
.br
.ti -1c
.RI "void \fBDLinq23\fP ()"
.br
.ti -1c
.RI "void \fBDLinq24\fP ()"
.br
.ti -1c
.RI "void \fBDLinq25\fP ()"
.br
.ti -1c
.RI "void \fBDLinq26\fP ()"
.br
.ti -1c
.RI "void \fBDLinq27\fP ()"
.br
.ti -1c
.RI "void \fBDLinq28\fP ()"
.br
.ti -1c
.RI "void \fBDLinq29\fP ()"
.br
.ti -1c
.RI "void \fBDLinq3\fP ()"
.br
.ti -1c
.RI "void \fBDLinq30\fP ()"
.br
.ti -1c
.RI "void \fBDLinq31\fP ()"
.br
.ti -1c
.RI "void \fBDLinq36\fP ()"
.br
.ti -1c
.RI "void \fBDLinq37\fP ()"
.br
.ti -1c
.RI "void \fBDLinq38\fP ()"
.br
.ti -1c
.RI "void \fBDLinq39\fP ()"
.br
.ti -1c
.RI "void \fBDLinq3b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq4\fP ()"
.br
.ti -1c
.RI "void \fBDLinq40\fP ()"
.br
.ti -1c
.RI "void \fBDLinq41\fP ()"
.br
.ti -1c
.RI "void \fBDLinq42\fP ()"
.br
.ti -1c
.RI "void \fBDLinq43\fP ()"
.br
.ti -1c
.RI "void \fBDLinq44\fP ()"
.br
.ti -1c
.RI "void \fBDLinq45\fP ()"
.br
.ti -1c
.RI "void \fBDLinq46\fP ()"
.br
.ti -1c
.RI "void \fBDLinq47\fP ()"
.br
.ti -1c
.RI "void \fBDLinq48\fP ()"
.br
.ti -1c
.RI "void \fBDLinq48b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq49\fP ()"
.br
.ti -1c
.RI "void \fBDLinq5\fP ()"
.br
.ti -1c
.RI "void \fBDLinq50\fP ()"
.br
.ti -1c
.RI "void \fBDLinq51\fP ()"
.br
.ti -1c
.RI "void \fBDLinq52\fP ()"
.br
.ti -1c
.RI "void \fBDLinq52b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq53\fP ()"
.br
.ti -1c
.RI "void \fBDLinq53b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq53c\fP ()"
.br
.ti -1c
.RI "void \fBDLinq53d\fP ()"
.br
.ti -1c
.RI "void \fBDLinq54\fP ()"
.br
.ti -1c
.RI "void \fBDLinq55\fP ()"
.br
.ti -1c
.RI "void \fBDLinq56\fP ()"
.br
.ti -1c
.RI "void \fBDLinq57\fP ()"
.br
.ti -1c
.RI "void \fBDLinq58\fP ()"
.br
.ti -1c
.RI "void \fBDLinq59\fP ()"
.br
.ti -1c
.RI "void \fBDLinq6\fP ()"
.br
.ti -1c
.RI "void \fBDLinq60\fP ()"
.br
.ti -1c
.RI "void \fBDLinq61\fP ()"
.br
.ti -1c
.RI "void \fBDLinq62\fP ()"
.br
.ti -1c
.RI "void \fBDLinq63\fP ()"
.br
.ti -1c
.RI "void \fBDLinq7\fP ()"
.br
.ti -1c
.RI "void \fBDLinq8\fP ()"
.br
.ti -1c
.RI "void \fBDLinq9\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin10\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1a\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1b\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1c\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1d\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin1e\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin2\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin3\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin4\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin5\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin5a\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin5b\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin5c\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin6\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin7\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin8\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin9\fP ()"
.br
.ti -1c
.RI "void \fBDLinqJoin9b\fP ()"
.br
.ti -1c
.RI "void \fBDLinq2B\fP ()"
.br
.ti -1c
.RI "void \fBDLinq2C\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file LinqQuerySamples\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.Linq\&.LinqQuerySamples\&.DLinq17 ()"
Batching Select
.PP
Definition at line 226 of file LinqQuerySamples\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
