.TH "NHibernate.Cfg.HbmConstants" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.HbmConstants \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBnsPrefix\fP = 'hbm'"
.br
.ti -1c
.RI "const string \fBnsKey\fP = nsPrefix + ':key'"
.br
.ti -1c
.RI "const string \fBnsColumn\fP = nsPrefix + ':column'"
.br
.ti -1c
.RI "const string \fBnsFormula\fP = nsPrefix + ':formula'"
.br
.ti -1c
.RI "const string \fBnsOneToMany\fP = nsPrefix + ':one-to-many'"
.br
.ti -1c
.RI "const string \fBnsParam\fP = nsPrefix + ':param'"
.br
.ti -1c
.RI "const string \fBnsIndex\fP = nsPrefix + ':index'"
.br
.ti -1c
.RI "const string \fBnsListIndex\fP = nsPrefix + ':list-index'"
.br
.ti -1c
.RI "const string \fBnsGenerator\fP = nsPrefix + ':generator'"
.br
.ti -1c
.RI "const string \fBnsType\fP = nsPrefix + ':type'"
.br
.ti -1c
.RI "const string \fBnsCollectionId\fP = nsPrefix + ':collection-id'"
.br
.ti -1c
.RI "const string \fBnsClass\fP = nsPrefix + ':class'"
.br
.ti -1c
.RI "const string \fBnsSubclass\fP = nsPrefix + ':subclass'"
.br
.ti -1c
.RI "const string \fBnsJoinedSubclass\fP = nsPrefix + ':joined-subclass'"
.br
.ti -1c
.RI "const string \fBnsQuery\fP = nsPrefix + ':query'"
.br
.ti -1c
.RI "const string \fBnsSqlQuery\fP = nsPrefix + ':sql-query'"
.br
.ti -1c
.RI "const string \fBnsSynchronize\fP = nsPrefix + ':synchronize'"
.br
.ti -1c
.RI "const string \fBnsImport\fP = nsPrefix + ':import'"
.br
.ti -1c
.RI "const string \fBnsMeta\fP = nsPrefix + ':meta'"
.br
.ti -1c
.RI "const string \fBnsMetaValue\fP = nsPrefix + ':meta-value'"
.br
.ti -1c
.RI "const string \fBnsQueryParam\fP = nsPrefix + ':query-param'"
.br
.ti -1c
.RI "const string \fBnsReturnDiscriminator\fP = nsPrefix + ':return-discriminator'"
.br
.ti -1c
.RI "const string \fBnsReturnProperty\fP = nsPrefix + ':return-property'"
.br
.ti -1c
.RI "const string \fBnsReturnColumn\fP = nsPrefix + ':return-column'"
.br
.ti -1c
.RI "const string \fBnsLoader\fP = nsPrefix + ':loader'"
.br
.ti -1c
.RI "const string \fBnsSqlInsert\fP = nsPrefix + ':sql-insert'"
.br
.ti -1c
.RI "const string \fBnsSqlUpdate\fP = nsPrefix + ':sql-update'"
.br
.ti -1c
.RI "const string \fBnsSqlDelete\fP = nsPrefix + ':sql-delete'"
.br
.ti -1c
.RI "const string \fBnsSqlDeleteAll\fP = nsPrefix + ':sql-delete-all'"
.br
.ti -1c
.RI "const string \fBnsFilterDef\fP = nsPrefix + ':filter-def'"
.br
.ti -1c
.RI "const string \fBnsFilterParam\fP = nsPrefix + ':filter-param'"
.br
.ti -1c
.RI "const string \fBnsFilter\fP = nsPrefix + ':filter'"
.br
.ti -1c
.RI "const string \fBnsDatabaseObject\fP = nsPrefix + ':database-object'"
.br
.ti -1c
.RI "const string \fBnsDefinition\fP = nsPrefix + ':definition'"
.br
.ti -1c
.RI "const string \fBnsCreate\fP = nsPrefix + ':create'"
.br
.ti -1c
.RI "const string \fBnsDrop\fP = nsPrefix + ':drop'"
.br
.ti -1c
.RI "const string \fBnsDialectScope\fP = nsPrefix + ':dialect-scope'"
.br
.ti -1c
.RI "const string \fBnsResultset\fP = nsPrefix + ':resultset'"
.br
.ti -1c
.RI "const string \fBnsUnionSubclass\fP = nsPrefix + ':union-subclass'"
.br
.ti -1c
.RI "const string \fBnsTuplizer\fP = nsPrefix + ':tuplizer'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file HbmConstants\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
