.TH "NHibernate.Mapping.PrimitiveArray" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.PrimitiveArray \- 
.PP
A primitive array has a primary key consisting of the key columns + index column\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.Array\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrimitiveArray\fP (\fBPersistentClass\fP owner)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsPrimitiveArray\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A primitive array has a primary key consisting of the key columns + index column\&. 


.PP
Definition at line 10 of file PrimitiveArray\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
