.TH "NHibernate.Test.Criteria.CriteriaQueryTest" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.CriteriaQueryTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEscapeCharacter\fP ()"
.br
.ti -1c
.RI "void \fBScrollCriteria\fP ()"
.br
.ti -1c
.RI "void \fBAllowToSetLimitOnSubqueries\fP ()"
.br
.ti -1c
.RI "void \fBTestSubcriteriaBeingNull\fP ()"
.br
.ti -1c
.RI "void \fBSubselect\fP ()"
.br
.ti -1c
.RI "void \fBSubselectWithComponent\fP ()"
.br
.ti -1c
.RI "void \fBCloningCriteria\fP ()"
.br
.ti -1c
.RI "void \fBCloningCriteria_AddCount_RemoveOrdering\fP ()"
.br
.ti -1c
.RI "void \fBDetachedCriteriaTest\fP ()"
.br
.ti -1c
.RI "void \fBSubqueryPaginationOnlyWithFirst\fP ()"
.br
.ti -1c
.RI "void \fBSubqueryPagination\fP ()"
.br
.ti -1c
.RI "void \fBSimplePagination\fP ()"
.br
.ti -1c
.RI "void \fBSimplePaginationOnlyWithFirst\fP ()"
.br
.ti -1c
.RI "void \fBCloningDetachedCriteriaTest\fP ()"
.br
.ti -1c
.RI "void \fBProjectionCache\fP ()"
.br
.ti -1c
.RI "void \fBNH_1155_ShouldNotLoadAllChildrenInPagedSubSelect\fP ()"
.br
.ti -1c
.RI "void \fBProjectionsTest\fP ()"
.br
.ti -1c
.RI "void \fBCloningProjectionsTest\fP ()"
.br
.ti -1c
.RI "void \fBProjectionsUsingProperty\fP ()"
.br
.ti -1c
.RI "void \fBDistinctProjectionsOfComponents\fP ()"
.br
.ti -1c
.RI "void \fBGroupByComponent\fP ()"
.br
.ti -1c
.RI "void \fBCloningProjectionsUsingProperty\fP ()"
.br
.ti -1c
.RI "void \fBRestrictionOnSubclassCollection\fP ()"
.br
.ti -1c
.RI "void \fBClassProperty\fP ()"
.br
.ti -1c
.RI "void \fBProjectedId\fP ()"
.br
.ti -1c
.RI "void \fBProjectedEmbeddedCompositeId\fP ()"
.br
.ti -1c
.RI "void \fBProjectedListIncludesEmbeddedCompositeId\fP ()"
.br
.ti -1c
.RI "void \fBProjectedCompositeId\fP ()"
.br
.ti -1c
.RI "void \fBProjectedCompositeIdWithAlias\fP ()"
.br
.ti -1c
.RI "void \fBProjectedComponent\fP ()"
.br
.ti -1c
.RI "void \fBProjectedListIncludesComponent\fP ()"
.br
.ti -1c
.RI "void \fBCloningProjectedId\fP ()"
.br
.ti -1c
.RI "void \fBCloningSubcriteriaJoinTypes\fP ()"
.br
.ti -1c
.RI "void \fBSubcriteriaJoinTypes\fP ()"
.br
.ti -1c
.RI "void \fBTypeMismatch\fP ()"
.br
.ti -1c
.RI "void \fBPropertySubClassDiscriminator\fP ()"
.br
.ti -1c
.RI "void \fBCriteriaInspection\fP ()"
.br
.ti -1c
.RI "void \fBDetachedCriteriaInspection\fP ()"
.br
.ti -1c
.RI "void \fBSameColumnAndAliasNames\fP ()"
.br
.ti -1c
.RI "void \fBSameColumnAndAliasNamesResultTransformer\fP ()"
.br
.ti -1c
.RI "void \fBCacheDetachedCriteria\fP ()"
.br
.ti -1c
.RI "void \fBPropertyWithFormulaAndPagingTest\fP ()"
.br
.ti -1c
.RI "void \fBSqlExpressionWithParameters\fP ()"
.br
.ti -1c
.RI "void \fBParametersInCountExpression\fP ()"
.br
.ti -1c
.RI "void \fBTransformToRowCountTest\fP ()"
.br
.ti -1c
.RI "void \fBOrderProjectionTest\fP ()"
.br
.ti -1c
.RI "void \fBOrderProjectionAliasedTest\fP ()"
.br
.ti -1c
.RI "void \fBLikeProjectionTest\fP ()"
.br
.ti -1c
.RI "void \fBLikeProjectionUsingRestrictionsTest\fP ()"
.br
.ti -1c
.RI "void \fBInsensitiveLikeProjectionUsingRestrictionsTest\fP ()"
.br
.ti -1c
.RI "void \fBAliasJoinCriterion\fP ()"
.br
.ti -1c
.RI "void \fBIgnoreCase\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBMappingsAssembly\fP\fC [get]\fP"
.br
.ti -1c
.RI "override IList \fBMappings\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file CriteriaQueryTest\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
