.TH "NHibernate.Linq.Visitors.QuerySourceIdentifier" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.Visitors.QuerySourceIdentifier \- 
.PP
Identifies and names - using \fBQuerySourceNamer\fP - all QueryModel query sources  

.SH SYNOPSIS
.br
.PP
.PP
Inherits QueryModelVisitorBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBVisitMainFromClause\fP (MainFromClause fromClause, QueryModel queryModel)"
.br
.ti -1c
.RI "override void \fBVisitAdditionalFromClause\fP (AdditionalFromClause fromClause, QueryModel queryModel, int index)"
.br
.ti -1c
.RI "override void \fBVisitJoinClause\fP (JoinClause joinClause, QueryModel queryModel, GroupJoinClause groupJoinClause)"
.br
.ti -1c
.RI "override void \fBVisitGroupJoinClause\fP (GroupJoinClause groupJoinClause, QueryModel queryModel, int index)"
.br
.ti -1c
.RI "override void \fBVisitJoinClause\fP (JoinClause joinClause, QueryModel queryModel, int index)"
.br
.ti -1c
.RI "override void \fBVisitResultOperator\fP (ResultOperatorBase resultOperator, QueryModel queryModel, int index)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBVisit\fP (\fBQuerySourceNamer\fP namer, QueryModel queryModel)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBQuerySourceNamer\fP \fBNamer\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Identifies and names - using \fBQuerySourceNamer\fP - all QueryModel query sources 

It may seem expensive to do this as a separate visitation of the query model, but unfortunately trying to identify query sources on the fly (i\&.e\&. while parsing the query model to generate the HQL expression tree) means a query source may be referenced by a \fCQuerySourceReference\fP before it has been identified - and named\&. 
.PP
Definition at line 16 of file QuerySourceIdentifier\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
