.TH "NHibernate.Test.NHSpecificTest.Dates.DateTimeAssert" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Dates.DateTimeAssert \- 
.PP
Useful assert to work with datetimes types\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAreEqual\fP (DateTime dt1, DateTime dt2)"
.br
.ti -1c
.RI "static void \fBAreEqual\fP (DateTime dt1, DateTime dt2, bool OnlyDatePart)"
.br
.ti -1c
.RI "static void \fBAreEqual\fP (DateTimeOffset dt1, DateTimeOffset dt2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Useful assert to work with datetimes types\&. 


.PP
Definition at line 10 of file DateTimeAssert\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
