.TH "NHibernate.Id.UUIDStringGenerator" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Id.UUIDStringGenerator \- 
.PP
An \fBIIdentifierGenerator\fP that returns a string of length  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Id\&.IIdentifierGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "object \fBGenerate\fP (\fBISessionImplementor\fP session, object obj)"
.br
.RI "\fIGenerate a new String for the identifier using the 'uuid\&.string' algorithm\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An \fBIIdentifierGenerator\fP that returns a string of length 


.IP "16." 4

.PP
.PP
This id generation strategy is specified in the mapping file as 
.PP
.nf
&lt;generator class="uuid\&.string" /&gt;

.fi
.PP
 
.PP
The identifier string will NOT consist of only alphanumeric characters\&. Use this only if you don't mind unreadable identifiers\&. 
.PP
This impelementation was known to be incompatible with Postgres\&. 
.PP
Definition at line 24 of file UUIDStringGenerator\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "object NHibernate\&.Id\&.UUIDStringGenerator\&.Generate (\fBISessionImplementor\fPsession, objectobj)"

.PP
Generate a new String for the identifier using the 'uuid\&.string' algorithm\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsession\fP The ISessionImplementor this id is being generated in\&.
.br
\fIobj\fP The entity for which the id is being generated\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The new identifier as a String\&.
.RE
.PP

.PP
Implements \fBNHibernate\&.Id\&.IIdentifierGenerator\fP\&.
.PP
Definition at line 34 of file UUIDStringGenerator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
