.TH "NHibernate.Test.NHSpecificTest.NH1579" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1579 \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApple\fP"
.br
.ti -1c
.RI "class \fBCart\fP"
.br
.ti -1c
.RI "class \fBEntity\fP"
.br
.ti -1c
.RI "class \fBFruit\fP"
.br
.ti -1c
.RI "class \fBNH1579Fixture\fP"
.br
.ti -1c
.RI "class \fBOrange\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
