.TH "NHibernate.DomainModel.ReverseComparator" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.ReverseComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompare\fP (object x, object y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ReverseComparator\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
