.TH "NHibernate.Intercept.DefaultFieldInterceptor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Intercept.DefaultFieldInterceptor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Intercept\&.AbstractFieldInterceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultFieldInterceptor\fP (\fBISessionImplementor\fP session, ISet< string > uninitializedFields, ISet< string > unwrapProxyFieldNames, string entityName, System\&.Type mappedClass)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file DefaultFieldInterceptor\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
