.TH "NHibernate.Test.NHSpecificTest.NH642.Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH642.Fixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMissingGetter\fP ()"
.br
.ti -1c
.RI "void \fBMissingSetter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
