.TH "NHibernate.DomainModel.A" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.A \- 
.PP
POCO for \fBA\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.DomainModel\&.B\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBA\fP ()"
.br
.RI "\fIDefault constructor for class \fBA\fP \fP"
.ti -1c
.RI "\fBA\fP (String name)"
.br
.RI "\fIConstructor for class \fBA\fP \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual Int64 \fBId\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for id \fP"
.ti -1c
.RI "virtual String \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for name \fP"
.ti -1c
.RI "virtual String \fBAnotherName\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for anotherName \fP"
.ti -1c
.RI "virtual \fBE\fP \fBForward\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
POCO for \fBA\fP 


.PP
Definition at line 9 of file A\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.DomainModel\&.A\&.A ()"

.PP
Default constructor for class \fBA\fP 
.PP
Definition at line 40 of file A\&.cs\&.
.SS "NHibernate\&.DomainModel\&.A\&.A (Stringname)"

.PP
Constructor for class \fBA\fP 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Initial name value
.RE
.PP

.PP
Definition at line 48 of file A\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual String NHibernate\&.DomainModel\&.A\&.AnotherName\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for anotherName 
.PP
Definition at line 79 of file A\&.cs\&.
.SS "virtual Int64 NHibernate\&.DomainModel\&.A\&.Id\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for id 
.PP
Definition at line 61 of file A\&.cs\&.
.SS "virtual String NHibernate\&.DomainModel\&.A\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for name 
.PP
Definition at line 70 of file A\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
