.TH "NHibernate.Test.NHSpecificTest.NH930.NVariable" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH930.NVariable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH930\&.NConditionalUDV\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH930\&.NFilterUDV\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBm_id\fP"
.br
.ti -1c
.RI "IList \fBm_precedentVariables\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IList \fBPrecedentVariables\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Model\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
