.TH "NHibernate.Linq" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBClauses\fP"
.br
.ti -1c
.RI "package \fBExpressions\fP"
.br
.ti -1c
.RI "package \fBExpressionTransformers\fP"
.br
.ti -1c
.RI "package \fBFunctions\fP"
.br
.ti -1c
.RI "package \fBGroupBy\fP"
.br
.ti -1c
.RI "package \fBGroupJoin\fP"
.br
.ti -1c
.RI "package \fBNestedSelects\fP"
.br
.ti -1c
.RI "package \fBResultOperators\fP"
.br
.ti -1c
.RI "package \fBReWriters\fP"
.br
.ti -1c
.RI "package \fBVisitors\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBINhQueryProvider\fP"
.br
.ti -1c
.RI "class \fBDefaultQueryProvider\fP"
.br
.ti -1c
.RI "class \fBEagerFetchingExtensionMethods\fP"
.br
.ti -1c
.RI "interface \fBINhFetchRequest< TQueried, TFetch >\fP"
.br
.ti -1c
.RI "class \fBNhFetchRequest< TQueried, TFetch >\fP"
.br
.ti -1c
.RI "class \fBReflectionHelper\fP"
.br
.ti -1c
.RI "class \fBEnumerableHelper\fP"
.br
.ti -1c
.RI "class \fBExpressionToHqlTranslationResults\fP"
.br
.ti -1c
.RI "class \fBIntermediateHqlTree\fP"
.br
.ti -1c
.RI "class \fBLinqExtensionMethodAttribute\fP"
.br
.ti -1c
.RI "class \fBLinqExtensionMethods\fP"
.br
.ti -1c
.RI "class \fBLinqLogging\fP"
.br
.ti -1c
.RI "class \fBNhLinqExpression\fP"
.br
.ti -1c
.RI "class \fBNhQueryable< T >\fP"
.br
.RI "\fIProvides the main entry point to a LINQ query\&. \fP"
.ti -1c
.RI "class \fBNhRelinqQueryParser\fP"
.br
.ti -1c
.RI "class \fBNHibernateNodeTypeProvider\fP"
.br
.ti -1c
.RI "class \fBAsQueryableExpressionNode\fP"
.br
.ti -1c
.RI "class \fBCacheableExpressionNode\fP"
.br
.ti -1c
.RI "class \fBCacheableResultOperator\fP"
.br
.ti -1c
.RI "class \fBTimeoutExpressionNode\fP"
.br
.ti -1c
.RI "class \fBTimeoutResultOperator\fP"
.br
.ti -1c
.RI "class \fBQuerySourceNamer\fP"
.br
.RI "\fIAssociate unique names to query sources\&. The HQL AST parser will rename them anyway, but we need to ensure uniqueness that is not provided by IQuerySource\&.ItemName\&. \fP"
.ti -1c
.RI "class \fBResultTransformer\fP"
.br
.ti -1c
.RI "class \fBSqlMethods\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNhLinqExpressionReturnType\fP { \fBSequence\fP, \fBScalar\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
