.TH "NHibernate.Mapping.ByCode.Impl.CustomizersImpl.OneToManyCustomizer" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.CustomizersImpl.OneToManyCustomizer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IOneToManyMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneToManyCustomizer\fP (\fBIModelExplicitDeclarationsHolder\fP explicitDeclarationsHolder, \fBPropertyPath\fP propertyPath, \fBICustomizersHolder\fP customizersHolder)"
.br
.ti -1c
.RI "void \fBClass\fP (System\&.Type entityType)"
.br
.ti -1c
.RI "void \fBEntityName\fP (string entityName)"
.br
.ti -1c
.RI "void \fBNotFound\fP (\fBNotFoundMode\fP mode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file OneToManyCustomizer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
