.TH "NHibernate.Hql.Ast.HqlIn" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.HqlIn \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Hql\&.Ast\&.HqlBooleanExpression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHqlIn\fP (\fBIASTFactory\fP factory, \fBHqlExpression\fP itemExpression, \fBHqlTreeNode\fP source)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 886 of file HqlTreeNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
