.TH "NHibernate.Test.Tools.hbm2ddl.SchemaMetadataUpdaterTest.SchemaMetadataUpdaterFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Tools.hbm2ddl.SchemaMetadataUpdaterTest.SchemaMetadataUpdaterFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCanRetrieveReservedWords\fP ()"
.br
.ti -1c
.RI "void \fBUpdateReservedWordsInDialect\fP ()"
.br
.ti -1c
.RI "void \fBExplicitAutoQuote\fP ()"
.br
.ti -1c
.RI "void \fBAutoQuoteTableAndColumnsAtStratup\fP ()"
.br
.ti -1c
.RI "void \fBAutoQuoteTableAndColumnsAtStratupIncludeKeyWordsImport\fP ()"
.br
.ti -1c
.RI "void \fBCanWorkWithAutoQuoteTableAndColumnsAtStratup\fP ()"
.br
.ti -1c
.RI "void \fBWhenConfiguredOnlyExplicitAutoQuote\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file SchemaMetadataUpdaterFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
