.TH "NHibernate.Test.Linq.AggregateTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.AggregateTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAggregateWithStartsWith\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithEndsWith\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithContains\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithEquals\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithNotStartsWith\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithMonthFunction\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithBeforeYearFunction\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithOnOrAfterYearFunction\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithUpperAndLowerFunctions\fP ()"
.br
.ti -1c
.RI "void \fBAggregateWithCustomFunction\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file AggregateTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
