.TH "NHibernate.Test.Linq.ByMethod.GroupByHavingTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Linq.ByMethod.GroupByHavingTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.Linq\&.LinqTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHavingCountSelectCount\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectCountWithInnerWhere\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectKey\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectKeyWithInnerWhere\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectTupleKeyCount\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectTupleKeyCountOfOrders\fP ()"
.br
.ti -1c
.RI "void \fBHavingCountSelectTupleKeyCountOfOrderLines\fP ()"
.br
.ti -1c
.RI "void \fBComplexQuery\fP ()"
.br
.ti -1c
.RI "void \fBSingleKeyGroupAndCountWithHavingClause\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBConfigure\fP (\fBCfg\&.Configuration\fP configuration)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file GroupByHavingTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
