.TH "NHibernate.Proxy.DynamicProxy" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Proxy.DynamicProxy \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefaultArgumentHandler\fP"
.br
.ti -1c
.RI "class \fBDefaultMethodEmitter\fP"
.br
.ti -1c
.RI "class \fBDefaultProxyAssemblyBuilder\fP"
.br
.ti -1c
.RI "class \fBDefaultyProxyMethodBuilder\fP"
.br
.ti -1c
.RI "class \fBHashSetExtensions\fP"
.br
.ti -1c
.RI "interface \fBIArgumentHandler\fP"
.br
.ti -1c
.RI "interface \fBIInterceptor\fP"
.br
.ti -1c
.RI "interface \fBIMethodBodyEmitter\fP"
.br
.ti -1c
.RI "class \fBInvocationInfo\fP"
.br
.ti -1c
.RI "interface \fBIProxy\fP"
.br
.ti -1c
.RI "interface \fBIProxyAssemblyBuilder\fP"
.br
.ti -1c
.RI "interface \fBIProxyCache\fP"
.br
.ti -1c
.RI "interface \fBIProxyMethodBuilder\fP"
.br
.ti -1c
.RI "class \fBOpCodesMap\fP"
.br
.ti -1c
.RI "class \fBProxyCache\fP"
.br
.ti -1c
.RI "class \fBProxyCacheEntry\fP"
.br
.ti -1c
.RI "class \fBProxyDummy\fP"
.br
.ti -1c
.RI "class \fBProxyFactory\fP"
.br
.ti -1c
.RI "class \fBProxyImplementor\fP"
.br
.ti -1c
.RI "class \fBProxyObjectReference\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate object \fBInterceptorHandler\fP (object proxy, MethodInfo targetMethod, StackTrace trace, System\&.Type[] genericTypeArgs, object[] args)"
.br
.ti -1c
.RI "delegate object \fBInvocationHandler\fP (\fBInvocationInfo\fP info)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
