.TH "NHibernate.Mapping.ByCode.Impl.VersionMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.VersionMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IVersionMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersionMapper\fP (MemberInfo member, \fBHbmVersion\fP hbmVersion)"
.br
.ti -1c
.RI "void \fBColumn\fP (Action< \fBIColumnMapper\fP > columnMapper)"
.br
.ti -1c
.RI "void \fBColumns\fP (params Action< \fBIColumnMapper\fP >[] columnMapper)"
.br
.ti -1c
.RI "void \fBColumn\fP (string name)"
.br
.ti -1c
.RI "void \fBType\fP (\fBIVersionType\fP persistentType)"
.br
.ti -1c
.RI "void \fBType< TPersistentType >\fP ()"
.br
.ti -1c
.RI "void \fBType\fP (System\&.Type persistentType)"
.br
.ti -1c
.RI "void \fBUnsavedValue\fP (object value)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool useInInsert)"
.br
.ti -1c
.RI "void \fBGenerated\fP (\fBVersionGeneration\fP generatedByDb)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file VersionMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
