.TH "NHibernate.Test.TypeParameters.Widget" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.TypeParameters.Widget \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBValueOne\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueTwo\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueThree\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValueFour\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBStr\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Widget\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
