.TH "NHibernate.Test.Criteria.Lambda.LambdaFixtureBase" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.Criteria.Lambda.LambdaFixtureBase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.CriteriaAssertFixture\fP, \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.ProjectionsFixture\fP, \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.QueryOverFixture\fP, \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.RestrictionsFixture\fP, and \fBNHibernate\&.Test\&.Criteria\&.Lambda\&.SubqueryFixture\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBICriteria\fP \fBCreateTestCriteria\fP (System\&.Type persistentClass)"
.br
.ti -1c
.RI "\fBICriteria\fP \fBCreateTestCriteria\fP (System\&.Type persistentClass, string alias)"
.br
.ti -1c
.RI "\fBIQueryOver\fP< T, T > \fBCreateTestQueryOver< T >\fP ()"
.br
.ti -1c
.RI "\fBIQueryOver\fP< T, T > \fBCreateTestQueryOver< T >\fP (\fBExpression\fP< Func< object >> alias)"
.br
.ti -1c
.RI "void \fBAssertCriteriaAreEqual\fP (\fBICriteria\fP expected, \fBICriteria\fP actual)"
.br
.ti -1c
.RI "void \fBAssertCriteriaAreEqual\fP (\fBDetachedCriteria\fP expected, \fBDetachedCriteria\fP actual)"
.br
.ti -1c
.RI "void \fBAssertCriteriaAreEqual< T >\fP (\fBICriteria\fP expected, \fBIQueryOver\fP< T > actual)"
.br
.ti -1c
.RI "\fBDetachedCriteria\fP \fBToDetachedCriteria< T >\fP (\fBQueryOver\fP< T > actual)"
.br
.ti -1c
.RI "void \fBAssertCriteriaAreEqual< T >\fP (\fBDetachedCriteria\fP expected, \fBQueryOver\fP< T > actual)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file LambdaFixtureBase\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
