.TH "NHibernate.SqlCommand.SelectFragment" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.SqlCommand.SelectFragment \- 
.PP
Represents part of an SQL \fCSELECT\fP clause  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSelectFragment\fP (\fBDialect\&.Dialect\fP d)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBSetUsedAliases\fP (string[] usedAliases)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBSetSuffix\fP (string suffix)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumn\fP (string columnName)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumns\fP (string[] columnNames)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumn\fP (string tableAlias, string columnName)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumn\fP (string tableAlias, string columnName, string columnAlias)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumns\fP (string tableAlias, string[] columnNames)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddColumns\fP (string tableAlias, string[] columnNames, string[] columnAliases)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddFormulas\fP (string tableAlias, string[] formulas, string[] formulaAliases)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBAddFormula\fP (string tableAlias, string formula, string formulaAlias)"
.br
.ti -1c
.RI "string \fBToFragmentString\fP ()"
.br
.RI "\fIEquivalent to ToSqlStringFragment\&. \fP"
.ti -1c
.RI "string \fBToSqlStringFragment\fP ()"
.br
.ti -1c
.RI "string \fBToSqlStringFragment\fP (bool includeLeadingComma)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBSetExtraSelectList\fP (string extraSelectList)"
.br
.ti -1c
.RI "\fBSelectFragment\fP \fBSetExtraSelectList\fP (\fBCaseFragment\fP caseFragment, string fragmentAlias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents part of an SQL \fCSELECT\fP clause 


.PP
Definition at line 12 of file SelectFragment\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "string NHibernate\&.SqlCommand\&.SelectFragment\&.ToFragmentString ()"

.PP
Equivalent to ToSqlStringFragment\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP
.PP
In H3, it is called \fBToFragmentString()\fP\&. It appears to be functionally equivalent as ToSqlStringFragment() here\&. 
.PP
Definition at line 122 of file SelectFragment\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
