.TH "NHibernate.Cfg.ConfigurationSchema.CollectionCacheConfiguration" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.ConfigurationSchema.CollectionCacheConfiguration \- 
.PP
\fBConfiguration\fP parsed values for a collection-cache XML node\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionCacheConfiguration\fP (string collection, \fBEntityCacheUsage\fP usage)"
.br
.RI "\fIInitializes a new instance of the \fBCollectionCacheConfiguration\fP class\&. \fP"
.ti -1c
.RI "\fBCollectionCacheConfiguration\fP (string collection, \fBEntityCacheUsage\fP usage, string region)"
.br
.RI "\fIInitializes a new instance of the \fBCollectionCacheConfiguration\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCollection\fP\fC [get]\fP"
.br
.RI "\fIThe role\&. \fP"
.ti -1c
.RI "string \fBRegion\fP\fC [get]\fP"
.br
.RI "\fIThe cache region\&. \fP"
.ti -1c
.RI "\fBEntityCacheUsage\fP \fBUsage\fP\fC [get]\fP"
.br
.RI "\fI\fBCache\fP strategy\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBConfiguration\fP parsed values for a collection-cache XML node\&. 


.PP
Definition at line 9 of file CollectionCacheConfiguration\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.Cfg\&.ConfigurationSchema\&.CollectionCacheConfiguration\&.CollectionCacheConfiguration (stringcollection, \fBEntityCacheUsage\fPusage)"

.PP
Initializes a new instance of the \fBCollectionCacheConfiguration\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcollection\fP The cache role\&.
.br
\fIusage\fP \fBCache\fP strategy\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIArgumentException\fP When \fIcollection\fP  is null or empty\&.
.RE
.PP

.PP
Definition at line 22 of file CollectionCacheConfiguration\&.cs\&.
.SS "NHibernate\&.Cfg\&.ConfigurationSchema\&.CollectionCacheConfiguration\&.CollectionCacheConfiguration (stringcollection, \fBEntityCacheUsage\fPusage, stringregion)"

.PP
Initializes a new instance of the \fBCollectionCacheConfiguration\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcollection\fP The cache role\&.
.br
\fIusage\fP \fBCache\fP strategy\&.
.br
\fIregion\fP The cache region\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIArgumentException\fP When \fIcollection\fP  is null or empty\&.
.RE
.PP

.PP
Definition at line 37 of file CollectionCacheConfiguration\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string NHibernate\&.Cfg\&.ConfigurationSchema\&.CollectionCacheConfiguration\&.Collection\fC [get]\fP"

.PP
The role\&. 
.PP
Definition at line 73 of file CollectionCacheConfiguration\&.cs\&.
.SS "string NHibernate\&.Cfg\&.ConfigurationSchema\&.CollectionCacheConfiguration\&.Region\fC [get]\fP"

.PP
The cache region\&. If null or empty the \fBCollectionCacheConfiguration\&.Collection\fP is used during configuration\&.
.PP
Definition at line 83 of file CollectionCacheConfiguration\&.cs\&.
.SS "\fBEntityCacheUsage\fP NHibernate\&.Cfg\&.ConfigurationSchema\&.CollectionCacheConfiguration\&.Usage\fC [get]\fP"

.PP
\fBCache\fP strategy\&. 
.PP
Definition at line 92 of file CollectionCacheConfiguration\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
