.TH "NHibernate.Test.NHSpecificTest.NH2100.DTO" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2100.DTO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2100\&.Class1DTO\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH2100\&.Class2DTO\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBID\fP"
.br
.ti -1c
.RI "int \fBEntityVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file Domain\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
