.TH "NHibernate.DomainModel.Baz" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.DomainModel.Baz \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.DomainModel\&.INamed\fP, and IComparable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaz\fP ()"
.br
.RI "\fIDefault constructor for class \fBBaz\fP \fP"
.ti -1c
.RI "void \fBSetDefaults\fP ()"
.br
.ti -1c
.RI "int \fBCompareTo\fP (object obj)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNestingComponent\fP \fBCollectionComponent\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the _collectionComponent \fP"
.ti -1c
.RI "String \fBCode\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for Code \fP"
.ti -1c
.RI "Int32 \fBCount\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for count \fP"
.ti -1c
.RI "String \fBName\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for name \fP"
.ti -1c
.RI "\fBFoo\fP \fBFoo\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for \fBFoo\fP \fP"
.ti -1c
.RI "IList \fBStringList\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for stringList \fP"
.ti -1c
.RI "IList \fBFees\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for fees \fP"
.ti -1c
.RI "IList \fBCustoms\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for customs \fP"
.ti -1c
.RI "IList \fBTopComponents\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for topComponents \fP"
.ti -1c
.RI "IDictionary \fBFooToGlarch\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for fooToGlarch \fP"
.ti -1c
.RI "IDictionary \fBFooComponentToFoo\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for fooComponentToFoo \fP"
.ti -1c
.RI "IDictionary \fBGlarchToFoo\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for glarchToFoo \fP"
.ti -1c
.RI "IDictionary \fBStringDateMap\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for stringDateMap \fP"
.ti -1c
.RI "IDictionary \fBTopGlarchez\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for topGlarchez \fP"
.ti -1c
.RI "IDictionary \fBCachedMap\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for cachedMap \fP"
.ti -1c
.RI "IDictionary \fBStringGlarchMap\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for stringGlarchMap \fP"
.ti -1c
.RI "IDictionary \fBAnyToAny\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for anyToAny \fP"
.ti -1c
.RI "IList \fBManyToAny\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for manyToAny \fP"
.ti -1c
.RI "int[] \fBIntArray\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the intArray \fP"
.ti -1c
.RI "\fBFooComponent\fP[] \fBComponents\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the _components \fP"
.ti -1c
.RI "DateTime[] \fBTimeArray\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the timeArray \fP"
.ti -1c
.RI "string[] \fBStringArray\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the stringArray \fP"
.ti -1c
.RI "\fBFooProxy\fP[] \fBFooArray\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the fooArray \fP"
.ti -1c
.RI "ISet< \fBFooProxy\fP > \fBFooSet\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for fooSet \fP"
.ti -1c
.RI "ISet< string > \fBStringSet\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for stringSet \fP"
.ti -1c
.RI "ISet< \fBBar\fP > \fBTopFoos\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for topFoos \fP"
.ti -1c
.RI "ISet< \fBBarProxy\fP > \fBCascadingBars\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for cascadingBars \fP"
.ti -1c
.RI "ISet< \fBCompositeElement\fP > \fBCached\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for cached \fP"
.ti -1c
.RI "ISet< \fBSortable\fP > \fBSortablez\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for sortablez \fP"
.ti -1c
.RI "IList \fBBag\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for bag \fP"
.ti -1c
.RI "IList \fBFooBag\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for fooBag \fP"
.ti -1c
.RI "IList \fBBazez\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for bazez \fP"
.ti -1c
.RI "IList \fBIdFooBag\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for idFooBag \fP"
.ti -1c
.RI "IList \fBByteBag\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for byteBag \fP"
.ti -1c
.RI "IList \fBParts\fP\fC [get, set]\fP"
.br
.RI "\fIGet/set for parts \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Baz\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NHibernate\&.DomainModel\&.Baz\&.Baz ()"

.PP
Default constructor for class \fBBaz\fP 
.PP
Definition at line 57 of file Baz\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.AnyToAny\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for anyToAny 
.PP
Definition at line 213 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.Bag\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for bag 
.PP
Definition at line 332 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.Bazez\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for bazez 
.PP
Definition at line 350 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.ByteBag\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for byteBag 
.PP
Definition at line 368 of file Baz\&.cs\&.
.SS "ISet<\fBCompositeElement\fP> NHibernate\&.DomainModel\&.Baz\&.Cached\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for cached 
.PP
Definition at line 314 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.CachedMap\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for cachedMap 
.PP
Definition at line 195 of file Baz\&.cs\&.
.SS "ISet<\fBBarProxy\fP> NHibernate\&.DomainModel\&.Baz\&.CascadingBars\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for cascadingBars 
.PP
Definition at line 305 of file Baz\&.cs\&.
.SS "String NHibernate\&.DomainModel\&.Baz\&.Code\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for Code 
.PP
Definition at line 78 of file Baz\&.cs\&.
.SS "\fBNestingComponent\fP NHibernate\&.DomainModel\&.Baz\&.CollectionComponent\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the _collectionComponent 
.PP
Definition at line 69 of file Baz\&.cs\&.
.SS "\fBFooComponent\fP [] NHibernate\&.DomainModel\&.Baz\&.Components\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the _components 
.PP
Definition at line 240 of file Baz\&.cs\&.
.SS "Int32 NHibernate\&.DomainModel\&.Baz\&.Count\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for count 
.PP
Definition at line 87 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.Customs\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for customs 
.PP
Definition at line 132 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.Fees\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for fees 
.PP
Definition at line 123 of file Baz\&.cs\&.
.SS "\fBFoo\fP NHibernate\&.DomainModel\&.Baz\&.Foo\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for \fBFoo\fP 
.PP
Definition at line 105 of file Baz\&.cs\&.
.SS "\fBFooProxy\fP [] NHibernate\&.DomainModel\&.Baz\&.FooArray\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the fooArray 
.PP
Definition at line 268 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.FooBag\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for fooBag 
.PP
Definition at line 341 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.FooComponentToFoo\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for fooComponentToFoo 
.PP
Definition at line 159 of file Baz\&.cs\&.
.SS "ISet<\fBFooProxy\fP> NHibernate\&.DomainModel\&.Baz\&.FooSet\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for fooSet 
.PP
Definition at line 278 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.FooToGlarch\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for fooToGlarch 
.PP
Definition at line 150 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.GlarchToFoo\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for glarchToFoo 
.PP
Definition at line 168 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.IdFooBag\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for idFooBag 
.PP
Definition at line 359 of file Baz\&.cs\&.
.SS "int [] NHibernate\&.DomainModel\&.Baz\&.IntArray\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the intArray 
.PP
Definition at line 231 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.ManyToAny\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for manyToAny 
.PP
Definition at line 222 of file Baz\&.cs\&.
.SS "String NHibernate\&.DomainModel\&.Baz\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for name 
.PP
Definition at line 96 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.Parts\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for parts 
.PP
Definition at line 377 of file Baz\&.cs\&.
.SS "ISet<\fBSortable\fP> NHibernate\&.DomainModel\&.Baz\&.Sortablez\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for sortablez 
.PP
Definition at line 323 of file Baz\&.cs\&.
.SS "string [] NHibernate\&.DomainModel\&.Baz\&.StringArray\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the stringArray 
.PP
Definition at line 258 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.StringDateMap\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for stringDateMap 
.PP
Definition at line 177 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.StringGlarchMap\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for stringGlarchMap 
.PP
Definition at line 204 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.StringList\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for stringList 
.PP
Definition at line 114 of file Baz\&.cs\&.
.SS "ISet<string> NHibernate\&.DomainModel\&.Baz\&.StringSet\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for stringSet 
.PP
Definition at line 287 of file Baz\&.cs\&.
.SS "DateTime [] NHibernate\&.DomainModel\&.Baz\&.TimeArray\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the timeArray 
.PP
Definition at line 249 of file Baz\&.cs\&.
.SS "IList NHibernate\&.DomainModel\&.Baz\&.TopComponents\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for topComponents 
.PP
Definition at line 141 of file Baz\&.cs\&.
.SS "ISet<\fBBar\fP> NHibernate\&.DomainModel\&.Baz\&.TopFoos\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for topFoos 
.PP
Definition at line 296 of file Baz\&.cs\&.
.SS "IDictionary NHibernate\&.DomainModel\&.Baz\&.TopGlarchez\fC [get]\fP, \fC [set]\fP"

.PP
Get/set for topGlarchez 
.PP
Definition at line 186 of file Baz\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
