.TH "NHibernate.Cfg.MappingSchema.HbmOneToMany" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.HbmOneToMany \- 
.PP
 

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Cfg\&.MappingSchema\&.IRelationship\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHbmNotFoundMode\fP \fBnotfound\fP"
.br
.ti -1c
.RI "string \fBnode\fP"
.br
.ti -1c
.RI "bool \fBembedxml\fP"
.br
.ti -1c
.RI "string \fBentityname\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBEntityName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBClass\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBHbmNotFoundMode\fP \fBNotFoundMode\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 1305 of file Hbm\&.generated\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHbmNotFoundMode\fP NHibernate\&.Cfg\&.MappingSchema\&.HbmOneToMany\&.notfound"

.PP
Definition at line 1309 of file Hbm\&.generated\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
