.TH "NHibernate.Engine.NamedQueryDefinition" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Engine.NamedQueryDefinition \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Engine\&.NamedSQLQueryDefinition\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamedQueryDefinition\fP (string query, bool cacheable, string cacheRegion, int timeout, int fetchSize, \fBFlushMode\fP flushMode, bool readOnly, string comment, IDictionary< string, string > parameterTypes)"
.br
.ti -1c
.RI "\fBNamedQueryDefinition\fP (string query, bool cacheable, string cacheRegion, int timeout, int fetchSize, \fBFlushMode\fP flushMode, \fBCacheMode\fP?cacheMode, bool readOnly, string comment, IDictionary< string, string > parameterTypes)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBQueryString\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsCacheable\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBCacheRegion\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBFetchSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBTimeout\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBFlushMode\fP \fBFlushMode\fP\fC [get]\fP"
.br
.ti -1c
.RI "IDictionary< string, string > \fBParameterTypes\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBQuery\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsReadOnly\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBComment\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCacheMode\fP \fBCacheMode\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file NamedQueryDefinition\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
