.TH "NHibernate.Test.MappingByCode.ConventionModelMapperTests.ComponetsAccessorTests" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.MappingByCode.ConventionModelMapperTests.ComponetsAccessorTests \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWhenMapComoponetWithNestBidirectionalComponentThenMapParentAccessor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file ComponetsAccessorTests\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
