.TH "NHibernate.Linq.GroupJoin.LocateGroupJoinQuerySource" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Linq.GroupJoin.LocateGroupJoinQuerySource \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ExpressionTreeVisitor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocateGroupJoinQuerySource\fP (\fBIsAggregatingResults\fP results)"
.br
.ti -1c
.RI "GroupJoinClause \fBDetect\fP (Expression expression)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override Expression \fBVisitQuerySourceReferenceExpression\fP (QuerySourceReferenceExpression expression)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file LocateGroupJoinQuerySource\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
