.TH "NHibernate.Test.UtilityTest.ISomething" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.UtilityTest.ISomething \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBList\fP (string role, string propertyRef, bool embedded)"
.br
.ti -1c
.RI "int \fBList< T >\fP (string role, string propertyRef, bool embedded)"
.br
.ti -1c
.RI "int \fBList< TK, TV >\fP (string role, string propertyRef, bool embedded)"
.br
.ti -1c
.RI "int \fBList< TK, TV >\fP (string role, string propertyRef, bool embedded, IComparer< TK > comparer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 132 of file ReflectHelperFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
