.TH "NHibernate.Mapping.ByCode.IFilterMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.IFilterMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Mapping\&.ByCode\&.Impl\&.FilterMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCondition\fP (string sqlCondition)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file IFilterMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
