.TH "NHibernate.Dialect.Schema.AbstractForeignKeyMetadata" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Dialect.Schema.AbstractForeignKeyMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Dialect\&.Schema\&.IForeignKeyMetadata\fP\&.
.PP
Inherited by \fBNHibernate\&.Dialect\&.Schema\&.FirebirdForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.MsSqlCeForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.MsSqlForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.MySQLForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.OracleForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.PostgreSQLForeignKeyMetadata\fP, \fBNHibernate\&.Dialect\&.Schema\&.SQLiteForeignKeyMetaData\fP, and \fBNHibernate\&.Dialect\&.Schema\&.SybaseAnywhereForeignKeyMetaData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractForeignKeyMetadata\fP (DataRow rs)"
.br
.ti -1c
.RI "void \fBAddColumn\fP (\fBIColumnMetadata\fP column)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBIColumnMetadata\fP[] \fBColumns\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file AbstractForeignKeyMetadata\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
