.TH "NHibernate.Hql.Ast.ANTLR.Tree.ISessionFactoryAwareNode" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Hql.Ast.ANTLR.Tree.ISessionFactoryAwareNode \- 
.PP
Interface for nodes which require access to the SessionFactory  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Hql\&.Ast\&.ANTLR\&.Tree\&.JavaConstantNode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBISessionFactoryImplementor\fP \fBSessionFactory\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for nodes which require access to the SessionFactory 

Author: Steve Ebersole Ported by: Steve Strong 
.PP
Definition at line 11 of file ISessionFactoryAwareNode\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
