.TH "NHibernate.Cfg.MappingSchema.IAssemblyResourceFilter" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Cfg.MappingSchema.IAssemblyResourceFilter \- 
.PP
Responsible for determining whether an embedded resource should be parsed for HBM XML data while iterating through an Assembly\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBNHibernate\&.Cfg\&.MappingSchema\&.EndsWithHbmXmlFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBShouldParse\fP (string resourceName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Responsible for determining whether an embedded resource should be parsed for HBM XML data while iterating through an Assembly\&. 


.PP
Definition at line 9 of file IAssemblyResourceFilter\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
