.TH "NHibernate.Test.NHSpecificTest.FileStreamSql2008.Convert" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.FileStreamSql2008.Convert \- 
.PP
Byte[]-to-String and String-to-Byte[] converter  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte[] \fBToBytes\fP (string str)"
.br
.ti -1c
.RI "static string \fBToStr\fP (byte[] bytes)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Byte[]-to-String and String-to-Byte[] converter 


.PP
Definition at line 8 of file Convert\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
