.TH "NHibernate.Criterion.Order" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Criterion.Order \- 
.PP
Represents an order imposed upon a \fBICriteria\fP result set\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrder\fP (\fBIProjection\fP projection, bool ascending)"
.br
.ti -1c
.RI "\fBOrder\fP (string propertyName, bool ascending)"
.br
.ti -1c
.RI "virtual \fBSqlString\fP \fBToSqlString\fP (\fBICriteria\fP criteria, \fBICriteriaQuery\fP criteriaQuery)"
.br
.RI "\fIRender the SQL fragment \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "\fBTypedValue\fP[] \fBGetTypedValues\fP (\fBICriteria\fP criteria, \fBICriteriaQuery\fP criteriaQuery)"
.br
.ti -1c
.RI "\fBOrder\fP \fBIgnoreCase\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBOrder\fP \fBAsc\fP (string propertyName)"
.br
.RI "\fIAscending order \fP"
.ti -1c
.RI "static \fBOrder\fP \fBAsc\fP (\fBIProjection\fP projection)"
.br
.RI "\fIAscending order \fP"
.ti -1c
.RI "static \fBOrder\fP \fBDesc\fP (\fBIProjection\fP projection)"
.br
.RI "\fIDescending order \fP"
.ti -1c
.RI "static \fBOrder\fP \fBDesc\fP (string propertyName)"
.br
.RI "\fIDescending order \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBascending\fP"
.br
.ti -1c
.RI "string \fBpropertyName\fP"
.br
.ti -1c
.RI "\fBIProjection\fP \fBprojection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an order imposed upon a \fBICriteria\fP result set\&. 

Should \fBOrder\fP implement \fBICriteriaQuery\fP? 
.PP
Definition at line 18 of file Order\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBOrder\fP NHibernate\&.Criterion\&.Order\&.Asc (stringpropertyName)\fC [static]\fP"

.PP
Ascending order 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 94 of file Order\&.cs\&.
.SS "static \fBOrder\fP NHibernate\&.Criterion\&.Order\&.Asc (\fBIProjection\fPprojection)\fC [static]\fP"

.PP
Ascending order 
.PP
\fBParameters:\fP
.RS 4
\fIprojection\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 104 of file Order\&.cs\&.
.SS "static \fBOrder\fP NHibernate\&.Criterion\&.Order\&.Desc (\fBIProjection\fPprojection)\fC [static]\fP"

.PP
Descending order 
.PP
\fBParameters:\fP
.RS 4
\fIprojection\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 114 of file Order\&.cs\&.
.SS "static \fBOrder\fP NHibernate\&.Criterion\&.Order\&.Desc (stringpropertyName)\fC [static]\fP"

.PP
Descending order 
.PP
\fBParameters:\fP
.RS 4
\fIpropertyName\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 124 of file Order\&.cs\&.
.SS "virtual \fBSqlString\fP NHibernate\&.Criterion\&.Order\&.ToSqlString (\fBICriteria\fPcriteria, \fBICriteriaQuery\fPcriteriaQuery)\fC [virtual]\fP"

.PP
Render the SQL fragment 
.PP
Definition at line 40 of file Order\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
