.TH "NHibernate.Test.NHSpecificTest.NH2772.Trip" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH2772.Trip \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBTrackpoint\fP \fBCreateTrackpoint\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBHeader\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual byte[] \fBImage\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual IEnumerable< \fBTrackpoint\fP > \fBTrackpoints\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Model\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
