.TH "NHibernate.Test.NHSpecificTest.Futures.FutureQueryOverFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.Futures.FutureQueryOverFixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.Futures\&.FutureFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCanUseFutureCriteria\fP ()"
.br
.ti -1c
.RI "void \fBTwoFuturesRunInTwoRoundTrips\fP ()"
.br
.ti -1c
.RI "void \fBCanCombineSingleFutureValueWithEnumerableFutures\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSetUp\fP ()"
.br
.ti -1c
.RI "override void \fBOnTearDown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file FutureQueryOverFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
