.TH "NHibernate.Mapping.ByCode.Impl.AnyMapper" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Mapping.ByCode.Impl.AnyMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Mapping\&.ByCode\&.IAnyMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnyMapper\fP (MemberInfo member, System\&.Type foreignIdType, \fBHbmAny\fP any, \fBHbmMapping\fP mapDoc)"
.br
.ti -1c
.RI "\fBAnyMapper\fP (MemberInfo member, System\&.Type foreignIdType, \fBIAccessorPropertyMapper\fP accessorMapper, \fBHbmAny\fP any, \fBHbmMapping\fP mapDoc)"
.br
.ti -1c
.RI "void \fBAccess\fP (Accessor accessor)"
.br
.ti -1c
.RI "void \fBAccess\fP (System\&.Type accessorType)"
.br
.ti -1c
.RI "void \fBOptimisticLock\fP (bool takeInConsiderationForOptimisticLock)"
.br
.ti -1c
.RI "void \fBMetaType\fP (\fBIType\fP metaType)"
.br
.ti -1c
.RI "void \fBMetaType< TMetaType >\fP ()"
.br
.ti -1c
.RI "void \fBMetaType\fP (System\&.Type metaType)"
.br
.ti -1c
.RI "void \fBIdType\fP (\fBIType\fP idType)"
.br
.ti -1c
.RI "void \fBIdType< TIdType >\fP ()"
.br
.ti -1c
.RI "void \fBIdType\fP (System\&.Type idType)"
.br
.ti -1c
.RI "void \fBColumns\fP (Action< \fBIColumnMapper\fP > idColumnMapping, Action< \fBIColumnMapper\fP > classColumnMapping)"
.br
.ti -1c
.RI "void \fBMetaValue\fP (object value, System\&.Type entityType)"
.br
.RI "\fIAdd or modify a value-class pair\&. \fP"
.ti -1c
.RI "void \fBCascade\fP (\fBCascade\fP cascadeStyle)"
.br
.ti -1c
.RI "void \fBIndex\fP (string indexName)"
.br
.ti -1c
.RI "void \fBLazy\fP (bool isLazy)"
.br
.ti -1c
.RI "void \fBUpdate\fP (bool consideredInUpdateQuery)"
.br
.ti -1c
.RI "void \fBInsert\fP (bool consideredInInsertQuery)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file AnyMapper\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Mapping\&.ByCode\&.Impl\&.AnyMapper\&.MetaValue (objectvalue, System\&.TypeentityType)"

.PP
Add or modify a value-class pair\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP The value of the DB-field dor a given association instance (should override object\&.ToString)
.br
\fIentityType\fP The class associated to the specific \fIvalue\fP \&. 
.RE
.PP

.PP
Implements \fBNHibernate\&.Mapping\&.ByCode\&.IAnyMapper\fP\&.
.PP
Definition at line 130 of file AnyMapper\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
