.TH "NHibernate.Test.DriverTest.OracleDataClientDriverFixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.DriverTest.OracleDataClientDriverFixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNoBooleanParameters\fP ()"
.br
.RI "\fITesting NH-302 to verify that a DbType\&.Boolean gets replaced with an appropriate type\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file OracleDataClientDriverFixture\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "void NHibernate\&.Test\&.DriverTest\&.OracleDataClientDriverFixture\&.NoBooleanParameters ()"

.PP
Testing NH-302 to verify that a DbType\&.Boolean gets replaced with an appropriate type\&. 
.PP
Definition at line 20 of file OracleDataClientDriverFixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
