.TH "NHibernate.Test.NHSpecificTest.NH1356.Fixture" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1356.Fixture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNHibernate\&.Test\&.NHSpecificTest\&.BugTestCase\fP\&.
.PP
Inherited by \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1356\&.FixtureWithBag\fP, \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1356\&.FixtureWithList\fP, and \fBNHibernate\&.Test\&.NHSpecificTest\&.NH1356\&.FixtureWithSet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCanLoadWithGenericCompositeElement\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract ICollection< \fBAddress\fP > \fBNewCollection\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file Fixture\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
