.TH "NHibernate.Test.NHSpecificTest.NH1027.Item" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NHibernate.Test.NHSpecificTest.NH1027.Item \- 
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBId\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName3\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName4\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName5\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName6\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual string \fBName7\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBContainer\fP > \fBContainers\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual ISet< \fBShip\fP > \fBShips\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ManyToManyAssoc\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
