.TH "Org.BouncyCastle.Utilities.Zlib.ICompressor" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Org.BouncyCastle.Utilities.Zlib.ICompressor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, \fBOrg\&.BouncyCastle\&.Utilities\&.Zlib\&.Deflate\fP, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate, and Org\&.BouncyCastle\&.Utilities\&.Zlib\&.Inflate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] outputBuffer, int outputOffset, int outputCount, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflateInit\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateInit\fP (CompressionLevel level, bool nowrap)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "void \fBfree\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateInit\fP (bool nowrap)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateInit\fP (CompressionLevel level)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "void \fBfree\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "void \fBfree\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBdeflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (byte[] bufer, int offset, int count, byte[] p1, int p2, int p3, FlushType flushType)"
.br
.ti -1c
.RI "ZLibStatus \fBinflateEnd\fP ()"
.br
.ti -1c
.RI "ZLibStatus \fBinflate\fP (FlushType flushType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBavail_out\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBavail_in\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBnext_in\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnext_in_index\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBnext_out_index\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte[] \fBnext_out\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "String \fBmsg\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBadler\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBtotal_in\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "long \fBtotal_out\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file ZStream\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
