.TH "Renci.SshNet.Common.AuthenticationBannerEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Common.AuthenticationBannerEventArgs \- 
.PP
Provides data for \fBRenci\&.SshNet\&.ConnectionInfo\&.AuthenticationBanner\fP event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Common\&.AuthenticationEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthenticationBannerEventArgs\fP (string username, string message, string language)"
.br
.RI "\fIInitializes a new instance of the \fBAuthenticationBannerEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBBannerMessage\fP\fC [get, set]\fP"
.br
.RI "\fIGets banner message\&. \fP"
.ti -1c
.RI "string \fBLanguage\fP\fC [get, set]\fP"
.br
.RI "\fIGets banner language\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides data for \fBRenci\&.SshNet\&.ConnectionInfo\&.AuthenticationBanner\fP event\&. 


.PP
Definition at line 11 of file AuthenticationBannerEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Common\&.AuthenticationBannerEventArgs\&.AuthenticationBannerEventArgs (stringusername, stringmessage, stringlanguage)"

.PP
Initializes a new instance of the \fBAuthenticationBannerEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP The username\&.
.br
\fImessage\fP Banner message\&.
.br
\fIlanguage\fP Banner language\&.
.RE
.PP

.PP
Definition at line 29 of file AuthenticationBannerEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Renci\&.SshNet\&.Common\&.AuthenticationBannerEventArgs\&.BannerMessage\fC [get]\fP, \fC [set]\fP"

.PP
Gets banner message\&. 
.PP
Definition at line 16 of file AuthenticationBannerEventArgs\&.cs\&.
.SS "string Renci\&.SshNet\&.Common\&.AuthenticationBannerEventArgs\&.Language\fC [get]\fP, \fC [set]\fP"

.PP
Gets banner language\&. 
.PP
Definition at line 21 of file AuthenticationBannerEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
