.TH "Renci.SshNet.Common.AuthenticationPasswordChangeEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Common.AuthenticationPasswordChangeEventArgs \- 
.PP
Provides data for \fBRenci\&.SshNet\&.PasswordConnectionInfo\&.PasswordExpired\fP event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Common\&.AuthenticationEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthenticationPasswordChangeEventArgs\fP (string username)"
.br
.RI "\fIInitializes a new instance of the \fBAuthenticationPasswordChangeEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[] \fBNewPassword\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the new password\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides data for \fBRenci\&.SshNet\&.PasswordConnectionInfo\&.PasswordExpired\fP event\&. 


.PP
Definition at line 11 of file AuthenticationPasswordChangeEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Common\&.AuthenticationPasswordChangeEventArgs\&.AuthenticationPasswordChangeEventArgs (stringusername)"

.PP
Initializes a new instance of the \fBAuthenticationPasswordChangeEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP The username\&.
.RE
.PP

.PP
Definition at line 25 of file AuthenticationPasswordChangeEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "byte [] Renci\&.SshNet\&.Common\&.AuthenticationPasswordChangeEventArgs\&.NewPassword\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the new password\&. The new password\&. 
.PP
Definition at line 19 of file AuthenticationPasswordChangeEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
