.TH "Renci.SshNet.Common.AuthenticationPromptEventArgs" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Common.AuthenticationPromptEventArgs \- 
.PP
Provides data for \fBRenci\&.SshNet\&.KeyboardInteractiveConnectionInfo\&.AuthenticationPrompt\fP event\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenci\&.SshNet\&.Common\&.AuthenticationEventArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthenticationPromptEventArgs\fP (string username, string instruction, string language, IEnumerable< \fBAuthenticationPrompt\fP > prompts)"
.br
.RI "\fIInitializes a new instance of the \fBAuthenticationPromptEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLanguage\fP\fC [get, set]\fP"
.br
.RI "\fIGets prompt language\&. \fP"
.ti -1c
.RI "string \fBInstruction\fP\fC [get, set]\fP"
.br
.RI "\fIGets prompt instruction\&. \fP"
.ti -1c
.RI "IEnumerable< \fBAuthenticationPrompt\fP > \fBPrompts\fP\fC [get, set]\fP"
.br
.RI "\fIGets server information request prompts\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides data for \fBRenci\&.SshNet\&.KeyboardInteractiveConnectionInfo\&.AuthenticationPrompt\fP event\&. 


.PP
Definition at line 11 of file AuthenticationPromptEventArgs\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Common\&.AuthenticationPromptEventArgs\&.AuthenticationPromptEventArgs (stringusername, stringinstruction, stringlanguage, IEnumerable< \fBAuthenticationPrompt\fP >prompts)"

.PP
Initializes a new instance of the \fBAuthenticationPromptEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIusername\fP The username\&.
.br
\fIinstruction\fP The instruction\&.
.br
\fIlanguage\fP The language\&.
.br
\fIprompts\fP The information request prompts\&.
.RE
.PP

.PP
Definition at line 35 of file AuthenticationPromptEventArgs\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string Renci\&.SshNet\&.Common\&.AuthenticationPromptEventArgs\&.Instruction\fC [get]\fP, \fC [set]\fP"

.PP
Gets prompt instruction\&. 
.PP
Definition at line 21 of file AuthenticationPromptEventArgs\&.cs\&.
.SS "string Renci\&.SshNet\&.Common\&.AuthenticationPromptEventArgs\&.Language\fC [get]\fP, \fC [set]\fP"

.PP
Gets prompt language\&. 
.PP
Definition at line 16 of file AuthenticationPromptEventArgs\&.cs\&.
.SS "IEnumerable<\fBAuthenticationPrompt\fP> Renci\&.SshNet\&.Common\&.AuthenticationPromptEventArgs\&.Prompts\fC [get]\fP, \fC [set]\fP"

.PP
Gets server information request prompts\&. 
.PP
Definition at line 26 of file AuthenticationPromptEventArgs\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
