.TH "Renci.SshNet.Messages.Authentication" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Messages.Authentication \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBannerMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_BANNER message\&. \fP"
.ti -1c
.RI "class \fBFailureMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_FAILURE message\&. \fP"
.ti -1c
.RI "class \fBInformationRequestMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_INFO_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBInformationResponseMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_INFO_RESPONSE message\&. \fP"
.ti -1c
.RI "class \fBPasswordChangeRequiredMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_PASSWD_CHANGEREQ message\&. \fP"
.ti -1c
.RI "class \fBPublicKeyMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_PK_OK message\&. \fP"
.ti -1c
.RI "class \fBRequestMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_REQUEST message\&. Server as a base message for other user authentication requests\&. \fP"
.ti -1c
.RI "class \fBRequestMessageHost\fP"
.br
.RI "\fIRepresents 'hostbased' SSH_MSG_USERAUTH_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBRequestMessageKeyboardInteractive\fP"
.br
.RI "\fIRepresents 'keyboard-interactive' SSH_MSG_USERAUTH_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBRequestMessageNone\fP"
.br
.RI "\fIRepresents 'none' SSH_MSG_USERAUTH_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBRequestMessagePassword\fP"
.br
.RI "\fIRepresents 'password' SSH_MSG_USERAUTH_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBRequestMessagePublicKey\fP"
.br
.RI "\fIRepresents 'publickey' SSH_MSG_USERAUTH_REQUEST message\&. \fP"
.ti -1c
.RI "class \fBSuccessMessage\fP"
.br
.RI "\fIRepresents SSH_MSG_USERAUTH_SUCCESS message\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
