.TH "Renci.SshNet.Sftp.SftpListDirectoryAsyncResult" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renci.SshNet.Sftp.SftpListDirectoryAsyncResult \- 
.PP
Encapsulates the results of an asynchronous directory list operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits AsyncResult< IEnumerable< SftpFile >>\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSftpListDirectoryAsyncResult\fP (AsyncCallback asyncCallback, Object state)"
.br
.RI "\fIInitializes a new instance of the \fBSftpListDirectoryAsyncResult\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBFilesRead\fP\fC [get, set]\fP"
.br
.RI "\fIGets the number of files read so far\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Encapsulates the results of an asynchronous directory list operation\&. 


.PP
Definition at line 12 of file SftpListDirectoryAsyncResult\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Renci\&.SshNet\&.Sftp\&.SftpListDirectoryAsyncResult\&.SftpListDirectoryAsyncResult (AsyncCallbackasyncCallback, Objectstate)"

.PP
Initializes a new instance of the \fBSftpListDirectoryAsyncResult\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIasyncCallback\fP The async callback\&.
.br
\fIstate\fP The state\&.
.RE
.PP

.PP
Definition at line 24 of file SftpListDirectoryAsyncResult\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "int Renci\&.SshNet\&.Sftp\&.SftpListDirectoryAsyncResult\&.FilesRead\fC [get]\fP, \fC [set]\fP"

.PP
Gets the number of files read so far\&. 
.PP
Definition at line 17 of file SftpListDirectoryAsyncResult\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
