.TH "zlib.ZInputStream" 3 "Fri Jul 5 2013" "Version 1.0" "HSA.InfoSys" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zlib.ZInputStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BinaryReader\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZInputStream\fP (System\&.IO\&.Stream in_Renamed)"
.br
.ti -1c
.RI "\fBZInputStream\fP (System\&.IO\&.Stream in_Renamed, int level)"
.br
.ti -1c
.RI "override int \fBRead\fP ()"
.br
.ti -1c
.RI "int \fBread\fP (byte[] b, int off, int len)"
.br
.ti -1c
.RI "long \fBskip\fP (long n)"
.br
.ti -1c
.RI "override void \fBClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmaxInput\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual int \fBFlushMode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "virtual long \fBTotalIn\fP\fC [get]\fP"
.br
.RI "\fIReturns the total number of bytes input so far\&.\fP"
.ti -1c
.RI "virtual long \fBTotalOut\fP\fC [get]\fP"
.br
.RI "\fIReturns the total number of bytes output so far\&.\fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file ZInputStream\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "virtual long zlib\&.ZInputStream\&.TotalIn\fC [get]\fP"

.PP
Returns the total number of bytes input so far\&.
.PP
Definition at line 72 of file ZInputStream\&.cs\&.
.SS "virtual long zlib\&.ZInputStream\&.TotalOut\fC [get]\fP"

.PP
Returns the total number of bytes output so far\&.
.PP
Definition at line 81 of file ZInputStream\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HSA\&.InfoSys from the source code\&.
